import type { NavigationDeclaration } from './navigation.types';

const MAIN_SCROLL = [
  { name: 'main', direction: 'vertical', description: '页面主内容区' },
] as const;

export const NAVIGATION_DECLARATION = {
  app: 'gallery',
  routes: [
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'gallery.home.base', search: {}, description: '相册首页' }],
      queryParams: {},
      description: '相册首页',
    },
    {
      path: '/favorites',
      component: 'FavoritesPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'gallery.favorites.base', search: {}, description: '收藏页' }],
      queryParams: {},
      description: '收藏页',
    },
    {
      path: '/album/:albumId',
      component: 'AlbumDetailPage',
      params: { albumId: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'gallery.album.base', search: {}, description: '相册详情页' }],
      queryParams: {},
      description: '相册详情页',
    },
    {
      path: '/photo/:path',
      component: 'PhotoViewerPage',
      params: { path: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'gallery.photo.base', search: {}, description: '图片预览页' },
        { id: 'gallery.photo.modal.more', search: { modal: 'more' }, description: '图片预览页 - 更多菜单弹窗' },
        { id: 'gallery.photo.modal.details', search: { modal: 'details' }, description: '图片预览页 - 详情弹窗' },
        { id: 'gallery.photo.modal.rename', search: { modal: 'rename' }, description: '图片预览页 - 重命名弹窗' },
      ],
      queryParams: { album: 'string', from: 'string', modal: 'string' },
      description: '图片预览页',
    },
    {
      path: '/intent/view',
      component: 'PhotoViewerPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'gallery.photo.intent', search: {}, description: '通过 ACTION_VIEW 打开的图片预览页' },
        { id: 'gallery.photo.intent.modal.more', search: { modal: 'more' }, description: 'ACTION_VIEW 图片预览 - 更多菜单' },
        { id: 'gallery.photo.intent.modal.details', search: { modal: 'details' }, description: 'ACTION_VIEW 图片预览 - 详情弹窗' },
        { id: 'gallery.photo.intent.modal.rename', search: { modal: 'rename' }, description: 'ACTION_VIEW 图片预览 - 重命名弹窗' },
      ],
      queryParams: { modal: 'string' },
      description: '图片预览页（外部 ACTION_VIEW 入口）',
    },
  ],
  transitions: [
    {
      id: 'favorites.open',
      from: '/',
      to: '/favorites',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开收藏页',
      ui: { placement: 'content', icon: 'favorites', gesture: 'tap' },
    },
    {
      id: 'album.open',
      from: '/',
      to: '/album/:albumId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { albumId: 'string' },
      label: '打开相册详情页',
      ui: { placement: 'content', icon: 'album', gesture: 'tap' },
    },
    {
      id: 'photo.open',
      from: ['/', '/favorites', '/album/:albumId'],
      to: '/photo/:path',
      search: {},
      searchParams: { album: 'string', from: 'string' },
      mode: 'push',
      params: { path: 'string' },
      label: '打开图片预览页',
      ui: { placement: 'content', icon: 'photo', gesture: 'tap' },
    },
    {
      id: 'photo.modal.more.open',
      from: { path: '/photo/:path', search: { modal: null } },
      to: '/photo/:path',
      search: { modal: 'more' },
      searchParams: {},
      preserveParams: ['album', 'from'],
      mode: 'push',
      params: { path: 'string' },
      label: '打开图片预览更多菜单',
      ui: { placement: 'content', icon: 'modal_more', gesture: 'tap' },
    },
    {
      id: 'photo.modal.details.open',
      from: { path: '/photo/:path', search: { modal: 'more' } },
      to: '/photo/:path',
      search: { modal: 'details' },
      searchParams: {},
      preserveParams: ['album', 'from'],
      mode: 'replace',
      params: { path: 'string' },
      label: '从更多菜单打开详情弹窗',
      ui: { placement: 'content', icon: 'modal_details', gesture: 'tap' },
    },
    {
      id: 'photo.modal.rename.open',
      from: { path: '/photo/:path', search: { modal: 'more' } },
      to: '/photo/:path',
      search: { modal: 'rename' },
      searchParams: {},
      preserveParams: ['album', 'from'],
      mode: 'replace',
      params: { path: 'string' },
      label: '从更多菜单打开重命名弹窗',
      ui: { placement: 'content', icon: 'modal_rename', gesture: 'tap' },
    },
    {
      id: 'photo.intent.modal.more.open',
      from: { path: '/intent/view', search: { modal: null } },
      to: '/intent/view',
      search: { modal: 'more' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: 'ACTION_VIEW 模式下打开更多菜单',
      ui: { placement: 'content', icon: 'modal_more', gesture: 'tap' },
    },
    {
      id: 'photo.intent.modal.details.open',
      from: { path: '/intent/view', search: { modal: 'more' } },
      to: '/intent/view',
      search: { modal: 'details' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: 'ACTION_VIEW 模式下从更多菜单打开详情弹窗',
      ui: { placement: 'content', icon: 'modal_details', gesture: 'tap' },
    },
    {
      id: 'photo.intent.modal.rename.open',
      from: { path: '/intent/view', search: { modal: 'more' } },
      to: '/intent/view',
      search: { modal: 'rename' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: 'ACTION_VIEW 模式下从更多菜单打开重命名弹窗',
      ui: { placement: 'content', icon: 'modal_rename', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
