/**
 * Reddit 字符串资源 — 对应 AOSP res/values/strings.xml
 */
export const strings = {
  app_name: 'Reddit',

  // --- Home menu (TopBar dropdown) ---
  home_menu_home: '主页',
  home_menu_popular: '流行',
  home_menu_watch: '观看',
  home_menu_latest: '最新',
  home_menu_games: '游戏',
  home_menu_news: '资讯',

  // --- Drawer (sidebar) ---
  drawer_discover_communities: '发现社区',
  drawer_create_community: '创建社区',
  drawer_games_on_reddit: 'Reddit 上的游戏',
  drawer_discover_more_games: '发现更多游戏',
  drawer_reddit_pro: 'Reddit Pro',
  drawer_trending: '趋势',
  drawer_resources: '资源',
  drawer_ad_free_browsing: '无广告浏览',
  drawer_monetize: '创收',
  drawer_monetize_desc: '在 Reddit 上赚取现金',
  drawer_your_communities: '你的社区',
  drawer_custom_feed: '定制信息流',
  drawer_all: '全部',
  drawer_about: '关于',
  drawer_reddit_rules: 'Reddit 规则',
  drawer_privacy_policy: '隐私政策',
  drawer_user_agreement: '用户协议',
  drawer_acknowledgements: '致谢',

  // --- Post more menu (bottom sheet on HomePage) ---
  post_menu_follow_post: '关注帖子',
  post_menu_save: '保存',
  post_menu_translate: '翻译',
  post_menu_translate_settings: '翻译设置',
  post_menu_report: '举报',
  post_menu_show_less: '减少显示此类帖子',
  post_menu_why_recommended: '为何向我推荐此内容？',
  post_menu_copy_text: '复制文本',
  post_menu_crosspost: '转发到社区',

  // --- Communities (Answers) page ---
  communities_tagline: '来自真实用户的真实回答',
  communities_ask_placeholder: '提问',
  communities_learn_how: '了解 Reddit Answers 的工作原理',

  // --- Search page ---
  search_back: '返回',
  search_clear: '清除搜索',
  search_trending: '趋势',
  search_tab_all: '全部',
  search_tab_posts: '帖子',
  search_tab_communities: '社区',
  search_tab_comments: '评论',
  search_no_results: '没有找到匹配的结果',
  search_try_other: '试试其他关键词',
  search_members: '成员',

  // --- Edit profile page ---
  edit_profile_title: '编辑个人资料',
  edit_profile_save: '保存',
  edit_profile_add_image: '添加图像',
  edit_profile_display_name_label: '显示名称——可选',
  edit_profile_display_name_placeholder: '输入显示名称',
  edit_profile_display_name_helper: '这将显示在你的个人资料页面上，供浏览者查看，并且不会更改你的用户名。',
  edit_profile_about_label: '关于你——可选',
  edit_profile_about_placeholder: '介绍一下你自己',
  edit_profile_social_links_title: '社交媒体链接（最多 5 个）',
  edit_profile_social_links_desc: '访问你的 Reddit 个人资料的用户将看到你的社交媒体链接。',
  edit_profile_add_social_link: '添加社交媒体链接',

  // --- Profile page (account menu) ---
  profile_account_title: '我的账户',
  profile_settings: '设置',
  profile_manage_profile: '个人资料打理',
  profile_drafts: '草稿',
  profile_history: '历史记录',
  profile_saved: '已保存',
  profile_online_status: '在线状态',
  profile_style_avatar: '设置头像风格',
  profile_add_to_custom_feed: '添加到定制信息流',

  // --- Settings page ---
  settings_title: '设置',
  settings_section_general: '通用',
  settings_section_premium: 'REDDIT PREMIUM',
  settings_section_language: '语言',
  settings_section_view: '查看选项',
  settings_section_data: '数据使用',
  settings_section_accessibility: '辅助功能',
  settings_section_dark_mode: '深色模式',
  settings_section_advanced: '高级',
  settings_section_about: '关于',
  settings_section_support: '支持',
  settings_section_build: '构建信息',
  settings_account_for: 'u/{username} 的账户设置',
  settings_get_premium: '获取 Premium',
  settings_language: '语言',
  settings_content_languages: '内容语言',
  settings_device_language: '使用设备语言',
  settings_default_view: '默认视图',
  settings_thumbnails: '缩略图',
  settings_card: '卡片',
  settings_community_default: '社区默认',
  settings_show_nsfw: '显示成人内容（我已满18岁）',
  settings_blur_nsfw: '模糊成人（18+）图片和媒体',
  settings_community_themes: '使用社区主题',
  settings_low_data: '低数据模式',
  settings_text_size: '增大文字大小',
  settings_media_animations: '媒体和动画',
  settings_talkback: 'TalkBack 自定义',
  settings_auto_dark: '自动深色模式',
  settings_follow_os: '跟随系统设置',
  settings_dark_mode_label: '深色模式',
  settings_light_theme: '浅色主题',
  settings_dark_theme: '深色主题',
  settings_open_links: '打开链接',
  settings_in_app: '应用内',
  settings_default_browser: '默认浏览器',
  settings_saved_image_attribution: '已保存图片来源标注',
  settings_comment_jump: '评论跳转按钮',
  settings_default_comment_sort: '默认评论排序',
  settings_best: 'Best',
  settings_export_video_log: '导出视频日志',
  settings_reddit_rules: 'Reddit 规则',
  settings_privacy_policy: '隐私政策',
  settings_user_agreement: '用户协议',
  settings_acknowledgements: '致谢',
  settings_help_center: '帮助中心',
  settings_visit_bugs: '访问 r/bugs',
  settings_report_issue: '报告问题',
  settings_open_links_header: '打开链接',
} as const;

export type StringKey = keyof typeof strings;
