import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  app_name: 'Reddit',

  // --- Home menu (TopBar dropdown) ---
  home_menu_home: 'Home',
  home_menu_popular: 'Popular',
  home_menu_watch: 'Watch',
  home_menu_latest: 'Latest',
  home_menu_games: 'Games',
  home_menu_news: 'News',

  // --- Drawer (sidebar) ---
  drawer_discover_communities: 'Discover Communities',
  drawer_create_community: 'Create Community',
  drawer_games_on_reddit: 'Games on Reddit',
  drawer_discover_more_games: 'Discover more games',
  drawer_reddit_pro: 'Reddit Pro',
  drawer_trending: 'Trending',
  drawer_resources: 'Resources',
  drawer_ad_free_browsing: 'Ad-free browsing',
  drawer_monetize: 'Monetize',
  drawer_monetize_desc: 'Earn cash on Reddit',
  drawer_your_communities: 'Your Communities',
  drawer_custom_feed: 'Custom Feed',
  drawer_all: 'All',
  drawer_about: 'About',
  drawer_reddit_rules: 'Reddit Rules',
  drawer_privacy_policy: 'Privacy Policy',
  drawer_user_agreement: 'User Agreement',
  drawer_acknowledgements: 'Acknowledgements',

  // --- Post more menu (bottom sheet on HomePage) ---
  post_menu_follow_post: 'Follow post',
  post_menu_save: 'Save',
  post_menu_translate: 'Translate',
  post_menu_translate_settings: 'Translation settings',
  post_menu_report: 'Report',
  post_menu_show_less: 'Show fewer posts like this',
  post_menu_why_recommended: 'Why am I seeing this?',
  post_menu_copy_text: 'Copy text',
  post_menu_crosspost: 'Crosspost to community',

  // --- Communities (Answers) page ---
  communities_tagline: 'Real answers from real people',
  communities_ask_placeholder: 'Ask',
  communities_learn_how: 'Learn how Reddit Answers works',

  // --- Search page ---
  search_back: 'Back',
  search_clear: 'Clear search',
  search_trending: 'Trending',
  search_tab_all: 'All',
  search_tab_posts: 'Posts',
  search_tab_communities: 'Communities',
  search_tab_comments: 'Comments',
  search_no_results: 'No matching results found',
  search_try_other: 'Try other keywords',
  search_members: 'members',

  // --- Edit profile page ---
  edit_profile_title: 'Edit Profile',
  edit_profile_save: 'Save',
  edit_profile_add_image: 'Add Image',
  edit_profile_display_name_label: 'Display name — optional',
  edit_profile_display_name_placeholder: 'Enter display name',
  edit_profile_display_name_helper: 'This will be shown on your profile page for visitors to see, and won\'t change your username.',
  edit_profile_about_label: 'About you — optional',
  edit_profile_about_placeholder: 'Tell us about yourself',
  edit_profile_social_links_title: 'Social links (5 max)',
  edit_profile_social_links_desc: 'People who visit your Reddit profile will see your social links.',
  edit_profile_add_social_link: 'Add social link',

  // --- Profile page (account menu) ---
  profile_account_title: 'My account',
  profile_settings: 'Settings',
  profile_manage_profile: 'Manage profile',
  profile_drafts: 'Drafts',
  profile_history: 'History',
  profile_saved: 'Saved',
  profile_online_status: 'Online status',
  profile_style_avatar: 'Style avatar',
  profile_add_to_custom_feed: 'Add to custom feed',

  // --- Settings page ---
  settings_title: 'Settings',
  settings_section_general: 'GENERAL',
  settings_section_premium: 'REDDIT PREMIUM',
  settings_section_language: 'LANGUAGE',
  settings_section_view: 'VIEW OPTIONS',
  settings_section_data: 'DATA USAGE',
  settings_section_accessibility: 'ACCESSIBILITY',
  settings_section_dark_mode: 'DARK MODE',
  settings_section_advanced: 'ADVANCED',
  settings_section_about: 'ABOUT',
  settings_section_support: 'SUPPORT',
  settings_section_build: 'BUILD INFORMATION',
  settings_account_for: 'Account settings for u/{username}',
  settings_get_premium: 'Get Premium',
  settings_language: 'Language',
  settings_content_languages: 'Content languages',
  settings_device_language: 'Use device language',
  settings_default_view: 'Default view',
  settings_thumbnails: 'Thumbnails',
  settings_card: 'Card',
  settings_community_default: 'Community default',
  settings_show_nsfw: 'Show mature content (I\'m over 18)',
  settings_blur_nsfw: 'Blur mature (18+) images and media',
  settings_community_themes: 'Use community themes',
  settings_low_data: 'Low data mode',
  settings_text_size: 'Increase text size',
  settings_media_animations: 'Media and animations',
  settings_talkback: 'TalkBack customization',
  settings_auto_dark: 'Auto Dark Mode',
  settings_follow_os: 'Follow OS setting',
  settings_dark_mode_label: 'Dark mode',
  settings_light_theme: 'Light theme',
  settings_dark_theme: 'Dark theme',
  settings_open_links: 'Open links',
  settings_in_app: 'In app',
  settings_default_browser: 'Default browser',
  settings_saved_image_attribution: 'Saved image attribution',
  settings_comment_jump: 'Comment jump button',
  settings_default_comment_sort: 'Default comment sort',
  settings_best: 'Best',
  settings_export_video_log: 'Export video log',
  settings_reddit_rules: 'Reddit rules',
  settings_privacy_policy: 'Privacy policy',
  settings_user_agreement: 'User agreement',
  settings_acknowledgements: 'Acknowledgements',
  settings_help_center: 'Help Center',
  settings_visit_bugs: 'Visit r/bugs',
  settings_report_issue: 'Report an issue',
  settings_open_links_header: 'OPEN LINKS',
};
