import { NavigationDeclaration, ScrollContainerDeclaration } from './navigation.types';

const MAIN_SCROLL: ScrollContainerDeclaration[] = [
  { name: 'main', direction: 'vertical', description: '页面内容' },
];

export const NAVIGATION_DECLARATION = {
  app: 'tencent_meeting',
  routes: [
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'home.base', search: {}, description: '默认首页' },
      ],
      queryParams: {},
      description: '会议首页',
    },
    {
      path: '/history',
      component: 'HistoryMeetingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [
        { name: 'history', direction: 'vertical', description: '历史会议列表' }
      ],
      uiStates: [{ id: 'history.base', search: {}, description: '历史会议默认' }],
      queryParams: {},
      description: '历史会议',
    },
    {
      path: '/history/:meetingId',
      component: 'HistoryMeetingDetailPage',
      params: { meetingId: 'string' },
      entryPoint: 'none',
      scrollContainers: [
        { name: 'history-detail', direction: 'vertical', description: '历史会议详情' }
      ],
      uiStates: [{ id: 'history.detail.base', search: {}, description: '历史会议详情默认' }],
      queryParams: {},
      description: '历史会议详情',
    },
    {
      path: '/contacts',
      component: 'ContactsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'contacts.base', search: {}, description: '通讯录默认' }],
      queryParams: {},
      description: '通讯录',
    },
    {
      path: '/me',
      component: 'MePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'me.base', search: {}, description: '我的-默认' }],
      queryParams: {},
      description: '我的 - 账号中心',
    },
    {
      path: '/join',
      component: 'JoinMeetingPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'join.base', search: {}, description: '加入会议默认' }],
      queryParams: {},
      description: '加入会议',
    },
    {
      path: '/quick',
      component: 'QuickMeetingPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'quick.base', search: {}, description: '快速会议默认' }],
      queryParams: {},
      description: '快速会议配置',
    },
    {
      path: '/schedule',
      component: 'ScheduleMeetingPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'schedule.base', search: {}, description: '预定会议默认' }],
      queryParams: {},
      description: '预定会议',
    },
    {
      path: '/schedule/regular',
      component: 'ScheduleRegularMeetingPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'scheduleRegular.base', search: {}, description: '常规会议预定默认' }],
      queryParams: {},
      description: '预定会议-常规会议',
    },
    {
      path: '/attendees/:id',
      component: 'MeetingAttendeesPage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'attendees.base', search: {}, description: '参会人员列表' }],
      queryParams: {},
      description: '参会人员列表',
    },
    {
      path: '/meeting',
      component: 'MeetingPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'meeting.base', search: {}, description: '会议进行中' },
        { id: 'meeting.dialog.chat', search: { dialog: 'chat' }, description: '会议聊天弹窗' },
        { id: 'meeting.dialog.exit', search: { dialog: 'exit' }, description: '退出会议弹窗' },
      ],
      queryParams: {},
      description: '会议中',
    },
    {
      path: '/meeting/edit',
      component: 'EditMeetingPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'editMeeting.base', search: {}, description: '修改会议预定默认' }],
      queryParams: {},
      description: '修改会议预定',
    },
    {
      path: '/share',
      component: 'ShareScreenPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'share.base', search: {}, description: '共享屏幕默认' }],
      queryParams: {},
      description: '共享屏幕',
    },
    {
      path: '/settings',
      component: 'SettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.base',
          search: {},
          description: '设置默认',
          actions: [
            { id: 'settings.notifications.toggle', label: '接收消息通知：开关', behavior: 'toggle' },
            { id: 'settings.audio.micOnJoin.toggle', label: '入会开启麦克风：开关', behavior: 'toggle' },
            { id: 'settings.audio.speakerOnJoin.toggle', label: '入会开启扬声器：开关', behavior: 'toggle' },
            { id: 'settings.audio.micFloating.toggle', label: '开启麦克风浮窗：开关', behavior: 'toggle' },
            { id: 'settings.audio.micSound.toggle', label: '开麦时播放提示音：开关', behavior: 'toggle' },
            { id: 'settings.video.cameraOnJoin.toggle', label: '入会开启摄像头：开关', behavior: 'toggle' },
            { id: 'settings.video.videoMirror.toggle', label: '视频镜像：开关', behavior: 'toggle' },
            { id: 'settings.video.hideNonVideo.toggle', label: '隐藏非视频参会者：开关', behavior: 'toggle' },
            { id: 'settings.video.hideSelf.toggle', label: '隐藏自己：开关', behavior: 'toggle' },
            { id: 'settings.video.showPreview.toggle', label: '显示视频预览：开关', behavior: 'toggle' },
            { id: 'settings.chat.danmu.toggle', label: '显示弹幕：开关', behavior: 'toggle' },
            { id: 'settings.general.showDuration.toggle', label: '显示参会时长：开关', behavior: 'toggle' },
            { id: 'settings.general.nearbyDiscovery.toggle', label: '近场发现：开关', behavior: 'toggle' },
            { id: 'settings.general.voiceExcitation.toggle', label: '语音激励：开关', behavior: 'toggle' },
            { id: 'settings.general.shortcutFloat.toggle', label: '快捷浮窗：开关', behavior: 'toggle' },
            { id: 'settings.general.safeDrive.toggle', label: '安全驾驶模式：开关', behavior: 'toggle' },
            { id: 'settings.general.darkModeFollow.toggle', label: '深色模式跟随系统：开关', behavior: 'toggle' },
          ],
        },
      ],
      queryParams: {},
      description: '设置',
    },
    {
      path: '/account-security',
      component: 'AccountSecurityPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'accountSecurity.base',
          search: {},
          description: '账号与安全-默认',
          actions: [
            { id: 'accountSecurity.showIdentity.toggle', label: '对外展示认证身份：开关', behavior: 'toggle' },
          ],
        },
        {
          id: 'accountSecurity.dialog.delete',
          search: { dialog: 'delete-account' },
          description: '注销账号弹窗',
        },
      ],
      queryParams: {},
      description: '账号与安全',
    },
    {
      path: '/personal-room',
      component: 'PersonalRoomPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'personalRoom.base', search: {}, description: '个人会议室默认' }],
      queryParams: {},
      description: '个人会议室',
    },
    {
      path: '/messages',
      component: 'MessagesPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        // 顶层 Tab: 待办 (无子 Tab)
        { id: 'messages.todo', search: { tab: 'todo' }, description: '待办消息' },
        // 顶层 Tab: 全部 + 子 Tab 组合
        { id: 'messages.all', search: { tab: 'all' }, description: '全部消息-全部' },
        { id: 'messages.all.system', search: { tab: 'all', sub: 'system' }, description: '全部消息-系统通知' },
        { id: 'messages.all.welfare', search: { tab: 'all', sub: 'welfare' }, description: '全部消息-福利通知' },
      ],
      queryParams: {},
      description: '消息中心',
    },
    {
      path: '/profile',
      component: 'ProfilePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'profile.base', search: {}, description: '个人资料页-默认' }],
      queryParams: {},
      description: '个人资料页（从首页头像进入，无底栏）',
    },
  ],
  transitions: [
    {
      id: 'home.history.open',
      from: '/',
      to: '/history',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开历史会议',
      ui: { placement: 'content', icon: 'history', gesture: 'tap' },
    },
    {
      id: 'history.detail.open',
      from: '/history',
      to: '/history/:meetingId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { meetingId: 'string' },
      label: '打开历史会议详情',
      ui: { placement: 'content', icon: 'meeting', gesture: 'tap' },
    },
    {
      id: 'history.detail.back',
      from: '/history/:meetingId',
      to: '/history',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '返回历史会议列表',
      ui: { placement: 'content', icon: 'back', gesture: 'tap' },
    },
    {
      id: 'history.detail.rejoin',
      from: '/history/:meetingId',
      to: '/meeting',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '重新入会',
      ui: { placement: 'content', icon: 'meeting_join', gesture: 'tap' },
    },
    {
      id: 'history.detail.reschedule',
      from: '/history/:meetingId',
      to: '/schedule/regular',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '再次预定',
      ui: { placement: 'content', icon: 'schedule', gesture: 'tap' },
    },
    {
      id: 'home.ongoing.join',
      from: '/',
      to: '/meeting',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '加入进行中的会议',
      ui: { placement: 'content', icon: 'meeting_join', gesture: 'tap' },
    },
    {
      id: 'tab.home',
      from: ['/contacts', '/me'],
      to: '/',
      search: { dialog: null },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换至会议主页',
      ui: { placement: 'tabbar', icon: 'tab_home', gesture: 'tap' },
    },
    {
      id: 'tab.contacts',
      from: ['/', '/me'],
      to: '/contacts',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换至通讯录',
      ui: { placement: 'tabbar', icon: 'tab_contacts', gesture: 'tap' },
    },
    {
      id: 'tab.me',
      from: ['/', '/contacts'],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换至我的',
      ui: { placement: 'tabbar', icon: 'tab_me', gesture: 'tap' },
    },
    {
      id: 'home.profile.open',
      from: '/',
      to: '/profile',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开个人资料页',
      ui: { placement: 'content', icon: 'profile', gesture: 'tap' },
    },
    {
      id: 'profile.personal_room.open',
      from: '/profile',
      to: '/personal-room',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '从个人资料页打开个人会议室',
      ui: { placement: 'content', icon: 'personal_room', gesture: 'tap' },
    },
    {
      id: 'profile.account_security.open',
      from: '/profile',
      to: '/account-security',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '从个人资料页打开账号与安全',
      ui: { placement: 'content', icon: 'account_security', gesture: 'tap' },
    },
    {
      id: 'profile.settings.open',
      from: '/profile',
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '从个人资料页进入设置',
      ui: { placement: 'content', icon: 'settings', gesture: 'tap' },
    },
    {
      id: 'home.join.open',
      from: '/',
      to: '/join',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入加入会议页',
      ui: { placement: 'content', icon: 'join', gesture: 'tap' },
    },
    {
      id: 'home.quick.open',
      from: '/',
      to: '/quick',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入快速会议',
      ui: { placement: 'content', icon: 'quick', gesture: 'tap' },
    },
    {
      id: 'home.schedule.open',
      from: '/',
      to: '/schedule',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入预定会议',
      ui: { placement: 'content', icon: 'schedule', gesture: 'tap' },
    },
    {
      id: 'schedule.regular.open',
      from: '/schedule',
      to: '/schedule/regular',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入常规会议预定',
      ui: { placement: 'content', icon: 'schedule_regular', gesture: 'tap' },
    },
    {
      id: 'schedule.complete',
      from: '/schedule/regular',
      to: '/meeting/detail',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '完成预定会议',
      ui: { placement: 'topbar', icon: 'check', gesture: 'tap' },
    },
    {
      id: 'home.meeting.detail',
      from: '/',
      to: '/meeting/detail',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看会议详情',
      ui: { placement: 'content', icon: 'meeting_detail', gesture: 'tap' },
    },
    {
      id: 'meeting.detail.back',
      from: '/meeting/detail',
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '返回主页',
      ui: { placement: 'topbar', icon: 'back', gesture: 'tap' },
    },
    {
      id: 'meeting.detail.join',
      from: '/meeting/detail',
      to: '/meeting',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入会议',
      ui: { placement: 'content', icon: 'meeting_join', gesture: 'tap' },
    },
    {
      id: 'meeting.detail.actions.open',
      from: '/meeting/detail',
      to: '/meeting/detail',
      search: { dialog: 'actions' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开会议操作菜单',
      ui: { placement: 'topbar', icon: 'more', gesture: 'tap' },
    },
    {
      id: 'meeting.detail.edit.open',
      from: '/meeting/detail',
      to: '/meeting/edit',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开修改会议页',
      ui: { placement: 'content', icon: 'edit', gesture: 'tap' },
    },
    {
      id: 'meeting.detail.cancel',
      from: '/meeting/detail',
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '取消会议',
      ui: { placement: 'content', icon: 'cancel_meeting', gesture: 'tap' },
    },
    {
      id: 'meeting.edit.complete',
      from: '/meeting/edit',
      to: '/meeting/detail',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '确认修改',
      ui: { placement: 'topbar', icon: 'check', gesture: 'tap' },
    },
    {
      id: 'quick.meeting.open',
      from: '/quick',
      to: '/meeting',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入会议',
      ui: { placement: 'content', icon: 'meeting_join', gesture: 'tap' },
    },
    {
      id: 'join.meeting.open',
      from: '/join',
      to: '/meeting',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入会议',
      ui: { placement: 'content', icon: 'meeting_join', gesture: 'tap' },
    },
    {
      id: 'history.detail.attendees.open',
      from: '/history/:meetingId',
      to: '/attendees/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '查看参会人员',
      ui: { placement: 'content', icon: 'participants', gesture: 'tap' },
    },
    {
      id: 'meeting.chat.open',
      from: '/meeting',
      to: '/meeting',
      search: { dialog: 'chat' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开会议聊天',
      ui: { placement: 'content', icon: 'chat', gesture: 'tap' },
    },
    {
      id: 'meeting.exit.open',
      from: '/meeting',
      to: '/meeting',
      search: { dialog: 'exit' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开退出会议弹窗',
      ui: { placement: 'topbar', icon: 'meeting_exit', gesture: 'tap' },
    },
    {
      id: 'meeting.leave',
      from: { path: '/meeting', search: { dialog: 'exit' } },
      to: '/',
      search: { dialog: null },
      searchParams: {},
      mode: 'replace', // Leaving meeting resets stack usually, or just navigate home
      params: {},
      label: '离开会议',
      ui: { placement: 'content', icon: 'leave_meeting', gesture: 'tap' },
    },
    {
      id: 'meeting.end',
      from: { path: '/meeting', search: { dialog: 'exit' } },
      to: '/',
      search: { dialog: null },
      searchParams: {},
      mode: 'replace',
      label: '结束会议',
      ui: { placement: 'content', icon: 'end_meeting', gesture: 'tap' },
      params: {},
    },
    {
      id: 'home.share.open',
      from: '/',
      to: '/share',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入共享屏幕',
      ui: { placement: 'content', icon: 'share', gesture: 'tap' },
    },
    {
      id: 'home.messages.open',
      from: '/',
      to: '/messages',
      search: { tab: 'all' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开消息中心',
      ui: { placement: 'content', icon: 'messages', gesture: 'tap' },
    },
    {
      id: 'me.personal_room.open',
      from: '/me',
      to: '/personal-room',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开个人会议室',
      ui: { placement: 'content', icon: 'personal_room', gesture: 'tap' },
    },
    {
      id: 'me.account_security.open',
      from: '/me',
      to: '/account-security',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开账号与安全',
      ui: { placement: 'content', icon: 'account_security', gesture: 'tap' },
    },
    {
      id: 'me.settings.open',
      from: '/me',
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入设置',
      ui: { placement: 'content', icon: 'settings', gesture: 'tap' },
    },
    {
      id: 'settings.account_security.open',
      from: '/settings',
      to: '/account-security',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '设置页跳转账号安全',
      ui: { placement: 'content', icon: 'settings_account_security', gesture: 'tap' },
    },
    {
      id: 'accountSecurity.dialog.delete.open',
      from: { path: '/account-security', search: { dialog: null } },
      to: '/account-security',
      search: { dialog: 'delete-account' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开注销账号弹窗',
      ui: { placement: 'content', icon: 'delete_account', gesture: 'tap' },
    },
    // 顶层 Tab 切换（.switch 模式）- 只切换 tab，清除 sub
    {
      id: 'messages.tab.switch',
      from: { path: '/messages', search: { tab: '*' } },
      to: '/messages',
      search: { sub: null },  // 清除 sub 参数
      searchParams: { tab: 'string' },  // 动态目标 tab
      mode: 'replace',
      params: {},
      label: '切换消息 Tab',
      ui: { placement: 'topbar', icon: 'messages_tab', gesture: 'tap' },
    },
    // 子 Tab 切换（.switch 模式）- 在 tab=all 时切换 sub
    {
      id: 'messages.sub.switch',
      from: [
        // 从任意 tab=all 状态（包括带 sub 的）都可以切换子 Tab
        { path: '/messages', search: { tab: 'all' } },
        { path: '/messages', search: { tab: 'all', sub: 'system' } },
        { path: '/messages', search: { tab: 'all', sub: 'welfare' } },
      ],
      to: '/messages',
      search: { tab: 'all' },  // 保持 tab=all
      searchParams: { sub: 'string' },  // 动态目标 sub
      mode: 'replace',
      params: {},
      label: '切换消息子 Tab',
      ui: { placement: 'content', icon: 'messages_sub', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
