import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  // Tabs
  tab_home: 'Home',
  tab_me: 'My eBay',
  tab_search: 'Search',
  tab_inbox: 'Inbox',
  tab_sell: 'Sell',

  // Home page
  home_search_placeholder: 'Search on eBay',
  home_saved: 'Saved',
  home_sell: 'Sell',
  home_categories: 'Categories',
  home_deals: 'Deals',
  home_auth_prompt: 'Sign in for a more personalized eBay experience',
  home_register: 'Register',
  home_login: 'Sign in',
  home_promo_title: 'Save 20% on featured picks',
  home_promo_desc: 'Shop this week\'s best finds in tech, fashion, and home.',
  home_get_coupon: 'Get coupon',
  home_promo_footnote: 'Ends February 16. Save up to $500 on select items.',
  home_guarantee_title: 'Get your item or your money back',
  home_guarantee_desc: 'Shop worldwide with eBay Money Back Guarantee.',
  home_guarantee_cta: 'View coverage',
  home_easy_title: 'Enjoy an easier shopping experience',
  home_easy_desc: 'From checkout to returns, we help keep every order worry-free.',
  home_easy_cta: 'Explore now',
  home_category_section_title: 'Brand-new Electronics',
  home_cat1: 'Brand-new Electronics',
  home_cat2: 'Collectibles',
  home_cat3: 'Trading Cards',

  // Cart page
  cart_title: 'Cart',
  cart_empty_title: 'Your cart is empty',
  cart_empty_desc: 'Start browsing to find something you love.',

  // Inbox page
  inbox_title: 'Inbox',
  inbox_empty: 'No messages yet',

  // Me page
  me_title: 'My eBay',
  me_login: 'Sign in',
  me_latest_news: 'Your latest updates',
  me_watchlist: 'Watchlist',
  me_watchlist_desc: 'Your favorites and saved items',
  me_watchlist_subtitle: 'Keep an eye on items you follow',
  me_bids: 'Bids & Offers',
  me_bids_desc: 'Active auctions and seller offers',
  me_looking_for_messages: 'Looking for messages?',
  me_messages_moved: 'Messages are now next to the cart in the top-right corner.',
  me_shopping: 'Shopping',
  me_saved: 'Saved',
  me_saved_desc: 'Searches, sellers, and alerts',
  me_buy_again: 'Buy Again',
  me_buy_again_desc: 'Reorder items you purchased before',
  me_purchases: 'Purchases',
  me_purchases_desc: 'Your order history',
  me_recently_viewed: 'Recently Viewed',
  me_recently_viewed_desc: 'Items you looked at recently',
  me_selling: 'Selling',
  me_selling_overview: 'Selling overview',
  me_shortcuts: 'Shortcuts',
  me_account: 'Account',
  me_payments: 'Payments',
  me_help: 'Help',
  me_settings: 'Settings',
  me_feedback: 'Enjoying the new landing page experience?',

  // Search page
  search_placeholder: 'Search on eBay',
  search_recent: 'Recent searches',
  search_saved: 'Saved',
  search_clear_recent: 'Clear recent searches',
  search_save_search: 'Save this search',
  search_sort: 'Sort',
  search_filters: 'Filters',
  search_shop_by_category: 'Shop by category',
  search_results: 'results',
  search_shipping: 'shipping',
  search_sponsored: 'Sponsored',
  search_any: 'Any',
  search_all_categories: 'All categories',
  search_sample_query: 'Fan',

  // Sell page
  sell_title: 'Sell',
  sell_info: 'Please use the website to create and list items',
  sell_register: 'Register',
  sell_login: 'Sign in',
  sell_how_it_works: 'How it works',
  sell_learn_more: 'Learn more',

  // Selling steps
  selling_step1_title: 'List in minutes.',
  selling_step1_desc: 'Take some photos and write a great description. We\'ll help you price your item to sell.',
  selling_step2_title: 'Get paid fast and safely.',
  selling_step2_desc: 'When your item sells, we make it easy for you and the buyer to complete the payment.',
  selling_step3_title: 'Ship to the buyer.',
  selling_step3_desc: 'Pack it up, print the label right on eBay, and ship it out. It\'s that simple.',

  // Settings page
  settings_title: 'Settings',
  settings_account: 'Account',
  settings_sign_in: 'Sign in',
  settings_general: 'General',
  settings_theme: 'Theme',
  settings_country: 'Country or region',
  settings_country_value: 'China',
  settings_translation: 'Translation',
  settings_clear_searches: 'Clear search history',
  settings_support: 'Support',
  settings_customer_service: 'Customer service',
  settings_customer_service_desc: 'English support only',
  settings_shake_to_report: 'Shake to report',
  settings_about: 'About',
  settings_terms: 'User Agreement',
  settings_privacy: 'Privacy',
  settings_privacy_choices: 'Your Privacy Choices and AdChoice',
  settings_ads: 'Advertising and related preferences',
  settings_accessibility: 'Accessibility',
  settings_legal: 'Legal',
  settings_version: 'Version',
  settings_choose_theme: 'Choose app theme',
  settings_cancel: 'Cancel',
  settings_theme_light: 'Light',
  settings_theme_dark: 'Dark',
  settings_theme_battery: 'Battery Saver',
  settings_theme_system: 'System default',
  settings_theme_light_desc: 'Always use the light theme',
  settings_theme_dark_desc: 'Always use the dark theme',
  settings_theme_battery_desc: 'Use the dark theme only when Battery Saver is on',
  settings_theme_system_desc: 'Use your device display setting',

  // Filter drawer
  filter_title: 'Filters',
  filter_reset: 'Reset',
  filter_sort: 'Sort',
  filter_buying_format: 'Buying format',
  filter_condition: 'Condition',
  filter_price: 'Price',
  filter_category: 'Category',
  filter_brand: 'Brand',
  filter_location: 'Item location',
  filter_shipping: 'Shipping options',
  filter_custom: 'Customize',
  filter_show_more: 'Show more',
  filter_browse: 'View',
  filter_camera_hint: 'Use your camera to find items that match these filters.',
  filter_show_results: 'Show',
  filter_results: 'results',
  filter_back: 'Back',
  filter_auction_desc: 'Bid against other buyers',
  filter_buy_it_now_desc: 'Purchase the item right away',
  filter_offer_desc: 'Negotiate with the seller',
  filter_common_price_ranges: 'Common price ranges',
  filter_below: 'Below',
  filter_between: 'to',
  filter_above: 'Above',
  filter_choose_price: 'Choose your price',
  filter_min: 'Min',
  filter_max: 'Max',
  filter_inventory: 'Available inventory',
  filter_all_categories: 'All categories',
  filter_search_brand: 'Search brands',
  filter_hot: 'Popular',
  filter_hot_brand_desc: 'Trending brands on eBay',
  filter_free_shipping: 'Free international shipping',
  filter_custom_hide: 'Hide Sort and Filter buttons',
  filter_custom_hide_desc: 'Sort and Filter buttons will appear at the bottom of search results',
  filter_custom_expand: 'Expand all filters',
  filter_custom_expand_desc: 'Keep every available filter section expanded',
  filter_custom_lock: 'Lock filters',
  filter_custom_lock_desc: 'Apply your saved filters automatically to searches',
  filter_location_preset: 'Preset',
  filter_location_us_only: 'US only',

  // Sort modal
  sort_title: 'Sort',

  // Categories page
  categories_title: 'Categories',

  // Item detail page
  item_title: 'Item',
  item_in_carts: 'In {count} carts',
  item_watchers: '{count}',
  item_seller: 'Seller',
  item_positive_feedback: '{pct}% positive feedback',
  item_message_seller: 'Message',
  item_price_approx: 'Approx. ¥{cny}',
  item_price_per_unit: '({price}/unit)',
  item_or_best_offer: 'or Best Offer',
  item_shipping_cost: '{price} (approx. ¥{cny}) shipping',
  item_free_shipping: 'Free shipping',
  item_est_delivery: 'Est. delivery: {date}',
  item_condition: 'Condition',
  item_condition_desc: 'Condition description',
  item_quantity: 'Quantity',
  item_sold_count: '{count} sold',
  item_stock_count: '{count} available',
  item_buy_now: 'Buy It Now',
  item_add_to_cart: 'Add to cart',
  item_make_offer: 'Make an offer',
  item_add_to_watchlist: 'Add to watchlist',
  item_brand: 'Brand',
  item_type: 'Type',
  item_location: 'Location',
  item_listed_date: 'Listed',
  item_item_number: 'Item number',
  item_returns: 'Returns',
  item_returns_accepted: 'Seller accepts returns',
  item_payments: 'Payments',
  item_secure_payment: 'eBay secure payment',
  item_about: 'About this item',
  item_seller_desc: 'Item description from the seller',
  item_view_full_desc: 'See full description',
  item_watcher_notice: 'Other shoppers want this. {count} people are watching this item.',
};
