/**
 * Ebay 字符串资源 — 对应 AOSP res/values/strings.xml
 */
export const strings = {
  // Tabs
  tab_home: '主页',
  tab_me: '我的 eBay',
  tab_search: '搜索',
  tab_inbox: '收件箱',
  tab_sell: '出售',

  // Home page
  home_search_placeholder: '在 eBay 搜索',
  home_saved: '已保存',
  home_sell: '出售',
  home_categories: '类别',
  home_deals: '超值特惠',
  home_auth_prompt: '登录以享受个性化的 eBay 体验',
  home_register: '注册',
  home_login: '登录',
  home_promo_title: '精选商品享8折优惠',
  home_promo_desc: '本周数码科技、时尚、家居好物捡漏，超值开抢！',
  home_get_coupon: '获取优惠券',
  home_promo_footnote: '活动于2月16日结束。最高立减500美元。限指定商...',
  home_guarantee_title: '收货或退款，二选一保障',
  home_guarantee_desc: 'eBay 退款保障，放心购全球',
  home_guarantee_cta: '查看保障细则',
  home_easy_title: '尽享轻松购物体验',
  home_easy_desc: '为你全程提供安全可靠的配送及退货无忧服务',
  home_easy_cta: '即刻探索',
  home_category_section_title: '全新电子产品',
  home_cat1: '全新电子产品',
  home_cat2: '收藏品',
  home_cat3: '集换卡',

  // Cart page
  cart_title: '购物车',
  cart_empty_title: '购物车是空的',
  cart_empty_desc: '去逛逛，发现好物！',

  // Inbox page
  inbox_title: '收件箱',
  inbox_empty: '暂无消息',

  // Me page
  me_title: '我的 eBay',
  me_login: '登录',
  me_latest_news: '您的最新消息',
  me_watchlist: '追踪列表',
  me_watchlist_desc: '您的最爱和列表',
  me_watchlist_subtitle: '密切关注追踪物品',
  me_bids: '出价和议价',
  me_bids_desc: '进行中的拍卖和卖家议价',
  me_looking_for_messages: '在寻找消息？',
  me_messages_moved: '消息现在位于右上角的购物车旁。',
  me_shopping: '购物',
  me_saved: '已保存',
  me_saved_desc: '搜索、卖家、动态消息',
  me_buy_again: '再次购买',
  me_buy_again_desc: '购买已购买过的物品',
  me_purchases: '购买记录',
  me_purchases_desc: '您的订单记录',
  me_recently_viewed: '最近浏览',
  me_recently_viewed_desc: '您最近浏览的物品',
  me_selling: '出售',
  me_selling_overview: '销售概览',
  me_shortcuts: '快捷方式',
  me_account: '账户',
  me_payments: '付款',
  me_help: '帮助',
  me_settings: '设置',
  me_feedback: '喜欢新的着陆页体验吗？',

  // Search page
  search_placeholder: '在 eBay 搜索',
  search_recent: '最近搜索',
  search_saved: '已保存',
  search_clear_recent: '清除最近搜索的内容',
  search_save_search: '保存此搜索',
  search_sort: '排序',
  search_filters: '筛选条件',
  search_shop_by_category: '按类别选购',
  search_results: '个结果',
  search_shipping: '运费',
  search_sponsored: '赞助',
  search_any: '全部',
  search_all_categories: '全部类别',
  search_sample_query: '电风扇',

  // Sell page
  sell_title: '出售',
  sell_info: '请使用网站创建并刊登物品',
  sell_register: '注册',
  sell_login: '登录',
  sell_how_it_works: '运作方式',
  sell_learn_more: '了解详情',

  // Selling steps
  selling_step1_title: '刊登只需几分钟。',
  selling_step1_desc: '拍摄一些照片并撰写精彩的描述。我们会帮助您为物品定价，以促成销售。',
  selling_step2_title: '快速、安全地收款。',
  selling_step2_desc: '当您的物品售出时，我们会让您和买家轻松完成付款流程。',
  selling_step3_title: '向买家发货。',
  selling_step3_desc: '将物品装箱，直接在 eBay 上打印标签，然后寄出。就这么简单。',

  // Settings page
  settings_title: '设置',
  settings_account: '账户',
  settings_sign_in: '登录',
  settings_general: '常规',
  settings_theme: '主题',
  settings_country: '国家或地区',
  settings_country_value: '中国',
  settings_translation: '翻译',
  settings_clear_searches: '清除搜索记录',
  settings_support: '支持',
  settings_customer_service: '客户服务',
  settings_customer_service_desc: '仅提供英语版',
  settings_shake_to_report: '摇动以进行举报',
  settings_about: '关于',
  settings_terms: '用户协议',
  settings_privacy: '隐私权',
  settings_privacy_choices: '您的隐私选择和 AdChoice',
  settings_ads: '广告和相关偏好设置',
  settings_accessibility: '辅助功能',
  settings_legal: '法律',
  settings_version: '版本',
  settings_choose_theme: '选择 App 主题',
  settings_cancel: '取消',
  settings_theme_light: '浅色',
  settings_theme_dark: '深色',
  settings_theme_battery: '节电模式',
  settings_theme_system: '系统默认',
  settings_theme_light_desc: '始终使用浅色主题',
  settings_theme_dark_desc: '始终使用深色主题',
  settings_theme_battery_desc: '仅在设备启用“节电模式”时使用深色主题',
  settings_theme_system_desc: '使用设备显示设置中的主题',

  // Filter drawer
  filter_title: '筛选条件',
  filter_reset: '重置',
  filter_sort: '排序',
  filter_buying_format: '购买形式',
  filter_condition: '物品状况',
  filter_price: '价格',
  filter_category: '类别',
  filter_brand: '品牌',
  filter_location: '物品所在地',
  filter_shipping: '运送选项',
  filter_custom: '自定义',
  filter_show_more: '显示更多内容',
  filter_browse: '浏览',
  filter_camera_hint: '使用相机找到符合条件的物品。',
  filter_show_results: '显示',
  filter_results: '个结果',
  filter_back: '返回',
  filter_auction_desc: '参与拍卖，出价竞争',
  filter_buy_it_now_desc: '直接前往结果页面购买物品',
  filter_offer_desc: '定价和买家意愿达成中！',
  filter_common_price_ranges: '普通价格范围',
  filter_below: '低于',
  filter_between: '至',
  filter_above: '高于',
  filter_choose_price: '选择您的价格',
  filter_min: '最低',
  filter_max: '最高',
  filter_inventory: '现有库存',
  filter_all_categories: '全部类别',
  filter_search_brand: '搜索品牌',
  filter_hot: '热门',
  filter_hot_brand_desc: 'eBay 上最热门的品牌',
  filter_free_shipping: '免费跨国运送',
  filter_custom_hide: '隐藏排序和筛选按钮',
  filter_custom_hide_desc: '排序和筛选按钮将显示在搜索结果的底部',
  filter_custom_expand: '展开全部筛选条件',
  filter_custom_expand_desc: '全部可用筛选条件会保持展开',
  filter_custom_lock: '可锁定筛选条件',
  filter_custom_lock_desc: '锁定筛选条件，使其自动应用于您的搜索',
  filter_location_preset: '预设值',
  filter_location_us_only: '仅限美国',

  // Sort modal
  sort_title: '排序',

  // Categories page
  categories_title: '类别',

  // Item detail page
  item_title: '物品',
  item_in_carts: '在 {count} 人的购物车中',
  item_watchers: '{count}',
  item_seller: '卖家',
  item_positive_feedback: '{pct}% 好评率',
  item_message_seller: '消息',
  item_price_approx: '约 ¥{cny}',
  item_price_per_unit: '({price}/unit)',
  item_or_best_offer: '或议价',
  item_shipping_cost: '{price}（约 ¥{cny}）运费',
  item_free_shipping: '免运费',
  item_est_delivery: '预计送达日期：{date}',
  item_condition: '物品状况',
  item_condition_desc: '物品状况描述',
  item_quantity: '数量',
  item_sold_count: '已售出 {count} 件',
  item_stock_count: '库存 {count} 件',
  item_buy_now: '立即购买',
  item_add_to_cart: '添加至购物车',
  item_make_offer: '提出议价',
  item_add_to_watchlist: '添加至追踪列表',
  item_brand: '品牌',
  item_type: '类型',
  item_location: '所在地',
  item_listed_date: '刊登日期',
  item_item_number: '物品编号',
  item_returns: '退货',
  item_returns_accepted: '卖家接受退货',
  item_payments: '付款',
  item_secure_payment: 'eBay 安全支付',
  item_about: '关于物品',
  item_seller_desc: '卖家提供的物品描述',
  item_view_full_desc: '查看完整描述',
  item_watcher_notice: '其他买家有意向购买此物品。{count} 人正在追踪此物品。',
} as const;

export type StringKey = keyof typeof strings;
