/**
 * Alipay 字符串资源 — 对应 AOSP res/values/strings.xml
 */
export const strings = {

  // ── TabBar ──
  home: '首页',
  finance: '理财',
  video: '视频',
  messages: '消息',
  tabbar_me: '我的',

  // ── 我的页 (MyPage) ──
  balance: '余额',
  hide_all: '一键隐藏',
  use_old_vers: '返回旧版',
  try_new_version: '体验新版',
  pocket: '卡包',
  bank_cards: '银行卡',
  transactions: '账单',
  alipay_love: '公益',
  customer_center: '我的客服',
  favorites: '收藏',
  history: '足迹',
  huabei: '花呗',
  antsure: '蚂蚁保',
  follow: '关注',
  jiebei: '借呗',
  live: '直播',
  sme_loan: '网商贷',
  membership: '支付宝会员',
  merchant_services: '商家服务',
  mybank: '网商银行',
  my_shop: '我的店铺',
  my_miniprograms: '我的小程序',
  abook: '读书听书',
  sports: '运动',
  total_assets: '总资产',
  protection_center: '用户保护中心',
  yue_bao: '余额宝',
  yu_li_bao: '余利宝',
  zhima_credit: '芝麻信用',
  mypage_id: '证件',
  standard: '大众会员',
  complete_tasks_for_cards: '完成任务领福卡',
  view_account_balance: '查看账户余额',
  spending_journal: '消费记录变更手账',
  game: '游戏',
  view: '查看',
  nickname_unset: '未设置昵称',

  // ── 我的民生保障 ──
  my_social_services: '我的民生保障',
  medical_insurance: '医保',
  social_security: '社保',
  housing_fund: '住房公积金',
  employment: '就业',

  // ── 消息页 (MessagesPage) ──
  friends_etc: '搜索好友等',
  notifications: '消息盒子',
  add_contacts: '添加朋友',
  group_chat: '发起群聊',
  qr_code: '扫一扫',
  do_not_disturb: '免打扰',
  mark_as_read: '标为已读',
  mark_as_unread: '标为未读',
  pinned: '置顶',
  unpin: '取消置顶',
  delete_conversation: '删除该聊天',
  delete: '删除',
  cancel: '取消',
  confirm: '确认',
  confirm_2: '确定',
  friend_messages: '有好友新消息',
  no_unread_messages: '当前无未读消息',
  all_messages: '全部会话',
  settings: '消息设置',
  red_packet: '红包',
  transfer: '转账',
  request_money: '收款',
  draft: '草稿',
  no_more: '没有更多',
  people_you_may_know: '可能认识的人',
  stop_recommending: '不再推荐',
  customer_service_message: '客服消息',
  interactive_message: '互动消息',
  lifestyle: '生活号',
  community: '生活圈',
  club: '兴趣社区',
  group_assistant: '群助手',
  finance_circle: '理财盘友圈',
  messagespage_all: '全部',
  follow_finance_friends_for_live_updates: '关注理财"盘"友，查看实盘更新',
  from_finance_circle: '来自理财盘友圈',

  // ── 余额页 (BalancePage) ──
  youth_mode: '青春模式',
  funds_are_safely_secured: '资金安全有保障',
  available_balance_cny: '可用余额(元)',
  complete: '去完善',
  withdraw: '提现',
  top_up: '充值',
  discount: '立减金',
  family_card: '亲情卡',
  dadada: '搭搭哒',
  little_wallet: '小荷包',
  balance_details: '余额变动明细',
  no_records: '暂无记录',
  balancepage_cny: '元',
  balancepage_t: '转',

  // ── 设置页 (SettingsPage) ──
  settings_2: '设置',
  account_and_security: '账号与安全',
  payment_settings: '支付设置',
  elder_mode: '长辈模式',
  student_mode: '学生模式',
  notifications_2: '新消息通知',
  skin_center: '皮肤中心',
  visual_refresh: '视觉风格焕新',
  privacy_security_etc: '隐私设置/安全服务等',
  general: '通用',
  feedback_and_complaints: '反馈与投诉',
  about: '关于',
  version_10_8_20: '版本号 10.8.20',
  log_in_with_another_account: '登录其他账号',
  log_out: '退出登录',
  personal_info_sharing_list: '《个人信息共享清单》',
  personal_info_collected_list: '《个人信息已收集清单》',

  // ── 通用设置 (GeneralSettingsPage) ──
  generalsettingspage_on: '已开启',
  generalsettingspage_off: '已关闭',
  simplified_chinese: '简体中文',
  traditional_chinese_tw: '繁体中文(台湾)',
  traditional_chinese_hk: '繁体中文(香港)',
  widgets_and_shortcuts: '桌面小组件和快捷方式',
  language: '多语言',
  translation: '翻译工具',
  font_size: '字体大小',
  dark_mode: '深色模式',
  speed_mode: '极速模式',
  skin_settings: '皮肤设置',
  home_management: '首页管理',
  video_management: '视频页管理',
  messages_management: '消息页管理',
  my_page_management: '我的页管理',
  other_features: '其他功能管理',
  navigation: '导航设置',
  clipboard: '剪贴板设置',
  refresh_sound: '刷新音效',
  storage_management: '存储空间管理',
  clear_cache: '清理缓存',
  clear_chat_history: '清空聊天记录',

  // ── 语言设置 (LanguageSettingsPage) ──
  language_2: '语言设置',
  languagesettingspage_save: '保存',

  // ── 通用 / 来自 living 反编译 ──
  author: '作者',
  copy: '复制',
  loading: '加载中...',
  loading_2: '加载中',
  report: '举报',
  unfold: '展开',
  refresh: '点击重新加载',
  search: '搜索',

  // ── 错误边界 ──
  app_error: '应用出现错误',

  // ── HomePage ──
  beijing: '北京',
  frequent: '常用',
  manage: '管理',
  recent_messages: '最近消息',
  new_messages: '条新消息',
  for_you: '为你推荐',
  flash_sale_delivery: '闪购·外卖',
  daily_deals: '天天秒杀',
  activate_student_mode_for_exclusive_perks: '开启学生模式享专属特权',
  verify_student_id: '认证学生身份',
  exclusive_perks: '享专属特权',
  activate_student_mode: '开启学生模式',
  charity_ant_forest: '公益·蚂蚁森林',
  energy_stolen: '有能量被偷!',
  protect_your_energy: '快去保护能量',
  collect: '去收取 &gt;',
  green_energy: '绿色能量',
  collect_expired_energy: '收过期能量',
  limited_time: '限时速领',
  energy_available: '有能量可收',
  will_expire_soon: '不收会过期',
  homepage_exp: '过',
  homepage_get: '收',
  zhima_score: '芝麻分',
  fair_credit: '信用中等',
  score_boost_tasks: '涨分任务来啦',
  take_tasks_to_boost: '领任务涨分',
  do_it: '去完成',
  zhima_credit_tips: '芝麻分信用锦囊',
  awaiting_you: '等你去完成',
  go_ahead: '快去做',
  zhima_780_korea_visa_perks: '芝麻分780特权韩国签...',
  simplified_docs: '材料极简化',
  learn_more: '来了解',
  your_spending_report_is_ready: '你的消费详情已出',
  view_your_spending_details: '查看你的消费详情',
  view_now: '立即查看',
  spending_review: '消费回忆',
  weekly_bill: '本周账单',
  earn_with_alipay: '玩赚支付宝',
  cash_rewards_available_today: '今日现金待领取',
  earn_0_01_50_rewards: '赚0.01–50元奖励',
  check_in: '去签到',
  claim: '待领',
  today: '今天',
  tomorrow: '明天',
  day_3: '第3天',
  haidilao: '海底捞',

  // ── FinancePage ──
  total_assets_cny: '总资产(元)',
  free_insurance: '免费升级保障',
  yesterdays_earnings: '昨日收益',
  family_coverage: '家庭保障',
  financepage_n_0: '0份',
  rewards_center: '福利中心',
  can_gold_tickets_redeem_gold_funds_check_it_out: '黄金票能兑黄金基金？去看看',
  fixed_deposit: '买定期',
  major_bank_custody_5m_account_security: '大银行资金托管·500万账户安全',
  ccb_6_months: '中国建设银行 | 6个月',
  boc_6_months: '中国银行 | 6个月',
  rate_trends: '利率动态',
  multiple_banks_lower_deposit_rates: '多家银行继续下调存款利率，市场进入"1时代"',
  n_1_era: '1时代',
  available_fixed_products: '在售定期宝',
  yield_calculator: '收益计算器',
  risk_preference: '风险偏好',
  expected_return: '期望收益',
  expected_term: '期望期限',
  cib_custody: '兴业银行托管',
  target_estimated_yield: '追求测算收益达成',
  est_annual_yield: '测算年化收益率',
  n_6_months: '6个月',
  term: '定期期限',
  try_it_out: '闲钱小试',
  calculate: '算1笔',
  discover_bank_grade_low_risk_investments: '发现 · 银行同款，低风险安稳理财',
  your_dec_savings_report_is_here: '你的12月攒钱报告来了！',

  // ── BillsPage ──
  month_suffix: '月',
  search_transactions: '搜索交易记录',
  expenses: '支出',
  refunds: '退款',
  orders: '订单',
  filter: '筛选',
  reset: '重置',
  amount: '金额',
  category: '分类',
  minimum_amount: '最低金额',
  maximum_amount: '最高金额',
  select_month: '月份选择',
  custom_time: '自定义时间',
  set_spending_budget: '设置支出预算',
  income_and_expense_analysis: '收支分析',
  income: '收入',
  other: '其他',
  transfer_red_packet: '转账红包',
  no_records_this_month: '本月暂无记录',
  turn_on_notifications_to_stay_updated: '开启通知，交易信息不错过',
  enable: '开启',
  bill_details: '账单详情',
  transaction_successful: '交易成功',
  created_time: '创建时间',
  payment_time: '支付时间',
  bill_transfer_note: '转账备注',
  red_packet_description: '红包说明',
  target_account: '对方账户',
  recharge_description: '充值说明',
  product_description: '商品说明',
  recharge_number: '充值号码',
  transaction_target: '交易对象',
  payment_reward: '支付奖励',
  acquiring_institution: '收单机构',
  clearing_institution: '清算机构',
  payee_full_name: '收款方全称',
  service_detail: '服务详情',
  transaction_detail: '交易详情',
  order_number: '订单号',
  merchant_order_number: '商家订单号',
  bill_management: '账单管理',
  bill_category: '账单分类',
  label_2: '标签',
  please_select: '请选择',
  recommended_for_you: '为您推荐',
  include_in_income_and_expense: '计入收支',
  remark: '备注',
  tap_to_add_note: '点击写备注',
  contact_merchant: '联系商家',
  view_interaction_history: '查看往来记录',
  aa_request: 'AA收款',
  transaction_certificate: '往来流水证明',
  request_receipt: '申请电子回单',
  installment: '去分期',
  question_about_order: '对此订单有疑问',
  no_bill_found: '未找到该账单',

  // ── BillAnalysisPage ──
  this_month: '本月',
  total_expenses_cny: '共支出 (元)',
  total_income: '共收入',
  balance_2: '结余',

  // ── TransferPage ──
  to_alipay: '转到支付宝',
  to_bank_card: '转到银行卡',
  recent: '最近',
  contacts: '联系人',
  enter_phone_card_number_or_name_to_transfer: '输入手机号、银行卡号、联系人姓名转账',
  qr_transfer: '二维码转账',
  scheduled_transfer: '预约转账',
  no_fees: '免收手续费',
  instant_arrival: '即刻就到账',
  transfer_history: '转账记录',
  transfer_to_multiple: '向多人转账',
  transferpage_pay: '支',

  // ── TransferToAlipayPage ──
  payees_account: '对方账户',
  phone_name_alipay_account: '手机号/姓名/支付宝账户',
  enter_payees_alipay_account: '填写对方支付宝账号',
  please_verify_account_info_funds_will_arrive: '请确认对方账号信息，资金将实时到账',
  select_recent_contact: '选择最近联系人',
  no_more_2: '没有更多了',
  transfer_without_account: '无账号转账',

  // ── TransferAmountPage ──
  transfer_amount: '转账金额',
  enter_amount: '请输入金额',
  transfer_note: '转账留言',
  add_note_50_chars_max: '添加备注 (50字以内)',
  lend: '出借',
  thanks: '谢谢',
  living_expenses: '生活费',
  rent: '房租',
  buy_for: '代买',
  repayment: '还款',
  transfer_protection: '转账保障',
  customer_service: '客服咨询',
  manual_input: '手动输入',
  unknown: '未知',

  // ── TransferSuccessPage ──
  transfer_successful: '转账成功',
  transfersuccesspage_done: '完成',
  payee: '收款方',
  payment_method: '付款方式',
  account_balance: '账户余额',
  notify_payee_now: '立即通知收款人',
  note: '备注',
  accurate_info_easy_reconciliation: '信息准确，对账无忧',
  notify: '通知TA',
  n_2000g_baba_farm_fertilizer: '2000g 芭芭农场肥料',
  baba_farm: '芭芭农场',
  limited_double: '限时翻倍',
  check_it_out: '去看看',
  n_7_day_online_payment_red_packet: '网上支付7天红包',
  alipay: '支付宝',
  save_0_28_day: '每天减0.28元',
  free: '免费领',
  n_1_lucky_card: '1张 好运卡',
  get_lucky: '接好运',
  up_to_100_credit_card_bonus: '最高开100元信用卡...',
  unknown_user: '未知用户',

  // ── FastPaySettingsPage ──
  quick_pay: '极速付款',
  quick_pay_active: '极速付款中',
  turn_on: '邀你开启',
  hi_you_have_enabled: 'Hi，你已开启',
  account_secured: '账户安全保障中',
  what_is_quick_pay: '极速付款是什么',
  faster_startup: '启动省时',
  clean_interface: '页面简洁',
  small_amount_no_password: '可小额免密',
  fastpaysettingspage_pw: '密',
  enable_small_amount_payment: '开通小额免密',
  payment_authorization_agreement: '《付款授权服务协议》',
  agree_and_enable: '同意协议并开通',
  reminder: '温馨提示',
  disable_quick_pay_no_password_mode: '确认关闭极速付款小额免密？',
  reconsider: '再看看',
  confirm_disable: '确认关闭',
  disable_quick_pay: '是否关闭极速付款？',
  settings_3: '功能设置',
  no_password_payment: '付款免密密码',
  faster_payment: '付款更快',
  pay_without_password_for_amounts_under_200: '200元以内无需密码即可付款',
  per_transaction_limit: '单笔免密额度',
  unlimited: '不限次',
  daily_limit: '单日免密次数',
  preferred_payment: '优先扣款方式',
  charges_per_payment_order: '根据 支付顺序设置 扣款',
  set_up: '去设置',
  payment_easter_egg: '付款彩蛋',
  limited_time_2: '限时体验',
  see_lucky_quotes_and_special_effects_when_paying: '付款时可见幸运语录和专属动效',
  how_to_use_quick_pay: '极速付款怎么用',
  fastpaysettingspage_faq: '常见问题',
  n_1_what_if_quick_pay_uses_the_wrong_payment_method: '1. 极速付款扣不到想要的支付方式怎么办？',
  n_1_set_preferred_payment_on_this_page_2_you_can: '1、可在当前页面，设置扣款方式来指定【优先扣款方式】；2、在支付时，也可以切换【优先扣款方式】。',
  n_2_why_cant_i_use_quick_pay_in_some_scenarios: '2. 为什么我开通了极速付款，但是有些场景无法使用？',
  different_merchants_scenarios_may_vary_if: '不同商户、不同付款场景可能会有差异，若无法使用可返回使用默认付款方式完成支付。',
  disable_quick_pay_2: '关闭极速付款',
  quick_pay_enables_faster_checkout_with_a_clean: '开启后付款将启动极速模式，快速启动超省时，页面简洁少打扰，小金额支持免密支付。',
  agree: '同意',

  // ── PayPage ──
  pay_merchant: '向商家付款',
  prefer_this_payment_method: '优先使用此付款方式',
  tap_to_pay: '碰一下',
  receive: '收钱',
  tap_to_view_payment_code: '点击可查看付款码数字',
  n_0_68_red_packet_expires_in_10h: '0.68 元红包 10 小时后过期',

  // ── ReceivePage ──
  personal_receive: '个人收钱',
  business_receive: '经营收钱',
  set_amount: '设置金额',
  save_image: '保存图片',
  earn_up_to_140_via_tap_receive: '碰收钱最高赚140元',
  go_now: '立即去',
  enable_merchant_services: '开启商家服务',
  free_withdrawal_benefits: '可享提现免费权益',
  get_the_payment_ring_first: '先去下单收钱小蓝环',
  supports_credit_card_huabei: '支持信用卡/花呗',
  payment_records: '收款记录',

  // ── PaymentSettingsPage ──
  payment_password: '支付密码',
  biometric_payment: '生物支付',
  face_id: '面容',
  face_payment_in_stores: '到店刷脸支付',
  tap_to_pay_2: '碰一下支付',
  smart_devices: '智能设备',
  watch_band_smart_card_etc: '手表、手环、智能卡等',
  try_new_payment_methods: '体验全新支付方式',
  payment_order: '支付顺序',
  auto_renew_no_password: '自动续费/免密支付',
  payment_manager: '支付管家',
  payment_lab: '支付实验室',
  benefits_usage: '权益使用',

  // ── PayOrderSettingsPage ──
  general_2: '通用场景',
  custom_order: '自定义顺序',
  auto_match: '系统自动匹配',
  pay_in_list_order: '按列表顺序付款',
  long_press_to_drag: '长按拖动',
  ccb_debit_card_5445: '建设银行储蓄卡 (5445)',

  // ── ContactsPage ──
  contacts_2: '通讯录',
  new_friends: '新的朋友',
  group_chats: '群聊',
  tags: '标签',
  help: '使用与帮助',
  smart_services: '智能服务',
  dedicated_support: '专属客服',
  recent_transfer_contacts: '最近转账联系人',
  a_ming: '阿明',
  lao_wang: '老王',
  xiao_li: '小丽',
  hao_jie: '浩杰',
  contactspage_rui: '锐',

  // ── ContactProfilePage ──
  edit_note: '编辑备注',
  more_info: '更多资料',
  posts: '动态',
  transaction_history: '资金往来记录',
  verified: '已认证',

  // ── BalanceRecordsPage ──
  balance_details_2: '余额明细',

  // ── NotificationSettingsPage ──
  service_notifications: '服务通知',
  transaction_and_security_alerts: '交易与账号安全通知',
  activity_notifications: '活动通知',
  voice_alert_on_receiving_money: '收钱到账语音提醒',
  when_you_receive_via_qr_code: '当你通过二维码收钱时',
  friend_message_alerts: '朋友消息提醒',
  show_message_details: '显示朋友消息详情',
  sound: '声音',
  vibration: '振动',
  voice_and_video_call_notifications: '语音和视频通话通知',
  call_ringtone: '语音和视频通话来电铃声',
  quick_answer_via_popup: '语音和视频通话用弹窗快捷接听',
  when_alipay_is_open: '支付宝打开时',
  when_alipay_is_closed: '支付宝未打开时',

  // ── FontSizeSettingsPage ──
  standard_2: '标准',

  // ── DarkModeSettingsPage ──
  follow_system: '跟随系统',
  light_mode: '普通模式',
  manual: '手动选择',
  when_enabled_dark_mode_follows_system_settings: '开启后，将跟随系统打开或者关闭深色模式',

  // ── SpeedModeSettingsPage ──
  quick_launch: '极速启动',

  // ── ClipboardSettingsPage ──
  allow_clipboard_access: '允许读取剪贴板',

  // ── HomeManagePage ──
  search_box_management: '搜索框管理',
  search_landing_management: '搜索前置页管理',
  app_activity_alerts: '应用动态提醒',
  smart_scene_services: '智能场景服务',
  voice_quick_floating_ball: '语音快捷悬浮球',
  recommended_cards: '推荐卡片',
  activity_banner: '活动氛围图',
  featured_column: '优选栏目',
  pinned_app_order: '置顶应用排序',

  // ── MyPageManagePage ──
  service_reminders: '服务提醒',
  more_services: '更多服务',
  my_orders: '我的订单',
  my_assets: '我的资产',

  // ── SearchBoxManagePage ──
  search_box_style: '搜索框氛围',
  search_suggestions: '搜索框推荐',

  // ── SearchPreManagePage ──
  top_search_suggestions: '顶部搜索推荐词',

  // ── ActivityAmbiencePage ──

  // ── VoiceFloatingBallPage ──

  // ── ChatPage ──
  chat: '聊天',
  hello: '你好！',
  ok_got_it: '好的，收到了。',

  // ── VideoPage ──
  this_page_is_under_construction: '该页面暂未实现内容',

  // ── PaymentPasswordModal ──
  enter_payment_password: '请输入支付密码',
  incorrect_payment_password: '支付密码不正确',
  forgot_password: '忘记密码',
  placeholder: '占位',
  forgot_password_2: '忘记密码?',

  // ── CashierPage（收银台） ──
  order_info: '订单信息',
  confirm_pay: '确认付款',
  cashier_cancel_title: '是否放弃本次付款?',
  cashier_cancel_hint: '只差最后一步，即可完成订单支付。',
  cashier_abandon: '放弃',
  cashier_continue: '继续付款',
  cashier_use_fingerprint: '使用指纹',
  cashier_use_password: '使用密码',
  cashier_account: '账号',
  cashier_yuebao: '余额宝',
  cashier_bank_discount: '立减0.11元',
  cashier_provider: '本服务由支付宝(杭州)数字服务技术有限公司提供',
  cashier_merchant_fallback: '商户',
  cashier_user_initial_fallback: '用',
  cashier_invalid_amount: '金额无效',
  cashier_insufficient_balance: '余额不足',

  // ── PaymentPasswordModal ──
  payment_password_modal_bank_cards: '银行卡',
  payment_password_modal_debit_card: '储蓄卡',
  payment_password_modal_credit: '信贷',
  payment_password_modal_mybank_loan: '网商贷',
  payment_password_modal_available_after_open: '需开通后使用',
  payment_password_modal_unavailable_methods: '以下付款方式暂不可用',
  payment_password_modal_add_bank_card: '添加银行卡付款',

  // ── MultiCardRechargeModal ──
  multi_card_recharge_title: '银行卡组合充值',
  multi_card_recharge_choose_more: '选择更多卡',
  multi_card_recharge_no_cards: '暂无可用银行卡',
  multi_card_recharge_input_placeholder: '点击输入金额，银行单笔限额50000.00',
  multi_card_recharge_total: '本次合计转入',
  multi_card_recharge_next: '下一步',
  multi_card_recharge_confirm: '确定',

  // ── AddBankCardPage ──
  add_bank_card_title: '添加银行卡',
  add_bank_card_secure_hint: '支付宝全力保护你的信息安全',
  add_bank_card_search_placeholder: '输入银行卡名称或本人银行卡号',
  add_bank_card_photo_add: '拍照添卡',
  add_bank_card_tap_to_add: '碰一下添加卡',
  add_bank_card_tap_to_add_hint: '体验全新添卡方式',
  add_bank_card_try_now: '去试试',
  add_bank_card_quick_add: '免输卡号添加',
  add_bank_card_add: '添加',
  add_bank_card_add_card_title: '添加{bankName}银行卡',
  add_bank_card_sms_verify: '需要短信验证确认本人操作',
  add_bank_card_agree_and_add: '同意协议并添加',
  add_bank_card_agreement_hint: '支付宝将向该银行提供您的姓名、证件信息，获取您名下所有可开通快捷支付服务的银行卡号及银行预留手机号，以便您添加。',
  add_bank_card_no_card_hint: '银行侧反馈未查询到可签约的银行卡，请确认绑卡银行名称后重试。',
  add_bank_card_confirm: '确定',
  add_bank_card_exit_title: '是否遇到问题',
  add_bank_card_forgot_number: '忘记卡号也能添加',
  add_bank_card_go_add: '去添加 >',
  add_bank_card_free_insurance: '绑卡后免费享百万账户安全险',
  add_bank_card_go_view: '去查看 >',
  add_bank_card_other_issues: '是否遇到其他问题',
  add_bank_card_feedback: '去反馈 >',
  add_bank_card_quit: '放弃并退出',
  add_bank_card_continue: '继续绑卡',

  // ── AddBankCardVerifyPage ──
  add_bank_card_verify_title: '添加银行卡',
  add_bank_card_verify_done: '完成',
  add_bank_card_verify_add_card: '添加{name}卡',
  add_bank_card_verify_debit_card: '储蓄卡（{masked}）',
  add_bank_card_verify_sent_sms: '已向 {phone} 发送短信验证码',
  add_bank_card_verify_resend: '重发验证码({seconds})',
  add_bank_card_verify_resend_idle: '重发验证码',
  add_bank_card_verify_invalid_code: '验证码错误，请重试',
  add_bank_card_verify_hint_title: '提示',
  add_bank_card_verify_slow_sms: '没有收到验证码？再等等，有的银行发短信比较慢哦',
  add_bank_card_verify_exit: '退出',
  add_bank_card_verify_continue: '继续验证',
  add_bank_card_verify_success: '添加成功',
  add_bank_card_verify_success_hint: '{cardLabel}已放入「我的-银行卡」',
  add_bank_card_verify_easier: '用卡更便捷',
  add_bank_card_verify_share_card: '秋暖心意 分享银行卡给亲友',
  add_bank_card_verify_share_hint: '可设置固定额度，出行购物都能用',
  add_bank_card_verify_explore: '去看看',
  add_bank_card_verify_manage_cards: '管理银行卡',
  add_bank_card_verify_manage_hint: '前往我的银行卡，查账单查卡号等',
  add_bank_card_verify_manage: '去管理',

  // ── BankCardsPage ──
  bank_cards_page_add_card: '添加卡',
  bank_cards_page_featured_banks: '推荐银行服务',
  bank_cards_page_cards: '张银行卡',
  bank_cards_page_debit_balance: '储蓄卡可查余额',
  bank_cards_page_view: '查看',
  bank_cards_page_spending: '有支出',
  bank_cards_page_view_balance: '查余额',
  bank_cards_page_view_number: '查卡号',
  bank_cards_page_view_bill: '查账单',
  bank_cards_page_disabled_cards: '已停用付款的卡',
  bank_cards_page_disabled_count_suffix: '张',
  bank_cards_page_lottery: '银行卡天天抽奖',
  bank_cards_page_lottery_hint: '每日用卡支付 抽惊喜好礼',
  bank_cards_page_go_draw: '去抽奖',
  bank_cards_page_discount: '支付立减金',
  bank_cards_page_discount_hint: '绑卡后可用的立减金',
  bank_cards_page_success_toast: '添加银行卡成功',
  bank_cards_page_debit_card_label: '储蓄卡 {last4}',
  bank_cards_page_bank_card_fallback: '银行卡',

  // ── BillAnalysisPage ──
  bill_analysis_monthly: '月度',
  bill_analysis_yearly: '年度',
  bill_analysis_select_year: '年份选择',
  bill_analysis_total: '共{count}笔',
  bill_analysis_monthly_expense: '本月支出',
  bill_analysis_monthly_income: '本月收入',
  bill_analysis_yearly_expense: '本年支出',
  bill_analysis_yearly_income: '本年收入',
  bill_analysis_green_tag: '绿色能量',
  bill_analysis_green_hint: '查看电子账单得绿色能量8g',
  bill_analysis_expense_categories: '支出分类',
  bill_analysis_top_category: '本月在{name}上的平均每笔支出为¥{avg}',
  bill_analysis_expense_ranking: '支出排行',
  bill_analysis_income_ranking: '收入排行',
  bill_analysis_expense_ranking_hint_monthly: '你最贵的三笔支出占本月支出的{pct}%',
  bill_analysis_expense_ranking_hint_yearly: '你最贵的三笔支出占本年支出的{pct}%',
  bill_analysis_income_ranking_hint_monthly: '你最贵的三笔收入占本月收入的{pct}%',
  bill_analysis_income_ranking_hint_yearly: '你最贵的三笔收入占本年收入的{pct}%',
  bill_analysis_expand_all: '展开全部',
  bill_analysis_expand: '展开',
  bill_analysis_collapse: '收起',
  bill_analysis_expense_compare: '支出对比',
  bill_analysis_income_compare: '收入对比',
  bill_analysis_budget_hint: '设置预算来更好管理你的支出',
  bill_analysis_set_budget: '设置每月预算 >',
  bill_analysis_month: '月',
  bill_analysis_day: '日',
  bill_analysis_no_budget: '预算：无',
  bill_analysis_bank_cards: '银行卡支出',
  bill_analysis_txns: '{count}笔',

  // ── BillSearchPage ──
  bill_search_search_history: '搜索历史',
  bill_search_clear: '清空',
  bill_search_no_records: '没有找到近一年的相关记录',
  bill_search_try_another: '找找其他的吧',
  bill_search_view_earlier_bills: '查看更早的账单',

  // ── BillsPage ──
  bills_filters_applied: '筛选已生效',
  bills_no_records: '没有找到近一年的相关记录',
  bills_try_another: '找找其他的吧',
  bills_view_earlier_bills: '查看更早的账单',

  // ── FinancePage ──
  finance_page_search_hint: '煤炭再度走强 煤超疯要来？',
  finance_page_total_assets: '总资产(元)',
  finance_page_free_upgrade: '免费升级保障',
  finance_page_yesterday_income: '昨日收益',
  finance_page_family_protection: '家庭保障',
  finance_page_family_count: '3份',
  finance_page_rewards_center: '福利中心',
  finance_page_rewards_hint: '理财好礼等你领',
  finance_page_market_hotspot: '市场热点',
  finance_page_headline: '中国电网设备全球“爆单”',
  finance_page_sub1: '北美缺电加剧',
  finance_page_sub2: '出海订单激增',
  finance_page_sub3: '恒生电网领跑同类',
  finance_page_explore: '去看看',
  finance_page_fund_watchlist: '基金自选',
  finance_page_stock_watchlist: '股票自选',
  finance_page_fund_name: '天弘上证50ETF联...',
  finance_page_stock_name: '恒生电子',
  finance_page_low_volatility: '低波动率',
  finance_page_six_month_change: '近6月涨跌幅',
  finance_page_three_day_inflow: '近3日主力净流入',
  finance_page_hot: '热门',
  finance_page_hot_news: '美伊冲突扰动市场 三大指数涨跌互现 甲骨文...',
  finance_page_stock_inflow_value: '-1,597.78万',

  // ── TotalAssetsPage / YuebaoPage ──
  total_assets_page_go_finance: '去理财',
  total_assets_page_banner_cta: '去看看',
  total_assets_page_banner_question: '逾期还款，会影响征信吗？',
  total_assets_page_overview: '资产概览',
  total_assets_page_upgrade_badge: '升百万保障',
  total_assets_page_view_score: '查看理财分',
  total_assets_page_my_assets: '我的资产(元)',
  total_assets_page_current_label: '活期资产',
  total_assets_page_stable_label: '稳健理财',
  total_assets_page_advanced_label: '进阶理财',
  total_assets_page_tab_position: '持仓分析',
  total_assets_page_tab_earning: '收益分析',
  total_assets_page_tab_opportunity: '投资机会',
  total_assets_page_tab_protection: '保障分析',
  total_assets_page_analysis_hint: '关注到你目前已经清仓，接下来有投资计划吗？',
  total_assets_page_guess_ask: '猜你想问：',
  total_assets_page_btn_observe: '还在观望中',
  total_assets_page_btn_opportunity: '有新的好机会吗',
  total_assets_page_wealth_section: '理财资产',
  total_assets_page_fixed: '定期',
  total_assets_page_fixed_hint: '收益稳健',
  total_assets_page_funds: '基金',
  total_assets_page_funds_hint: '10元试试',
  total_assets_page_gold: '黄金',
  total_assets_page_gold_hint: '买入0费率',
  total_assets_page_broker: '券商理财',
  total_assets_page_broker_hint: '更稳更专业',
  yuebao_page_fund_pill: '广发钱袋子货... 七日年化1.0300%',
  yuebao_page_announce: '清明假期余额宝收益及转出提醒',
  yuebao_page_total: '总金额(元)',
  yuebao_page_safe: '资金安全',
  yuebao_page_yesterday_label: '昨日收益(元)',
  yuebao_page_no_earnings: '暂无收益',
  yuebao_page_cumulative_label: '累计收益(元)',
  yuebao_page_cumulative_demo: '1.89',
  yuebao_page_money_tree: '摇钱树',
  yuebao_page_out: '转出',
  yuebao_page_in: '转入',
  yuebao_page_schedule: '定时转入',
  yuebao_page_subsidy: '攒钱补贴',
  yuebao_page_subsidy_claim: '领取1.08元支付红包',
  yuebao_page_icon_save: '攒着',
  yuebao_page_icon_cash: '领现金',
  yuebao_page_icon_earn: '闲钱多赚',
  yuebao_page_icon_current: '活钱理财',
  yuebao_page_icon_more: '更多',
  yuebao_page_promo_title_before: '限时得 ',
  yuebao_page_promo_title_highlight: '1元',
  yuebao_page_promo_title_after: '现金',
  yuebao_page_promo_sub: '花一笔 赚一笔',
  yuebao_page_promo_btn: '立即领取',
  yuebao_page_steady: '稳健理财',
  yuebao_page_steady_more: '追求更高收益',
  yuebao_page_current_row: '活期理财',
  yuebao_page_current_rate: '2.88%',

  // ── PaymentPasswordChangePage ──
  payment_password_change_remember_account: '您是否记得账号',
  payment_password_change_current_password: '当前使用的支付密码',
  payment_password_change_forgot: '不记得',
  payment_password_change_remember: '记得',
  payment_password_change_title: '修改支付密码',
  payment_password_change_forgot_hint: '当前演示暂不支持找回支付密码，请选择"记得"进行验证。',
  payment_password_change_back: '返回',
  payment_password_change_verify_title: '验证支付密码',
  payment_password_change_verify_hint: '输入当前支付密码，以身份验证',
  payment_password_change_set_title: '设置新支付密码',
  payment_password_change_set_hint: '请输入6位数字作为新支付密码',
  payment_password_change_done: '支付密码已更新',
  payment_password_change_wrong_password: '支付密码错误，请重试',
  payment_password_change_same_password: '新支付密码不能与原密码相同',
  payment_password_change_invalid_password: '支付密码不能是重复、连续的数字',

  // ── RechargeCardPage ──
  recharge_card_title: '充值卡充值',
  recharge_card_number: '充值卡号',
  recharge_card_example: '例如 ALIPAY100',
  recharge_card_confirm: '确认充值',
  recharge_card_failed: '充值失败：卡号无效或已使用',
  recharge_card_success: '充值成功：+{value}元',
  recharge_card_available_cards: '可用充值卡',
  recharge_card_used: '已使用',
  recharge_card_value: '+{value}元',

  // ── RechargePage ──
  recharge_page_title: '充值',
  recharge_page_method: '充值方式',
  recharge_page_add_card: '请添加银行卡',
  recharge_page_limit_hint: '该卡本次最多可转入¥50000',
  recharge_page_amount: '充值金额',
  recharge_page_bank_fast_top_up: '银行快充',
  recharge_page_bank_fast_hint: '充值金额更高',
  recharge_page_multi_card: '多卡充值',
  recharge_page_multi_card_hint: '多张卡充值一次完成',
  recharge_page_collapse: '收起',
  recharge_page_expand: '全部',
  recharge_page_confirm: '充值',
  recharge_page_select_method: '选择充值方式',
  recharge_page_bank_limit: '银行单笔限额50000.00元',
  recharge_page_ask_family: '找家人朋友代充',
  recharge_page_add_debit_card: '添加储蓄卡充值',

  // ── RechargeSuccessPage ──
  recharge_success_title: '充值成功',
  recharge_success_transfer_result: '转入结果',
  recharge_success_success: '转入成功',
  recharge_success_done: '完成',
  recharge_success_home: '回首页',
  recharge_success_payment_method: '付款方式',
  recharge_success_coupon: '全场券',
  recharge_success_coupon_hint: '便宜寄寄快递 满0.1元可用',
  recharge_success_free_claim: '免费领',
  recharge_success_shopping_coupon: '购物券 不挑皮 种籽气垫',
  recharge_success_shopping_hint: '平台补贴 24小时持妆不暗沉',
  recharge_success_explore: '去看看',
  recharge_success_bank_card: '银行卡',

  // ── RefundPage ──
  refund_page_title: '退款',
  refund_page_refund_to_payer: '退款给付款方',
  refund_page_confirm: '确认退款',
  refund_page_merchant_fallback: '商户',

  // ── SubscriptionsPage ──
  subscriptions_title: '会员订阅',
  subscriptions_membership_type: '会员类型',
  subscriptions_price: '价格（元）',
  subscriptions_billing_cycle: '周期',
  subscriptions_auto_renew_on: '已开启自动续费',
  subscriptions_auto_renew_off: '未开启自动续费',
  subscriptions_submit: '确认订阅并支付',
  subscriptions_type_required: '会员类型不能为空',
  subscriptions_invalid_price: '价格无效',
  subscriptions_insufficient: '余额不足',

  n_800_pt_service_upgrade: '800分服务升级',

  // ── 补充缺失 ──
  transfer_to_payee: '向 {payeeName} 转账',
  activity_ambience_description: '首页活动氛围图位于置顶应用和应用宫格中间。开关开启时，当支付宝开展大型营销活动（如新春活动），您可以在该区域进入活动。关闭开关后，将不再展示活动氛围图。',
  expense_breakdown: '支出构成',
  chart_area_transfer: '图表区域: 转账',
  monthly_comparison: '月度对比',
  chatpage_me: '我',
  chatpage_send: '发送',
  clipboard_on_description: '开启状态下，剪贴板信息仅会在您的设备上进行处理，支付宝不会存储您的剪贴板信息或用于任何其它用途。',
  clipboard_off_description: '关闭后，将不再读取剪贴板信息，在吱口令、搜索等场景下，使用体验可能会受到影响。',
  contact_not_found: 'Contact not found',
  alipay_account: '支付宝账户',
  real_name: '真实姓名',
  send_message: '发消息',
  send_red_packet: '发红包',
  go_transfer: '去转账',
  friends_count_suffix: '个朋友',
  preview_font_size: '预览字体大小',
  drag_slider_to_set_font_size: '拖动下面的滑块，可设置字体大小',
  font_size_change_description: '设置后，会改变我的、朋友消息列表和聊天会话页面字体大小，选择一个适合自己的字体大小吧。',
  go_collect: '去收取',
  mypage_manage_description: '你可以开启或隐藏我的相关服务，若移除部分服务，相应的服务入口将隐藏，但不会清空任何历史数据。',
  mypage_manage_basic_note: '支付宝会员、用户保护中心、账单、总资产等基础服务暂不支持移除。',
  pay_and_receive: '收付款',
  payment_rewards: '支付有礼',

  // ── 扫一扫页 (ScanPage) ──
  scan_code: '扫码',
  scan_light: '灵光',
  scan_no_qr_found: '未扫描到二维码？获取帮助',
  scan_album: '相册',
  search_box_manage_description: '首页搜索框会为你推荐你可能感兴趣的推荐词，或在特定的时间节点进行搜索框装扮，也可选择关闭该功能，相应的推荐词或氛围装扮将不再展示。',
  search_pre_manage_description: '顶部搜索推荐词会为你推荐你可能感兴趣的搜索词，也可选择关闭该功能，这些搜索词将不再展示。',
  speed_mode_description: '设备运行较慢时，将自动收起首页推荐并减少后台服务，加快页面浏览',
  transfer_protection_off: '转账保障未开启',
  recent_contacts: '最近联系人',
  people_you_may_want_to_send: '你可能想发的人',
  account_not_found_try_again: '你搜索的账号不存在，请更换手机号或邮箱后重新搜索',
  voice_floating_ball_description: '开启语音快捷悬浮球，你可以在支付宝端的任何页面，通过语音唤醒服务，先人一步快速打开服务。',
  bank_rate_news: '多家银行继续下调存款利率，市场进入"1时代"',
  follow_finance_friends: '关注理财"盘"友，查看实盘更新',
} as const;

export type StringKey = keyof typeof strings;
