/**
 * Alipay 英文翻译 — 对应 AOSP res/values-en/strings.xml
 */
import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {

  // ── TabBar ──
  home: 'Home',
  finance: 'Finance',
  video: 'Video',
  messages: 'Messages',
  tabbar_me: 'Me',

  // ── 我的页 (MyPage) ──
  balance: 'Balance',
  hide_all: 'Hide All',
  use_old_vers: 'Use Old Vers.',
  try_new_version: 'Try New Version',
  pocket: 'Pocket',
  bank_cards: 'Bank Cards',
  transactions: 'Bills',
  alipay_love: 'Alipay Love',
  customer_center: 'Customer Center',
  favorites: 'Favorites',
  history: 'History',
  huabei: 'Huabei',
  antsure: 'Ant Insurance',
  follow: 'Follow',
  jiebei: 'Jiebei',
  live: 'Live',
  sme_loan: 'SME Loan',
  membership: 'Membership',
  merchant_services: 'Merchant Services',
  mybank: 'MYbank',
  my_shop: 'My Shop',
  my_miniprograms: 'My MiniPrograms',
  abook: 'Abook',
  sports: 'Sports',
  total_assets: 'Total Assets',
  protection_center: 'Protection Center',
  yue_bao: "Yu'E Bao",
  yu_li_bao: 'Yu Li Bao',
  zhima_credit: 'Zhima',
  mypage_id: 'ID',
  standard: 'Standard',
  complete_tasks_for_cards: 'Complete tasks for cards',
  view_account_balance: 'View account balance',
  spending_journal: 'Spending journal',
  game: 'Game',
  view: 'View',
  nickname_unset: 'Nickname Unset',

  // ── 我的民生保障 ──
  my_social_services: 'My Social Services',
  medical_insurance: 'Health Insurance',
  social_security: 'Social Insurance',
  housing_fund: 'Housing Fund',
  employment: 'Z jobs',

  // ── 消息页 (MessagesPage) ──
  friends_etc: 'Friends, etc.',
  notifications: 'Notifications',
  add_contacts: 'Add Contacts',
  group_chat: 'Group Chat',
  qr_code: 'QR Code',
  do_not_disturb: 'Do Not Disturb',
  mark_as_read: 'Mark as Read',
  mark_as_unread: 'Mark as Unread',
  pinned: 'Pinned',
  unpin: 'Unpin',
  delete_conversation: 'Delete conversation',
  delete: 'Delete',
  cancel: 'Cancel',
  confirm: 'Confirm',
  confirm_2: 'Confirm',
  friend_messages: 'Friend Messages',
  no_unread_messages: 'No unread messages',
  all_messages: 'All messages',
  settings: 'Settings',
  red_packet: 'Red Packet',
  transfer: 'Transfer',
  request_money: 'Request Money',
  draft: 'Draft',
  no_more: 'No more',
  people_you_may_know: 'People you may know',
  stop_recommending: 'Stop recommending',
  customer_service_message: 'Customer Service Message',
  interactive_message: 'Interactive Message',
  lifestyle: 'Lifestyle',
  community: 'Community',
  club: 'Club',
  group_assistant: 'Group Assistant',
  finance_circle: 'Finance Circle',
  messagespage_all: 'All',
  follow_finance_friends_for_live_updates: 'Follow finance friends for live updates',
  from_finance_circle: 'From Finance Circle',

  // ── 余额页 (BalancePage) ──
  youth_mode: 'Youth Mode',
  funds_are_safely_secured: 'Funds are safely secured',
  available_balance_cny: 'Available Balance (CNY)',
  complete: 'Complete',
  withdraw: 'Withdraw',
  top_up: 'Top Up',
  discount: 'Discount',
  family_card: 'Family Card',
  dadada: 'DaDaDa',
  little_wallet: 'Little Wallet',
  balance_details: 'Balance Details',
  no_records: 'No records',
  balancepage_cny: 'CNY',
  balancepage_t: 'T',

  // ── 设置页 (SettingsPage) ──
  settings_2: 'Settings',
  account_and_security: 'Account & Security',
  payment_settings: 'Payment Settings',
  elder_mode: 'Elder Mode',
  student_mode: 'Student Mode',
  notifications_2: 'Notifications',
  skin_center: 'Skin Center',
  visual_refresh: 'Visual Refresh',
  privacy_security_etc: 'Privacy / Security, etc.',
  general: 'General',
  feedback_and_complaints: 'Help and Feedback',
  about: 'About',
  version_10_8_20: 'Version 10.8.20',
  log_in_with_another_account: 'Switch Account',
  log_out: 'Log out',
  personal_info_sharing_list: 'Personal Info Sharing List',
  personal_info_collected_list: 'Personal Info Collected List',

  // ── 通用设置 (GeneralSettingsPage) ──
  generalsettingspage_on: 'Enabled',
  generalsettingspage_off: 'Disabled',
  simplified_chinese: 'Simplified Chinese',
  traditional_chinese_tw: 'Traditional Chinese (TW)',
  traditional_chinese_hk: 'Traditional Chinese (HK)',
  widgets_and_shortcuts: 'Desktop Widgets & Shortcuts',
  language: 'Language',
  translation: 'Translation Tool',
  font_size: 'Font Size',
  dark_mode: 'Dark Mode',
  speed_mode: 'Speed Mode',
  skin_settings: 'Skin Settings',
  home_management: 'Home Management',
  video_management: 'Video Management',
  messages_management: 'Messages Management',
  my_page_management: 'My Page Management',
  other_features: 'Other Features',
  navigation: 'Navigation',
  clipboard: 'Clipboard',
  refresh_sound: 'Refresh Sound',
  storage_management: 'Storage Management',
  clear_cache: 'Clear Cache',
  clear_chat_history: 'Clear Chat History',

  // ── 语言设置 (LanguageSettingsPage) ──
  language_2: 'Language',
  languagesettingspage_save: 'Save',

  // ── 通用 / 来自 living 反编译 ──
  author: 'Author',
  copy: 'Copy',
  loading: 'Loading...',
  loading_2: 'Loading',
  report: 'Report',
  unfold: 'Unfold',
  refresh: 'Refresh',
  search: 'Search',

  // ── 错误边界 ──
  app_error: 'App Error',

  // ── HomePage ──
  beijing: 'Beijing',
  frequent: 'Frequent',
  manage: 'Manage',
  recent_messages: 'Recent Messages',
  new_messages: 'new messages',
  for_you: 'For You',
  flash_sale_delivery: 'Flash Sale · Delivery',
  daily_deals: 'Daily Deals',
  activate_student_mode_for_exclusive_perks: 'Activate Student Mode for exclusive perks',
  verify_student_id: 'Verify Student ID',
  exclusive_perks: 'Exclusive perks',
  activate_student_mode: 'Activate Student Mode',
  charity_ant_forest: 'Charity · Ant Forest',
  energy_stolen: 'Energy stolen!',
  protect_your_energy: 'Protect your energy',
  collect: 'Collect >',
  green_energy: 'Green Energy',
  collect_expired_energy: 'Collect expired energy',
  limited_time: 'Limited time',
  energy_available: 'Energy available',
  will_expire_soon: 'Will expire soon',
  homepage_exp: 'Exp',
  homepage_get: 'Get',
  zhima_score: 'Zhima Score',
  fair_credit: 'Fair Credit',
  score_boost_tasks: 'Score boost tasks',
  take_tasks_to_boost: 'Take tasks to boost',
  do_it: 'Do it',
  zhima_credit_tips: 'Zhima Credit Tips',
  awaiting_you: 'Awaiting you',
  go_ahead: 'Go ahead',
  zhima_780_korea_visa_perks: 'Zhima 780 Korea visa perks...',
  simplified_docs: 'Simplified docs',
  learn_more: 'Learn more',
  your_spending_report_is_ready: 'Your spending report is ready',
  view_your_spending_details: 'View your spending details',
  view_now: 'View now',
  spending_review: 'Spending Review',
  weekly_bill: 'Weekly Bill',
  earn_with_alipay: 'Earn with Alipay',
  cash_rewards_available_today: 'Cash rewards available today',
  earn_0_01_50_rewards: 'Earn ¥0.01–50 rewards',
  check_in: 'Check in',
  claim: 'Claim',
  today: 'Today',
  tomorrow: 'Tomorrow',
  day_3: 'Day 3',
  haidilao: 'Haidilao',

  // ── FinancePage ──
  total_assets_cny: 'Total Assets (CNY)',
  free_insurance: 'Free Insurance',
  yesterdays_earnings: "Yesterday's Earnings",
  family_coverage: 'Family Coverage',
  financepage_n_0: '0',
  rewards_center: 'Rewards Center',
  can_gold_tickets_redeem_gold_funds_check_it_out: 'Can gold tickets redeem gold funds? Check it out',
  fixed_deposit: 'Fixed Deposit',
  major_bank_custody_5m_account_security: 'Major bank custody · ¥5M account security',
  ccb_6_months: 'CCB | 6 months',
  boc_6_months: 'BOC | 6 months',
  rate_trends: 'Rate Trends',
  multiple_banks_lower_deposit_rates: 'Multiple banks lower deposit rates',
  n_1_era: '1-era',
  available_fixed_products: 'Available Fixed Products',
  yield_calculator: 'Yield Calculator',
  risk_preference: 'Risk Preference',
  expected_return: 'Expected Return',
  expected_term: 'Expected Term',
  cib_custody: 'CIB Custody',
  target_estimated_yield: 'Target estimated yield',
  est_annual_yield: 'Est. annual yield',
  n_6_months: '6 months',
  term: 'Term',
  try_it_out: 'Try it out',
  calculate: 'Calculate',
  discover_bank_grade_low_risk_investments: 'Discover · Bank-grade, low-risk investments',
  your_dec_savings_report_is_here: 'Your Dec savings report is here!',

  // ── BillsPage ──
  month_suffix: '',
  search_transactions: 'Search transactions',
  expenses: 'Expenses',
  refunds: 'Refunds',
  orders: 'Orders',
  filter: 'Filter',
  reset: 'Reset',
  amount: 'Amount',
  category: 'Category',
  minimum_amount: 'Min amount',
  maximum_amount: 'Max amount',
  select_month: 'Select Month',
  custom_time: 'Custom Time',
  set_spending_budget: 'Set spending budget',
  income_and_expense_analysis: 'Analysis',
  income: 'Income',
  other: 'Other',
  transfer_red_packet: 'Transfer Red Packet',
  no_records_this_month: 'No records this month',
  turn_on_notifications_to_stay_updated: 'Turn on notifications to stay updated',
  enable: 'Enable',
  bill_details: 'Bill Details',
  transaction_successful: 'Transaction Successful',
  created_time: 'Created Time',
  payment_time: 'Payment Time',
  bill_transfer_note: 'Transfer Note',
  red_packet_description: 'Red Packet Description',
  target_account: 'Target Account',
  recharge_description: 'Recharge Description',
  product_description: 'Product Description',
  recharge_number: 'Recharge Number',
  transaction_target: 'Transaction Target',
  payment_reward: 'Reward',
  acquiring_institution: 'Acquiring Institution',
  clearing_institution: 'Clearing Institution',
  payee_full_name: 'Payee Full Name',
  service_detail: 'Service Detail',
  transaction_detail: 'Transaction Detail',
  order_number: 'Order No.',
  merchant_order_number: 'Merchant Order No.',
  bill_management: 'Bill Management',
  bill_category: 'Bill Category',
  label_2: 'Label',
  please_select: 'Please select',
  recommended_for_you: 'Recommended',
  include_in_income_and_expense: 'Include in income/expense',
  remark: 'Remark',
  tap_to_add_note: 'Tap to add a note',
  contact_merchant: 'Contact Merchant',
  view_interaction_history: 'View History',
  aa_request: 'AA Request',
  transaction_certificate: 'Transaction Certificate',
  request_receipt: 'Request Receipt',
  installment: 'Installment',
  question_about_order: 'Question About Order',
  no_bill_found: 'Bill not found',

  // ── BillAnalysisPage ──
  this_month: 'This Month',
  total_expenses_cny: 'Total Expenses (CNY)',
  total_income: 'Total Income',
  balance_2: 'Balance',

  // ── TransferPage ──
  to_alipay: 'To Alipay',
  to_bank_card: 'To Bank Card',
  recent: 'Recent',
  contacts: 'Contacts',
  enter_phone_card_number_or_name_to_transfer: 'Enter phone, card number, or name to transfer',
  qr_transfer: 'QR Transfer',
  scheduled_transfer: 'Scheduled Transfer',
  no_fees: 'No fees',
  instant_arrival: 'Instant arrival',
  transfer_history: 'Transfer History',
  transfer_to_multiple: 'Transfer to multiple',
  transferpage_pay: 'Pay',

  // ── TransferToAlipayPage ──
  payees_account: "Payee's Account",
  phone_name_alipay_account: 'Phone / Name / Alipay account',
  enter_payees_alipay_account: "Enter payee's Alipay account",
  please_verify_account_info_funds_will_arrive: 'Please verify account info. Funds will arrive instantly.',
  select_recent_contact: 'Select recent contact',
  no_more_2: 'No more',
  transfer_without_account: 'Transfer without account',

  // ── TransferAmountPage ──
  transfer_amount: 'Transfer Amount',
  enter_amount: 'Enter amount',
  transfer_note: 'Transfer Note',
  add_note_50_chars_max: 'Add note (50 chars max)',
  lend: 'Lend',
  thanks: 'Thanks',
  living_expenses: 'Living expenses',
  rent: 'Rent',
  buy_for: 'Buy for',
  repayment: 'Repayment',
  transfer_protection: 'Transfer Protection',
  customer_service: 'Customer Service',
  manual_input: 'Manual Input',
  unknown: 'Unknown',

  // ── TransferSuccessPage ──
  transfer_successful: 'Transfer Successful',
  transfersuccesspage_done: 'Done',
  payee: 'Payee',
  payment_method: 'Payment Method',
  account_balance: 'Account Balance',
  notify_payee_now: 'Notify payee now',
  note: 'Note',
  accurate_info_easy_reconciliation: 'Accurate info, easy reconciliation',
  notify: 'Notify',
  n_2000g_baba_farm_fertilizer: '2000g Baba Farm Fertilizer',
  baba_farm: 'Baba Farm',
  limited_double: 'Limited double',
  check_it_out: 'Check it out',
  n_7_day_online_payment_red_packet: '7-Day Online Payment Red Packet',
  alipay: 'Alipay',
  save_0_28_day: 'Save ¥0.28/day',
  free: 'Free',
  n_1_lucky_card: '1 Lucky Card',
  get_lucky: 'Get Lucky',
  up_to_100_credit_card_bonus: 'Up to ¥100 credit card bonus...',
  unknown_user: 'Unknown User',

  // ── FastPaySettingsPage ──
  quick_pay: 'Quick Pay',
  quick_pay_active: 'Quick Pay active',
  turn_on: 'Turn on',
  hi_you_have_enabled: 'Hi, you have enabled',
  account_secured: 'Account secured',
  what_is_quick_pay: 'What is Quick Pay',
  faster_startup: 'Faster startup',
  clean_interface: 'Clean interface',
  small_amount_no_password: 'Small amount no-password',
  fastpaysettingspage_pw: 'PW',
  enable_small_amount_payment: 'Enable small amount payment',
  payment_authorization_agreement: 'Payment Authorization Agreement',
  agree_and_enable: 'Agree & Enable',
  reminder: 'Reminder',
  disable_quick_pay_no_password_mode: 'Disable Quick Pay no-password mode?',
  reconsider: 'Reconsider',
  confirm_disable: 'Confirm Disable',
  disable_quick_pay: 'Disable Quick Pay?',
  settings_3: 'Settings',
  no_password_payment: 'No-password Payment',
  faster_payment: 'Faster payment',
  pay_without_password_for_amounts_under_200: 'Pay without password for amounts under ¥200',
  per_transaction_limit: 'Per-transaction limit',
  unlimited: 'Unlimited',
  daily_limit: 'Daily limit',
  preferred_payment: 'Preferred Payment',
  charges_per_payment_order: 'Charges per payment order',
  set_up: 'Set up',
  payment_easter_egg: 'Payment Easter Egg',
  limited_time_2: 'Limited time',
  see_lucky_quotes_and_special_effects_when_paying: 'See lucky quotes and special effects when paying',
  how_to_use_quick_pay: 'How to use Quick Pay',
  fastpaysettingspage_faq: 'FAQ',
  n_1_what_if_quick_pay_uses_the_wrong_payment_method: '1. What if Quick Pay uses the wrong payment method?',
  n_1_set_preferred_payment_on_this_page_2_you_can: '1. Set preferred payment on this page. 2. You can also switch during payment.',
  n_2_why_cant_i_use_quick_pay_in_some_scenarios: "2. Why can't I use Quick Pay in some scenarios?",
  different_merchants_scenarios_may_vary_if: 'Different merchants/scenarios may vary. If unavailable, use the default payment method.',
  disable_quick_pay_2: 'Disable Quick Pay',
  quick_pay_enables_faster_checkout_with_a_clean: 'Quick Pay enables faster checkout with a clean interface and no-password for small amounts.',
  agree: 'Agree',

  // ── PayPage ──
  pay_merchant: 'Pay Merchant',
  prefer_this_payment_method: 'Prefer this payment method',
  tap_to_pay: 'Tap to Pay',
  receive: 'Receive',
  tap_to_view_payment_code: 'Tap to view payment code',
  n_0_68_red_packet_expires_in_10h: '¥0.68 red packet expires in 10h',

  // ── ReceivePage ──
  personal_receive: 'Personal Receive',
  business_receive: 'Business Receive',
  set_amount: 'Set Amount',
  save_image: 'Save Image',
  earn_up_to_140_via_tap_receive: 'Earn up to ¥140 via Tap Receive',
  go_now: 'Go now',
  enable_merchant_services: 'Enable Merchant Services',
  free_withdrawal_benefits: 'Free withdrawal benefits',
  get_the_payment_ring_first: 'Get the payment ring first',
  supports_credit_card_huabei: 'Supports credit card / Huabei',
  payment_records: 'Payment Records',

  // ── PaymentSettingsPage ──
  payment_password: 'Payment Password',
  biometric_payment: 'Biometric Payment',
  face_id: 'Face ID',
  face_payment_in_stores: 'Face payment in stores',
  tap_to_pay_2: 'Tap to Pay',
  smart_devices: 'Smart Devices',
  watch_band_smart_card_etc: 'Watch, band, smart card, etc.',
  try_new_payment_methods: 'Try new payment methods',
  payment_order: 'Payment Priority',
  auto_renew_no_password: 'Auto-renew / Password-Free Payments',
  payment_manager: 'Payment Manager',
  payment_lab: 'Payment Lab',
  benefits_usage: 'Benefits Usage',

  // ── PayOrderSettingsPage ──
  general_2: 'General',
  custom_order: 'Custom Order',
  auto_match: 'Auto Match',
  pay_in_list_order: 'Pay in list order',
  long_press_to_drag: 'Long press to drag',
  ccb_debit_card_5445: 'CCB Debit Card (5445)',

  // ── ContactsPage ──
  contacts_2: 'Contacts',
  new_friends: 'New Friends',
  group_chats: 'Group Chats',
  tags: 'Tags',
  help: 'Help',
  smart_services: 'Smart Services',
  dedicated_support: 'Dedicated Support',
  recent_transfer_contacts: 'Recent Transfer Contacts',
  a_ming: 'A Ming',
  lao_wang: 'Lao Wang',
  xiao_li: 'Xiao Li',
  hao_jie: 'Hao Jie',
  contactspage_rui: 'Rui',

  // ── ContactProfilePage ──
  edit_note: 'Edit Note',
  more_info: 'More Info',
  posts: 'Posts',
  transaction_history: 'Transaction History',
  verified: 'Verified',

  // ── BalanceRecordsPage ──
  balance_details_2: 'Balance Details',

  // ── NotificationSettingsPage ──
  service_notifications: 'Service Notifications',
  transaction_and_security_alerts: 'Transaction & Account Security Alerts',
  activity_notifications: 'Activity Notifications',
  voice_alert_on_receiving_money: 'Voice alert on receiving money',
  when_you_receive_via_qr_code: 'When you receive via QR code',
  friend_message_alerts: 'Friend Message Alerts',
  show_message_details: 'Show Message Content',
  sound: 'Sound',
  vibration: 'Vibration',
  voice_and_video_call_notifications: 'Voice & Video Call Notifications',
  call_ringtone: 'Voice & Video Call Ringtone',
  quick_answer_via_popup: 'Quick answer via popup',
  when_alipay_is_open: 'When Alipay is open',
  when_alipay_is_closed: 'When Alipay is closed',

  // ── FontSizeSettingsPage ──
  standard_2: 'Standard',

  // ── DarkModeSettingsPage ──
  follow_system: 'Follow System',
  light_mode: 'Light Mode',
  manual: 'Manual',
  when_enabled_dark_mode_follows_system_settings: 'When enabled, dark mode follows system settings',

  // ── SpeedModeSettingsPage ──
  quick_launch: 'Quick Launch',

  // ── ClipboardSettingsPage ──
  allow_clipboard_access: 'Allow clipboard access',

  // ── HomeManagePage ──
  search_box_management: 'Search Box Management',
  search_landing_management: 'Search Landing Management',
  app_activity_alerts: 'App Activity Alerts',
  smart_scene_services: 'Smart Scene Services',
  voice_quick_floating_ball: 'Voice Quick Floating Ball',
  recommended_cards: 'Recommended Cards',
  activity_banner: 'Activity Banner',
  featured_column: 'Featured Column',
  pinned_app_order: 'Pinned App Order',

  // ── MyPageManagePage ──
  service_reminders: 'Service Reminders',
  more_services: 'More Services',
  my_orders: 'My Orders',
  my_assets: 'My Assets',

  // ── SearchBoxManagePage ──
  search_box_style: 'Search Box Style',
  search_suggestions: 'Search Suggestions',

  // ── SearchPreManagePage ──
  top_search_suggestions: 'Top Search Suggestions',

  // ── ActivityAmbiencePage ──

  // ── VoiceFloatingBallPage ──

  // ── ChatPage ──
  chat: 'Chat',
  hello: 'Hello!',
  ok_got_it: 'OK, got it.',

  // ── VideoPage ──
  this_page_is_under_construction: 'This page is under construction',

  // ── PaymentPasswordModal ──
  enter_payment_password: 'Enter payment password',
  incorrect_payment_password: 'Incorrect payment password',
  forgot_password: 'Forgot password',
  placeholder: 'Placeholder',
  forgot_password_2: 'Forgot password?',
  cashier_cancel_title: 'Give up this payment?',
  cashier_cancel_hint: 'Only one step left to complete the order payment.',
  cashier_abandon: 'Give Up',
  cashier_continue: 'Continue',
  cashier_use_fingerprint: 'Use Fingerprint',
  cashier_use_password: 'Use Password',
  cashier_account: 'Account',
  cashier_yuebao: "Yu'e Bao",
  cashier_bank_discount: 'Save ¥0.11',
  cashier_provider: 'Provided by Alipay Digital Services Co., Ltd.',
  cashier_merchant_fallback: 'Merchant',
  cashier_user_initial_fallback: 'U',
  cashier_invalid_amount: 'Invalid amount',
  cashier_insufficient_balance: 'Insufficient balance',
  payment_password_modal_bank_cards: 'Bank Cards',
  payment_password_modal_debit_card: 'Debit Card',
  payment_password_modal_credit: 'Credit',
  payment_password_modal_mybank_loan: 'MYbank Loan',
  payment_password_modal_available_after_open: 'Available after activation',
  payment_password_modal_unavailable_methods: 'The following payment methods are unavailable',
  payment_password_modal_add_bank_card: 'Add bank card to pay',
  multi_card_recharge_title: 'Multi-card Top-up',
  multi_card_recharge_choose_more: 'Choose more cards',
  multi_card_recharge_no_cards: 'No bank cards available',
  multi_card_recharge_input_placeholder: 'Tap to enter amount, single-card limit ¥50000.00',
  multi_card_recharge_total: 'Total this time',
  multi_card_recharge_next: 'Next',
  multi_card_recharge_confirm: 'OK',
  add_bank_card_title: 'Add Bank Card',
  add_bank_card_secure_hint: 'Alipay fully protects your information security',
  add_bank_card_search_placeholder: 'Enter bank name or your card number',
  add_bank_card_photo_add: 'Scan Card',
  add_bank_card_tap_to_add: 'Tap to Add Card',
  add_bank_card_tap_to_add_hint: 'Try the new way to add cards',
  add_bank_card_try_now: 'Try Now',
  add_bank_card_quick_add: 'Quick Add Without Card Number',
  add_bank_card_add: 'Add',
  add_bank_card_add_card_title: 'Add {bankName} Card',
  add_bank_card_sms_verify: 'SMS verification is required to confirm this action',
  add_bank_card_agree_and_add: 'Agree & Add',
  add_bank_card_agreement_hint: 'Alipay will provide your name and ID information to the bank, and retrieve your eligible cards and reserved phone number for quick binding.',
  add_bank_card_no_card_hint: 'The bank did not return any eligible cards. Please confirm the bank name and try again.',
  add_bank_card_confirm: 'OK',
  add_bank_card_exit_title: 'Need help?',
  add_bank_card_forgot_number: 'Add even if you forgot the card number',
  add_bank_card_go_add: 'Go Add >',
  add_bank_card_free_insurance: 'Free account security insurance after binding',
  add_bank_card_go_view: 'View >',
  add_bank_card_other_issues: 'Any other problems?',
  add_bank_card_feedback: 'Feedback >',
  add_bank_card_quit: 'Give Up & Exit',
  add_bank_card_continue: 'Continue',
  add_bank_card_verify_title: 'Add Bank Card',
  add_bank_card_verify_done: 'Done',
  add_bank_card_verify_add_card: 'Add {name} Card',
  add_bank_card_verify_debit_card: 'Debit Card ({masked})',
  add_bank_card_verify_sent_sms: 'A verification code was sent to {phone}',
  add_bank_card_verify_resend: 'Resend Code ({seconds})',
  add_bank_card_verify_resend_idle: 'Resend Code',
  add_bank_card_verify_invalid_code: 'Incorrect code. Please try again.',
  add_bank_card_verify_hint_title: 'Need help',
  add_bank_card_verify_slow_sms: "Didn't receive the code? Some banks send SMS messages a bit slower.",
  add_bank_card_verify_exit: 'Exit',
  add_bank_card_verify_continue: 'Keep Verifying',
  add_bank_card_verify_success: 'Added successfully',
  add_bank_card_verify_success_hint: '{cardLabel} was added to My > Bank Cards',
  add_bank_card_verify_easier: 'Make card usage easier',
  add_bank_card_verify_share_card: 'Share a bank card with family and friends',
  add_bank_card_verify_share_hint: 'Set a spending limit for travel and shopping',
  add_bank_card_verify_explore: 'Explore',
  add_bank_card_verify_manage_cards: 'Manage Bank Cards',
  add_bank_card_verify_manage_hint: 'View bills, card numbers and more',
  add_bank_card_verify_manage: 'Manage',
  bank_cards_page_add_card: 'Add Card',
  bank_cards_page_featured_banks: 'Featured banking services',
  bank_cards_page_cards: 'Cards',
  bank_cards_page_debit_balance: 'Balance available',
  bank_cards_page_view: 'View',
  bank_cards_page_spending: 'Has spending',
  bank_cards_page_view_balance: 'Balance',
  bank_cards_page_view_number: 'Card Number',
  bank_cards_page_view_bill: 'Bills',
  bank_cards_page_disabled_cards: 'Disabled payment cards',
  bank_cards_page_disabled_count_suffix: '',
  bank_cards_page_lottery: 'Daily Bank Card Lucky Draw',
  bank_cards_page_lottery_hint: 'Pay with a bank card every day for surprise gifts',
  bank_cards_page_go_draw: 'Draw Now',
  bank_cards_page_discount: 'Payment Discount',
  bank_cards_page_discount_hint: 'Discounts available after binding cards',
  bank_cards_page_success_toast: 'Bank card added successfully',
  bank_cards_page_debit_card_label: 'Debit Card {last4}',
  bank_cards_page_bank_card_fallback: 'Bank Card',
  bill_analysis_monthly: 'Monthly',
  bill_analysis_yearly: 'Yearly',
  bill_analysis_select_year: 'Select year',
  bill_analysis_total: '{count} transactions in total',
  bill_analysis_monthly_expense: 'Monthly expenses',
  bill_analysis_monthly_income: 'Monthly income',
  bill_analysis_yearly_expense: 'Yearly expenses',
  bill_analysis_yearly_income: 'Yearly income',
  bill_analysis_green_tag: 'Green Energy',
  bill_analysis_green_hint: 'View e-bills to earn 8g of green energy',
  bill_analysis_expense_categories: 'Expense Categories',
  bill_analysis_top_category: 'Top category: {name}, averaging ¥{avg} per transaction this month.',
  bill_analysis_expense_ranking: 'Expense Ranking',
  bill_analysis_income_ranking: 'Income Ranking',
  bill_analysis_expense_ranking_hint_monthly: 'Top 3 expenses make up {pct}% of this month.',
  bill_analysis_expense_ranking_hint_yearly: 'Top 3 expenses make up {pct}% of this year.',
  bill_analysis_income_ranking_hint_monthly: 'Top 3 income records make up {pct}% of this month.',
  bill_analysis_income_ranking_hint_yearly: 'Top 3 income records make up {pct}% of this year.',
  bill_analysis_expand_all: 'View all',
  bill_analysis_expand: 'Expand',
  bill_analysis_collapse: 'Collapse',
  bill_analysis_expense_compare: 'Expense Comparison',
  bill_analysis_income_compare: 'Income Comparison',
  bill_analysis_budget_hint: 'Set a budget to better manage your spending',
  bill_analysis_set_budget: 'Set monthly budget >',
  bill_analysis_month: 'Month',
  bill_analysis_day: 'Day',
  bill_analysis_no_budget: 'Budget: None',
  bill_analysis_bank_cards: 'Bank Card Spending',
  bill_analysis_txns: '{count} txns',
  bill_search_search_history: 'Search history',
  bill_search_clear: 'Clear',
  bill_search_no_records: 'No related records were found for the past year',
  bill_search_try_another: 'Try another keyword or view an earlier month',
  bill_search_view_earlier_bills: 'View earlier bills',
  bills_filters_applied: 'Filters applied',
  bills_no_records: 'No related records were found for the past year',
  bills_try_another: 'Try another filter or view an earlier month',
  bills_view_earlier_bills: 'View earlier bills',
  finance_page_total_assets: 'My Assets(CNY)',
  finance_page_free_upgrade: 'Free protection upgrade',
  finance_page_yesterday_income: 'New Gains',
  finance_page_family_protection: 'Insurance',
  finance_page_family_count: '3 plans',
  finance_page_rewards_center: 'Rewards Center',
  finance_page_rewards_hint: 'Finance gifts are waiting for you',
  finance_page_market_hotspot: 'Market Spotlight',
  finance_page_headline: 'China power-grid equipment orders surge worldwide',
  finance_page_sub1: 'North America faces deeper power shortages',
  finance_page_sub2: 'Overseas orders keep climbing',
  finance_page_sub3: 'Grid leaders outperform peers',
  finance_page_explore: 'Explore',
  finance_page_fund_watchlist: 'Fund Watchlist',
  finance_page_stock_watchlist: 'Stock Watchlist',
  finance_page_fund_name: 'Tianhong SSE 50 ETF',
  finance_page_stock_name: 'Hundsun Tech',
  finance_page_low_volatility: 'Low Volatility',
  finance_page_six_month_change: '6-month return',
  finance_page_three_day_inflow: '3-day main inflow',
  finance_page_hot: 'Hot',
  finance_page_hot_news: 'US-Iran tensions shake markets as major indices diverge and Oracle...',
  finance_page_stock_inflow_value: '-15.98M',

  total_assets_page_go_finance: 'Wealth',
  total_assets_page_banner_cta: 'See',
  total_assets_page_banner_question: 'Does late repayment affect credit?',
  total_assets_page_overview: 'Overview',
  total_assets_page_upgrade_badge: '¥1M cover',
  total_assets_page_view_score: 'Wealth score',
  total_assets_page_my_assets: 'My assets (CNY)',
  total_assets_page_current_label: 'Liquid',
  total_assets_page_stable_label: 'Stable',
  total_assets_page_advanced_label: 'Advanced',
  total_assets_page_tab_position: 'Holdings',
  total_assets_page_tab_earning: 'Returns',
  total_assets_page_tab_opportunity: 'Ideas',
  total_assets_page_tab_protection: 'Protection',
  total_assets_page_analysis_hint: 'You have exited positions. Any new plans?',
  total_assets_page_guess_ask: 'You might ask:',
  total_assets_page_btn_observe: 'Still watching',
  total_assets_page_btn_opportunity: 'Any opportunities?',
  total_assets_page_wealth_section: 'Wealth assets',
  total_assets_page_fixed: 'Fixed-term',
  total_assets_page_fixed_hint: 'Steady yield',
  total_assets_page_funds: 'Funds',
  total_assets_page_funds_hint: 'Try from ¥10',
  total_assets_page_gold: 'Gold',
  total_assets_page_gold_hint: '0 fee to buy',
  total_assets_page_broker: 'Broker WM',
  total_assets_page_broker_hint: 'Stable & pro',
  yuebao_page_fund_pill: 'Fund... 7-day annualized 1.0300%',
  yuebao_page_announce: 'Holiday earnings & transfer reminder',
  yuebao_page_total: 'Total (CNY)',
  yuebao_page_safe: 'Secure',
  yuebao_page_yesterday_label: "Yesterday's gain (CNY)",
  yuebao_page_no_earnings: 'No earnings yet',
  yuebao_page_cumulative_label: 'All-time gain (CNY)',
  yuebao_page_cumulative_demo: '1.89',
  yuebao_page_money_tree: 'Bonus',
  yuebao_page_out: 'Withdraw',
  yuebao_page_in: 'Deposit',
  yuebao_page_schedule: 'Scheduled deposit',
  yuebao_page_subsidy: 'Saving subsidy',
  yuebao_page_subsidy_claim: 'Claim ¥1.08 red packet',
  yuebao_page_icon_save: 'Save',
  yuebao_page_icon_cash: 'Cash',
  yuebao_page_icon_earn: 'Earn more',
  yuebao_page_icon_current: 'Flexible cash',
  yuebao_page_icon_more: 'More',
  yuebao_page_promo_title_before: 'Limited: ',
  yuebao_page_promo_title_highlight: '¥1',
  yuebao_page_promo_title_after: ' cash',
  yuebao_page_promo_sub: 'Spend once, earn once',
  yuebao_page_promo_btn: 'Claim',
  yuebao_page_steady: 'Stable WM',
  yuebao_page_steady_more: 'Higher yield',
  yuebao_page_current_row: 'Liquid WM',
  yuebao_page_current_rate: '2.88%',

  payment_password_change_remember_account: 'Do you remember the account',
  payment_password_change_current_password: 'and its current payment password?',
  payment_password_change_forgot: 'No',
  payment_password_change_remember: 'Yes',
  payment_password_change_title: 'Change Payment Password',
  payment_password_change_forgot_hint: 'Password recovery is not available in this demo. Please choose "Yes" to verify.',
  payment_password_change_back: 'Back',
  payment_password_change_verify_title: 'Verify Payment Password',
  payment_password_change_verify_hint: 'Enter your current payment password for verification',
  payment_password_change_set_title: 'Set New Payment Password',
  payment_password_change_set_hint: 'Enter a 6-digit number as your new payment password',
  payment_password_change_done: 'Payment password updated',
  payment_password_change_wrong_password: 'Incorrect payment password. Please try again.',
  payment_password_change_same_password: 'The new payment password cannot match the current one.',
  payment_password_change_invalid_password: 'The payment password cannot be repeating or sequential digits.',
  recharge_card_title: 'Recharge Card',
  recharge_card_number: 'Recharge Card Number',
  recharge_card_example: 'e.g. ALIPAY100',
  recharge_card_confirm: 'Confirm Top-up',
  recharge_card_failed: 'Top-up failed: invalid or already used card number',
  recharge_card_success: 'Top-up successful: +{value}',
  recharge_card_available_cards: 'Available Recharge Cards',
  recharge_card_used: 'Used',
  recharge_card_value: '+{value}',
  recharge_page_title: 'Top Up',
  recharge_page_method: 'Top-up Method',
  recharge_page_add_card: 'Please add a bank card',
  recharge_page_limit_hint: 'Max ¥50000 for this card',
  recharge_page_amount: 'Top-up Amount',
  recharge_page_bank_fast_top_up: 'Fast Bank Top-up',
  recharge_page_bank_fast_hint: 'Higher amount limit',
  recharge_page_multi_card: 'Multi-card Top-up',
  recharge_page_multi_card_hint: 'Complete one top-up with multiple cards',
  recharge_page_collapse: 'Collapse',
  recharge_page_expand: 'All',
  recharge_page_confirm: 'Top Up',
  recharge_page_select_method: 'Select Top-up Method',
  recharge_page_bank_limit: 'Single transaction limit ¥50000.00',
  recharge_page_ask_family: 'Ask family or friends to top up for you',
  recharge_page_add_debit_card: 'Add a debit card for top-up',
  recharge_success_title: 'Top-up Successful',
  recharge_success_transfer_result: 'Transfer Result',
  recharge_success_success: 'Transfer Successful',
  recharge_success_done: 'Done',
  recharge_success_home: 'Home',
  recharge_success_payment_method: 'Payment Method',
  recharge_success_coupon: 'Coupon',
  recharge_success_coupon_hint: 'Express delivery coupon, available over ¥0.1',
  recharge_success_free_claim: 'Claim Free',
  recharge_success_shopping_coupon: 'Shopping Coupon',
  recharge_success_shopping_hint: 'Platform subsidy, 24-hour long wear',
  recharge_success_explore: 'Explore',
  recharge_success_bank_card: 'Bank Card',
  refund_page_title: 'Refund',
  refund_page_refund_to_payer: 'Refund to payer',
  refund_page_confirm: 'Confirm Refund',
  refund_page_merchant_fallback: 'Merchant',
  subscriptions_title: 'Membership Subscription',
  subscriptions_membership_type: 'Membership Type',
  subscriptions_price: 'Price',
  subscriptions_billing_cycle: 'Billing Cycle',
  subscriptions_auto_renew_on: 'Auto Renew On',
  subscriptions_auto_renew_off: 'Auto Renew Off',
  subscriptions_submit: 'Subscribe & Pay',
  subscriptions_type_required: 'Membership type is required',
  subscriptions_invalid_price: 'Invalid price',
  subscriptions_insufficient: 'Insufficient balance',

  n_800_pt_service_upgrade: '800 Pt. Service Upgrade',

  // ── 补充缺失 ──
  order_info: 'Order Details',
  confirm_pay: 'Confirm Payment',
  transfer_to_payee: 'Transfer to {payeeName}',
  activity_ambience_description: 'Activity ambience appears between pinned apps and app grid. When enabled, you can access major promotions (e.g., Spring Festival) in this area. Turn off to hide it.',
  expense_breakdown: 'Expense Breakdown',
  chart_area_transfer: 'Chart: Transfer',
  monthly_comparison: 'Monthly Comparison',
  chatpage_me: 'Me',
  chatpage_send: 'Send',
  clipboard_on_description: 'When enabled, clipboard data is only processed on your device. Alipay will not store or use your clipboard data for any other purpose.',
  clipboard_off_description: 'When disabled, clipboard data will no longer be read. Features like Zhi-commands and search may be affected.',
  contact_not_found: 'Contact not found',
  alipay_account: 'Alipay Account',
  real_name: 'Real Name',
  send_message: 'Send Message',
  send_red_packet: 'Send Red Packet',
  go_transfer: 'Transfer',
  friends_count_suffix: ' friends',
  preview_font_size: 'Preview Font Size',
  drag_slider_to_set_font_size: 'Drag the slider below to adjust font size',
  font_size_change_description: 'This will change the font size on My Page, friends message list, and chat pages. Choose a size that works for you.',
  go_collect: 'Collect',
  mypage_manage_description: 'You can show or hide My Page services. Hiding a service only removes its entry point without clearing any data.',
  mypage_manage_basic_note: 'Basic services like Alipay Membership, Security Center, Transactions, and Total Assets cannot be hidden.',
  pay_and_receive: 'Pay/Collect',
  payment_rewards: 'Payment Rewards',

  // ── 扫一扫页 (ScanPage) ──
  scan_code: 'Scan',
  scan_light: 'Smart',
  scan_no_qr_found: 'No QR code found? Get help',
  scan_album: 'Album',
  search_box_manage_description: 'The home search box shows recommended keywords or themed decorations. Disable to hide these suggestions and decorations.',
  search_pre_manage_description: 'Search suggestions recommend keywords you might be interested in. Disable to hide these suggestions.',
  speed_mode_description: 'When device runs slowly, home recommendations will be collapsed and background services reduced to speed up browsing',
  transfer_protection_off: 'Transfer Protection Not Enabled',
  recent_contacts: 'Recent Contacts',
  people_you_may_want_to_send: 'People You May Want to Send To',
  account_not_found_try_again: 'Account not found. Please try a different phone number or email.',
  voice_floating_ball_description: 'Enable the voice shortcut floating button to use voice commands on any Alipay page for quick service access.',
  bank_rate_news: 'Multiple banks continue to cut deposit rates as market enters the "1% era"',
  follow_finance_friends: 'Follow investment friends to see live portfolio updates',
};
