import { NavigationDeclaration, ScrollContainerDeclaration } from './navigation.types';

const MAIN_SCROLL: ScrollContainerDeclaration[] = [
  { name: 'main', direction: 'vertical', description: '页面主内容区' },
];

const READING_PAGE_SCROLL: ScrollContainerDeclaration[] = [
  { name: 'main', direction: 'vertical', description: '页面主内容区' },
  { name: 'categories', direction: 'horizontal', description: '分类标签横向滚动' },
  { name: 'heroCarousel', direction: 'horizontal', description: '书籍轮播横向滚动' },
];

export const NAVIGATION_DECLARATION = {
  app: 'wechat_reading',
  routes: [
    {
      path: '/',
      component: 'ReadingPage',
      params: {},
      entryPoint: 'home',
      scrollContainers: READING_PAGE_SCROLL,
      uiStates: [
        {
          id: 'reading.base',
          search: {},
          description: '阅读首页',
          actions: [
            { id: 'reading.recommendations.refresh.submit', label: '为你推荐：换一批', behavior: 'submit' },
          ],
        },
      ],
      queryParams: {},
      description: '阅读首页',
    },
    {
      path: '/search',
      component: 'SearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'search.base',
          search: {},
          description: '搜索页-热搜',
          actions: [
            {
              id: 'search.hot.item',
              label: '搜索页：点击热搜词',
              behavior: 'input',
              scope: 'item',
              paramsSchema: { hotId: 'string', value: 'string' },
            },
          ],
        },
        { id: 'search.results', search: { query: '*' }, description: '搜索页-结果' },
      ],
      queryParams: {},
      description: '搜索页',
    },
    {
      path: '/bookshelf',
      component: 'BookshelfPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'bookshelf.base', search: {}, description: '书架默认视图' },
        {
          id: 'bookshelf.select',
          search: { select: 'true' },
          description: '书架选择模式',
          actions: [
            { id: 'bookshelf.selectAll.toggle', label: '书架选择模式：全选/取消全选', behavior: 'toggle' },
            {
              id: 'bookshelf.item.select.toggle',
              label: '书架选择模式：选择/取消选择书籍',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { bookId: 'string' },
            },
          ],
        },
        {
          id: 'bookshelf.select.confirmRemove',
          search: { select: 'true', modal: 'confirm_remove' },
          description: '选择模式-移出确认',
          actions: [
            { id: 'bookshelf.removeSelected.submit', label: '选择模式：确认移出所选书籍', behavior: 'submit' },
          ],
        },
        {
          id: 'bookshelf.select.private',
          search: { select: 'true', modal: 'private_reading' },
          description: '选择模式-私密阅读弹窗',
          actions: [
            { id: 'bookshelf.privateReading.enable.submit', label: '选择模式：开启私密阅读', behavior: 'submit' },
          ],
        },
      ],
      queryParams: {},
      description: '个人书架',
    },
    {
      path: '/audiobooks',
      component: 'AudiobooksPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'audiobooks.audio',
          search: { sub: 'audio' },
          description: '有声书-推荐',
          actions: [
            { id: 'audiobooks.recommendations.refresh.submit', label: '有声书：为你推荐-换一批', behavior: 'submit' },
          ],
        },
        { id: 'audiobooks.community', search: { sub: 'community' }, description: '有声书-社区' },
      ],
      queryParams: {},
      description: '有声书中心',
    },
    {
      path: '/me',
      component: 'MePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'me.base', search: {}, description: '个人中心' }],
      queryParams: {},
      description: '个人中心',
    },
    {
      path: '/book/:bookId',
      component: 'BookDetailPage',
      params: { bookId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'bookDetail.base',
          search: {},
          description: '书籍详情',
          actions: [
            {
              id: 'bookDetail.item.shelf.add.submit',
              label: '书籍详情：加入书架',
              behavior: 'submit',
              scope: 'item',
              paramsSchema: { bookId: 'string' },
            },
          ],
        },
        {
          id: 'bookDetail.modal.shelf',
          search: { modal: 'shelf' },
          description: '加入书架弹窗',
          actions: [
            {
              id: 'bookDetail.item.shelf.remove.submit',
              label: '书籍详情：移出书架',
              behavior: 'submit',
              scope: 'item',
              paramsSchema: { bookId: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '书籍详情页',
    },
    {
      path: '/read/:bookId',
      component: 'ReaderPage',
      params: { bookId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'reader.base',
          search: {},
          description: '阅读器',
          actions: [
            {
              id: 'reader.item.shelf.add.submit',
              label: '阅读器：加入书架',
              behavior: 'submit',
              scope: 'item',
              paramsSchema: { bookId: 'string' },
            },
          ],
        },
        {
          id: 'reader.modal.shelf',
          search: { modal: 'shelf' },
          description: '书架弹窗',
          actions: [
            {
              id: 'reader.item.shelf.remove.submit',
              label: '阅读器：移出书架',
              behavior: 'submit',
              scope: 'item',
              paramsSchema: { bookId: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '阅读器',
    },
    {
      path: '/edit-profile',
      component: 'EditProfilePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'editProfile.base',
          search: {},
          description: '编辑资料',
          actions: [
            {
              id: 'profile.edit.name.input',
              label: '编辑资料：输入昵称',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'profile.edit.introduction.input',
              label: '编辑资料：输入介绍自己',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'profile.edit.signature.input',
              label: '编辑资料：输入签名',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '编辑资料',
    },
    {
      path: '/gender-selection',
      component: 'GenderSelectionPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'genderSelection.base',
          search: {},
          description: '性别选择',
          actions: [
            { id: 'profile.gender.select.male', label: '选择性别：男', behavior: 'select' },
            { id: 'profile.gender.select.female', label: '选择性别：女', behavior: 'select' },
            { id: 'profile.gender.submit', label: '性别选择：完成', behavior: 'submit' },
          ],
        },
      ],
      queryParams: {},
      description: '性别选择',
    },
    {
      path: '/my-profile',
      component: 'MyProfilePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'myProfile.shelf', search: { tab: 'shelf' }, description: '我的主页-书架' },
        {
          id: 'myProfile.finished',
          search: { tab: 'finished' },
          description: '我的主页-读完',
          // 动态 Tab（更贴近真实微信读书）：
          // - “读完列表”由阅读进度驱动，不依赖是否仍在书架
          // - 但主页“读完”展示会排除“在书架且设为隐私”的读完书
          stateCondition: {
            op: 'notEmpty',
            ref: 'finishedBookIds',
            filterFn:
              '(bookId, data) => { const shelfItem = (data.shelf || []).find(x => x.bookId === bookId); if (shelfItem && shelfItem.isPrivate === true) return false; const progress = data.bookProgress?.[bookId]; const book = (data.store || []).find(b => b.id === bookId); return !!(progress && book && progress.charOffset >= book.totalWords); }',
          },
        },
      ],
      queryParams: {},
      description: '我的主页',
    },
    {
      path: '/my-reading',
      component: 'MyReadingPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'myReading.week', search: { tab: 'week' }, description: '周视图' },
        { id: 'myReading.month', search: { tab: 'month' }, description: '月视图' },
        {
          id: 'myReading.year',
          search: { tab: 'year' },
          description: '年视图',
          actions: [
            { id: 'myReading.year.prev.submit', label: '年视图：上一年', behavior: 'submit' },
            { id: 'myReading.year.next.submit', label: '年视图：下一年', behavior: 'submit' },
          ],
        },
        { id: 'myReading.total', search: { tab: 'total' }, description: '总视图' },
        { id: 'myReading.history', search: { tab: 'history' }, description: '阅历视图' },
      ],
      queryParams: {},
      description: '阅读统计',
    },
    {
      path: '/reading-list',
      component: 'ReadingListPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'readingList.all', search: { category: 'all' }, description: '全部书单' },
        { id: 'readingList.reading', search: { category: 'reading' }, description: '在读书单' },
        { id: 'readingList.finished', search: { category: 'finished' }, description: '读完书单' },
      ],
      queryParams: {},
      description: '阅读书单',
    },
    {
      path: '/book-lists',
      component: 'BookListsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'bookLists.my', search: { category: 'all' }, description: '我的书单' },
        { id: 'bookLists.collected', search: { category: 'finished' }, description: '收藏的书单' },
      ],
      queryParams: {},
      description: '书单',
    },
    {
      path: '/book-lists/edit',
      component: 'EditBookListPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'bookLists.edit.base', search: {}, description: '编辑书单' }],
      queryParams: {},
      description: '编辑书单',
    },
    {
      path: '/book-lists/add-books',
      component: 'AddBooksToListPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'bookLists.addBooks.base', search: {}, description: '从书架添加书籍' }],
      queryParams: {},
      description: '添加书籍到书单',
    },
    {
      path: '/settings',
      component: 'SettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.base',
          search: {},
          description: '设置首页',
          actions: [
            { id: 'settings.reader.autoLock.toggle', label: '阅读时不自动锁屏：开关', behavior: 'toggle' },
            { id: 'settings.reader.allowLandscape.toggle', label: '阅读时允许横屏：开关', behavior: 'toggle' },
            { id: 'settings.reader.hideThought.toggle', label: '阅读时隐藏他人的想法：开关', behavior: 'toggle' },
            { id: 'settings.reader.showTimeBattery.toggle', label: '阅读时显示时间和电量：开关', behavior: 'toggle' },
            { id: 'settings.reader.volumeKeyTurn.toggle', label: '使用音量键翻页：开关', behavior: 'toggle' },
            { id: 'settings.reader.firstLineIndent.toggle', label: '正文首行缩进：开关', behavior: 'toggle' },
            { id: 'settings.reader.clickLeftNext.toggle', label: '点击左侧翻到下一页：开关', behavior: 'toggle' },
            { id: 'settings.reader.blockWebNovels.toggle', label: '屏蔽网文：开关', behavior: 'toggle' },
            { id: 'settings.reader.mixAudio.toggle', label: '允许与其他应用同时播放：开关', behavior: 'toggle' },
          ],
        },
      ],
      queryParams: {},
      description: '设置',
    },
    {
      path: '/settings/auto-download',
      component: 'AutoDownloadPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.autoDownload.base', search: {}, description: '自动下载设置' }],
      queryParams: {},
      description: '自动下载设置',
    },
    {
      path: '/settings/page-turn-style',
      component: 'PageTurnStylePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.pageTurnStyle.base',
          search: {},
          description: '翻页方式',
          actions: [
            { id: 'settings.pageTurnStyle.select.simulation', label: '翻页方式：仿真翻页', behavior: 'select' },
            { id: 'settings.pageTurnStyle.select.swipe', label: '翻页方式：左右滑动', behavior: 'select' },
            { id: 'settings.pageTurnStyle.select.scroll', label: '翻页方式：上下滚动', behavior: 'select' },
            { id: 'settings.pageTurnStyle.select.cover', label: '翻页方式：覆盖翻页', behavior: 'select' },
          ],
        },
      ],
      queryParams: {},
      description: '翻页方式设置',
    },
    {
      path: '/settings/dark-mode',
      component: 'DarkModePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.darkMode.base',
          search: {},
          description: '暗黑模式设置',
          actions: [
            { id: 'settings.darkMode.followSystem.toggle', label: '深色模式：跟随系统', behavior: 'toggle' },
            { id: 'settings.darkMode.select.light', label: '深色模式：浅色', behavior: 'select' },
            { id: 'settings.darkMode.select.dark', label: '深色模式：深色', behavior: 'select' },
          ],
        },
      ],
      queryParams: {},
      description: '暗黑模式设置',
    },
    {
      path: '/settings/privacy',
      component: 'PrivacyPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.privacy.base',
          search: {},
          description: '隐私设置',
          actions: [
            { id: 'settings.privacy.requireFollowRequest.toggle', label: '关注你须获得你的同意：开关', behavior: 'toggle' },
            { id: 'settings.privacy.hideVipGlobal.toggle', label: '全局隐藏资深会员：开关', behavior: 'toggle' },
            { id: 'settings.privacy.autoPrivateReading.toggle', label: '加入书架后自动开启私密阅读：开关', behavior: 'toggle' },
            { id: 'settings.privacy.shelfReplacement.toggle', label: '替身书架：开关', behavior: 'toggle' },
            { id: 'settings.privacy.rejectStrangerMsg.toggle', label: '不接收未关注人的私信：开关', behavior: 'toggle' },
            { id: 'settings.privacy.closePersonalizedRec.toggle', label: '关闭个性化推荐：开关', behavior: 'toggle' },
            { id: 'settings.privacy.closeReadingRank.toggle', label: '关闭读书排行榜：开关', behavior: 'toggle' },
          ],
        },
      ],
      queryParams: {},
      description: '隐私设置',
    },
    {
      path: '/settings/privacy/profile',
      component: 'ProfilePrivacyPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.profilePrivacy.base',
          search: {},
          description: '主页隐私设置',
          actions: [
            { id: 'settings.profilePrivacy.showShelf.toggle', label: '展示模块：书架', behavior: 'toggle' },
            { id: 'settings.profilePrivacy.showLiked.toggle', label: '展示模块：喜好的书', behavior: 'toggle' },
            { id: 'settings.profilePrivacy.showLists.toggle', label: '展示模块：书单', behavior: 'toggle' },
            { id: 'settings.profilePrivacy.showBadge.toggle', label: '展示模块：勋章', behavior: 'toggle' },
            { id: 'settings.profilePrivacy.showThought.toggle', label: '展示模块：想法', behavior: 'toggle' },

            { id: 'settings.profilePrivacy.visibility.select.self', label: '可见范围：仅自己可见', behavior: 'select' },
            { id: 'settings.profilePrivacy.visibility.select.mutual', label: '可见范围：互关可见', behavior: 'select' },
            { id: 'settings.profilePrivacy.visibility.select.follower', label: '可见范围：关注我的人可见', behavior: 'select' },
            { id: 'settings.profilePrivacy.visibility.select.all', label: '可见范围：所有人可见', behavior: 'select' },
          ],
        },
      ],
      queryParams: {},
      description: '主页隐私设置',
    },
    {
      path: '/settings/notifications',
      component: 'NotificationsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.notifications.base',
          search: {},
          description: '通知设置',
          actions: [
            { id: 'settings.notifications.notifyNewFollower.toggle', label: '接收新关注提醒：开关', behavior: 'toggle' },
            { id: 'settings.notifications.notifyNewWechatFriend.toggle', label: '接收微信朋友新加入提醒：开关', behavior: 'toggle' },
            { id: 'settings.notifications.notifyActivityWelfare.toggle', label: '接收活动福利私信提醒：开关', behavior: 'toggle' },
          ],
        },
      ],
      queryParams: {},
      description: '通知设置',
    },
    {
      path: '/following',
      component: 'FollowingPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'following.following',
          search: { tab: 'following' },
          description: '我关注的',
          actions: [
            {
              id: 'following.item.unfollow.toggle',
              label: '关注列表：取消关注',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { userId: 'string' },
            },
          ],
        },
        { id: 'following.followers', search: { tab: 'followers' }, description: '关注我的' },
      ],
      queryParams: {},
      description: '关注列表',
    },
    {
      path: '/wechat-friends',
      component: 'WechatFriendsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'wechatFriends.base',
          search: {},
          description: '微信朋友列表',
          actions: [
            {
              id: 'wechatFriends.item.follow.toggle',
              label: '微信朋友：关注/取消关注',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { userId: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '微信朋友',
    },
    {
      path: '/user/:userId',
      component: 'UserProfilePage',
      params: { userId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'userProfile.base',
          search: {},
          description: '用户主页',
          actions: [
            {
              id: 'userProfile.item.follow.toggle',
              label: '用户主页：关注/取消关注',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { userId: 'string' },
            },
          ],
        },
        {
          id: 'userProfile.modal.unfollow',
          search: { modal: 'unfollow_confirm' },
          description: '取消关注确认弹窗',
          actions: [
            {
              id: 'userProfile.item.unfollow.submit',
              label: '用户主页：确认取消关注',
              behavior: 'submit',
              scope: 'item',
              paramsSchema: { userId: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '用户主页',
    },
    {
      path: '/user/:userId/shelf',
      component: 'UserBookshelfPage',
      params: { userId: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'userShelf.base', search: {}, description: '用户书架' }],
      queryParams: {},
      description: '用户书架',
    },
    {
      path: '/wallet/coins',
      component: 'CoinsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.coins.base', search: {}, description: '阅读币' }],
      queryParams: {},
      description: '阅读币钱包',
    },
    {
      path: '/wallet/transactions',
      component: 'TransactionsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'wallet.transactions.base', search: {}, description: '兑换记录' }],
      queryParams: {},
      description: '阅读币记录',
    },
    {
      path: '/categories',
      component: 'CategoryListPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'categories.base', search: {}, description: '分类列表' }],
      queryParams: {},
      description: '书籍分类列表',
    },
    {
      path: '/categories/:categoryName',
      component: 'CategoryDetailPage',
      params: { categoryName: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'categoryDetail.base', search: {}, description: '分类详情' }],
      queryParams: {},
      description: '分类详情 — 按分类浏览书籍列表',
    },
  ],
  transitions: [
    {
      id: 'reading.open',
      from: ['/bookshelf'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '打开书城（阅读首页）',
      ui: { placement: 'content', icon: 'book_store', gesture: 'tap' },
    },
    {
      id: 'search.open',
      from: ['/', '/bookshelf', '/book-lists', '/book-lists/edit', '/book-lists/add-books'],
      to: '/search',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开搜索页',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'categories.open',
      from: ['/'],
      to: '/categories',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开分类列表',
      ui: { placement: 'content', icon: 'categories', gesture: 'tap' },
    },
    {
      id: 'category.detail.open',
      from: ['/categories'],
      to: '/categories/:categoryName',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { categoryName: 'string' },
      label: '打开分类详情',
      ui: { placement: 'content', icon: 'category_detail', gesture: 'tap' },
    },
    {
      id: 'tab.reading',
      from: [
        '/bookshelf',
        '/book-lists',
        '/book-lists/edit',
        '/book-lists/add-books',
        { path: '/audiobooks', search: { sub: '*' } },
        '/me',
      ],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到阅读首页',
      ui: { placement: 'tabbar', icon: 'tab_reading', gesture: 'tap' },
    },
    {
      id: 'tab.bookshelf',
      from: [
        '/',
        '/book-lists',
        '/book-lists/edit',
        '/book-lists/add-books',
        { path: '/audiobooks', search: { sub: '*' } },
        '/me',
      ],
      to: '/bookshelf',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到书架',
      ui: { placement: 'tabbar', icon: 'tab_bookshelf', gesture: 'tap' },
    },
    {
      id: 'tab.audiobooks',
      from: [
        '/',
        '/bookshelf',
        '/book-lists',
        '/book-lists/edit',
        '/book-lists/add-books',
        '/me',
      ],
      to: '/audiobooks',
      // 默认进入“有声书-推荐（audio）”，但若用户此前已在有声书页切到“书友（community）”，
      // 回到主 Tab 时允许恢复到 community（依赖访问记忆/主 Tab 常驻）。
      // 用 cases 表达语义，并对 community 分支标注 requires_prior_visit。
      search: { sub: 'audio' },
      searchParams: { sub: 'string' },
      cases: [
        {
          when: { op: 'eq', left: { ref: 'param', key: 'sub' }, right: 'community' },
          to: '/audiobooks',
          search: { sub: 'community' },
          availability: 'requires_prior_visit',
          availabilityNote:
            '仅当用户此前在有声书页切换到“书友（community）”，且主 Tab 常驻/存在访问记忆时，回到“有声书/书友”可直接恢复到书友。',
        },
        { when: { op: 'always' }, to: '/audiobooks', search: { sub: 'audio' } },
      ],
      mode: 'replace',
      params: {},
      label: '切换到有声书',
      ui: { placement: 'tabbar', icon: 'tab_audiobooks', gesture: 'tap' },
    },
    {
      id: 'tab.me',
      from: [
        '/',
        '/bookshelf',
        '/book-lists',
        '/book-lists/edit',
        '/book-lists/add-books',
        { path: '/audiobooks', search: { sub: '*' } },
      ],
      to: '/me',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到我的',
      ui: { placement: 'tabbar', icon: 'tab_me', gesture: 'tap' },
    },
    // 有声书页内 Tab 切换（合并为单个 transition，通过 data-trigger-params 区分）
    {
      id: 'audiobooks.tab.switch',
      from: { path: '/audiobooks', search: { sub: '*' } },
      to: '/audiobooks',
      search: {},
      searchParams: { sub: 'string' },
      mode: 'replace',
      params: {},
      label: '切换有声书 Tab',
      ui: { placement: 'content', icon: 'audiobooks_tab', gesture: 'tap' },
    },
    {
      id: 'book.detail.open',
      from: ['/', { path: '/reading-list', search: { category: '*' } }, { path: '/my-profile', search: { tab: '*' } }, '/user/:userId', '/user/:userId/shelf', { path: '/audiobooks', search: { sub: '*' } }, { path: '/search', search: { query: '*' } }, { path: '/search', search: {} }, '/categories/:categoryName'],
      to: '/book/:bookId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { bookId: 'string' },
      label: '查看书籍详情',
      ui: { placement: 'content', icon: 'book_detail', gesture: 'tap' },
      // 多来源数据源
      dataSource: [
        {
          from: '/',
          ref: 'recommendations',  // 简单 ID 数组
          paramMapping: { bookId: '$value' },
        },
        {
          // 阅读列表-全部：由阅读进度驱动（不依赖是否仍在书架）
          from: { path: '/reading-list', search: { category: 'all' } },
          ref: 'allProgressBookIds',
          paramMapping: { bookId: '$value' },
        },
        {
          // 阅读列表-在读：由阅读进度驱动（不依赖是否仍在书架）
          from: { path: '/reading-list', search: { category: 'reading' } },
          ref: 'readingBookIds',
          paramMapping: { bookId: '$value' },
        },
        {
          // 阅读列表-读完：由阅读进度驱动（不依赖是否仍在书架）
          from: { path: '/reading-list', search: { category: 'finished' } },
          ref: 'finishedBookIds',
          paramMapping: { bookId: '$value' },
        },
        {
          // 我的主页-书架 Tab：公开书架中的书（isPrivate=false）
          from: { path: '/my-profile', search: { tab: 'shelf' } },
          ref: 'shelf[isPrivate=false]',
          paramMapping: { bookId: 'bookId' },
        },
        {
          // 我的主页-读完 Tab：读完列表（排除“在书架且私密”的读完书）
          from: { path: '/my-profile', search: { tab: 'finished' } },
          ref: 'finishedBookIds',
          filterFn:
            '(bookId, data) => { const shelfItem = (data.shelf || []).find(x => x.bookId === bookId); if (shelfItem && shelfItem.isPrivate === true) return false; const progress = data.bookProgress?.[bookId]; const book = (data.store || []).find(b => b.id === bookId); return !!(progress && book && progress.charOffset >= book.totalWords); }',
          paramMapping: { bookId: '$value' },
        },
        {
          // 参数化数组查找：从其他用户的 recentBooks 获取 bookId
          from: '/user/:userId',
          ref: 'users[id={userId}].recentBooks',
          paramMapping: { bookId: '$value' },
        },
        {
          // 参数化数组查找：从其他用户书架页获取 bookId（recentBooks 就是展示的书）
          from: '/user/:userId/shelf',
          ref: 'users[id={userId}].recentBooks',
          paramMapping: { bookId: '$value' },
        },
        {
          // 有声书
          from: { path: '/audiobooks', search: { sub: 'audio' } },
          ref: 'recommendedAudiobooks',
          paramMapping: { bookId: '$value' },
        },
        {
          // 分类详情页：按分类筛选的书籍列表
          from: '/categories/:categoryName',
          ref: 'store',
          paramMapping: { bookId: 'id' },
        },
      ],
    },
    {
      id: 'reader.open',
      from: ['/', '/bookshelf', '/book/:bookId'],
      to: '/read/:bookId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { bookId: 'string' },
      label: '打开阅读器',
      ui: { placement: 'content', icon: 'reader_open', gesture: 'tap' },
      // 多来源数据源
      dataSource: [
        {
          // 阅读首页轮播图显示的是书架中的书
          from: '/',
          ref: 'shelf',
          paramMapping: { bookId: 'bookId' },
        },
        {
          from: '/bookshelf',
          ref: 'shelf',
          paramMapping: { bookId: 'bookId' },
        },
        // /book/:bookId 不需要 dataSource，bookId 从源路径继承
      ],
    },
    // === 阅读统计页跳转 ===
    {
      id: 'myReading.open.week',
      from: ['/', '/me'],
      to: '/my-reading',
      search: { tab: 'week' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看周阅读统计',
      ui: { placement: 'content', icon: 'my_reading_week', gesture: 'tap' },
    },
    {
      id: 'myReading.open.month',
      from: '/',
      to: '/my-reading',
      search: { tab: 'month' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看月阅读统计',
      ui: { placement: 'content', icon: 'my_reading_month', gesture: 'tap' },
    },
    {
      id: 'myReading.open.total',
      from: { path: '/my-profile', search: { tab: '*' } },
      to: '/my-reading',
      search: { tab: 'total' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看总阅读统计',
      ui: { placement: 'content', icon: 'my_reading_total', gesture: 'tap' },
    },
    // 阅读统计页内 Tab 切换（合并为单个 transition，通过 data-trigger-params 区分）
    {
      id: 'myReading.tab.switch',
      from: { path: '/my-reading', search: { tab: '*' } },
      to: '/my-reading',
      search: {},
      searchParams: { tab: 'string' },
      mode: 'replace',
      params: {},
      label: '切换阅读统计 Tab',
      ui: { placement: 'content', icon: 'my_reading_tab', gesture: 'tap' },
    },
    // === 阅读列表页跳转 ===
    {
      id: 'readingList.open.all',
      from: [
        { path: '/my-reading', search: { tab: 'total' } },
        { path: '/my-reading', search: { tab: 'year' } },
        { path: '/my-reading', search: { tab: 'month' } },
      ],
      to: '/reading-list',
      search: { category: 'all' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看全部书单',
      ui: { placement: 'content', icon: 'reading_list_all', gesture: 'tap' },
    },
    {
      id: 'readingList.open.reading',
      from: '/me',
      to: '/reading-list',
      search: { category: 'reading' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看在读书单',
      ui: { placement: 'content', icon: 'reading_list_reading', gesture: 'tap' },
    },
    {
      id: 'readingList.open.finished',
      from: [
        '/me',
        { path: '/my-profile', search: { tab: 'finished' } },  // 从读完 Tab 跳转
        { path: '/my-reading', search: { tab: 'total' } },
        { path: '/my-reading', search: { tab: 'year' } },
        { path: '/my-reading', search: { tab: 'month' } },
      ],
      to: '/reading-list',
      search: { category: 'finished' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看读完书单',
      ui: { placement: 'content', icon: 'reading_list_finished', gesture: 'tap' },
    },
    // 阅读列表页内 Tab 切换（合并为单个 transition，通过 data-trigger-params 区分）
    {
      id: 'readingList.tab.switch',
      from: { path: '/reading-list', search: { category: '*' } },
      to: '/reading-list',
      search: {},
      searchParams: { category: 'string' },
      mode: 'replace',
      params: {},
      label: '切换阅读列表 Tab',
      ui: { placement: 'content', icon: 'reading_list_tab', gesture: 'tap' },
    },
    {
      id: 'profile.my.open',
      from: ['/me', '/bookshelf'],
      to: '/my-profile',
      search: { tab: 'shelf' },  // 默认进入书架 Tab
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看我的主页',
      ui: { placement: 'content', icon: 'profile_my', gesture: 'tap' },
    },
    // 我的主页 Tab 切换
    {
      id: 'myProfile.tab.switch',
      from: { path: '/my-profile', search: { tab: '*' } },
      to: '/my-profile',
      search: {},
      searchParams: { tab: 'string' },
      mode: 'replace',
      params: {},
      label: '切换我的主页 Tab',
      ui: { placement: 'content', icon: 'my_profile_tab', gesture: 'tap' },
    },
    {
      id: 'profile.edit.open',
      from: ['/me', { path: '/my-profile', search: { tab: '*' } }, '/settings/privacy/profile'],
      to: '/edit-profile',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '编辑个人资料',
      ui: { placement: 'content', icon: 'profile_edit', gesture: 'tap' },
    },
    {
      id: 'profile.gender.open',
      from: '/edit-profile',
      to: '/gender-selection',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '选择性别',
      ui: { placement: 'content', icon: 'profile_gender', gesture: 'tap' },
    },
    {
      id: 'settings.open',
      from: ['/me'],
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开设置页',
      ui: { placement: 'topbar', icon: 'settings', gesture: 'tap' },
    },
    {
      id: 'settings.autoDownload.open',
      from: '/settings',
      to: '/settings/auto-download',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '自动下载设置',
      ui: { placement: 'content', icon: 'settings_auto', gesture: 'tap' },
    },
    {
      id: 'settings.pageTurn.open',
      from: '/settings',
      to: '/settings/page-turn-style',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '翻页方式设置',
      ui: { placement: 'content', icon: 'settings_page_turn', gesture: 'tap' },
    },
    {
      id: 'settings.darkMode.open',
      from: '/settings',
      to: '/settings/dark-mode',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '深色模式设置',
      ui: { placement: 'content', icon: 'settings_dark_mode', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.open',
      from: '/settings',
      to: '/settings/privacy',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '隐私设置',
      ui: { placement: 'content', icon: 'settings_privacy', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.profile.open',
      from: ['/settings/privacy', { path: '/my-profile', search: { tab: '*' } }],
      to: '/settings/privacy/profile',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '主页隐私设置',
      ui: { placement: 'content', icon: 'settings_privacy_profile', gesture: 'tap' },
    },
    {
      id: 'settings.notifications.open',
      from: '/settings',
      to: '/settings/notifications',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '通知设置',
      ui: { placement: 'content', icon: 'settings_notifications', gesture: 'tap' },
    },
    {
      id: 'wallet.coins.open',
      from: ['/me'],
      to: '/wallet/coins',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看阅读币',
      ui: { placement: 'content', icon: 'wallet_coins', gesture: 'tap' },
    },
    {
      id: 'wallet.transactions.open',
      from: '/wallet/coins',
      to: '/wallet/transactions',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看交易记录',
      ui: { placement: 'content', icon: 'wallet_transactions', gesture: 'tap' },
    },
    {
      id: 'following.open.following',
      from: ['/me'],
      to: '/following',
      search: { tab: 'following' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看我关注的',
      ui: { placement: 'content', icon: 'following_list', gesture: 'tap' },
    },
    {
      id: 'bookLists.open',
      from: ['/me'],
      to: '/book-lists',
      search: { category: 'all' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开书单',
      ui: { placement: 'content', icon: 'book_lists', gesture: 'tap' },
    },
    {
      id: 'bookLists.edit.open',
      from: ['/book-lists'],
      to: '/book-lists/edit',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开编辑书单',
      ui: { placement: 'content', icon: 'book_lists', gesture: 'tap' },
    },
    {
      id: 'bookLists.addBooks.open',
      from: ['/book-lists/edit'],
      to: '/book-lists/add-books',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '从书架添加书籍',
      ui: { placement: 'content', icon: 'bookshelf', gesture: 'tap' },
    },
    {
      id: 'bookLists.viewPopular',
      from: ['/book-lists'],
      to: '/categories',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看热门书单',
      ui: { placement: 'content', icon: 'categories', gesture: 'tap' },
    },
    {
      id: 'bookLists.viewProfile',
      from: ['/book-lists', { path: '/book-lists', search: { category: '*' } }],
      to: '/my-profile',
      search: { tab: 'shelf' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看公开主页',
      ui: { placement: 'content', icon: 'profile_my', gesture: 'tap' },
    },
    {
      id: 'following.open.followers',
      from: [{ path: '/my-profile', search: { tab: '*' } }],
      to: '/following',
      search: { tab: 'followers' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看关注我的',
      ui: { placement: 'content', icon: 'followers_list', gesture: 'tap' },
    },
    {
      id: 'following.tab.switch',
      from: { path: '/following', search: { tab: '*' } },
      to: '/following',
      search: {},
      searchParams: { tab: 'string' },
      mode: 'replace',
      params: {},
      label: '切换关注页 Tab',
      ui: { placement: 'content', icon: 'following_tab', gesture: 'tap' },
    },
    {
      id: 'wechatFriends.open',
      from: { path: '/following', search: { tab: 'following' } },
      to: '/wechat-friends',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开微信朋友列表',
      ui: { placement: 'content', icon: 'wechat_friends', gesture: 'tap' },
    },
    {
      id: 'user.profile.open',
      // 入口只在“我关注的”列表中存在
      from: { path: '/following', search: { tab: 'following' } },
      to: '/user/:userId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { userId: 'string' },
      label: '打开用户主页',
      ui: { placement: 'content', icon: 'user_profile', gesture: 'tap' },
      // 数据源：userId 来自关注列表
      dataSource: {
        ref: 'user.following',
        paramMapping: { userId: '$value' },
      },
    },
    {
      id: 'user.profile.open.fromFriends',
      from: '/wechat-friends',
      to: '/user/:userId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { userId: 'string' },
      label: '从微信朋友打开用户主页',
      ui: { placement: 'content', icon: 'user_profile', gesture: 'tap' },
    },
    {
      id: 'user.shelf.open',
      from: ['/user/:userId', { path: '/my-profile', search: { tab: 'shelf' } }],
      to: '/user/:userId/shelf',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { userId: 'string' },
      label: '查看用户书架',
      ui: { placement: 'content', icon: 'user_shelf', gesture: 'tap' },
      // data 模式补全：从“我的主页”进入“我的书架”时，userId 来自当前用户
      // （否则 /my-profile -> /user/:userId/shelf 在 data 模式无法展开，会被跳过）
      dataSource: [
        {
          from: { path: '/my-profile', search: { tab: 'shelf' } },
          ref: 'user.id',
          paramMapping: { userId: '$value' },
        },
      ],
    },
    {
      id: 'bookshelf.select.enter',
      from: { path: '/bookshelf', search: { select: null } },
      to: '/bookshelf',
      search: { select: 'true' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入书架选择模式',
      // 入口语义：长按“某一本书封面”进入选择模式，因此书架为空时入口不存在
      // data-mode 的 condition/ref 只读取数据配置文件（ConfigData），不读取运行时状态；
      // 因此这里用 ConfigData 的 shelf 表示“书架条目列表是否为空”。
      ui: {
        placement: 'content',
        icon: 'bookshelf_select',
        gesture: 'longPress',
        condition: { op: 'notEmpty', ref: 'shelf' },
      },
    },
    {
      id: 'bookshelf.select.enter.tap',
      from: { path: '/bookshelf', search: { select: null } },
      to: '/bookshelf',
      search: { select: 'true' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '进入书架选择模式（按钮）',
      ui: { placement: 'content', icon: 'bookshelf_select_button', gesture: 'tap' },
    },
    {
      id: 'bookshelf.select.exit',
      from: { path: '/bookshelf', search: { select: 'true', modal: null } },
      to: '/bookshelf',
      search: { select: null, modal: null },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '退出书架选择模式',
      ui: { placement: 'content', icon: 'bookshelf_select_exit', gesture: 'tap' },
    },
    {
      id: 'bookshelf.modal.private.open',
      from: { path: '/bookshelf', search: { select: 'true', modal: null } },
      to: '/bookshelf',
      search: { select: 'true', modal: 'private_reading' },
      searchParams: {},
      preserveParams: [],
      mode: 'push',
      params: {},
      label: '打开私密阅读弹窗',
      ui: { placement: 'content', icon: 'bookshelf_modal_private', gesture: 'tap' },
    },
    {
      id: 'bookshelf.modal.confirm_remove.open',
      from: { path: '/bookshelf', search: { select: 'true', modal: null } },
      to: '/bookshelf',
      search: { select: 'true', modal: 'confirm_remove' },
      searchParams: {},
      preserveParams: [],
      mode: 'push',
      params: {},
      label: '打开移出书架弹窗',
      ui: { placement: 'content', icon: 'bookshelf_modal_remove', gesture: 'tap' },
    },
    {
      id: 'book.modal.shelf.open',
      from: { path: '/book/:bookId', search: { modal: null } },
      to: '/book/:bookId',
      search: { modal: 'shelf' },
      searchParams: {},
      mode: 'push',
      params: { bookId: 'string' },
      label: '书架管理',
      ui: {
        placement: 'content',
        icon: 'book_modal_shelf',
        gesture: 'tap',
        // 入口显示条件：bookId 存在于书架中
        condition: {
          op: 'memberOf',
          ref: 'shelf',
          param: 'bookId',
          field: 'bookId',
          text: '已加入书架',
        },
      },
      // 数据源：可展开的 bookId 来自书架
      dataSource: {
        ref: 'shelf',
        paramMapping: { bookId: 'bookId' },
      },
    },
    {
      id: 'reader.modal.shelf.open',
      from: { path: '/read/:bookId', search: { modal: null } },
      to: '/read/:bookId',
      search: { modal: 'shelf' },
      searchParams: {},
      mode: 'push',
      params: { bookId: 'string' },
      label: '书架管理',
      ui: {
        placement: 'content',
        icon: 'reader_modal_shelf',
        gesture: 'tap',
        // 入口显示条件：bookId 存在于书架中
        condition: {
          op: 'memberOf',
          ref: 'shelf',
          param: 'bookId',
          field: 'bookId',
          text: '已加入书架',
        },
      },
      // 数据源：可展开的 bookId 来自书架
      dataSource: {
        ref: 'shelf',
        paramMapping: { bookId: 'bookId' },
      },
    },
    {
      id: 'reader.toc.open',
      from: [
        { path: '/read/:bookId', search: { tool: null } },
        { path: '/read/:bookId', search: { tool: '*' } }
      ],
      to: '/read/:bookId',
      search: { tool: 'toc' },
      searchParams: {},
      mode: 'replace',
      params: { bookId: 'string' },
      label: '打开目录',
      ui: { placement: 'content', icon: 'reader_tool_toc', gesture: 'tap' },
    },
    {
      id: 'reader.progress.open',
      from: [
        { path: '/read/:bookId', search: { tool: null } },
        { path: '/read/:bookId', search: { tool: '*' } }
      ],
      to: '/read/:bookId',
      search: { tool: 'progress' },
      searchParams: {},
      mode: 'replace',
      params: { bookId: 'string' },
      label: '打开阅读进度',
      ui: { placement: 'content', icon: 'reader_tool_progress', gesture: 'tap' },
    },
    {
      id: 'reader.theme.open',
      from: [
        { path: '/read/:bookId', search: { tool: null } },
        { path: '/read/:bookId', search: { tool: '*' } }
      ],
      to: '/read/:bookId',
      search: { tool: 'theme' },
      searchParams: {},
      mode: 'replace',
      params: { bookId: 'string' },
      label: '打开阅读主题',
      ui: { placement: 'content', icon: 'reader_tool_theme', gesture: 'tap' },
    },
    {
      id: 'reader.typography.open',
      from: [
        { path: '/read/:bookId', search: { tool: null } },
        { path: '/read/:bookId', search: { tool: '*' } }
      ],
      to: '/read/:bookId',
      search: { tool: 'typography' },
      searchParams: {},
      mode: 'replace',
      params: { bookId: 'string' },
      label: '打开阅读排版',
      ui: { placement: 'content', icon: 'reader_tool_typography', gesture: 'tap' },
    },
    {
      id: 'reader.tool.close',
      from: { path: '/read/:bookId', search: { tool: '*' } },
      to: '/read/:bookId',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: { bookId: 'string' },
      label: '关闭阅读工具面板',
      ui: { placement: 'content', icon: 'reader_tool_close', gesture: 'tap' },
    },
    {
      id: 'user.modal.unfollow.open',
      from: { path: '/user/:userId', search: { modal: null } },
      to: '/user/:userId',
      search: { modal: 'unfollow_confirm' },
      searchParams: {},
      mode: 'push',
      params: { userId: 'string' },
      label: '打开取消关注弹窗',
      ui: {
        placement: 'content',
        icon: 'user_modal_unfollow',
        gesture: 'tap',
        // 入口显示条件：userId 存在于关注列表中
        condition: {
          op: 'memberOf',
          ref: 'user.following',
          param: 'userId',
          field: '$value',  // user.following 是 ['user_508'] 形式
          text: '✓ 已关注',
        },
      },
      // 数据源：可展开的 userId 来自关注列表
      dataSource: {
        ref: 'user.following',
        paramMapping: { userId: '$value' },
      },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
