/**
 * RedBook 字符串资源 — 对应 AOSP res/values/strings.xml
 */
export const strings = {

  // ── TabBar ──
  home: '首页',
  shop: '市集',
  post: '发布',
  messages: '消息',
  tabbar_me: '我',

  // ── TabBar 发布菜单 ──
  choose_from_album: '从相册选择',
  shoot_and_live: '拍摄与直播',
  write_text: '写文字',
  cancel: '取消',

  // ── HomePage ──
  following: '关注',
  explore: '发现',
  nearby: '同城',
  recommend: '推荐',
  video: '视频',
  live: '直播',
  short_drama: '短剧',
  following_2: '已关注',
  homepage_more: '更多',
  follow_people_you_like_to_see_their_posts: '关注你感兴趣的人，看他们的动态',
  no_more_following_content: '- 暂时没有更多关注内容 -',
  my_channels: '我的频道',
  tap_to_enter_channel: '点击进入频道',
  homepage_edit: '进入编辑',
  recommended_channels: '推荐频道',
  tap_to_add_channel: '点击添加频道',
  homepage_all: '全城',
  map_explore: '地图探索',
  nearby_2: '同城 ⇆',
  distance: '位置距离',
  the_end: '- THE END -',

  // ── HomePage ──
  avatar: '头像',
  fashion: '穿搭',
  wallpaper: '壁纸',
  food: '美食',
  emotions: '情感',
  music: '音乐',
  nails: '美甲',
  funny: '搞笑',
  crafts: '手工',
  travel: '旅行',
  makeup: '彩妆',
  hairstyle: '发型',
  dance: '舞蹈',
  drawing: '绘画',
  reading: '读书',
  home_decor: '家装',
  celebrity: '明星',
  movies_and_tv: '影视',
  games: '游戏',
  photography: '摄影',
  anime: '动漫',
  home_2: '家居',
  cars: '汽车',
  weight_loss: '减脂',
  study: '学习',
  skincare: '护肤',
  wedding: '婚礼',
  stationery: '文具',
  sneakers: '潮鞋',
  career: '职场',
  culture: '文化',
  pets: '萌宠',
  tech: '科技',
  fitness: '健身',
  variety_shows: '综艺',
  bags: '箱包',
  science: '科学',
  baby: '母婴',
  homepage_art: '艺术',
  psychology: '心理',
  motorcycle: '机车',
  campus: '校园',
  sports: '体育',
  outdoor: '户外',
  figures: '潮玩',
  camping: '露营',
  social_science: '社科',
  humanities: '人文',

  // ── HomePage ──
  popular_spots: '热门打卡地',
  weekend_trips: '周末出行',
  nearby_travel: '周边游',
  attractions: '景点',

  // ── 时间格式 ──
  just_now: '刚刚',
  month_suffix: '月',
  day_suffix: '日',

  // ── 图片占位 ──
  no_image: 'No Image',

  // ── MePage ──
  set_background: '设置背景',
  rednote_id: '小红书号：',
  ip_location: 'IP属地：',
  unknown: '未知',
  tap_here_to_fill_in_your_bio: '点击这里，填写简介',
  followers: '粉丝',
  likes_and_collects: '获赞与收藏',
  edit_profile: '编辑资料',
  inspiration: '创作灵感',
  learn_to_create: '学创作找灵感',
  history: '浏览记录',
  viewed_notes: '看过的笔记',
  group_chats: '群聊',
  view_details: '查看详情',
  notes: '笔记',
  comments: '评论',
  collects: '收藏',
  likes: '赞过',
  public: '公开',
  private: '私密',
  collection: '合集',
  share_your_diving_diary: '晒出你的潜水日记',
  join_trending_topics: '官方喊你来参与热门话题',
  post_now: '去发布',
  nothing_here_yet: '这里空空如也~',

  // ── MessagePage ──
  likes_and_saves: '赞和收藏',
  new_followers: '新增关注',
  comments_and_at: '评论和@',

  // ── SettingsPage ──
  settings: '设置',
  account_and_security: '账号与安全',
  general_settings: '通用设置',
  notification_settings: '通知设置',
  language_and_translation: '多语言和翻译',
  privacy_settings: '隐私设置',
  storage: '存储空间',
  rednote_used_space: '小红书占用空间',
  phone_used_space: '手机已用空间',
  phone_free_space: '手机可用空间',
  takes_up_1_percent_of_phone_storage: '占手机可用空间的 1%',
  cache: '缓存',
  cache_description: '清理缓存以释放存储空间',
  clean: '清理',
  manage: '管理',
  downloads_description: '查看和管理已下载内容',
  drafts: '草稿',
  drafts_description: '管理未发布的草稿',
  chat_files: '聊天文件',
  chat_files_description: '查看聊天中的文件占用',
  content_preferences: '内容偏好调节',
  shipping_address: '收货地址',
  add_widgets: '添加小组件',
  teen_mode: '未成年人模式',
  settingspage_off: '未开启',
  settingspage_on: '已开启',
  new_features: '新功能体验',
  help_and_support: '帮助与客服',
  about_rednote: '关于小红书',
  switch_account: '切换账号',
  log_out: '退出登录',
  personal_info_collected_list: '《个人信息收集清单》',
  third_party_info_sharing_list: '《第三方信息共享清单》',
  rednote_user_agreement: '《小红书用户服务协议》',
  rednote_privacy_policy: '《小红书用户隐私政策》',

  // ── LanguageSettingsPage ──
  simplified_chinese: '简体中文',
  traditional_chinese: '繁体中文',
  languagesettingspage_save: '保存',
  select_language: '选择语言',

  // ── SearchPage ──
  search: '搜索',
  searchpage_hot: '热',
  searchpage_new: '新',
  searchpage_all: '全部',
  users: '用户',
  products: '商品',
  images: '图片',
  searchpage_ask: '问一问',
  general: '综合',
  latest: '最新',
  most_liked: '最多点赞',
  most_commented: '最多评论',
  most_collected: '最多收藏',
  recent_searches: '历史记录',
  delete_all: '全部删除',
  searchpage_done: '完成',
  discover: '猜你想搜',
  rednote_trending: '小红书热点',
  sort_by: '排序依据',
  note_type: '笔记类型',
  searchpage_any: '不限',
  image_and_text: '图文',
  post_time: '发布时间',
  within_1_day: '一天内',
  within_1_week: '一周内',
  within_6_months: '半年内',
  search_scope: '搜索范围',
  viewed: '已看过',
  not_viewed: '未看过',
  near_me: '附近',
  reset: '重置',
  collapse: '收起',
  no_related_content_found: '未找到相关内容',
  rednote_id_2: '小红书号:',
  no_users_found: '未找到相关用户',

  // ── DetailPage ──
  not_interested: '不喜欢',
  default: '默认',
  share_your_thoughts: '留下你的想法吧',
  reply: '回复',
  replying_to: '正在回复:',
  detailpage_send: '发送',
  say_something: '说点什么...',

  // ── ChatPage ──
  message: '发消息...',

  // ── Drawer ──
  discover_friends: '添加好友',
  annual_report_2025: '2025年度报告',
  creator_center: '创作者中心',
  my_drafts: '我的草稿',
  my_downloads: '我的下载',
  orders: '订单',
  shopping_cart: '购物车',
  wallet: '钱包',
  applets: '小程序',
  community_guidelines: '社区公约',
  scan: '扫一扫',

  // ── ShareModal ──
  share_to: '分享至',
  invite_friends: '邀请好友',
  direct_message: '私信好友',
  wechat: '微信好友',
  moments: '朋友圈',
  sharemodal_qq: 'QQ好友',
  qq_zone: 'QQ空间',
  copy_link: '复制链接',
  generate_share_image: '生成分享图',
  share_to_group: '建群分享',
  save_image: '保存图片',

  // ── EditProfilePage ──
  preview: '预览',
  name: '名字',
  rednote_id_3: '小红书号',
  cover_image: '背景图',
  editprofilepage_bio: '简介',
  introduce_yourself: '介绍一下自己',
  gender: '性别',
  male: '男',
  female: '女',
  birthday: '生日',
  select_birthday: '选择生日',
  region: '地区',
  select_region: '选择所在的地区',
  occupation: '职业',
  select_occupation: '选择职业',
  school: '学校',
  select_school: '选择学校',
  original_content: '原创信息',
  not_verified_yet: '暂未完成原创认证',
  select_gender: '选择性别',

  // ── UserPage ──
  no_bio: '暂无简介',
  this_person_is_lazy_and_wrote_nothing: '这个人很懒，什么都没有写～',
  message_2: '私信',

  // ── FollowListPage ──

  // ── HistoryPage ──
  no_browsing_history: '暂无浏览记录',

  // ── ChatSettingsPage ──
  set_nickname: '设置备注名',
  search_chat_history: '查找聊天记录',
  chatsettingspage_pin: '置顶',
  mute_notifications: '消息免打扰',
  block: '加入黑名单',
  report: '举报',
  clear_chat_history: '清空聊天记录',

  // ── AccountSecurityPage ──
  phone_number: '手机号',
  login_password: '登录密码',
  not_set: '未设置',
  wechat_account: '微信账号',
  not_linked: '未绑定',
  weibo_account: '微博账号',
  qq_account: 'QQ账号',
  id_verification: '实名认证',
  not_verified: '未认证',
  official_verification: '官方认证',
  professional_org_or_business_verification: '个人职业资质、机构、企业认证',
  device_management: '登录设备管理',
  account_recovery: '账号找回',
  recover_and_log_in_to_another_account: '无法登录其他账号，通过该方式找回并登录',
  pro_account: '专业号',
  not_upgraded: '未升级',
  delete_account: '注销账号',

  // ── GeneralSettingsPage ──
  display: '显示',
  font_size: '字体大小',
  use_system_default_font: '使用系统默认字体',
  dark_mode: '深色模式',
  features: '功能',
  play_note_audio_by_default: '默认播放图文笔记声音',
  auto_refresh: '允许自动刷新',
  content_won_t_auto_refresh_unless_restarted: '关闭后除重新启动外将不会自动刷新内容',
  mute_video_and_live_by_default: '打开视频和直播时默认静音',
  download_over_mobile_data: '使用移动流量下载内容',
  enable_video_hdr: '视频开启HDR效果',
  enable_image_hdr: '图片开启HDR效果',
  use_mobile_network_to_improve_browsing: '使用移动网络改善浏览体验',
  history_will_be_cleared_when_turned_off: '关闭后，不再记录并删除历史浏览记录',
  video_interaction_buttons_at_bottom: '视频底部互动按钮',
  buttons_move_to_the_right_side_when_turned_off: '关闭后，首页视频互动按钮将在右侧展示',
  other: '其他',
  pre_upload_video_when_posting: '允许发布时提前上传视频',
  reduces_wait_time_for_video_publishing: '开启可减少视频发布的等待时长',

  // ── NotificationSettingsPage ──
  receive_notifications: '接收消息通知',
  interaction_notifications: '互动通知',
  dm_notifications: '私信通知',
  receive: '接收',
  community_notifications: '社区内容通知',
  author_updates: '关注作者的更新',
  following_unread_reminder: '关注未读提醒',
  live_reminder: '开播提醒',
  notificationsettingspage_off: '不接收',
  content_recommendations: '内容推荐',
  user_recommendations: '用户推荐',
  other_notifications: '其他通知',
  shopping_notifications: '商城通知',
  shopping_and_after_sale: '购物及售后通知',
  you_may_miss_delivery_and_price_drop_alerts: '关闭后，可能会错过"物流动态"、"降价提醒"等通知',
  in_app_banner: 'App内通知横幅',

  // ── PrivacySettingsPage ──
  interaction: '互动',
  quick_protection: '一键防护',
  block_dms_comments_shares_from_non_followers_for: '开启后，7天内将不接收未关注人的私信/评论/分享',
  online_status: '在线状态',
  friends: '好友',
  show_chat_badge: '展示聊天标识',
  only_followers_can_comment: '只允许我关注的人评论我',
  only_followers_can_send_danmaku: '只允许我关注的人给我发弹幕',
  only_followers_can_at_me: '只允许我关注的人@ 我',
  allow_downloading_all_notes: '允许下载全部笔记',
  including_images_videos_and_text_copy: '包含图片视频下载和正文复制',
  who_can_dm_me: '谁可以私信我',
  people_i_follow: '我关注的人',
  my_collects: '我的收藏',
  private_2: '不公开',
  my_reviews: '我的评价',
  public_2: '已公开',
  connections: '关系',
  ways_to_find_me: '找到我的方式',
  following_and_followers: '关注与粉丝列表',
  recommend_people_i_may_know: '给我推荐可能认识的人',
  blocked_users: '黑名单用户',
  permissions: '权限',
  system_permissions: '系统权限管理',
  all_system_permissions_used_in_app: 'APP 内使用的所有系统权限',

  // ── Privacy Sub-pages ──
  collects_privacy: '收藏隐私设置',
  make_collects_public: '公开我的收藏',
  others_won_t_see_your_collects_when_off: '关闭后，他人将无法查看你所有收藏的内容',
  review_privacy: '评价隐私设置',
  public_review_categories: '公开评价的类别',
  location: '地点',
  recommend_me_to_people_i_may_know: '把我推荐给可能认识的人',
  show_me_in_others_connections: '把我展示在他人关系列表',
  hide_my_notes_from_nearby: '在「附近」页隐藏我的笔记',
  hide_my_notes_from_visual_search: '在「识图搜同款」中隐藏我的笔记',
  hide_my_following_list: '隐藏我的关注列表',
  hide_my_followers_list: '隐藏我的粉丝列表',
  mutual_followers: '互相关注的人',
  disable_dm: '禁止私信',
  choose_who_can_dm_me: '选择可以私信我的人',
  personalization: '个性化选项',
  enable_personalized_recommendations: '开启个性化推荐',
  disabling_may_show_less_relevant_content: '关闭后，将不会使用你的偏好特征进行内容推荐，你可能会看到不感兴趣的内容',
  learn_more: '详细了解',
  enable_personalized_ads: '开启广告个性化推荐',
  ad_count_stays_the_same_but_relevance_decreases: '关闭后，看到的广告数量不变但相关度会降低。',
  third_party_data: '第三方数据合作',
  go_to_settings: '去设置',
  rednote_requests_these_permissions_for_specific: '为保证产品与功能的使用，小红书会在特定场景下向你申请以下权限',
  contacts: '通讯录',
  location_2: '位置',
  camera: '照相机',
  photos: '相册',
  microphone: '麦克风',
  clipboard: '剪切板',
  system_permission_settings: '系统权限设置',
  public_visible_to_all: '公开：所有人可见',
  friends_visible_to_mutual_followers: '好友：仅互相关注的人可见',
  off_hidden_from_everyone: '关闭：所有人不可见',
  both_can_see_online_status_group_chats_show: '开启后，双方可以看到对方的在线状态，群聊中会展示在线人数',

  // ── Notification Sub-pages ──
  interested_notes_only: '仅感兴趣的笔记',
  community_highlights_only: '仅社区热点',
  live_stream_reminder: '直播开播提醒',
  trending_push: '热榜推送',
  topic_recommendations: '话题推荐',
  private_chat: '私聊',
  strangers: '陌生人',
  people_i_may_know_only: '仅我可能认识的人',
  authors_i_may_like_only: '仅我可能喜欢的作者',

  // ── LikesAndCollectionsPage ──
  liked_your_note: '赞了你的笔记',
  collected_your_note: '收藏了你的笔记',
  liked_your_comment: '赞了你的评论',
  no_messages: '暂无消息',

  // ── CommentsAndAtPage ──
  replied_to_you: '回复了你:',
  no_comments: '暂无评论',

  // ── NewFollowersPage ──
  followed_you: '关注了你',
  mutual: '互相关注',
  follow_back: '回粉',
  no_new_followers: '暂无新增关注',

  // ── ShopPage ──
  beauty: '美妆护肤',
  fashion_2: '时尚穿搭',
  home_and_living: '家居生活',
  food_and_drinks: '美食美酒',
  baby_and_kids: '母婴亲子',
  sports_and_outdoor: '运动户外',
  electronics: '数码家电',
  must_buys: '双11必买',
  flash_sale: '限时购',
  picks: '种草',
  shoppage_end: '- 到底了 -',

  // ── Publish Pages ──
  write_a_post: '写想法',
  placeholder: '占位',
  next: '下一步',
  say_something_or_ask_a_question: '说点什么或提个问题...',
  write_long_post: '写长文',
  supports_10k_and_words_full_screen_reading: '支持万字，全屏阅读体验',
  publish_note: '发布笔记',
  add_title: '添加标题',
  topic: '话题',
  poll: '投票',
  tag_location: '标记地点',
  visible_to_all: '公开可见',
  add_component: '添加组件',
  can_add_files: '可添加文件',
  advanced_options: '高级选项',
  save_draft: '存草稿',
  basic: '基础',
  fresh: '清新',
  memo: '备忘',
  border: '边框',
  doodle: '涂鸦',
  choose_a_card_you_like: '选一个喜欢的卡片',

  // ── AddFriendPage ──
  search_users: '搜索用户',
  no_intro: '暂无介绍',

  // ── 通用 / 共享 ──
  ok: '确定',
  like: '点赞',
  no_more: '没有更多了',
  none: '暂无',

  // ── 补充翻译 ──
  popular_slimming_outfits: '大家都在搜: "显瘦穿搭"',
  slimming_outfits: '显瘦穿搭',
  which_in_app_notification_banners_to_receive: '接收哪些类型的App内通知横幅',
  enter_new_image_url: '请输入新的图片URL',
  shanghai: '上海',
  k: '万',
  press_again_to_go_home: '再按一次返回桌面',
  this_outfit_looks_great_love_it: '这套搭配很好看！爱了爱了❤️',
  ucas: '中国科学院大学',
  cas_physics: '中国科学院物理研',
  brbr_syrian_food: 'BRBR叙利亚餐',

  // ── 时间格式 ──
  min_ago: '分钟前',
  hr_ago: '小时前',
  days_ago: '天前',

  // ── 北京区域名 ──
  popular_areas: '热门商圈',
  dongcheng: '东城区',
  chaoyang: '朝阳区',
  haidian: '海淀区',
  tongzhou: '通州区',
  daxing: '大兴区',
  xicheng: '西城区',
  fengtai: '丰台区',
  sanlitun: '三里屯',
  wangjing: '望京',
  liyuan: '梨园',
  yaojiayuan: '姚家园',
  jianwai_ave: '建外大街',
  dawang_rd: '大望路',
  hongmiao: '红庙',
  xiyuan: '西苑',

  // ── SearchPage ──
  singer_2026_announced: '歌手2026官宣',
  movie_releases: '电影上映',
  birthday_quotes: '生日文案',
  day_and_night_rotation: '旋转昼夜',

  // ── 补充缺失 ──
  user_not_found: '用户未找到',
  note_not_found: '笔记未找到',
  total_prefix: '共',
  comments_suffix: '条评论',
  replying: '正在回复',
  edit_field: '修改',
  people_paid: '人付款',
  ip_location_2: 'IP属地',
  whole_city: '全城',
  same_city: '同城',
  followed: '已关注',
  everyone_searching: '大家都在搜: "显瘦穿搭"',
  english: 'English',
} as const;

export type StringKey = keyof typeof strings;
