/**
 * RedBook 英文翻译 — 对应 AOSP res/values-en/strings.xml
 */
import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {

  // ── TabBar ──
  home: 'Home',
  shop: 'Market',
  post: 'Post',
  messages: 'Messages',
  tabbar_me: 'Me',

  // ── TabBar 发布菜单 ──
  choose_from_album: 'Choose from Album',
  shoot_and_live: 'Shoot & Live',
  write_text: 'Write Text',
  cancel: 'Cancel',

  // ── HomePage ──
  following: 'Following',
  explore: 'Explore',
  nearby: 'Nearby',
  recommend: 'For You',
  video: 'Video',
  live: 'Live',
  short_drama: 'Short Drama',
  following_2: 'Following',
  homepage_more: 'More',
  follow_people_you_like_to_see_their_posts: 'Follow people you like to see their posts',
  no_more_following_content: '- No more following content -',
  my_channels: 'My Channels',
  tap_to_enter_channel: 'Tap to enter channel',
  homepage_edit: 'Edit',
  recommended_channels: 'Recommended Channels',
  tap_to_add_channel: 'Tap to add channel',
  homepage_all: 'All',
  map_explore: 'Map Explore',
  nearby_2: 'Nearby ⇆',
  distance: 'Distance',
  the_end: '- THE END -',

  // ── HomePage ──
  avatar: 'Avatar',
  fashion: 'Fashion',
  wallpaper: 'Wallpaper',
  food: 'Food',
  emotions: 'Emotions',
  music: 'Music',
  nails: 'Nails',
  funny: 'Funny',
  crafts: 'Crafts',
  travel: 'Travel',
  makeup: 'Makeup',
  hairstyle: 'Hairstyle',
  dance: 'Dance',
  drawing: 'Drawing',
  reading: 'Reading',
  home_decor: 'Home Decor',
  celebrity: 'Celebrity',
  movies_and_tv: 'Movies & TV',
  games: 'Games',
  photography: 'Photography',
  anime: 'Anime',
  home_2: 'Home',
  cars: 'Cars',
  weight_loss: 'Weight Loss',
  study: 'Study',
  skincare: 'Skincare',
  wedding: 'Wedding',
  stationery: 'Stationery',
  sneakers: 'Sneakers',
  career: 'Career',
  culture: 'Culture',
  pets: 'Pets',
  tech: 'Tech',
  fitness: 'Fitness',
  variety_shows: 'Variety Shows',
  bags: 'Bags',
  science: 'Science',
  baby: 'Baby',
  homepage_art: 'Art',
  psychology: 'Psychology',
  motorcycle: 'Motorcycle',
  campus: 'Campus',
  sports: 'Sports',
  outdoor: 'Outdoor',
  figures: 'Figures',
  camping: 'Camping',
  social_science: 'Social Science',
  humanities: 'Humanities',

  // ── HomePage ──
  popular_spots: 'Popular Spots',
  weekend_trips: 'Weekend Trips',
  nearby_travel: 'Nearby Travel',
  attractions: 'Attractions',

  // ── 时间格式 ──
  just_now: 'Just now',
  month_suffix: '',  // English dates don't use month/day suffix particles
  day_suffix: '',

  // ── 图片占位 ──
  no_image: 'No Image',

  // ── MePage ──
  set_background: 'Edit background image',
  rednote_id: 'rednote ID: ',
  ip_location: 'IP Location: ',
  unknown: 'Unknown',
  tap_here_to_fill_in_your_bio: 'Tap here to fill in your bio',
  followers: 'Followers',
  likes_and_collects: 'Likes & Saves',
  edit_profile: 'Edit profile',
  inspiration: 'Sparks',
  learn_to_create: 'Find sparks',
  history: 'History',
  viewed_notes: 'Viewed notes',
  group_chats: 'Group Chats',
  view_details: 'View Details',
  notes: 'Notes',
  comments: 'Comments',
  collects: 'Saves',
  likes: 'Likes',
  public: 'Public',
  private: 'Private',
  collection: 'Album',
  share_your_diving_diary: 'Share your diving diary',
  join_trending_topics: 'Join trending topics',
  post_now: 'Post Now',
  nothing_here_yet: 'Nothing here yet~',

  // ── MessagePage ──
  likes_and_saves: 'Likes & Saves',
  new_followers: 'New followers',
  comments_and_at: 'Comments & @',

  // ── SettingsPage ──
  settings: 'Settings',
  account_and_security: 'Account Security',
  general_settings: 'General',
  notification_settings: 'Notifications',
  language_and_translation: 'Language and translation',
  privacy_settings: 'Privacy',
  storage: 'Storage',
  rednote_used_space: 'rednote Used Space',
  phone_used_space: 'Phone Used Space',
  phone_free_space: 'Phone Free Space',
  takes_up_1_percent_of_phone_storage: 'Takes up 1% of phone storage',
  cache: 'Cache',
  cache_description: 'Clear cache to free up storage',
  clean: 'Clean',
  manage: 'Manage',
  downloads_description: 'View and manage downloaded content',
  drafts: 'Drafts',
  drafts_description: 'Manage unpublished drafts',
  chat_files: 'Chat Files',
  chat_files_description: 'View chat file storage usage',
  content_preferences: 'Content preferences',
  shipping_address: 'Delivery addresses',
  add_widgets: 'Widgets',
  teen_mode: 'Minor mode',
  settingspage_off: 'Disabled',
  settingspage_on: 'Enabled',
  new_features: 'Try New Features',
  help_and_support: 'Help center',
  about_rednote: 'About rednote',
  switch_account: 'Switch Account',
  log_out: 'Log Out',
  personal_info_collected_list: 'Personal Info Collected List',
  third_party_info_sharing_list: 'Third-party Info Sharing List',
  rednote_user_agreement: 'rednote User Agreement',
  rednote_privacy_policy: 'rednote Privacy Policy',

  // ── LanguageSettingsPage ──
  simplified_chinese: 'Simplified Chinese',
  traditional_chinese: 'Traditional Chinese',
  languagesettingspage_save: 'Save',
  select_language: 'Select Language',

  // ── SearchPage ──
  search: 'Search',
  searchpage_hot: 'Hot',
  searchpage_new: 'New',
  searchpage_all: 'All',
  users: 'Users',
  products: 'Products',
  images: 'Images',
  searchpage_ask: 'Ask',
  general: 'General',
  latest: 'Latest',
  most_liked: 'Most Liked',
  most_commented: 'Most Commented',
  most_collected: 'Most Collected',
  recent_searches: 'Recent searches',
  delete_all: 'Delete All',
  searchpage_done: 'Done',
  discover: 'Discover',
  rednote_trending: 'rednote Trending',
  sort_by: 'Sort By',
  note_type: 'Note Type',
  searchpage_any: 'Any',
  image_and_text: 'Image & Text',
  post_time: 'Post Time',
  within_1_day: 'Within 1 Day',
  within_1_week: 'Within 1 Week',
  within_6_months: 'Within 6 Months',
  search_scope: 'Search Scope',
  viewed: 'Viewed',
  not_viewed: 'Not Viewed',
  near_me: 'Near Me',
  reset: 'Reset',
  collapse: 'Collapse',
  no_related_content_found: 'No related content found',
  rednote_id_2: 'rednote ID:',
  no_users_found: 'No users found',

  // ── DetailPage ──
  not_interested: 'Not Interested',
  default: 'Default',
  share_your_thoughts: 'Share your thoughts',
  reply: 'Reply',
  replying_to: 'Replying to:',
  detailpage_send: 'Send',
  say_something: 'Say something...',

  // ── ChatPage ──
  message: 'Message...',

  // ── Drawer ──
  discover_friends: 'Add friends',
  annual_report_2025: '2025 Annual Report',
  creator_center: 'Creator Center',
  my_drafts: 'Drafts',
  my_downloads: 'My Download',
  orders: 'Orders',
  shopping_cart: 'Cart',
  wallet: 'Wallet',
  applets: 'Applets',
  community_guidelines: 'Community Guidelines',
  scan: 'Scan',

  // ── ShareModal ──
  share_to: 'Share to',
  invite_friends: 'Invite Friends',
  direct_message: 'Direct Message',
  wechat: 'WeChat',
  moments: 'Moments',
  sharemodal_qq: 'QQ',
  qq_zone: 'QQ Zone',
  copy_link: 'Copy Link',
  generate_share_image: 'Generate Share Image',
  share_to_group: 'Share to Group',
  save_image: 'Save Image',

  // ── EditProfilePage ──
  preview: 'Preview',
  name: 'Name',
  rednote_id_3: 'Rednote ID',
  cover_image: 'Background',
  editprofilepage_bio: 'Bio',
  introduce_yourself: 'Introduce yourself',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  birthday: 'Birthday',
  select_birthday: 'Edit birthday',
  region: 'Region',
  select_region: 'Edit region',
  occupation: 'Occupation',
  select_occupation: 'Edit occupation',
  school: 'School',
  select_school: 'Add education',
  original_content: 'Original',
  not_verified_yet: 'Original certification not completed yet',
  select_gender: 'Select Gender',

  // ── UserPage ──
  no_bio: 'No bio',
  this_person_is_lazy_and_wrote_nothing: 'This person is lazy and wrote nothing~',
  message_2: 'Message',

  // ── FollowListPage ──

  // ── HistoryPage ──
  no_browsing_history: 'No browsing history',

  // ── ChatSettingsPage ──
  set_nickname: 'Set Nickname',
  search_chat_history: 'Search Chat History',
  chatsettingspage_pin: 'Pin',
  mute_notifications: 'Mute Notifications',
  block: 'Block',
  report: 'Report',
  clear_chat_history: 'Clear Chat History',

  // ── AccountSecurityPage ──
  phone_number: 'Mobile',
  login_password: 'Password',
  not_set: 'Not Set',
  wechat_account: 'WeChat',
  not_linked: 'Not linked',
  weibo_account: 'Weibo Account',
  qq_account: 'QQ',
  id_verification: 'ID verification',
  not_verified: 'Not verified',
  official_verification: 'Official verification',
  professional_org_or_business_verification: 'Personal professional, institutional and business verification',
  device_management: 'Device management',
  account_recovery: 'Recover account',
  recover_and_log_in_to_another_account: 'Recover an account you cannot access',
  pro_account: 'Pro account',
  not_upgraded: 'Not Enabled',
  delete_account: 'Delete Account',

  // ── GeneralSettingsPage ──
  display: 'Display',
  font_size: 'Text size',
  use_system_default_font: 'Match system font',
  dark_mode: 'Dark mode',
  features: 'Features',
  play_note_audio_by_default: 'Auto-play note audio',
  auto_refresh: 'Auto-refresh',
  content_won_t_auto_refresh_unless_restarted: 'If disabled, content will not automatically update unless you restart the app',
  mute_video_and_live_by_default: 'Mute videos and livestreams by default',
  download_over_mobile_data: 'Download with mobile data',
  enable_video_hdr: 'HDR media for videos',
  enable_image_hdr: 'Enable image HDR',
  use_mobile_network_to_improve_browsing: 'Use mobile data for a better experience',
  history_will_be_cleared_when_turned_off: 'If disabled, browsing history will no longer be recorded',
  video_interaction_buttons_at_bottom: 'Buttons below video',
  buttons_move_to_the_right_side_when_turned_off: 'When disabled, the homepage video buttons will appear on the right',
  other: 'Other',
  pre_upload_video_when_posting: 'Pre-upload videos before posting',
  reduces_wait_time_for_video_publishing: 'Enable for faster video posting',

  // ── NotificationSettingsPage ──
  receive_notifications: 'Receive Notifications',
  interaction_notifications: 'Engagement notifications',
  dm_notifications: 'Chat notifications',
  receive: 'Allow',
  community_notifications: 'Community Notifications',
  author_updates: 'Followed accounts',
  following_unread_reminder: 'Following unread reminder',
  live_reminder: 'Livestream notifications',
  notificationsettingspage_off: 'Off',
  content_recommendations: 'Content recommendations',
  user_recommendations: 'User recommendations',
  other_notifications: 'Others',
  shopping_notifications: 'Shopping Notifications',
  shopping_and_after_sale: 'Shopping and after-sale',
  you_may_miss_delivery_and_price_drop_alerts: 'You may miss delivery and price drop alerts',
  in_app_banner: 'In-App Banner',

  // ── PrivacySettingsPage ──
  interaction: 'Interactions',
  quick_protection: 'Protection mode',
  block_dms_comments_shares_from_non_followers_for: "When enabled, direct messages, comments and shares from people you don't follow will be blocked for 7 days",
  online_status: 'Activity status',
  friends: 'Friends',
  show_chat_badge: 'Show chat badges',
  only_followers_can_comment: 'Only allow comments from following',
  only_followers_can_send_danmaku: 'Bullet comments only from people I follow',
  only_followers_can_at_me: 'Only allow mentions from following',
  allow_downloading_all_notes: 'Allow downloading all notes',
  including_images_videos_and_text_copy: 'Includes downloading images, videos, and copying text',
  who_can_dm_me: 'Direct messages',
  people_i_follow: 'People I follow',
  my_collects: 'My saves',
  private_2: 'Private',
  my_reviews: 'My review',
  public_2: 'Public',
  connections: 'Connections',
  ways_to_find_me: 'How to find me',
  following_and_followers: 'Following & Followers',
  recommend_people_i_may_know: 'Recommend people I may know',
  blocked_users: 'Blacklist',
  permissions: 'Permissions',
  system_permissions: 'System permissions',
  all_system_permissions_used_in_app: 'All system permissions used within the app',

  // ── Privacy Sub-pages ──
  collects_privacy: 'Collects Privacy',
  make_collects_public: 'Make collects public',
  others_won_t_see_your_collects_when_off: "Others won't see your collects when off",
  review_privacy: 'Review Privacy',
  public_review_categories: 'Public review categories',
  location: 'Location',
  recommend_me_to_people_i_may_know: 'Recommend me to people I may know',
  show_me_in_others_connections: "Show me in others' connections",
  hide_my_notes_from_nearby: 'Hide my notes from Nearby',
  hide_my_notes_from_visual_search: 'Hide my notes from visual search',
  hide_my_following_list: 'Hide my following list',
  hide_my_followers_list: 'Hide my followers list',
  mutual_followers: 'Mutual followers',
  disable_dm: 'Disable DM',
  choose_who_can_dm_me: 'Choose who can DM me',
  personalization: 'Personalization',
  enable_personalized_recommendations: 'Enable personalized recommendations',
  disabling_may_show_less_relevant_content: 'Disabling may show less relevant content',
  learn_more: 'Learn more',
  enable_personalized_ads: 'Enable personalized ads',
  ad_count_stays_the_same_but_relevance_decreases: 'Ad count stays the same but relevance decreases.',
  third_party_data: 'Third-party data partnership',
  go_to_settings: 'Go to Settings',
  rednote_requests_these_permissions_for_specific: 'rednote requests these permissions for specific features',
  contacts: 'Contacts',
  location_2: 'Location',
  camera: 'Camera',
  photos: 'Photos',
  microphone: 'Microphone',
  clipboard: 'Clipboard',
  system_permission_settings: 'System Permission Settings',
  public_visible_to_all: 'Public: Visible to all',
  friends_visible_to_mutual_followers: 'Friends: Visible to mutual followers',
  off_hidden_from_everyone: 'Off: Hidden from everyone',
  both_can_see_online_status_group_chats_show: 'Both can see online status; group chats show online count',

  // ── Notification Sub-pages ──
  interested_notes_only: 'Interested notes only',
  community_highlights_only: 'Community highlights only',
  live_stream_reminder: 'Live stream reminder',
  trending_push: 'Trending push',
  topic_recommendations: 'Topic recommendations',
  private_chat: 'Private Chat',
  strangers: 'Strangers',
  people_i_may_know_only: 'People I may know only',
  authors_i_may_like_only: 'Authors I may like only',

  // ── LikesAndCollectionsPage ──
  liked_your_note: 'liked your note',
  collected_your_note: 'collected your note',
  liked_your_comment: 'liked your comment',
  no_messages: 'No messages',

  // ── CommentsAndAtPage ──
  replied_to_you: 'replied to you:',
  no_comments: 'No comments',

  // ── NewFollowersPage ──
  followed_you: 'followed you',
  mutual: 'Mutual',
  follow_back: 'Follow Back',
  no_new_followers: 'No new followers',

  // ── ShopPage ──
  beauty: 'Beauty',
  fashion_2: 'Fashion',
  home_and_living: 'Home & Living',
  food_and_drinks: 'Food & Drinks',
  baby_and_kids: 'Baby & Kids',
  sports_and_outdoor: 'Sports & Outdoor',
  electronics: 'Electronics',
  must_buys: 'Must Buys',
  flash_sale: 'Flash Sale',
  picks: 'Picks',
  shoppage_end: '- End -',

  // ── Publish Pages ──
  write_a_post: 'Write a Post',
  placeholder: 'Placeholder',
  next: 'Next',
  say_something_or_ask_a_question: 'Say something or ask a question...',
  write_long_post: 'Write Long Post',
  supports_10k_and_words_full_screen_reading: 'Supports 10k+ words, full-screen reading',
  publish_note: 'Publish Note',
  add_title: 'Add Title',
  topic: 'Topic',
  poll: 'Poll',
  tag_location: 'Tag Location',
  visible_to_all: 'Visible to all',
  add_component: 'Add Component',
  can_add_files: 'Can add files',
  advanced_options: 'Advanced Options',
  save_draft: 'Save Draft',
  basic: 'Basic',
  fresh: 'Fresh',
  memo: 'Memo',
  border: 'Border',
  doodle: 'Doodle',
  choose_a_card_you_like: 'Choose a card you like',

  // ── AddFriendPage ──
  search_users: 'Search users',
  no_intro: 'No intro',

  // ── 通用 / 共享 ──
  ok: 'OK',
  like: 'Like',
  no_more: 'No more',
  none: 'None',

  // ── 补充翻译 ──
  popular_slimming_outfits: 'Popular: "Slimming Outfits"',
  slimming_outfits: 'Slimming Outfits',
  which_in_app_notification_banners_to_receive: 'Which in-app notification banners to receive',
  enter_new_image_url: 'Enter new image URL',
  shanghai: 'Shanghai',
  k: 'K',
  press_again_to_go_home: 'Press again to go home',
  this_outfit_looks_great_love_it: 'This outfit looks great! Love it ❤️',
  ucas: 'UCAS',
  cas_physics: 'CAS Physics',
  brbr_syrian_food: 'BRBR Syrian Food',

  // ── 时间格式 ──
  min_ago: ' min ago',
  hr_ago: ' hr ago',
  days_ago: ' days ago',

  // ── 北京区域名 ──
  popular_areas: 'Popular Areas',
  dongcheng: 'Dongcheng',
  chaoyang: 'Chaoyang',
  haidian: 'Haidian',
  tongzhou: 'Tongzhou',
  daxing: 'Daxing',
  xicheng: 'Xicheng',
  fengtai: 'Fengtai',
  sanlitun: 'Sanlitun',
  wangjing: 'Wangjing',
  liyuan: 'Liyuan',
  yaojiayuan: 'Yaojiayuan',
  jianwai_ave: 'Jianwai Ave',
  dawang_rd: 'Dawang Rd',
  hongmiao: 'Hongmiao',
  xiyuan: 'Xiyuan',

  // ── SearchPage ──
  singer_2026_announced: 'Singer 2026 Announced',
  movie_releases: 'Movie Releases',
  birthday_quotes: 'Birthday Quotes',
  day_and_night_rotation: 'Day & Night Rotation',

  // ── 补充缺失 ──
  user_not_found: 'User not found',
  note_not_found: 'Note not found',
  total_prefix: 'Total',
  comments_suffix: ' comments',
  replying: 'Replying to',
  edit_field: 'Edit',
  people_paid: ' people paid',
  ip_location_2: 'IP Location',
  whole_city: 'All City',
  same_city: 'Same City',
  followed: 'Followed',
  everyone_searching: 'Everyone is searching: "Slimming Outfits"',
  english: 'English',
};
