import type { NavigationDeclaration } from './navigation.types';

const MAIN_SCROLL = [
  { name: 'main', direction: 'vertical', description: '页面主内容区' },
] as const;

export const NAVIGATION_DECLARATION = {
  app: 'sms',
  routes: [
    {
      path: '/',
      component: 'ConversationListPage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'sms.list.base', search: {}, description: '会话列表页' }],
      queryParams: {},
      description: '会话列表页',
    },
    {
      path: '/new',
      component: 'NewMessagePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'sms.new.base', search: {}, description: '新建短信页' }],
      queryParams: {},
      description: '新建短信页',
    },
    {
      path: '/conversation/:conversationId',
      component: 'ConversationDetailPage',
      params: { conversationId: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'sms.detail.base', search: {}, description: '短信会话详情页' }],
      queryParams: {},
      description: '短信会话详情页',
    },
    {
      path: '/settings',
      component: 'SettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'sms.settings.base', search: {}, description: '短信设置页' }],
      queryParams: {},
      description: '短信设置页',
    },
    {
      path: '/settings/free-network-sms',
      component: 'FreeNetworkSmsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'sms.settings.freeNetwork.base', search: {}, description: '免费网络短信设置页' }],
      queryParams: {},
      description: '免费网络短信设置页',
    },
    {
      path: '/settings/advanced',
      component: 'AdvancedSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'sms.settings.advanced.base', search: {}, description: '高级设置页' }],
      queryParams: {},
      description: '高级设置页',
    },
    {
      path: '/settings/5g-message',
      component: 'FiveGMessagePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'sms.settings.fiveG.base', search: {}, description: '5G消息设置页' }],
      queryParams: {},
      description: '5G消息设置页',
    },
    {
      path: '/settings/*',
      component: 'SettingsPlaceholderPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'sms.settings.placeholder.base', search: {}, description: '设置占位页' }],
      queryParams: {},
      description: '设置占位页',
    },
  ],
  transitions: [
    {
      id: 'compose.open',
      from: '/',
      to: '/new',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开新建短信页',
      ui: { placement: 'fab', icon: 'add', gesture: 'tap' },
    },
    {
      id: 'settings.open',
      from: '/',
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开短信设置页',
      ui: { placement: 'topbar', icon: 'settings', gesture: 'tap' },
    },
    {
      id: 'conversation.open',
      from: '/',
      to: '/conversation/:conversationId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { conversationId: 'string' },
      label: '打开会话详情页',
      ui: { placement: 'content', icon: 'conversation', gesture: 'tap' },
    },
    {
      id: 'conversation.open.fromNew',
      from: '/new',
      to: '/conversation/:conversationId',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: { conversationId: 'string' },
      label: '发送新短信后进入会话详情页',
      ui: { placement: 'content', icon: 'send', gesture: 'tap' },
    },
    {
      id: 'settings.free-network.open',
      from: '/settings',
      to: '/settings/free-network-sms',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开免费网络短信设置',
      ui: { placement: 'content', icon: 'free_sms', gesture: 'tap' },
    },
    {
      id: 'settings.advanced.open',
      from: '/settings',
      to: '/settings/advanced',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开高级设置',
      ui: { placement: 'content', icon: 'advanced', gesture: 'tap' },
    },
    {
      id: 'settings.5g.open',
      from: '/settings',
      to: '/settings/5g-message',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开5G消息设置',
      ui: { placement: 'content', icon: '5g', gesture: 'tap' },
    },
    {
      id: 'settings.placeholder.open',
      from: '/settings',
      to: '/settings/*',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开设置占位页',
      ui: { placement: 'content', icon: 'setting_item', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
