import { NavigationDeclaration, ScrollContainerDeclaration } from './navigation.types';

const MAIN_SCROLL: ScrollContainerDeclaration[] = [
  { name: 'main', direction: 'vertical', description: '页面主内容区' },
];

export const NAVIGATION_DECLARATION = {
  app: 'spotify',

  routes: [
    // =========================
    // Main Tabs
    // =========================
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      // Home 内会打开“歌曲菜单 Sheet”，需要 trackId 作为动态 query
      queryParams: { trackId: 'string' },
      uiStates: [
        // Home Top Tabs（必填离散状态：tab）
        { id: 'home.tab.all', search: { tab: 'all' }, description: '首页-全部' },
        { id: 'home.tab.wrapped', search: { tab: 'wrapped' }, description: '首页-年度总结' },
        { id: 'home.tab.music', search: { tab: 'music' }, description: '首页-音乐' },
        { id: 'home.tab.podcast', search: { tab: 'podcast' }, description: '首页-播客' },

        // Sidebar Drawer（保持 tab，但打开 drawer）
        {
          id: 'home.tab.all.drawer.sidebar',
          search: { tab: 'all', drawer: 'sidebar' },
          description: '首页-全部-侧边栏',
        },
        {
          id: 'home.tab.wrapped.drawer.sidebar',
          search: { tab: 'wrapped', drawer: 'sidebar' },
          description: '首页-年度总结-侧边栏',
        },
        {
          id: 'home.tab.music.drawer.sidebar',
          search: { tab: 'music', drawer: 'sidebar' },
          description: '首页-音乐-侧边栏',
        },
        {
          id: 'home.tab.podcast.drawer.sidebar',
          search: { tab: 'podcast', drawer: 'sidebar' },
          description: '首页-播客-侧边栏',
        },

        // Track Menu Sheet（保持 tab，但打开 sheet）
        {
          id: 'home.tab.all.sheet.trackMenu',
          search: { tab: 'all', sheet: 'track_menu' },
          description: '首页-全部-歌曲菜单',
        },
        {
          id: 'home.tab.wrapped.sheet.trackMenu',
          search: { tab: 'wrapped', sheet: 'track_menu' },
          description: '首页-年度总结-歌曲菜单',
        },
        {
          id: 'home.tab.music.sheet.trackMenu',
          search: { tab: 'music', sheet: 'track_menu' },
          description: '首页-音乐-歌曲菜单',
        },
        {
          id: 'home.tab.podcast.sheet.trackMenu',
          search: { tab: 'podcast', sheet: 'track_menu' },
          description: '首页-播客-歌曲菜单',
        },

        // Add to Playlist Sheet
        {
          id: 'home.tab.all.sheet.addPlaylist',
          search: { tab: 'all', sheet: 'add_playlist' },
          description: '首页-全部-加入歌单',
        },
        {
          id: 'home.tab.wrapped.sheet.addPlaylist',
          search: { tab: 'wrapped', sheet: 'add_playlist' },
          description: '首页-年度总结-加入歌单',
        },
        {
          id: 'home.tab.music.sheet.addPlaylist',
          search: { tab: 'music', sheet: 'add_playlist' },
          description: '首页-音乐-加入歌单',
        },
        {
          id: 'home.tab.podcast.sheet.addPlaylist',
          search: { tab: 'podcast', sheet: 'add_playlist' },
          description: '首页-播客-加入歌单',
        },
      ],
      description: '首页',
    },
    {
      path: '/search',
      component: 'SearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [
        {
          id: 'search.base',
          search: {},
          description: '搜索',
        },
      ],
      description: '搜索',
    },
    {
      path: '/search/input',
      component: 'SearchInputPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      queryParams: { q: 'string', trackId: 'string' },
      uiStates: [
        {
          id: 'search.input.base',
          search: {},
          description: '搜索输入',
          actions: [
            {
              id: 'search.track.play',
              label: '搜索：播放歌曲',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { trackId: 'string' },
            },
          ],
        },
        { id: 'search.input.sheet.trackMenu', search: { sheet: 'track_menu' }, description: '搜索输入-歌曲菜单' },
        { id: 'search.input.sheet.addPlaylist', search: { sheet: 'add_playlist' }, description: '搜索输入-加入歌单' },
      ],
      description: '搜索输入',
    },
    {
      path: '/library',
      component: 'LibraryPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [
        { id: 'library.base', search: {}, description: '音乐库' },
        {
          id: 'library.sheet.addArtist',
          search: { sheet: 'add_artist' },
          description: '音乐库-添加艺人',
          actions: [
            {
              id: 'library.addArtist.artist.toggle',
              label: '添加艺人：选择切换',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { artistId: 'string', to: 'boolean' },
            },
            {
              id: 'library.addArtist.submit',
              label: '添加艺人：完成',
              behavior: 'submit',
            },
          ],
        },
      ],
      description: '音乐库',
    },
    {
      path: '/premium',
      component: 'PremiumPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'premium.base', search: {}, description: 'Premium' }],
      description: 'Premium',
    },
    // Create（用于”创建”入口的 overlay 页面；view 为必填离散状态）
    {
      path: '/create',
      component: 'CreatePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: [],
      queryParams: {},
      uiStates: [
        { id: 'create.menu', search: { view: 'menu' }, description: '创建-菜单（TabBar）' },
        { id: 'create.menu.library', search: { view: 'menu', source: 'library' }, description: '创建-菜单（音乐库+）' },
        {
          id: 'create.naming',
          search: { view: 'naming' },
          description: '创建-命名歌单',
          actions: [
            {
              id: 'create.playlist.submit',
              label: '创建歌单：提交',
              behavior: 'submit',
              paramsSchema: { name: 'string' },
            },
          ],
        },
      ],
      description: '创建',
    },

    // =========================
    // Content Pages
    // =========================
    {
      path: '/playlist/:id',
      component: 'PlaylistPage',
      params: { id: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: { trackId: 'string' },
      uiStates: [
        { id: 'playlist.base', search: {}, description: '歌单详情' },
        { id: 'playlist.sheet.trackMenu', search: { sheet: 'track_menu' }, description: '歌单-歌曲菜单' },
        { id: 'playlist.sheet.addPlaylist', search: { sheet: 'add_playlist' }, description: '歌单-添加至其他歌单' },
      ],
      description: '歌单',
    },
    {
      path: '/player',
      component: 'PlayerPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: [],
      queryParams: { trackId: 'string' },
      uiStates: [
        {
          id: 'player.base',
          search: {},
          description: '播放器',
          actions: [
            {
              id: 'track.like.toggle',
              label: '歌曲：点赞切换',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { trackId: 'string', to: 'boolean' },
            },
            {
              id: 'track.play.toggle',
              label: '歌曲：播放/暂停切换',
              behavior: 'toggle',
              scope: 'item',
              paramsSchema: { trackId: 'string', to: 'boolean' },
            },
            {
              id: 'playlist.track.add',
              label: '歌曲：加入歌单',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { playlist: 'string', trackId: 'string' },
            },
            {
              id: 'playlist.track.remove',
              label: '歌曲：从歌单移除',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { trackId: 'string' },
            },
            {
              id: 'track.share.invoke',
              label: '歌曲：分享',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { trackId: 'string' },
            },
            {
              id: 'track.queue.add',
              label: '歌曲：加入播放队列',
              behavior: 'other',
              scope: 'item',
              paramsSchema: { trackId: 'string' },
            },
            {
              id: 'player.control.skipPrevious',
              label: '播放器：上一首',
              behavior: 'other',
            },
            {
              id: 'player.control.skipNext',
              label: '播放器：下一首',
              behavior: 'other',
            },
            {
              id: 'player.shuffle.toggle',
              label: '播放器：随机播放开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'player.repeat.toggle',
              label: '播放器：循环播放开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
          ],
        },
        { id: 'player.sheet.queue', search: { sheet: 'queue' }, description: '播放器-队列面板' },
        {
          id: 'player.sheet.timer',
          search: { sheet: 'timer' },
          description: '播放器-睡眠定时器',
          actions: [
            {
              id: 'player.timer.set',
              label: '定时器：设置时间',
              behavior: 'submit',
              paramsSchema: { minutes: 'number' },
            },
            {
              id: 'player.timer.fade.toggle',
              label: '定时器：淡出开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
          ],
        },
        { id: 'player.sheet.trackMenu', search: { sheet: 'track_menu' }, description: '播放器-歌曲菜单' },
        { id: 'player.sheet.addPlaylist', search: { sheet: 'add_playlist' }, description: '播放器-加入歌单' },
      ],
      description: '播放器',
    },
    {
      path: '/video/:id',
      component: 'ShortVideoPage',
      params: { id: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'video.base', search: {}, description: '短视频' }],
      description: '短视频',
    },
    {
      path: '/category/:id',
      component: 'CategoryPage',
      params: { id: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'category.base', search: {}, description: '分类' }],
      description: '分类',
    },
    {
      path: '/artist/:name',
      component: 'ArtistPage',
      params: { name: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: { trackId: 'string' },
      uiStates: [
        {
          id: 'artist.base',
          search: {},
          description: '艺人',
          actions: [
            {
              id: 'artist.follow.toggle',
              label: '艺人：关注切换',
              behavior: 'toggle',
              paramsSchema: { artist: 'string', to: 'boolean' },
            },
          ],
        },
        { id: 'artist.sheet.trackMenu', search: { sheet: 'track_menu' }, description: '艺人-歌曲菜单' },
        { id: 'artist.sheet.addPlaylist', search: { sheet: 'add_playlist' }, description: '艺人-加入歌单' },
      ],
      description: '艺人',
    },
    {
      path: '/liked-songs',
      component: 'LikedSongsPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: { trackId: 'string' },
      uiStates: [
        { id: 'likedSongs.base', search: {}, description: '已点赞的歌曲' },
        { id: 'likedSongs.sheet.trackMenu', search: { sheet: 'track_menu' }, description: '已点赞的歌曲-歌曲菜单' },
        { id: 'likedSongs.sheet.addPlaylist', search: { sheet: 'add_playlist' }, description: '已点赞的歌曲-加入歌单' },
      ],
      description: '已点赞的歌曲',
    },
    {
      path: '/history',
      component: 'RecentPlayedPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: { trackId: 'string' },
      uiStates: [
        { id: 'history.base', search: {}, description: '最近播放' },
        { id: 'history.sheet.trackMenu', search: { sheet: 'track_menu' }, description: '最近播放-歌曲菜单' },
        { id: 'history.sheet.addPlaylist', search: { sheet: 'add_playlist' }, description: '最近播放-加入歌单' },
      ],
      description: '最近播放',
    },
    {
      path: '/new-releases',
      component: 'WhatsNewPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'whatsNew.base', search: {}, description: '新增内容' }],
      description: '新增内容',
    },

    // =========================
    // Profile & Settings
    // =========================
    {
      path: '/profile',
      component: 'ProfilePage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'profile.base', search: {}, description: '个人资料' }],
      description: '个人资料',
    },
    {
      path: '/settings',
      component: 'SettingsPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'settings.base', search: {}, description: '设置和隐私' }],
      description: '设置和隐私',
    },
    {
      path: '/settings/account',
      component: 'AccountPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'settings.account.base', search: {}, description: '账号' }],
      description: '账号',
    },
    {
      path: '/settings/content',
      component: 'ContentDisplayPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [
        {
          id: 'settings.content.base',
          search: {},
          description: '内容与显示',
          actions: [
            {
              id: 'settings.content.reduceMotion.toggle',
              label: '减少动画数量：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.content.canvas.toggle',
              label: 'Canvas：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.content.explicit.toggle',
              label: '允许播放儿童不宜内容：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.content.unavailable.toggle',
              label: '显示无法播放的歌曲：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.content.createButton.toggle',
              label: '创建按钮显示：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
          ],
        },
      ],
      description: '内容与显示',
    },
    {
      path: '/settings/playback',
      component: 'PlaybackPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [
        {
          id: 'settings.playback.base',
          search: {},
          description: '播放',
          actions: [
            {
              id: 'settings.playback.gapless.toggle',
              label: '无缝播放：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.playback.automix.toggle',
              label: '自动合辑：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.playback.autoplay.toggle',
              label: '自动播放：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.playback.mono.toggle',
              label: '单声道音频：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.playback.broadcast.toggle',
              label: '设备广播状态：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
          ],
        },
      ],
      description: '播放',
    },
    {
      path: '/settings/privacy',
      component: 'PrivacyPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [
        {
          id: 'settings.privacy.base',
          search: {},
          description: '隐私',
          actions: [
            {
              id: 'settings.privacy.privateSession.toggle',
              label: '私人听歌房：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.privacy.listeningActivity.toggle',
              label: '收听动态：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.privacy.recentArtists.toggle',
              label: '最近听过其作品的艺人：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.privacy.publicPlaylists.toggle',
              label: '公开歌单：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.privacy.profilePlaylists.toggle',
              label: '歌单会显示在你的个人资料中：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
          ],
        },
      ],
      description: '隐私',
    },
    {
      path: '/settings/notifications',
      component: 'NotificationsPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'settings.notifications.base', search: {}, description: '通知' }],
      description: '通知',
    },
    {
      path: '/settings/apps',
      component: 'AppsDevicesPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [
        {
          id: 'settings.apps.base',
          search: {},
          description: '应用与设备',
          actions: [
            {
              id: 'settings.apps.voiceAssistant.toggle',
              label: '语音助手建议：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.apps.connectControl.toggle',
              label: 'Spotify 畅联功能控制：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.apps.localVisibility.toggle',
              label: '本地设备可见性：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.apps.localFiles.toggle',
              label: '本地音频文件：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
          ],
        },
      ],
      description: '应用与设备',
    },
    {
      path: '/settings/data-saver',
      component: 'DataSaverPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [
        {
          id: 'settings.dataSaver.base',
          search: {},
          description: '数据节省',
          actions: [
            {
              id: 'settings.dataSaver.mode.select.on',
              label: '节省流量模式：始终开启',
              behavior: 'select',
            },
            {
              id: 'settings.dataSaver.mode.select.auto',
              label: '节省流量模式：自动',
              behavior: 'select',
            },
            {
              id: 'settings.dataSaver.mode.select.off',
              label: '节省流量模式：始终关闭',
              behavior: 'select',
            },
            {
              id: 'settings.dataSaver.downloadCellular.toggle',
              label: '通过移动流量下载：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.dataSaver.downloadAudioOnly.toggle',
              label: '仅下载视频播客的音频：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
            {
              id: 'settings.dataSaver.streamAudioOnly.toggle',
              label: '仅串流播放视频播客的音频：开关',
              behavior: 'toggle',
              paramsSchema: { to: 'boolean' },
            },
          ],
        },
      ],
      description: '数据节省',
    },
    {
      path: '/settings/quality',
      component: 'MediaQualityPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [
        {
          id: 'settings.quality.base',
          search: {},
          description: '媒体质量',
          actions: [
            { id: 'settings.quality.wifi.select.auto', label: 'Wi‑Fi 串流品质：自动', behavior: 'select' },
            { id: 'settings.quality.wifi.select.low', label: 'Wi‑Fi 串流品质：低', behavior: 'select' },
            { id: 'settings.quality.wifi.select.normal', label: 'Wi‑Fi 串流品质：标准', behavior: 'select' },
            { id: 'settings.quality.wifi.select.high', label: 'Wi‑Fi 串流品质：高', behavior: 'select' },
            { id: 'settings.quality.wifi.select.veryHigh', label: 'Wi‑Fi 串流品质：超高', behavior: 'select' },
            { id: 'settings.quality.wifi.select.lossless', label: 'Wi‑Fi 串流品质：无损', behavior: 'select' },
            { id: 'settings.quality.cellular.select.auto', label: '移动流量串流品质：自动', behavior: 'select' },
            { id: 'settings.quality.cellular.select.low', label: '移动流量串流品质：低', behavior: 'select' },
            { id: 'settings.quality.cellular.select.normal', label: '移动流量串流品质：标准', behavior: 'select' },
            { id: 'settings.quality.cellular.select.high', label: '移动流量串流品质：高', behavior: 'select' },
            { id: 'settings.quality.cellular.select.veryHigh', label: '移动流量串流品质：超高', behavior: 'select' },
            { id: 'settings.quality.download.select.low', label: '下载品质：低', behavior: 'select' },
            { id: 'settings.quality.download.select.normal', label: '下载品质：标准', behavior: 'select' },
            { id: 'settings.quality.download.select.high', label: '下载品质：高', behavior: 'select' },
            { id: 'settings.quality.download.select.veryHigh', label: '下载品质：超高', behavior: 'select' },
          ],
        },
      ],
      description: '媒体质量',
    },
    {
      path: '/settings/about',
      component: 'AboutPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'settings.about.base', search: {}, description: '关于' }],
      description: '关于',
    },

    // =========================
    // Premium Payment
    // =========================
    {
      path: '/premium/payment',
      component: 'PaymentPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: { planId: 'string' },
      uiStates: [
        {
          id: 'premium.payment.base',
          search: {},
          description: 'Premium 支付',
          actions: [
            {
              id: 'payment.method.select.spotify',
              label: '支付方式：选择 Spotify',
              behavior: 'select',
            },
            {
              id: 'payment.method.select.google',
              label: '支付方式：选择 Google Play',
              behavior: 'select',
            },
          ],
        },
      ],
      description: 'Premium 支付',
    },

    // =========================
    // Auth / Signup
    // =========================
    {
      path: '/login-landing',
      component: 'LoginLandingPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'auth.loginLanding.base', search: {}, description: '登录入口' }],
      description: '登录入口',
    },
    {
      path: '/signup',
      component: 'SignupPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'auth.signup.base', search: {}, description: '注册入口' }],
      description: '注册入口',
    },
    {
      path: '/signup/email',
      component: 'CreateAccountPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'auth.signup.email.base', search: {}, description: '注册-输入邮箱' }],
      description: '注册-输入邮箱',
    },
    {
      path: '/signup/password',
      component: 'CreatePasswordPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'auth.signup.password.base', search: {}, description: '注册-创建密码' }],
      description: '注册-创建密码',
    },
    {
      path: '/signup/date',
      component: 'CreateDatePage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'auth.signup.date.base', search: {}, description: '注册-出生日期' }],
      description: '注册-出生日期',
    },
    {
      path: '/signup/gender',
      component: 'CreateGenderPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'auth.signup.gender.base', search: {}, description: '注册-性别' }],
      description: '注册-性别',
    },
    {
      path: '/signup/finish',
      component: 'CreateNamePage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'auth.signup.name.base', search: {}, description: '注册-创建昵称' }],
      description: '注册-创建昵称',
    },
    {
      path: '/signup/artists',
      component: 'ChooseArtistsPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: {},
      uiStates: [{ id: 'auth.signup.artists.base', search: {}, description: '注册-选择艺人' }],
      description: '注册-选择艺人',
    },
    {
      path: '/signup/complete',
      component: 'SignupCompletePage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      queryParams: { selectedArtists: 'string' },
      uiStates: [{ id: 'auth.signup.complete.base', search: {}, description: '注册完成' }],
      description: '注册完成',
    },
  ],

  transitions: [
    // =========================
    // Bottom TabBar
    // =========================
    {
      id: 'tab.home',
      from: [
        '/search/input',
        '/search',
        '/library',
        '/premium',
        { path: '/create', search: { view: '*' } },
        '/playlist/:id',
        '/video/:id',
        '/category/:id',
        '/artist/:name',
        '/liked-songs',
        '/premium/payment',
        '/profile',
        '/settings',
        '/settings/account',
        '/settings/content',
        '/settings/playback',
        '/settings/privacy',
        '/settings/notifications',
        '/settings/apps',
        '/settings/data-saver',
        '/settings/quality',
        '/settings/about',
        '/history',
        '/new-releases',
      ],
      to: '/',
      search: { tab: 'all' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到主页',
      ui: { placement: 'tabbar', icon: 'tab_home', gesture: 'tap' },
    },
    {
      id: 'tab.search',
      from: [
        { path: '/', search: { tab: '*', drawer: null, sheet: null } },
        '/search/input',
        '/library',
        '/premium',
        { path: '/create', search: { view: '*' } },
        '/playlist/:id',
        '/video/:id',
        '/category/:id',
        '/artist/:name',
        '/liked-songs',
        '/premium/payment',
        '/profile',
        '/settings',
        '/settings/account',
        '/settings/content',
        '/settings/playback',
        '/settings/privacy',
        '/settings/notifications',
        '/settings/apps',
        '/settings/data-saver',
        '/settings/quality',
        '/settings/about',
        '/history',
        '/new-releases',
      ],
      to: '/search',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到搜索',
      ui: { placement: 'tabbar', icon: 'tab_search', gesture: 'tap' },
    },
    {
      id: 'tab.library',
      from: [
        { path: '/', search: { tab: '*', drawer: null, sheet: null } },
        '/search/input',
        '/search',
        '/premium',
        { path: '/create', search: { view: '*' } },
        '/playlist/:id',
        '/video/:id',
        '/category/:id',
        '/artist/:name',
        '/liked-songs',
        '/premium/payment',
        '/profile',
        '/settings',
        '/settings/account',
        '/settings/content',
        '/settings/playback',
        '/settings/privacy',
        '/settings/notifications',
        '/settings/apps',
        '/settings/data-saver',
        '/settings/quality',
        '/settings/about',
        '/history',
        '/new-releases',
      ],
      to: '/library',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到音乐库',
      ui: { placement: 'tabbar', icon: 'tab_library', gesture: 'tap' },
    },
    {
      id: 'tab.premium',
      from: [
        { path: '/', search: { tab: '*', drawer: null, sheet: null } },
        '/search/input',
        '/search',
        '/library',
        '/player',
        { path: '/create', search: { view: '*' } },
        '/playlist/:id',
        '/video/:id',
        '/category/:id',
        '/artist/:name',
        '/liked-songs',
        '/premium/payment',
        '/profile',
        '/settings',
        '/settings/account',
        '/settings/content',
        '/settings/playback',
        '/settings/privacy',
        '/settings/notifications',
        '/settings/apps',
        '/settings/data-saver',
        '/settings/quality',
        '/settings/about',
        '/history',
        '/new-releases',
      ],
      to: '/premium',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到 Premium',
      ui: { placement: 'tabbar', icon: 'tab_premium', gesture: 'tap' },
    },

    // Create Overlay
    {
      id: 'create.open',
      from: [
        { path: '/', search: { tab: '*', drawer: null, sheet: null } },
        '/search/input',
        '/search',
        '/library',
        '/premium',
        '/playlist/:id',
        '/video/:id',
        '/category/:id',
        '/artist/:name',
        '/liked-songs',
        '/premium/payment',
        '/profile',
        '/settings',
        '/settings/account',
        '/settings/content',
        '/settings/playback',
        '/settings/privacy',
        '/settings/notifications',
        '/settings/apps',
        '/settings/data-saver',
        '/settings/quality',
        '/settings/about',
        '/history',
        '/new-releases',
      ],
      to: '/create',
      search: { view: 'menu' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开创建',
      ui: { placement: 'tabbar', icon: 'create_open', gesture: 'tap' },
    },
    {
      id: 'library.create.open',
      from: '/library',
      to: '/create',
      search: { view: 'menu', source: 'library' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开创建（音乐库）',
      ui: { placement: 'topbar', icon: 'create_open', gesture: 'tap' },
    },
    {
      id: 'create.naming.open',
      from: [{ path: '/create', search: { view: 'menu' } }, { path: '/create', search: { view: 'menu', source: 'library' } }],
      to: '/create',
      search: { view: 'naming' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '创建歌单：进入命名',
      ui: { placement: 'content', icon: 'create_naming', gesture: 'tap' },
    },
    {
      id: 'create.naming.directOpen',
      from: [{ path: '/', search: { tab: '*' } }, '/search/input', '/player', '/artist/:name', '/liked-songs', '/history', '/playlist/:id'],
      to: '/create',
      search: { view: 'naming' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '创建歌单：从加入歌单流程直接进入命名',
      ui: { placement: 'content', icon: 'create_naming_direct', gesture: 'tap' },
    },

    // =========================
    // Home: Top Tabs / Drawer / Sheets
    // =========================
    {
      id: 'home.tab.all',
      from: [{ path: '/', search: { tab: '*', drawer: null, sheet: null } }],
      to: '/',
      search: { tab: 'all' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换首页 Tab：全部',
      ui: { placement: 'topbar', icon: 'home_tab_all', gesture: 'tap' },
    },
    {
      id: 'home.tab.wrapped',
      from: [{ path: '/', search: { tab: '*', drawer: null, sheet: null } }],
      to: '/',
      search: { tab: 'wrapped' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换首页 Tab：年度总结',
      ui: { placement: 'topbar', icon: 'home_tab_wrapped', gesture: 'tap' },
    },
    {
      id: 'home.tab.music',
      from: [{ path: '/', search: { tab: '*', drawer: null, sheet: null } }],
      to: '/',
      search: { tab: 'music' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换首页 Tab：音乐',
      ui: { placement: 'topbar', icon: 'home_tab_music', gesture: 'tap' },
    },
    {
      id: 'home.tab.podcast',
      from: [{ path: '/', search: { tab: '*', drawer: null, sheet: null } }],
      to: '/',
      search: { tab: 'podcast' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换首页 Tab：播客',
      ui: { placement: 'topbar', icon: 'home_tab_podcast', gesture: 'tap' },
    },
    {
      id: 'home.sidebar.open',
      from: [{ path: '/', search: { tab: '*', drawer: null, sheet: null } }],
      to: '/',
      search: { drawer: 'sidebar' },
      searchParams: {},
      preserveParams: ['tab'],
      mode: 'push',
      params: {},
      label: '打开侧边栏',
      ui: { placement: 'topbar', icon: 'sidebar_open', gesture: 'tap' },
    },
    {
      id: 'search.sidebar.open',
      from: [{ path: '/search', search: { drawer: null, sheet: null } }],
      to: '/search',
      search: { drawer: 'sidebar' },
      searchParams: {},
      preserveParams: [],
      mode: 'push',
      params: {},
      label: '搜索页打开侧边栏',
      ui: { placement: 'topbar', icon: 'sidebar_open', gesture: 'tap' },
    },
    {
      id: 'search.input.open',
      from: ['/search'],
      to: '/search/input',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开搜索输入页',
      ui: { placement: 'content', icon: 'search_input_open', gesture: 'tap' },
    },
    {
      id: 'search.input.trackMenu.open',
      from: [{ path: '/search/input', search: { sheet: null } }],
      to: '/search/input',
      search: { sheet: 'track_menu' },
      searchParams: { trackId: 'string' },
      preserveParams: ['q'],
      mode: 'push',
      params: {},
      label: '搜索输入：打开歌曲菜单',
      ui: { placement: 'content', icon: 'search_input_track_menu_open', gesture: 'tap' },
    },
    {
      id: 'search.input.addPlaylist.open',
      from: [{ path: '/search/input', search: { sheet: 'track_menu' } }],
      to: '/search/input',
      search: { sheet: 'add_playlist' },
      searchParams: { trackId: 'string' },
      preserveParams: ['q'],
      mode: 'replace',
      params: {},
      label: '搜索输入：从歌曲菜单进入加入歌单',
      ui: { placement: 'content', icon: 'search_input_add_playlist_open', gesture: 'tap' },
    },
    {
      id: 'search.input.addPlaylist.directOpen',
      from: [{ path: '/search/input', search: { sheet: null } }],
      to: '/search/input',
      search: { sheet: 'add_playlist' },
      searchParams: { trackId: 'string' },
      preserveParams: ['q'],
      mode: 'push',
      params: {},
      label: '搜索输入：直接打开加入歌单',
      ui: { placement: 'content', icon: 'search_input_add_playlist_direct_open', gesture: 'tap' },
    },
    {
      id: 'library.sidebar.open',
      from: [{ path: '/library', search: { drawer: null, sheet: null } }],
      to: '/library',
      search: { drawer: 'sidebar' },
      searchParams: {},
      preserveParams: [],
      mode: 'push',
      params: {},
      label: '音乐库打开侧边栏',
      ui: { placement: 'topbar', icon: 'sidebar_open', gesture: 'tap' },
    },
    {
      id: 'home.trackMenu.open',
      from: [{ path: '/', search: { tab: '*', drawer: null, sheet: null } }],
      to: '/',
      search: { sheet: 'track_menu' },
      searchParams: { trackId: 'string' },
      preserveParams: ['tab'],
      mode: 'push',
      params: {},
      label: '打开歌曲菜单',
      ui: { placement: 'content', icon: 'track_menu_open', gesture: 'tap' },
    },
    {
      id: 'home.addPlaylist.open',
      from: [{ path: '/', search: { tab: '*', sheet: 'track_menu' } }],
      to: '/',
      search: { sheet: 'add_playlist' },
      searchParams: { trackId: 'string' },
      preserveParams: ['tab'],
      mode: 'replace',
      params: {},
      label: '首页：加入歌单选择',
      ui: { placement: 'content', icon: 'home_add_playlist_open', gesture: 'tap' },
    },

    // Artist page track menu
    {
      id: 'artist.trackMenu.open',
      from: [{ path: '/artist/:name', search: { sheet: null } }],
      to: '/artist/:name',
      search: { sheet: 'track_menu' },
      searchParams: { trackId: 'string' },
      mode: 'push',
      params: { name: 'string' },
      label: '艺人：打开歌曲菜单',
      ui: { placement: 'content', icon: 'artist_track_menu_open', gesture: 'tap' },
    },
    {
      id: 'artist.addPlaylist.open',
      from: [{ path: '/artist/:name', search: { sheet: 'track_menu' } }],
      to: '/artist/:name',
      search: { sheet: 'add_playlist' },
      searchParams: { trackId: 'string' },
      mode: 'replace',
      params: { name: 'string' },
      label: '艺人：加入歌单选择',
      ui: { placement: 'content', icon: 'artist_add_playlist_open', gesture: 'tap' },
    },

    // History (RecentPlayedPage) track menu
    {
      id: 'history.trackMenu.open',
      from: [{ path: '/history', search: { sheet: null } }],
      to: '/history',
      search: { sheet: 'track_menu' },
      searchParams: { trackId: 'string' },
      mode: 'push',
      params: {},
      label: '最近播放：打开歌曲菜单',
      ui: { placement: 'content', icon: 'history_track_menu_open', gesture: 'tap' },
    },
    {
      id: 'history.addPlaylist.open',
      from: [{ path: '/history', search: { sheet: 'track_menu' } }],
      to: '/history',
      search: { sheet: 'add_playlist' },
      searchParams: { trackId: 'string' },
      mode: 'replace',
      params: {},
      label: '最近播放：加入歌单选择',
      ui: { placement: 'content', icon: 'history_add_playlist_open', gesture: 'tap' },
    },

    // LikedSongs track menu
    {
      id: 'likedSongs.trackMenu.open',
      from: [{ path: '/liked-songs', search: { sheet: null } }],
      to: '/liked-songs',
      search: { sheet: 'track_menu' },
      searchParams: { trackId: 'string' },
      mode: 'push',
      params: {},
      label: '已点赞的歌曲：打开歌曲菜单',
      ui: { placement: 'content', icon: 'liked_track_menu_open', gesture: 'tap' },
    },
    {
      id: 'likedSongs.addPlaylist.open',
      from: [{ path: '/liked-songs', search: { sheet: 'track_menu' } }],
      to: '/liked-songs',
      search: { sheet: 'add_playlist' },
      searchParams: { trackId: 'string' },
      mode: 'replace',
      params: {},
      label: '已点赞的歌曲：加入歌单选择',
      ui: { placement: 'content', icon: 'liked_add_playlist_open', gesture: 'tap' },
    },

    // Sidebar entries（从侧边栏打开页面）
    {
      id: 'profile.open',
      from: [{ path: '/', search: { tab: '*', drawer: 'sidebar' } }, { path: '/search', search: { drawer: 'sidebar' } }, { path: '/library', search: { drawer: 'sidebar' } }],
      to: '/profile',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '打开个人资料',
      ui: { placement: 'content', icon: 'profile_open', gesture: 'tap' },
    },
    {
      id: 'settings.open',
      from: [{ path: '/', search: { tab: '*', drawer: 'sidebar' } }, { path: '/search', search: { drawer: 'sidebar' } }, { path: '/library', search: { drawer: 'sidebar' } }, '/profile'],
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '打开设置和隐私',
      ui: { placement: 'content', icon: 'settings_open', gesture: 'tap' },
    },
    {
      id: 'history.open',
      from: [{ path: '/', search: { tab: '*', drawer: 'sidebar' } }, { path: '/search', search: { drawer: 'sidebar' } }, { path: '/library', search: { drawer: 'sidebar' } }],
      to: '/history',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '打开最近播放',
      ui: { placement: 'content', icon: 'history_open', gesture: 'tap' },
    },
    {
      id: 'whatsNew.open',
      from: [{ path: '/', search: { tab: '*', drawer: 'sidebar' } }, { path: '/search', search: { drawer: 'sidebar' } }, { path: '/library', search: { drawer: 'sidebar' } }],
      to: '/new-releases',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '打开新增内容',
      ui: { placement: 'content', icon: 'whats_new_open', gesture: 'tap' },
    },
    {
      id: 'auth.loginLanding.open',
      from: [{ path: '/', search: { tab: '*', drawer: 'sidebar' } }, { path: '/search', search: { drawer: 'sidebar' } }, { path: '/library', search: { drawer: 'sidebar' } }],
      to: '/login-landing',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '打开登录入口',
      ui: { placement: 'content', icon: 'login_open', gesture: 'tap' },
    },

    // =========================
    // Navigation: open detail pages
    // =========================
    {
      id: 'playlist.open',
      from: [{ path: '/', search: { tab: '*' } }, '/search', '/search/input', '/library', '/profile', '/history', '/liked-songs', '/playlist/:id', '/artist/:name', '/player', { path: '/create', search: { view: '*' } }],
      to: '/playlist/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开歌单',
      ui: { placement: 'content', icon: 'playlist_open', gesture: 'tap' },
    },
    {
      id: 'likedSongs.open',
      from: ['/library'],
      to: '/liked-songs',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开已点赞的歌曲',
      ui: { placement: 'content', icon: 'liked_songs_open', gesture: 'tap' },
    },
    {
      id: 'artist.open',
      from: ['/library', '/playlist/:id', '/search', '/search/input', '/liked-songs', '/history', '/artist/:name', '/player', { path: '/', search: { tab: '*' } }],
      to: '/artist/:name',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { name: 'string' },
      label: '打开艺人',
      ui: { placement: 'content', icon: 'artist_open', gesture: 'tap' },
    },
    {
      id: 'library.addArtist.open',
      from: { path: '/library', search: { sheet: null } },
      to: '/library',
      search: { sheet: 'add_artist' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '音乐库：打开添加艺人',
      ui: { placement: 'content', icon: 'library_add_artist', gesture: 'tap' },
    },
    {
      id: 'video.open',
      from: ['/search', '/search/input'],
      to: '/video/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开视频',
      ui: { placement: 'content', icon: 'video_open', gesture: 'tap' },
    },
    {
      id: 'category.open',
      from: ['/search', '/search/input'],
      to: '/category/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开分类',
      ui: { placement: 'content', icon: 'category_open', gesture: 'tap' },
    },

    // Playlist: track menu sheet
    {
      id: 'playlist.trackMenu.open',
      from: { path: '/playlist/:id', search: { sheet: null } },
      to: '/playlist/:id',
      search: { sheet: 'track_menu' },
      searchParams: { trackId: 'string' },
      mode: 'push',
      params: { id: 'string' },
      label: '歌单：打开歌曲菜单',
      ui: { placement: 'content', icon: 'playlist_track_menu', gesture: 'tap' },
    },
    {
      id: 'playlist.addPlaylist.open',
      from: { path: '/playlist/:id', search: { sheet: 'track_menu' } },
      to: '/playlist/:id',
      search: { sheet: 'add_playlist' },
      searchParams: { trackId: 'string' },
      mode: 'replace',
      params: { id: 'string' },
      label: '歌单：添加至其他歌单',
      ui: { placement: 'content', icon: 'playlist_add_playlist', gesture: 'tap' },
    },

    // Player
    {
      id: 'player.open',
      from: [
        { path: '/', search: { tab: '*' } },
        '/search',
        '/search/input',
        '/library',
        '/premium',
        { path: '/create', search: { view: '*' } },
        '/playlist/:id',
        '/video/:id',
        '/category/:id',
        '/artist/:name',
        '/liked-songs',
        '/premium/payment',
        '/profile',
        '/settings',
        '/settings/account',
        '/settings/content',
        '/settings/playback',
        '/settings/privacy',
        '/settings/notifications',
        '/settings/apps',
        '/settings/data-saver',
        '/settings/quality',
        '/settings/about',
        '/history',
        '/new-releases',
      ],
      to: '/player',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开播放器',
      ui: { placement: 'fab', icon: 'player_open', gesture: 'tap' },
    },
    {
      id: 'player.queue.open',
      from: { path: '/player', search: { sheet: null } },
      to: '/player',
      search: { sheet: 'queue' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开队列面板',
      ui: { placement: 'content', icon: 'player_queue_open', gesture: 'tap' },
    },
    {
      id: 'player.timer.open',
      from: { path: '/player', search: { sheet: 'queue' } },
      to: '/player',
      search: { sheet: 'timer' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开睡眠定时器（从队列）',
      ui: { placement: 'content', icon: 'player_timer_open', gesture: 'tap' },
    },
    {
      id: 'player.timer.openFromMenu',
      from: { path: '/player', search: { sheet: 'track_menu', trackId: '*' } },
      to: '/player',
      search: { sheet: 'timer' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '打开睡眠定时器（从曲目菜单）',
      ui: { placement: 'content', icon: 'player_timer_open', gesture: 'tap' },
    },
    {
      id: 'player.trackMenu.open',
      from: { path: '/player', search: { sheet: null } },
      to: '/player',
      search: { sheet: 'track_menu' },
      searchParams: { trackId: 'string' },
      mode: 'push',
      params: {},
      label: '播放器：打开歌曲菜单',
      ui: { placement: 'content', icon: 'player_track_menu_open', gesture: 'tap' },
    },
    {
      id: 'player.addPlaylist.open',
      from: { path: '/player', search: { sheet: 'track_menu' } },
      to: '/player',
      search: { sheet: 'add_playlist' },
      searchParams: { trackId: 'string' },
      mode: 'replace',
      params: {},
      label: '播放器：加入歌单选择',
      ui: { placement: 'content', icon: 'player_add_playlist_open', gesture: 'tap' },
    },

    // Settings subpages
    {
      id: 'settings.account.open',
      from: ['/settings'],
      to: '/settings/account',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开账号设置',
      ui: { placement: 'content', icon: 'settings_account_open', gesture: 'tap' },
    },
    {
      id: 'settings.content.open',
      from: ['/settings'],
      to: '/settings/content',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开内容与显示',
      ui: { placement: 'content', icon: 'settings_content_open', gesture: 'tap' },
    },
    {
      id: 'settings.playback.open',
      from: ['/settings'],
      to: '/settings/playback',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开播放设置',
      ui: { placement: 'content', icon: 'settings_playback_open', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.open',
      from: ['/settings'],
      to: '/settings/privacy',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开隐私设置',
      ui: { placement: 'content', icon: 'settings_privacy_open', gesture: 'tap' },
    },
    {
      id: 'settings.notifications.open',
      from: ['/settings'],
      to: '/settings/notifications',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开通知设置',
      ui: { placement: 'content', icon: 'settings_notifications_open', gesture: 'tap' },
    },
    {
      id: 'settings.apps.open',
      from: ['/settings'],
      to: '/settings/apps',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开应用与设备',
      ui: { placement: 'content', icon: 'settings_apps_open', gesture: 'tap' },
    },
    {
      id: 'settings.dataSaver.open',
      from: ['/settings'],
      to: '/settings/data-saver',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开数据节省',
      ui: { placement: 'content', icon: 'settings_data_saver_open', gesture: 'tap' },
    },
    {
      id: 'settings.quality.open',
      from: ['/settings'],
      to: '/settings/quality',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开媒体质量',
      ui: { placement: 'content', icon: 'settings_quality_open', gesture: 'tap' },
    },
    {
      id: 'settings.about.open',
      from: ['/settings'],
      to: '/settings/about',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开关于',
      ui: { placement: 'content', icon: 'settings_about_open', gesture: 'tap' },
    },

    // Premium Payment
    {
      id: 'premium.payment.open',
      from: ['/premium'],
      to: '/premium/payment',
      search: {},
      searchParams: { planId: 'string' },
      mode: 'push',
      params: {},
      label: '打开 Premium 支付',
      ui: { placement: 'content', icon: 'premium_payment_open', gesture: 'tap' },
    },

    // =========================
    // Auth / Signup Flow
    // =========================
    {
      id: 'auth.signup.open',
      from: ['/login-landing'],
      to: '/signup',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开注册入口',
      ui: { placement: 'content', icon: 'signup_open', gesture: 'tap' },
    },
    {
      id: 'auth.signup.email.open',
      from: ['/signup'],
      to: '/signup/email',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '注册：输入邮箱',
      ui: { placement: 'content', icon: 'signup_email_open', gesture: 'tap' },
    },
    {
      id: 'auth.signup.password.open',
      from: ['/signup/email'],
      to: '/signup/password',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '注册：创建密码',
      ui: { placement: 'content', icon: 'signup_password_open', gesture: 'tap' },
    },
    {
      id: 'auth.signup.date.open',
      from: ['/signup/password'],
      to: '/signup/date',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '注册：填写出生日期',
      ui: { placement: 'content', icon: 'signup_date_open', gesture: 'tap' },
    },
    {
      id: 'auth.signup.gender.open',
      from: ['/signup/date'],
      to: '/signup/gender',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '注册：选择性别',
      ui: { placement: 'content', icon: 'signup_gender_open', gesture: 'tap' },
    },
    {
      id: 'auth.signup.name.open',
      from: ['/signup/gender'],
      to: '/signup/finish',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '注册：创建昵称',
      ui: { placement: 'content', icon: 'signup_name_open', gesture: 'tap' },
    },
    {
      id: 'auth.signup.artists.open',
      from: ['/signup/finish'],
      to: '/signup/artists',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '注册：选择艺人',
      ui: { placement: 'content', icon: 'signup_artists_open', gesture: 'tap' },
    },
    {
      id: 'auth.signup.complete.open',
      from: ['/signup/artists'],
      to: '/signup/complete',
      search: {},
      searchParams: { selectedArtists: 'string' },
      mode: 'push',
      params: {},
      label: '注册：完成',
      ui: { placement: 'content', icon: 'signup_complete_open', gesture: 'tap' },
    },
    {
      id: 'signup.complete.startListening',
      from: ['/signup/complete'],
      to: '/',
      search: { tab: 'all' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '注册完成：开始聆听',
      ui: { placement: 'content', icon: 'start_listening', gesture: 'tap' },
    },
    {
      id: 'signup.complete.later',
      from: ['/signup/complete'],
      to: '/',
      search: { tab: 'all' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '注册完成：以后再说',
      ui: { placement: 'content', icon: 'start_later', gesture: 'tap' },
    },
  ],

  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
