import type { NavigationDeclaration, ScrollContainerDeclaration } from './navigation.types';

const MAIN_SCROLL: ScrollContainerDeclaration[] = [
  { name: 'main', direction: 'vertical', description: '主内容区（Layout 容器）' },
];

const NO_SCROLL: ScrollContainerDeclaration[] = [];

export const NAVIGATION_DECLARATION = {
  app: 'alipay',

  routes: [
    // =========================
    // Main Tabs
    // =========================
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'home.base', search: {}, description: '首页' }],
      queryParams: {},
      description: '首页',
    },
    {
      path: '/finance',
      component: 'FinancePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'finance.base', search: {}, description: '理财' }],
      queryParams: {},
      description: '理财',
    },
    {
      path: '/video',
      component: 'VideoPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'video.base', search: {}, description: '视频' }],
      queryParams: {},
      description: '视频',
    },
    {
      path: '/messages',
      component: 'MessagesPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'messages.base', search: {}, description: '消息' }],
      queryParams: {},
      description: '消息',
    },
    {
      path: '/my',
      component: 'MyPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'my.base', search: {}, description: '我的' }],
      queryParams: {},
      description: '我的',
    },
    {
      path: '/bank-cards',
      component: 'BankCardsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: NO_SCROLL,
      uiStates: [{ id: 'bank_cards.base', search: {}, description: '银行卡' }],
      queryParams: { toast: 'string' },
      description: '银行卡',
    },
    {
      path: '/bank-cards/add',
      component: 'AddBankCardPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: NO_SCROLL,
      uiStates: [{ id: 'bank_cards.add.base', search: {}, description: '添加银行卡' }],
      queryParams: { returnTo: 'string' },
      description: '添加银行卡',
    },
    {
      path: '/bank-cards/add/verify',
      component: 'AddBankCardVerifyPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: NO_SCROLL,
      uiStates: [{ id: 'bank_cards.verify.base', search: {}, description: '添加银行卡短信验证' }],
      queryParams: { bankName: 'string', cardNumber: 'string', returnTo: 'string' },
      description: '添加银行卡短信验证',
    },
    {
      path: '/settings/payment/bank-cards',
      component: 'BankCardsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: NO_SCROLL,
      uiStates: [{ id: 'settings.payment.bank_cards.base', search: {}, description: '支付设置-银行卡' }],
      queryParams: {},
      description: '支付设置-银行卡',
    },

    // =========================
    // Chat
    // =========================
    {
      path: '/chat',
      component: 'ChatPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'chat.base', search: {}, description: '聊天页面' }],
      queryParams: { id: 'string', type: 'string' },
      description: '聊天页面',
    },

    // =========================
    // Contacts
    // =========================
    {
      path: '/contacts',
      component: 'ContactsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'contacts.base', search: {}, description: '通讯录' }],
      queryParams: {},
      description: '通讯录',
    },
    {
      path: '/contacts/profile',
      component: 'ContactProfilePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'contacts.profile.base', search: {}, description: '联系人资料' }],
      queryParams: { contactId: 'string' },
      description: '联系人资料',
    },

    // =========================
    // Settings
    // =========================
    {
      path: '/settings',
      component: 'SettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.base',
          search: {},
          description: '设置',
          actions: [
            {
              id: 'settings.visualRefresh.toggle',
              label: '视觉风格焕新：开关',
              behavior: 'toggle',
            },
          ],
        },
      ],
      queryParams: {},
      description: '设置',
    },
    {
      path: '/settings/payment',
      component: 'PaymentSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.payment.base', search: {}, description: '支付设置' }],
      queryParams: {},
      description: '支付设置',
    },
    {
      path: '/settings/payment/order',
      component: 'PayOrderSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.payment.order.base',
          search: {},
          description: '支付顺序',
          actions: [
            { id: 'payOrder.mode.select.system', label: '支付顺序：系统自动匹配', behavior: 'select' },
            { id: 'payOrder.mode.select.custom', label: '支付顺序：自定义顺序', behavior: 'select' },
          ],
        },
      ],
      queryParams: {},
      description: '支付顺序',
    },
    {
      path: '/settings/payment/fast-pay',
      component: 'FastPaySettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.payment.fastPay.base',
          search: {},
          description: '极速付款',
          actions: [
            { id: 'fastPay.enabled.toggle', label: '极速付款：开关', behavior: 'toggle' },
            { id: 'fastPay.easterEgg.toggle', label: '付款彩蛋：开关', behavior: 'toggle' },
          ],
        },
        { id: 'settings.payment.fastPay.modal.agreement', search: { modal: 'agreement' }, description: '开通小额免密-协议弹窗' },
        {
          id: 'settings.payment.fastPay.modal.password',
          search: { modal: 'password' },
          description: '开通小额免密-支付密码弹窗',
          actions: [
            {
              id: 'fastPayPassword.keypad.press',
              label: '输入支付密码数字键（开通小额免密）',
              behavior: 'other',
              paramsSchema: { digit: 'string' },
            },
            { id: 'fastPayPassword.keypad.delete', label: '删除支付密码一位（开通小额免密）', behavior: 'other' },
          ],
        },
        {
          id: 'settings.payment.fastPay.modal.noPwdDisableConfirm',
          search: { modal: 'noPwdDisableConfirm' },
          description: '关闭小额免密确认弹窗',
          actions: [{ id: 'fastPay.noPwd.disable.submit', label: '确认关闭小额免密', behavior: 'submit' }],
        },
        {
          id: 'settings.payment.fastPay.modal.disableFastPayConfirm',
          search: { modal: 'disableFastPayConfirm' },
          description: '关闭极速付款确认弹窗',
          actions: [{ id: 'fastPay.disable.submit', label: '确认关闭极速付款', behavior: 'submit' }],
        },
      ],
      queryParams: {},
      description: '极速付款',
    },
    {
      path: '/settings/notifications',
      component: 'NotificationSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.notifications.base',
          search: {},
          description: '新消息通知',
          actions: [
            { id: 'notification.tradeSecurity.toggle', label: '交易与账号安全通知：开关', behavior: 'toggle' },
            { id: 'notification.service.toggle', label: '服务通知：开关', behavior: 'toggle' },
            { id: 'notification.activity.toggle', label: '活动通知：开关', behavior: 'toggle' },
            { id: 'notification.avCall.toggle', label: '语音和视频通话通知：开关', behavior: 'toggle' },
            { id: 'notification.avCallPopup.toggle', label: '语音和视频通话弹窗快捷接听：开关', behavior: 'toggle' },
            { id: 'notification.friendReminder.toggle', label: '朋友消息提醒：开关', behavior: 'toggle' },
            { id: 'notification.friendDetail.toggle', label: '显示朋友消息详情：开关', behavior: 'toggle' },
            { id: 'notification.sound.toggle', label: '声音：开关', behavior: 'toggle' },
            { id: 'notification.vibration.toggle', label: '振动：开关', behavior: 'toggle' },
            { id: 'notification.avCallRing.toggle', label: '语音和视频通话来电铃声：开关', behavior: 'toggle' },
          ],
        },
      ],
      queryParams: {},
      description: '新消息通知',
    },
    {
      path: '/settings/general',
      component: 'GeneralSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.base',
          search: {},
          description: '通用',
          actions: [
            { id: 'general.refreshSound.toggle', label: '刷新音效：开关', behavior: 'toggle' },
          ],
        },
      ],
      queryParams: {},
      description: '通用',
    },
    {
      path: '/settings/general/language',
      component: 'LanguageSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.language.base',
          search: {},
          description: '多语言',
          actions: [
            { id: 'language.select.zhCN', label: '选择语言：简体中文', behavior: 'select' },
            { id: 'language.select.zhTW', label: '选择语言：繁体中文(台湾)', behavior: 'select' },
            { id: 'language.select.zhHK', label: '选择语言：繁体中文(香港)', behavior: 'select' },
            { id: 'language.select.en', label: '选择语言：English', behavior: 'select' },
            { id: 'language.save.submit', label: '保存语言设置', behavior: 'submit' },
          ],
        },
      ],
      queryParams: {},
      description: '多语言',
    },
    {
      path: '/settings/general/font-size',
      component: 'FontSizeSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.fontSize.base',
          search: {},
          description: '字体大小',
          actions: [
            {
              id: 'fontSize.slider.input',
              label: '字体大小：调整滑块',
              behavior: 'input',
              paramsSchema: { value: 'number' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '字体大小',
    },
    {
      path: '/settings/general/dark-mode',
      component: 'DarkModeSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.darkMode.base',
          search: {},
          description: '深色模式',
          actions: [
            { id: 'darkMode.followSystem.toggle', label: '跟随系统：开关', behavior: 'toggle' },
            { id: 'darkMode.mode.select.light', label: '选择普通模式', behavior: 'select' },
            { id: 'darkMode.mode.select.dark', label: '选择深色模式', behavior: 'select' },
          ],
        },
      ],
      queryParams: {},
      description: '深色模式',
    },
    {
      path: '/settings/general/speed-mode',
      component: 'SpeedModeSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.speedMode.base',
          search: {},
          description: '极速模式',
          actions: [{ id: 'speedMode.enabled.toggle', label: '极速启动：开关', behavior: 'toggle' }],
        },
      ],
      queryParams: {},
      description: '极速模式',
    },
    {
      path: '/settings/general/clipboard',
      component: 'ClipboardSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.clipboard.base',
          search: {},
          description: '剪贴板设置',
          actions: [{ id: 'clipboard.allowRead.toggle', label: '允许读取剪贴板：开关', behavior: 'toggle' }],
        },
      ],
      queryParams: {},
      description: '剪贴板设置',
    },
    {
      path: '/settings/general/my-manage',
      component: 'MyPageManagePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.myManage.base',
          search: {},
          description: '我的页管理',
          actions: [
            { id: 'myManage.documents.toggle', label: '证件：开关', behavior: 'toggle' },
            { id: 'myManage.asset.yuebao.toggle', label: '余额宝：开关', behavior: 'toggle' },
            { id: 'myManage.asset.huabei.toggle', label: '花呗：开关', behavior: 'toggle' },
            { id: 'myManage.asset.antInsure.toggle', label: '蚂蚁保：开关', behavior: 'toggle' },
            { id: 'myManage.asset.sesame.toggle', label: '芝麻信用：开关', behavior: 'toggle' },
            { id: 'myManage.asset.yulibao.toggle', label: '余利宝：开关', behavior: 'toggle' },
            { id: 'myManage.asset.mybankLoan.toggle', label: '网商贷：开关', behavior: 'toggle' },
            { id: 'myManage.asset.mybank.toggle', label: '网商银行：开关', behavior: 'toggle' },
            { id: 'myManage.civic.toggle', label: '我的民生保障：开关', behavior: 'toggle' },
            { id: 'myManage.orders.toggle', label: '我的订单：开关', behavior: 'toggle' },
            { id: 'myManage.moreServices.toggle', label: '更多服务：开关', behavior: 'toggle' },
          ],
        },
      ],
      queryParams: {},
      description: '我的页管理',
    },
    {
      path: '/settings/general/home-manage',
      component: 'HomeManagePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.general.homeManage.base', search: {}, description: '首页管理' }],
      queryParams: {},
      description: '首页管理',
    },
    {
      path: '/settings/general/home-manage/search-box',
      component: 'SearchBoxManagePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.homeManage.searchBox.base',
          search: {},
          description: '搜索框管理',
          actions: [
            { id: 'homeManage.searchBox.recommend.toggle', label: '搜索框推荐：开关', behavior: 'toggle' },
            { id: 'homeManage.searchBox.ambience.toggle', label: '搜索框氛围：开关', behavior: 'toggle' },
          ],
        },
      ],
      queryParams: {},
      description: '搜索框管理',
    },
    {
      path: '/settings/general/home-manage/search-pre',
      component: 'SearchPreManagePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.homeManage.searchPre.base',
          search: {},
          description: '搜索前置页管理',
          actions: [{ id: 'homeManage.searchPreWords.toggle', label: '顶部搜索推荐词：开关', behavior: 'toggle' }],
        },
      ],
      queryParams: {},
      description: '搜索前置页管理',
    },
    {
      path: '/settings/general/home-manage/voice-float',
      component: 'VoiceFloatingBallPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.homeManage.voiceFloat.base',
          search: {},
          description: '语音快捷悬浮球',
          actions: [{ id: 'homeManage.voiceFloating.toggle', label: '语音快捷悬浮球：开关', behavior: 'toggle' }],
        },
      ],
      queryParams: {},
      description: '语音快捷悬浮球',
    },
    {
      path: '/settings/general/home-manage/activity-ambience',
      component: 'ActivityAmbiencePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'settings.general.homeManage.activityAmbience.base',
          search: {},
          description: '活动氛围图',
          actions: [{ id: 'homeManage.activityAmbience.toggle', label: '活动氛围图：开关', behavior: 'toggle' }],
        },
      ],
      queryParams: {},
      description: '活动氛围图',
    },

    // =========================
    // Bills / Balance
    // =========================
    {
      path: '/bill',
      component: 'BillsPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'bill.base', search: {}, description: '账单-全部' },
        { id: 'bill.tab.expense', search: { quickFilters: 'expense' }, description: '账单-支出' },
        { id: 'bill.tab.transfer', search: { quickFilters: 'transfer' }, description: '账单-转账' },
        { id: 'bill.tab.refund', search: { quickFilters: 'refund' }, description: '账单-退款' },
        { id: 'bill.tab.order', search: { quickFilters: 'order' }, description: '账单-订单' },
        { id: 'bill.tab.offline', search: { quickFilters: 'offline' }, description: '账单-线下消费' },
        { id: 'bill.tab.topUp', search: { quickFilters: 'topUp' }, description: '账单-充值缴费' },
        { id: 'bill.tab.shopping', search: { quickFilters: 'shopping' }, description: '账单-网购' },
        { id: 'bill.tab.merchantCollection', search: { quickFilters: 'merchantCollection' }, description: '账单-二维码收款' },
        { id: 'bill.filter', search: { modal: 'filter' }, description: '账单-筛选弹窗' },
      ],
      queryParams: {
        minAmount: 'string',
        maxAmount: 'string',
        categories: 'string',
      },
      description: '账单',
    },
    {
      path: '/bill/search',
      component: 'BillSearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'bill.search.base', search: {}, description: '账单搜索' }],
      queryParams: {},
      description: '账单搜索',
    },
    {
      path: '/bill/detail/:id',
      component: 'BillDetailPage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'bill.detail.base', search: {}, description: '账单详情' }],
      queryParams: {},
      description: '账单详情',
    },

    // =========================
    // Bill Analysis
    // =========================
    {
      path: '/bill/analysis',
      component: 'BillAnalysisPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'bill.analysis.base', search: {}, description: '收支分析' }],
      queryParams: {},
      description: '收支分析',
    },
    {
      path: '/balance',
      component: 'BalancePage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'balance.base', search: {}, description: '余额' }],
      queryParams: {},
      description: '余额',
    },
    {
      path: '/assets',
      component: 'TotalAssetsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'assets.base', search: {}, description: '总资产' }],
      queryParams: {},
      description: '总资产',
    },
    {
      path: '/yuebao',
      component: 'YuebaoPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'yuebao.base', search: {}, description: '余额宝' }],
      queryParams: {},
      description: '余额宝',
    },
    {
      path: '/balance/records',
      component: 'BalanceRecordsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'balance.records.base', search: {}, description: '余额明细-全部' },
        { id: 'balance.records.tab.out', search: { tab: 'out' }, description: '余额明细-支出' },
        { id: 'balance.records.tab.in', search: { tab: 'in' }, description: '余额明细-收入' },
      ],
      queryParams: {},
      description: '余额明细',
    },

    // =========================
    // Balance Recharge
    // =========================
    {
      path: '/balance/recharge',
      component: 'RechargePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: NO_SCROLL,
      uiStates: [
        { id: 'balance.recharge.base', search: {}, description: '余额充值' },
        { id: 'balance.recharge.modal.multi', search: { modal: 'multi' }, description: '多卡充值面板' },
        {
          id: 'balance.recharge.modal.password',
          search: { modal: 'password' },
          description: '充值支付密码弹窗',
          actions: [
            {
              id: 'rechargePassword.keypad.press',
              label: '输入充值密码数字键',
              behavior: 'other',
              paramsSchema: { digit: 'string' },
            },
            { id: 'rechargePassword.keypad.delete', label: '删除充值密码一位', behavior: 'other' },
          ],
        },
        {
          id: 'balance.recharge.modal.multiPay',
          search: { modal: 'multiPay' },
          description: '多卡充值支付密码弹窗',
          actions: [
            {
              id: 'rechargeMultiPassword.keypad.press',
              label: '输入多卡充值密码数字键',
              behavior: 'other',
              paramsSchema: { digit: 'string' },
            },
            { id: 'rechargeMultiPassword.keypad.delete', label: '删除多卡充值密码一位', behavior: 'other' },
          ],
        },
      ],
      queryParams: {},
      description: '余额充值',
    },
    {
      path: '/balance/recharge/success',
      component: 'RechargeSuccessPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: NO_SCROLL,
      uiStates: [{ id: 'balance.recharge.success.base', search: {}, description: '充值成功' }],
      queryParams: {},
      description: '充值成功',
    },
    {
      path: '/settings/payment/recharge',
      component: 'RechargeCardPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: NO_SCROLL,
      uiStates: [{ id: 'settings.payment.recharge.base', search: {}, description: '充值卡充值' }],
      queryParams: {},
      description: '充值卡充值',
    },

    // =========================
    // Scan (扫一扫)
    // =========================
    {
      path: '/scan',
      component: 'ScanPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: NO_SCROLL,
      uiStates: [{ id: 'scan.base', search: {}, description: '扫一扫' }],
      queryParams: {},
      description: '扫一扫',
    },

    // =========================
    // Pay / Transfer flow
    // =========================
    {
      path: '/pay',
      component: 'PayPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'pay.base', search: {}, description: '收付款' }],
      queryParams: {},
      description: '收付款',
    },
    {
      path: '/pay/receive',
      component: 'ReceivePage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'pay.receive.base', search: {}, description: '收钱' }],
      queryParams: {},
      description: '收钱',
    },
    {
      path: '/pay/transfer',
      component: 'TransferPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'pay.transfer.base', search: {}, description: '转账' }],
      queryParams: {},
      description: '转账',
    },
    {
      path: '/pay/transfer/to-account',
      component: 'TransferToAlipayPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'transfer.toAccount.base',
          search: {},
          description: '填写对方支付宝账号',
          actions: [
            {
              id: 'transferToAccount.account.input',
              label: '输入对方账号',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
          ],
        },
        { id: 'transfer.toAccount.modal.contacts', search: { modal: 'contacts' }, description: '选择最近联系人' },
        { id: 'transfer.toAccount.modal.accountNotFound', search: { modal: 'accountNotFound' }, description: '账号不存在提示弹窗' },
      ],
      queryParams: {},
      description: '填写对方支付宝账号',
    },
    {
      path: '/pay/transfer/amount',
      component: 'TransferAmountPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'transfer.amount.base',
          search: {},
          description: '填写转账金额',
          actions: [
            { id: 'transferAmount.note.select.borrow', label: '转账留言：出借', behavior: 'select' },
            { id: 'transferAmount.note.select.thanks', label: '转账留言：谢谢', behavior: 'select' },
            { id: 'transferAmount.note.select.living', label: '转账留言：生活费', behavior: 'select' },
            { id: 'transferAmount.note.select.rent', label: '转账留言：房租', behavior: 'select' },
            { id: 'transferAmount.note.select.buy', label: '转账留言：代买', behavior: 'select' },
            { id: 'transferAmount.note.select.repay', label: '转账留言：还款', behavior: 'select' },
          ],
        },
        {
          id: 'transfer.amount.modal.password',
          search: { modal: 'password' },
          description: '支付密码弹窗',
          actions: [
            {
              id: 'transferPassword.keypad.press',
              label: '输入支付密码数字键',
              behavior: 'other',
              paramsSchema: { digit: 'string' },
            },
            { id: 'transferPassword.keypad.delete', label: '删除支付密码一位', behavior: 'other' },
          ],
        },
      ],
      queryParams: { contactId: 'string' },
      description: '转账金额',
    },
    {
      path: '/pay/transfer/success',
      component: 'TransferSuccessPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'transfer.success.base', search: {}, description: '转账成功' }],
      queryParams: {},
      description: '转账成功',
    },
    {
      path: '/pay/cashier',
      component: 'CashierPage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: NO_SCROLL,
      uiStates: [
        {
          id: 'cashier.base',
          search: {},
          description: '收银台',
        },
        {
          id: 'cashier.modal.password',
          search: { modal: 'password' },
          description: '收银台-支付密码弹窗',
          actions: [
            {
              id: 'cashierPassword.keypad.press',
              label: '输入支付密码数字键',
              behavior: 'other',
              paramsSchema: { digit: 'string' },
            },
            { id: 'cashierPassword.keypad.delete', label: '删除支付密码一位', behavior: 'other' },
          ],
        },
      ],
      queryParams: { amount: 'string', orderId: 'string', merchantName: 'string', subject: 'string' },
      description: '收银台（外部支付请求）',
    },
  ],

  transitions: [
    // =========================
    // Tab switching
    // =========================
    {
      id: 'tab.home',
      from: ['/', '/finance', '/video', '/messages', '/my'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到首页',
      ui: { placement: 'tabbar', icon: 'tab_home', gesture: 'tap' },
    },
    {
      id: 'tab.finance',
      from: ['/', '/finance', '/video', '/messages', '/my'],
      to: '/finance',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到理财',
      ui: { placement: 'tabbar', icon: 'tab_finance', gesture: 'tap' },
    },
    {
      id: 'tab.video',
      from: ['/', '/finance', '/video', '/messages', '/my'],
      to: '/video',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到视频',
      ui: { placement: 'tabbar', icon: 'tab_video', gesture: 'tap' },
    },
    {
      id: 'tab.messages',
      from: ['/', '/finance', '/video', '/messages', '/my'],
      to: '/messages',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到消息',
      ui: { placement: 'tabbar', icon: 'tab_messages', gesture: 'tap' },
    },
    {
      id: 'tab.my',
      from: ['/', '/finance', '/video', '/messages', '/my'],
      to: '/my',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到我的',
      ui: { placement: 'tabbar', icon: 'tab_my', gesture: 'tap' },
    },

    // =========================
    // Home
    // =========================
    {
      id: 'scan.open',
      from: '/',
      to: '/scan',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开扫一扫',
      ui: { placement: 'content', icon: 'scan', gesture: 'tap' },
    },
    {
      id: 'pay.open',
      from: '/',
      to: '/pay',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开收付款',
      ui: { placement: 'content', icon: 'pay', gesture: 'tap' },
    },
    {
      id: 'scan.pay',
      from: '/scan',
      to: '/pay',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '从扫一扫打开收付款',
      ui: { placement: 'content', icon: 'pay', gesture: 'tap' },
    },
    {
      id: 'transfer.open',
      from: ['/', '/pay', '/balance'],
      to: '/pay/transfer',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开转账',
      ui: { placement: 'content', icon: 'transfer', gesture: 'tap' },
    },

    // =========================
    // My
    // =========================
    {
      id: 'settings.open',
      from: '/my',
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开设置',
      ui: { placement: 'topbar', icon: 'settings', gesture: 'tap' },
    },
    {
      id: 'bill.open',
      from: '/my',
      to: '/bill',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开账单',
      ui: { placement: 'content', icon: 'bill', gesture: 'tap' },
    },
    {
      id: 'balance.open',
      from: '/my',
      to: '/balance',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开余额',
      ui: { placement: 'content', icon: 'balance', gesture: 'tap' },
    },
    {
      id: 'assets.open',
      from: '/my',
      to: '/assets',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开总资产',
      ui: { placement: 'content', icon: 'assets', gesture: 'tap' },
    },
    {
      id: 'yuebao.open',
      from: '/my',
      to: '/yuebao',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开余额宝',
      ui: { placement: 'content', icon: 'yuebao', gesture: 'tap' },
    },
    {
      id: 'assets.finance.open',
      from: '/assets',
      to: '/finance',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '总资产页前往理财',
      ui: { placement: 'topbar', icon: 'finance', gesture: 'tap' },
    },
    {
      id: 'bankCards.open',
      from: '/my',
      to: '/bank-cards',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开银行卡',
      ui: { placement: 'content', icon: 'bank_cards', gesture: 'tap' },
    },
    {
      id: 'bankCards.add.open',
      from: ['/bank-cards', '/settings/payment/bank-cards', '/balance/recharge'],
      to: '/bank-cards/add',
      search: {},
      searchParams: { returnTo: 'string' },
      mode: 'push',
      params: {},
      label: '打开添加银行卡',
      ui: { placement: 'topbar', icon: 'add', gesture: 'tap' },
    },
    {
      id: 'balance.records.open',
      from: '/balance',
      to: '/balance/records',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看余额明细',
      ui: { placement: 'content', icon: 'balance_records', gesture: 'tap' },
    },
    {
      id: 'balance.recharge.open',
      from: '/balance',
      to: '/balance/recharge',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '余额充值',
      ui: { placement: 'content', icon: 'recharge', gesture: 'tap' },
    },
    {
      id: 'balance.recharge.success.open',
      from: '/balance/recharge',
      to: '/balance/recharge/success',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '充值成功',
      ui: { placement: 'none', icon: 'recharge_success', gesture: 'tap' },
    },
    {
      id: 'recharge.success.toHome',
      from: '/balance/recharge/success',
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '回首页',
      ui: { placement: 'topbar', icon: 'home', gesture: 'tap' },
    },
    {
      id: 'recharge.success.done',
      from: '/balance/recharge/success',
      to: '/balance',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '完成充值',
      ui: { placement: 'content', icon: 'done', gesture: 'tap' },
    },
    {
      id: 'recharge.multi.open',
      from: { path: '/balance/recharge', search: { modal: null } },
      to: '/balance/recharge',
      search: { modal: 'multi' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开多卡充值',
      ui: { placement: 'content', icon: 'multi_recharge', gesture: 'tap' },
    },
    {
      id: 'rechargePassword.open',
      from: { path: '/balance/recharge', search: { modal: null } },
      to: '/balance/recharge',
      search: { modal: 'password' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开充值支付密码',
      ui: { placement: 'content', icon: 'payment_password', gesture: 'tap' },
    },
    {
      id: 'rechargeMultiPay.open',
      from: { path: '/balance/recharge', search: { modal: 'multi' } },
      to: '/balance/recharge',
      search: { modal: 'multiPay' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开多卡充值支付密码',
      ui: { placement: 'content', icon: 'payment_password', gesture: 'tap' },
    },
    {
      id: 'balance.bankCards.open',
      from: ['/balance', '/balance/recharge'],
      to: '/settings/payment/bank-cards',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开银行卡管理',
      ui: { placement: 'content', icon: 'bank_cards', gesture: 'tap' },
    },
    {
      id: 'bankCards.add.verify.open',
      from: '/bank-cards/add',
      to: '/bank-cards/add/verify',
      search: {},
      searchParams: { bankName: 'string', cardNumber: 'string', returnTo: 'string' },
      mode: 'push',
      params: {},
      label: '银行卡验证',
      ui: { placement: 'content', icon: 'verify', gesture: 'tap' },
    },
    {
      id: 'bankCards.add.verify.done',
      from: '/bank-cards/add/verify',
      to: '/bank-cards',
      search: { toast: 'card_added' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '添加银行卡完成',
      ui: { placement: 'none', icon: 'done', gesture: 'tap' },
    },
    {
      id: 'bankCards.add.verify.doneReturnRecharge',
      from: '/bank-cards/add/verify',
      to: '/balance/recharge',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '添加银行卡完成并返回充值页',
      ui: { placement: 'none', icon: 'done', gesture: 'tap' },
    },
    {
      id: 'bankCards.add.verify.doneReturnMulti',
      from: '/bank-cards/add/verify',
      to: '/balance/recharge',
      search: { modal: 'multi' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '添加银行卡完成并返回多卡充值',
      ui: { placement: 'none', icon: 'done', gesture: 'tap' },
    },
    {
      id: 'settings.payment.password.open',
      from: '/settings/payment',
      to: '/settings/payment/password',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开支付密码',
      ui: { placement: 'content', icon: 'password', gesture: 'tap' },
    },
    {
      id: 'settings.payment.subscriptions.open',
      from: '/settings/payment',
      to: '/settings/payment/subscriptions',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开免密支付',
      ui: { placement: 'content', icon: 'subscriptions', gesture: 'tap' },
    },

    // =========================
    // Settings navigation
    // =========================
    {
      id: 'settings.general.open',
      from: '/settings',
      to: '/settings/general',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开通用设置',
      ui: { placement: 'content', icon: 'settings_general', gesture: 'tap' },
    },
    {
      id: 'settings.payment.open',
      from: '/settings',
      to: '/settings/payment',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开支付设置',
      ui: { placement: 'content', icon: 'settings_payment', gesture: 'tap' },
    },
    {
      id: 'settings.notifications.open',
      from: '/settings',
      to: '/settings/notifications',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开新消息通知',
      ui: { placement: 'content', icon: 'settings_notifications', gesture: 'tap' },
    },
    {
      id: 'settings.payment.order.open',
      from: '/settings/payment',
      to: '/settings/payment/order',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开支付顺序设置',
      ui: { placement: 'content', icon: 'pay_order', gesture: 'tap' },
    },
    {
      id: 'settings.payment.fastPay.open',
      from: '/settings/payment',
      to: '/settings/payment/fast-pay',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开极速付款设置',
      ui: { placement: 'content', icon: 'fast_pay', gesture: 'tap' },
    },
    {
      id: 'fastPay.payOrder.open',
      from: '/settings/payment/fast-pay',
      to: '/settings/payment/order',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '从极速付款进入支付顺序',
      ui: { placement: 'content', icon: 'pay_order', gesture: 'tap' },
    },
    {
      id: 'fastPay.noPwd.agreement.open',
      from: { path: '/settings/payment/fast-pay', search: { modal: null } },
      to: '/settings/payment/fast-pay',
      search: { modal: 'agreement' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '开通小额免密：打开协议弹窗',
      ui: { placement: 'content', icon: 'fast_pay_no_pwd_agreement', gesture: 'tap' },
    },
    {
      id: 'fastPay.noPwd.password.open',
      from: { path: '/settings/payment/fast-pay', search: { modal: 'agreement' } },
      to: '/settings/payment/fast-pay',
      search: { modal: 'password' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '开通小额免密：打开支付密码弹窗',
      ui: { placement: 'content', icon: 'fast_pay_password', gesture: 'tap' },
    },
    {
      id: 'fastPay.noPwd.disableConfirm.open',
      from: { path: '/settings/payment/fast-pay', search: { modal: null } },
      to: '/settings/payment/fast-pay',
      search: { modal: 'noPwdDisableConfirm' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '关闭小额免密：打开确认弹窗',
      ui: { placement: 'content', icon: 'fast_pay_no_pwd_disable_confirm', gesture: 'tap' },
    },
    {
      id: 'fastPay.disableConfirm.open',
      from: { path: '/settings/payment/fast-pay', search: { modal: null } },
      to: '/settings/payment/fast-pay',
      search: { modal: 'disableFastPayConfirm' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '关闭极速付款：打开确认弹窗',
      ui: { placement: 'content', icon: 'fast_pay_disable_confirm', gesture: 'tap' },
    },
    {
      id: 'settings.general.language.open',
      from: '/settings/general',
      to: '/settings/general/language',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开多语言设置',
      ui: { placement: 'content', icon: 'language', gesture: 'tap' },
    },
    {
      id: 'settings.general.fontSize.open',
      from: '/settings/general',
      to: '/settings/general/font-size',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开字体大小设置',
      ui: { placement: 'content', icon: 'font_size', gesture: 'tap' },
    },
    {
      id: 'settings.general.darkMode.open',
      from: '/settings/general',
      to: '/settings/general/dark-mode',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开深色模式设置',
      ui: { placement: 'content', icon: 'dark_mode', gesture: 'tap' },
    },
    {
      id: 'settings.general.speedMode.open',
      from: '/settings/general',
      to: '/settings/general/speed-mode',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开极速模式设置',
      ui: { placement: 'content', icon: 'speed_mode', gesture: 'tap' },
    },
    {
      id: 'settings.general.clipboard.open',
      from: '/settings/general',
      to: '/settings/general/clipboard',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开剪贴板设置',
      ui: { placement: 'content', icon: 'clipboard', gesture: 'tap' },
    },
    {
      id: 'settings.general.myManage.open',
      from: '/settings/general',
      to: '/settings/general/my-manage',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开我的页管理',
      ui: { placement: 'content', icon: 'my_manage', gesture: 'tap' },
    },
    {
      id: 'settings.general.homeManage.open',
      from: '/settings/general',
      to: '/settings/general/home-manage',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开首页管理',
      ui: { placement: 'content', icon: 'home_manage', gesture: 'tap' },
    },
    {
      id: 'settings.homeManage.searchBox.open',
      from: '/settings/general/home-manage',
      to: '/settings/general/home-manage/search-box',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开搜索框管理',
      ui: { placement: 'content', icon: 'search_box_manage', gesture: 'tap' },
    },
    {
      id: 'settings.homeManage.searchPre.open',
      from: '/settings/general/home-manage',
      to: '/settings/general/home-manage/search-pre',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开搜索前置页管理',
      ui: { placement: 'content', icon: 'search_pre_manage', gesture: 'tap' },
    },
    {
      id: 'settings.homeManage.voiceFloat.open',
      from: '/settings/general/home-manage',
      to: '/settings/general/home-manage/voice-float',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开语音快捷悬浮球设置',
      ui: { placement: 'content', icon: 'voice_float', gesture: 'tap' },
    },
    {
      id: 'settings.homeManage.activityAmbience.open',
      from: '/settings/general/home-manage',
      to: '/settings/general/home-manage/activity-ambience',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开活动氛围图设置',
      ui: { placement: 'content', icon: 'activity_ambience', gesture: 'tap' },
    },

    // =========================
    // Pay flow
    // =========================
    {
      id: 'receive.open',
      from: '/pay',
      to: '/pay/receive',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开收钱页',
      ui: { placement: 'content', icon: 'receive', gesture: 'tap' },
    },
    {
      id: 'transfer.toAccount.open',
      from: '/pay/transfer',
      to: '/pay/transfer/to-account',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '填写对方账号',
      ui: { placement: 'content', icon: 'transfer_to_account', gesture: 'tap' },
    },
    {
      id: 'transfer.amount.open',
      from: ['/pay/transfer', '/pay/transfer/to-account', '/contacts/profile', '/chat'],
      to: '/pay/transfer/amount',
      search: {},
      searchParams: { contactId: 'string' },
      mode: 'push',
      params: {},
      label: '进入转账金额页',
      ui: { placement: 'content', icon: 'transfer_amount', gesture: 'tap' },
    },
    {
      id: 'transfer.success.open',
      from: '/pay/transfer/amount',
      to: '/pay/transfer/success',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开转账成功页',
      ui: { placement: 'none', icon: 'transfer_success', gesture: 'tap' },
    },
    {
      id: 'transfer.success.done',
      from: '/pay/transfer/success',
      to: '/pay/transfer',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '完成并返回转账页',
      ui: { placement: 'topbar', icon: 'done', gesture: 'tap' },
    },

    // =========================
    // TransferToAccount modals (URL states)
    // =========================
    {
      id: 'transferToAccount.recentContacts.open',
      from: { path: '/pay/transfer/to-account', search: { modal: null } },
      to: '/pay/transfer/to-account',
      search: { modal: 'contacts' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开最近联系人选择',
      ui: { placement: 'content', icon: 'recent_contacts', gesture: 'tap' },
    },
    {
      id: 'transferToAccount.error.open',
      from: { path: '/pay/transfer/to-account', search: { modal: null } },
      to: '/pay/transfer/to-account',
      search: { modal: 'accountNotFound' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '显示账号不存在提示',
      ui: { placement: 'content', icon: 'account_not_found', gesture: 'tap' },
    },

    // =========================
    // TransferAmount modals (URL states)
    // =========================
    {
      id: 'transferAmount.password.open',
      from: { path: '/pay/transfer/amount', search: { modal: null } },
      to: '/pay/transfer/amount',
      search: { modal: 'password' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开支付密码弹窗',
      ui: { placement: 'content', icon: 'payment_password', gesture: 'tap' },
    },

    // =========================
    // Cashier modals (URL states) — 由外部 Intent 触发
    // =========================
    {
      id: 'cashier.password.open',
      from: { path: '/pay/cashier', search: { modal: null } },
      to: '/pay/cashier',
      search: { modal: 'password' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开收银台支付密码弹窗',
      ui: { placement: 'content', icon: 'payment_password', gesture: 'tap' },
    },

    // =========================
    // Bills - inner tabs (URL states)
    // =========================
    {
      id: 'bill.tab.all',
      from: [
        { path: '/bill', search: { quickFilters: null } },
        { path: '/bill', search: { quickFilters: '*' } },
      ],
      to: '/bill',
      search: { quickFilters: null },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories'],
      mode: 'replace',
      params: {},
      label: '切换账单 Tab：全部',
      ui: { placement: 'content', icon: 'bill_tab_all', gesture: 'tap' },
    },
    {
      id: 'bill.tab.expense',
      from: [
        { path: '/bill', search: { quickFilters: null } },
        { path: '/bill', search: { quickFilters: '*' } },
      ],
      to: '/bill',
      search: { quickFilters: 'expense' },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories'],
      mode: 'replace',
      params: {},
      label: '切换账单 Tab：支出',
      ui: { placement: 'content', icon: 'bill_tab_expense', gesture: 'tap' },
    },
    {
      id: 'bill.tab.transfer',
      from: [
        { path: '/bill', search: { quickFilters: null } },
        { path: '/bill', search: { quickFilters: '*' } },
      ],
      to: '/bill',
      search: { quickFilters: 'transfer' },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories'],
      mode: 'replace',
      params: {},
      label: '切换账单 Tab：转账',
      ui: { placement: 'content', icon: 'bill_tab_transfer', gesture: 'tap' },
    },
    {
      id: 'bill.tab.refund',
      from: [
        { path: '/bill', search: { quickFilters: null } },
        { path: '/bill', search: { quickFilters: '*' } },
      ],
      to: '/bill',
      search: { quickFilters: 'refund' },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories'],
      mode: 'replace',
      params: {},
      label: '切换账单 Tab：退款',
      ui: { placement: 'content', icon: 'bill_tab_refund', gesture: 'tap' },
    },
    {
      id: 'bill.tab.order',
      from: [
        { path: '/bill', search: { quickFilters: null } },
        { path: '/bill', search: { quickFilters: '*' } },
      ],
      to: '/bill',
      search: { quickFilters: 'order' },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories'],
      mode: 'replace',
      params: {},
      label: '切换账单 Tab：订单',
      ui: { placement: 'content', icon: 'bill_tab_order', gesture: 'tap' },
    },
    {
      id: 'bill.tab.offline',
      from: [
        { path: '/bill', search: { quickFilters: null } },
        { path: '/bill', search: { quickFilters: '*' } },
      ],
      to: '/bill',
      search: { quickFilters: 'offline' },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories'],
      mode: 'replace',
      params: {},
      label: '切换账单 Tab：线下消费',
      ui: { placement: 'content', icon: 'bill_tab_offline', gesture: 'tap' },
    },
    {
      id: 'bill.tab.topUp',
      from: [
        { path: '/bill', search: { quickFilters: null } },
        { path: '/bill', search: { quickFilters: '*' } },
      ],
      to: '/bill',
      search: { quickFilters: 'topUp' },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories'],
      mode: 'replace',
      params: {},
      label: '切换账单 Tab：充值缴费',
      ui: { placement: 'content', icon: 'bill_tab_topUp', gesture: 'tap' },
    },
    {
      id: 'bill.tab.shopping',
      from: [
        { path: '/bill', search: { quickFilters: null } },
        { path: '/bill', search: { quickFilters: '*' } },
      ],
      to: '/bill',
      search: { quickFilters: 'shopping' },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories'],
      mode: 'replace',
      params: {},
      label: '切换账单 Tab：网购',
      ui: { placement: 'content', icon: 'bill_tab_shopping', gesture: 'tap' },
    },
    {
      id: 'bill.tab.merchantCollection',
      from: [
        { path: '/bill', search: { quickFilters: null } },
        { path: '/bill', search: { quickFilters: '*' } },
      ],
      to: '/bill',
      search: { quickFilters: 'merchantCollection' },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories'],
      mode: 'replace',
      params: {},
      label: '切换账单 Tab：二维码收款',
      ui: { placement: 'content', icon: 'bill_tab_merchantCollection', gesture: 'tap' },
    },
    {
      id: 'bill.filter.open',
      from: [
        { path: '/bill', search: { modal: null } },
        { path: '/bill', search: { modal: '*' } },
      ],
      to: '/bill',
      search: { modal: 'filter' },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories', 'quickFilters'],
      mode: 'replace',
      params: {},
      label: '打开账单筛选',
      ui: { placement: 'content', icon: 'bill_filter', gesture: 'tap' },
    },
    {
      id: 'bill.filter.close',
      from: { path: '/bill', search: { modal: 'filter' } },
      to: '/bill',
      search: { modal: null },
      searchParams: {},
      preserveParams: ['minAmount', 'maxAmount', 'categories', 'quickFilters'],
      mode: 'replace',
      params: {},
      label: '关闭账单筛选',
      ui: { placement: 'none', icon: 'bill_filter_close', gesture: 'tap' },
    },
    {
      id: 'bill.filter.apply',
      from: { path: '/bill', search: { modal: 'filter' } },
      to: '/bill',
      search: {
        modal: null,
        minAmount: null,
        maxAmount: null,
        categories: null,
        quickFilters: null,
      },
      searchParams: {
        minAmount: 'string',
        maxAmount: 'string',
        categories: 'string',
        quickFilters: 'string',
      },
      preserveParams: [],
      mode: 'replace',
      params: {},
      label: '应用账单筛选',
      ui: { placement: 'content', icon: 'bill_filter_apply', gesture: 'tap' },
    },
    {
      id: 'bill.detail.open',
      from: '/bill',
      to: '/bill/detail/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开账单详情',
      ui: { placement: 'content', icon: 'bill_detail', gesture: 'tap' },
    },
    {
      id: 'bill.search.open',
      from: '/bill',
      to: '/bill/search',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开账单搜索',
      ui: { placement: 'content', icon: 'bill_search', gesture: 'tap' },
    },
    {
      id: 'bill.search.detail.open',
      from: '/bill/search',
      to: '/bill/detail/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '从搜索打开账单详情',
      ui: { placement: 'content', icon: 'bill_detail', gesture: 'tap' },
    },

    // =========================
    // Balance records - inner tabs (URL states)
    // =========================
    {
      id: 'balanceRecords.tab.all',
      from: [
        { path: '/balance/records', search: { tab: null } },
        { path: '/balance/records', search: { tab: '*' } },
      ],
      to: '/balance/records',
      search: { tab: null },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换余额明细 Tab：全部',
      ui: { placement: 'content', icon: 'balance_records_tab_all', gesture: 'tap' },
    },
    {
      id: 'balanceRecords.tab.out',
      from: [
        { path: '/balance/records', search: { tab: null } },
        { path: '/balance/records', search: { tab: '*' } },
      ],
      to: '/balance/records',
      search: { tab: 'out' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换余额明细 Tab：支出',
      ui: { placement: 'content', icon: 'balance_records_tab_out', gesture: 'tap' },
    },
    {
      id: 'balanceRecords.tab.in',
      from: [
        { path: '/balance/records', search: { tab: null } },
        { path: '/balance/records', search: { tab: '*' } },
      ],
      to: '/balance/records',
      search: { tab: 'in' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换余额明细 Tab：收入',
      ui: { placement: 'content', icon: 'balance_records_tab_in', gesture: 'tap' },
    },

    // =========================
    // Contacts
    // =========================
    {
      id: 'contacts.open',
      from: '/messages',
      to: '/contacts',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开通讯录',
      ui: { placement: 'topbar', icon: 'contacts', gesture: 'tap' },
    },
    {
      id: 'contacts.profile.open',
      from: ['/contacts', '/chat'],      to: '/contacts/profile',
      search: {},
      searchParams: { contactId: 'string' },
      mode: 'push',
      params: {},
      label: '打开联系人资料',
      ui: { placement: 'content', icon: 'contact_profile', gesture: 'tap' },
    },
    // 移除下方重复的定义，合并到上面的统一入口
    {
      id: 'bill.analysis.open',
      from: '/bill',
      to: '/bill/analysis',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开收支分析',
      ui: { placement: 'content', icon: 'bill_analysis', gesture: 'tap' },
    },
    {
      id: 'chat.open',
      from: ['/messages', '/contacts/profile'],
      to: '/chat',
      search: {},
      searchParams: { id: 'string', type: 'string' },
      mode: 'push',
      params: {},
      label: '打开聊天',
      ui: { placement: 'content', icon: 'chat_open', gesture: 'tap' },
    },
  ],

  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = (typeof NAVIGATION_DECLARATION.transitions)[number]['id'];

