/**
 * WechatReading 字符串资源 — 对应 AOSP res/values/strings.xml
 */
export const strings = {
  app_name: '微信读书',

  // --- Tab Bar ---
  tab_reading: '阅读',
  tab_bookshelf: '书架',
  tab_audiobooks: '有声书',
  tab_me: '我',
  tab_book_friends: '书友',

  // --- Header / Search ---
  header_bookstore: '书城',
  search_placeholder_default: '置身事内',

  // --- Reading Page (Home) ---
  reading_hot_trend: '2025热搜趋势',
  reading_category: '分类',
  reading_ranking: '榜单',
  reading_book_list: '书单',
  reading_monthly_reading: '月阅读',
  reading_weekly_reading: '本周阅读',
  reading_minutes: '分钟',
  reading_more_ellipsis: '更多...',
  reading_recommended_for_you: '为你推荐',
  reading_refresh_batch: '换一批',
  reading_recommendation_value: '推荐值',

  // --- Bookshelf Page ---
  bookshelf_title: '书架',
  bookshelf_import: '导入',
  bookshelf_select: '选择',
  bookshelf_select_books: '选择书籍',
  bookshelf_selected_count: '已选择 {0} 本书籍',
  bookshelf_select_all: '全选',
  bookshelf_deselect_all: '取消全选',
  bookshelf_cancel: '取消',
  bookshelf_sort_default: '默认',
  bookshelf_sort_update: '更新',
  bookshelf_sort_progress: '进度',
  bookshelf_sort_recommendation: '推荐值',
  bookshelf_sort_title: '书名',
  bookshelf_sort_category: '分类',
  bookshelf_public_reading: '本公开阅读',
  bookshelf_private_reading: '本私密阅读',
  bookshelf_view_public_page: '查看我的公开主页',
  bookshelf_toolbar_private_reading: '私密阅读',
  bookshelf_toolbar_download: '下载到本地',
  bookshelf_toolbar_add_to_list: '添加到书单',
  bookshelf_toolbar_pin_top: '置顶',
  bookshelf_toolbar_group_to: '分组到...',
  bookshelf_toolbar_remove: '移出书架',
  bookshelf_private_modal_title: '私密阅读',
  bookshelf_private_modal_desc: '开启后，所选书籍的阅读记录将不会对外公开',
  bookshelf_private_modal_enable: '开启',
  bookshelf_remove_modal_title: '是否将所选书籍移出书架？',
  bookshelf_remove_modal_confirm: '移出',

  // --- Search Page ---
  search_hot_list: '热搜榜',
  search_more_rankings: '更多榜单',
  search_tab_all: '全部',
  search_tab_ebook: '电子书',
  search_tab_audiobook: '有声书',
  search_tab_fulltext: '全文',
  search_tab_author: '作者',
  search_tab_book_list: '书单',
  search_author_section: '作者',
  search_more: '更多',
  search_ebook_section: '电子书',
  search_audiobook_section: '有声书',
  search_no_result: '未找到相关结果',

  // --- Category Pages ---
  category_list_title: '分类',
  category_sub_all: '全部',
  category_filter_word_count: '字数',
  category_filter_payment_type: '付费类型',
  category_filter_popularity: '热度',

  // --- Book Detail Page ---
  book_detail_paid: '付费',
  book_detail_listen: '听',
  book_detail_top_chart: '总榜',
  book_detail_stat_reading: '阅读',
  book_detail_stat_listening: '收听',
  book_detail_stat_person: '人',
  book_detail_stat_times: '次',
  book_detail_friends_reading: '1位朋友在读',
  book_detail_my_reading: '我的阅读',
  book_detail_my_listening: '我的收听',
  book_detail_currently_reading: '在读',
  book_detail_currently_listening: '在听',
  book_detail_word_count: '字数',
  book_detail_rating: '评分',
  book_detail_weread_recommendation: '微信读书推荐值',
  book_detail_write_review: '写点评',
  book_detail_masterpiece: '神作',
  book_detail_recommend: '推荐',
  book_detail_average: '一般',
  book_detail_not_recommend: '不行',
  book_detail_tag_all: '全部',
  book_detail_tag_tragic_figures: '悲剧人物',
  book_detail_tag_tears: '泪流满面',
  book_detail_tag_plain_prose: '文笔朴素',
  book_detail_published_date: '2021年7月出版',
  book_detail_person_review: '人点评',
  book_detail_add_to_shelf: '加入书架',
  book_detail_added_to_shelf: '已加入书架',
  book_detail_read_button: '阅读',
  book_detail_shelf_modal_private: '私密阅读',
  book_detail_shelf_modal_download: '下载到本地',
  book_detail_shelf_modal_move: '移动到...',
  book_detail_shelf_modal_remove: '移出书架',
  book_detail_shelf_modal_cancel: '取消',

  // --- Reader Page ---
  reader_added: '已加入',
  reader_add_to_shelf: '加入书架',
  reader_no_content: '暂无内容',
  reader_intro: '简介',
  reader_swipe_to_start: '← 左滑开始阅读',
  reader_membership_paid: '付费会员可读',
  reader_free: '免费阅读',
  reader_approx_finish: '约51小时后读完',
  reader_reading_duration: '阅读时长',
  reader_notes: '笔记',
  reader_last_read_here: '上次读到这里',
  reader_reading_detail: '阅读明细',
  reader_auto_page_turn: '开启自动翻页',
  reader_theme_color: '颜色',
  reader_theme_background: '背景',
  reader_typography_margin_small: '小',
  reader_typography_margin_label: '边距',
  reader_typography_margin_large: '大',
  reader_typography_line_tight: '紧',
  reader_typography_line_label: '行距',
  reader_typography_line_loose: '松',
  reader_typography_font: '思源黑体',
  reader_typography_indent: '首行缩进',
  reader_typography_page_turn: '翻页方式',
  reader_shelf_modal_private: '私密阅读',
  reader_shelf_modal_download: '下载到本地',
  reader_shelf_modal_move: '移动到...',
  reader_shelf_modal_remove: '移出书架',
  reader_shelf_modal_cancel: '取消',

  // --- Audiobooks Page ---
  audiobooks_tab_audiobook: '有声书',
  audiobooks_tab_friends: '书友',
  audiobooks_search_category: '分类',
  audiobooks_community_recommended: '推荐',
  audiobooks_community_following: '关注',
  audiobooks_community_chat: '闲聊',
  audiobooks_community_topics: '话题',
  audiobooks_community_mine: '我的',
  audiobooks_recommended_for_you: '为你推荐',
  audiobooks_refresh_batch: '换一批',
  audiobooks_hot_chart: '热听榜',
  audiobooks_view_full_chart: '查看完整榜单',
  audiobooks_good_listen_value: '好听值',
  audiobooks_listens: '次收听',
  audiobooks_friends_tag: '书友',
  audiobooks_challenge_tag: '# 21天阅读挑战',

  // --- Me Page ---
  me_badge: '勋章',
  me_become_member: '成为付费会员',
  me_first_month_deal: '首月特惠 9 元/月',
  me_coins: '充值币',
  me_balance: '余额',
  me_benefits: '福利',
  me_benefits_detail: '0 天 | 赠币 40.00',
  me_reading_ranking: '读书排行榜',
  me_ranking_position: '第 1 名',
  me_reading_duration: '阅读时长',
  me_this_month: '本月',
  me_reading: '在读',
  me_finished: '读完',
  me_cumulative: '累计',
  me_books_unit: '本',
  me_notes: '笔记',
  me_no_notes: '尚未留下笔记',
  me_subscription: '订阅',
  me_not_published: '尚未上架',
  me_book_lists: '书单',
  me_unit_ge: '个',
  me_following: '关注',
  me_followers_count: '人关注我',
  me_following_count: '我关注了 {0} 人',
  me_liked: '赞过',
  me_no_likes: '暂无赞过',
  me_browsing_history: '浏览记录',
  me_this_month_books: '本月 4 本',
  me_web_version: '网页版',
  me_eink: '墨水屏',
  me_eink_desc: '专为微信读书定制',

  // --- My Profile Page ---
  my_profile_title: '我的主页',
  my_profile_followers_visible: '关注我的人可见',
  my_profile_reading_duration: '阅读时长',
  my_profile_likes_received: '收到的赞',
  my_profile_followers: '关注我',
  my_profile_tab_shelf: '书架',
  my_profile_tab_finished: '读完',
  my_profile_no_books: '暂无书籍',
  my_profile_recent_activity: '1天前 开始阅读 {0}',
  my_profile_view_shelf: '查看书架',
  my_profile_view_all: '查看全部',

  // --- Edit Profile Page ---
  edit_profile_title: '编辑个人主页',
  edit_profile_avatar: '头像',
  edit_profile_nickname: '昵称',
  edit_profile_nickname_placeholder: '请输入昵称',
  edit_profile_gender: '性别',
  edit_profile_gender_hint: '将外显并作为个性化书籍推荐的参考因素',
  edit_profile_introduction: '介绍自己',
  edit_profile_introduction_placeholder: '可以说说你的职业或爱好',
  edit_profile_signature: '我的签名',
  edit_profile_signature_placeholder: '请输入签名',

  // --- Gender Selection Page ---
  gender_title: '选择性别',
  gender_done: '完成',
  gender_male: '男',
  gender_female: '女',

  // --- Following Page ---
  following_tab_following: '我关注的',
  following_tab_followers: '关注我的',
  following_wechat_friends: '微信朋友',
  following_count: '已关注 {0} 人',
  following_status_followed: '已关注',
  following_no_followers: '暂时没有关注你的人',

  // --- Wechat Friends Page ---
  wechat_friends_title: '微信朋友',
  wechat_friends_select: '选择',
  wechat_friends_follow: '关注',
  wechat_friends_reading_time: '共阅读{0}',
  wechat_friends_reading_hours_minutes: '{0}小时{1}分钟',
  wechat_friends_reading_minutes: '{0}分钟',
  wechat_friends_currently_reading: '她正在…',

  // --- User Profile Page ---
  user_profile_personal_page: '个人主页',
  user_profile_wechat_friend: '微信朋友',
  user_profile_reading_duration: '阅读时长',
  user_profile_likes_received: '收到的赞',
  user_profile_followers: '关注他',
  user_profile_followed: '已关注',
  user_profile_follow: '关注',
  user_profile_badges_title: '获得勋章',
  user_profile_badges_count: '共获得 16 枚勋章',
  user_profile_bookshelf_title: '书架',
  user_profile_recent_activity: '5年前 开始阅读 {0}',
  user_profile_view_shelf: '查看书架',
  user_profile_unfollow_desc: '取消关注后将不再收到该用户的动态信息',
  user_profile_unfollow: '取消关注',
  user_profile_close: '关闭',

  // --- User Bookshelf Page ---
  user_bookshelf_shelf: '书架',
  user_bookshelf_count: '本书籍',

  // --- Coins Page ---
  coins_title: '充值币',
  coins_recharge: '充 值',
  coins_no_expire: '充值币永不过期，购买内容不受限制',
  coins_transactions: '交易记录',
  coins_purchase_books: '书币购买和活动领取书籍',
  coins_auto_purchase: '自动购买',

  // --- Transactions Page ---
  transactions_title: '交易记录',
  transactions_gift_record: '赠书记录',
  transactions_type_gift_coins: '赠币',

  // --- My Reading Page ---
  my_reading_title: '我的阅读',
  my_reading_tab_week: '周',
  my_reading_tab_month: '月',
  my_reading_tab_year: '年',
  my_reading_tab_total: '总',
  my_reading_tab_history: '阅历',
  my_reading_this_week: '本周',
  my_reading_this_month: '本月',
  my_reading_this_year: '今年',
  my_reading_daily_avg: '日均阅读',
  my_reading_friends_ranking: '朋友中排名',
  my_reading_rank_unit: '名',
  my_reading_challenge: '阅读挑战赛',
  my_reading_challenge_desc: '赢取 365 天付费会员卡 + 500 书币',
  my_reading_go_challenge: '去挑战',
  my_reading_duration_distribution: '阅读时长分布',
  my_reading_no_record_week: '本周暂无阅读记录',
  my_reading_no_record: '暂无阅读记录',
  my_reading_longest_weekday: '周{0}阅读最久，{1}分钟',
  my_reading_longest_day: '{0}日阅读最久，{1}分钟',
  my_reading_longest_month: '{0}月阅读最久，{1}分钟',
  my_reading_calendar_title: '阅读天数',
  my_reading_calendar_month: '月',
  my_reading_calendar_year: '年',
  my_reading_cumulative_days: '累计阅读',
  my_reading_cumulative_days_unit: '天',
  my_reading_cumulative_minutes: '累计阅读 {0} 分钟',

  // --- Reading List Page ---
  reading_list_title: '我的阅读',
  reading_list_tab_all: '全部',
  reading_list_tab_reading: '在读',
  reading_list_tab_finished: '读完',
  reading_list_filter: '筛选',
  reading_list_year_unit: '年',
  reading_list_less_than: '小于',
  reading_list_read_to: '读到',
  reading_list_status_reading: '在读',
  reading_list_month_finished: '月读完',
  reading_list_month_started: '月开始阅读',
  reading_list_no_records: '暂无书籍记录',

  // --- Book Lists Page ---
  book_lists_tab_my: '我的书单({0})',
  book_lists_tab_collected: '收藏的书单',
  book_lists_section_liked_books: '喜欢的书',
  book_lists_liked_title: '{0}喜欢的书',
  book_lists_add_books: '添加书籍',
  book_lists_my_lists_count_label: '{0}个我的书单',
  book_lists_view_public_homepage: '查看我的公开主页',
  book_lists_empty_collected: '暂无收藏书单',
  book_lists_view_popular: '查看热门书单',
  book_lists_edit_title: '编辑书单',
  book_lists_sync_to_home: '同步到首页',
  book_lists_done: '完成',
  book_lists_search_books: '搜索书籍',
  book_lists_shelf_section: '书架',
  book_lists_recommendation_placeholder: '点击写下推荐语…',
  book_lists_delete_book: '删除书籍',
  book_lists_add_books_done: '完成',
  book_lists_nothing_to_add: '暂无可添加的书籍',

  // --- Settings Page ---
  settings_title: '设置',
  settings_no_auto_lock: '阅读时不自动锁屏',
  settings_allow_landscape: '阅读时允许横屏',
  settings_hide_thoughts: '阅读时隐藏他人的想法',
  settings_show_time_battery: '阅读时显示时间和电量',
  settings_volume_key_turn: '使用音量键翻页',
  settings_first_line_indent: '正文首行缩进',
  settings_click_left_next: '点击左侧翻到下一页',
  settings_block_web_novels: '搜索和个性化推荐中屏蔽网文',
  settings_mix_audio: '允许与其他应用同时播放',
  settings_auto_download: '加入书架自动下载',
  settings_page_turn_style: '翻页方式',
  settings_dark_mode: '深色模式',
  settings_dark_mode_follow_system: '跟随系统',
  settings_dark_mode_enabled: '已开启',
  settings_dark_mode_disabled: '未开启',
  settings_privacy: '隐私',
  settings_student_auth: '认证学生身份',
  settings_student_auth_desc: '获赠专属勋章和付费会员',
  settings_teen_mode: '青少年模式',
  settings_teen_mode_status: '未开启',
  settings_notifications: '通知',
  settings_login_devices: '登录设备',
  settings_clear_cache: '清理缓存',
  settings_publish_on_weread: '上架微信读书',
  settings_publish_desc: '投稿征文',
  settings_business_cooperation: '商务合作',
  settings_about_weread: '关于微信读书',
  settings_follow_wechat_account: '关注微信公众号',
  settings_help_feedback: '帮助与反馈',
  settings_logout: '退出登录',

  // --- Auto Download Page ---
  auto_download_title: '加入书架自动下载',
  auto_download_member_only: '自动下载为会员专享功能',
  auto_download_upgrade: '去升级',
  auto_download_intro: '开启「加入书架自动下载」后',
  auto_download_rule_1: '书籍加入书架后，将自动下载全书。',
  auto_download_rule_2: '已在书架但尚未下载的书籍，在下次阅读时会自动下载。',
  auto_download_rule_3: '达到存储上限后，下载新内容将自动清理最久没阅读的书。',
  auto_download_rule_4: '按章购买、有声书、超大书籍（200M以上）仍需手动下载。',
  auto_download_rule_5: '通过书单批量加入书架的书籍，仍需手动下载。',

  // --- Page Turn Style Page ---
  page_turn_title: '翻页方式',
  page_turn_simulation: '仿真翻页',
  page_turn_swipe: '左右滑动',
  page_turn_scroll: '上下滚动',
  page_turn_cover: '覆盖翻页',

  // --- Dark Mode Page ---
  dark_mode_title: '深色模式',
  dark_mode_follow_system: '跟随系统',
  dark_mode_follow_system_desc: '开启后，将跟随系统打开或关闭深色模式',
  dark_mode_manual_select: '手动选择',
  dark_mode_light: '浅色',
  dark_mode_dark: '深色',

  // --- Privacy Page ---
  privacy_title: '隐私',
  privacy_personal_page: '个人主页',
  privacy_require_follow_request: '关注你须获得你的同意',
  privacy_require_follow_request_desc: '开启后，获得你同意的人才可关注你',
  privacy_hide_vip_global: '全局隐藏资深会员',
  privacy_hide_vip_global_desc: '开启后，自己和他人的资深会员身份均不可见',
  privacy_auto_private_reading: '加入书架后自动开启私密阅读',
  privacy_auto_private_reading_desc: '开启私密阅读的书籍阅读动态不会公开',
  privacy_shelf_replacement: '替身书架',
  privacy_shelf_replacement_desc: '开启后，替身书架将代替真实书架显示在你的个人资料中。其他人仅能查看你...',
  privacy_reject_stranger_msg: '不接收未关注人的私信',
  privacy_blacklist: '黑名单',
  privacy_wechat_articles: '微信公众号文章',
  privacy_account: '账号',
  privacy_close_personalized_rec: '关闭个性化推荐',
  privacy_close_reading_rank: '关闭读书排行榜',
  privacy_get_account_copy: '获取账户信息副本',
  privacy_basic_policy: '基本功能隐私政策及摘要',
  privacy_full_policy: '完整版隐私政策及摘要',
  privacy_personal_info_list: '个人信息收集清单',
  privacy_third_party_list: '第三方信息共享清单',

  // --- Profile Privacy Page ---
  profile_privacy_title: '个人主页',
  profile_privacy_edit_profile: '编辑个人资料',
  profile_privacy_display_modules: '展示模块',
  profile_privacy_shelf: '书架',
  profile_privacy_liked_books: '喜好的书',
  profile_privacy_book_lists: '书单',
  profile_privacy_badges: '勋章',
  profile_privacy_thoughts: '想法',
  profile_privacy_visibility: '可见范围',
  profile_privacy_self_only: '仅自己可见',
  profile_privacy_mutual_only: '互关可见',
  profile_privacy_followers_only: '关注我的人可见',
  profile_privacy_everyone: '所有人可见',

  // --- Notifications Page ---
  notifications_title: '通知',
  notifications_new_follower: '接收新关注提醒',
  notifications_new_follower_desc: '关闭后，其他用户关注你时，将不再通知你',
  notifications_wechat_friend: '接收微信朋友新加入提醒',
  notifications_wechat_friend_desc: '关闭后，有新的微信朋友加入微信读书，将不再通知你',
  notifications_activity_welfare: '接收活动福利私信提醒',
  notifications_activity_welfare_desc: '关闭后，有新的免费活动或福利时，将不再通过私信通知你。',

  // --- Common / Shared ---
  common_cancel: '取消',
  common_minutes_unit: '分钟',
  common_person_unit: '人',
  common_unit_ge: '个',
  common_wan: '万',
  common_wan_zi: '万字',
  common_zi: '字',
} as const;

export type StringKey = keyof typeof strings;
