import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  app_name: 'WeRead',

  // --- Tab Bar ---
  tab_reading: 'Reading',
  tab_bookshelf: 'Shelf',
  tab_audiobooks: 'Audiobooks',
  tab_me: 'Me',
  tab_book_friends: 'Friends',

  // --- Header / Search ---
  header_bookstore: 'Store',
  search_placeholder_default: 'Search books...',

  // --- Reading Page (Home) ---
  reading_hot_trend: '2025 Trending',
  reading_category: 'Categories',
  reading_ranking: 'Rankings',
  reading_book_list: 'Book Lists',
  reading_monthly_reading: 'Monthly Reading',
  reading_weekly_reading: 'This Week',
  reading_minutes: 'min',
  reading_more_ellipsis: 'More...',
  reading_recommended_for_you: 'Recommended for You',
  reading_refresh_batch: 'Refresh',
  reading_recommendation_value: 'Rec. Value',

  // --- Bookshelf Page ---
  bookshelf_title: 'Shelf',
  bookshelf_import: 'Import',
  bookshelf_select: 'Select',
  bookshelf_select_books: 'Select Books',
  bookshelf_selected_count: '{0} books selected',
  bookshelf_select_all: 'Select All',
  bookshelf_deselect_all: 'Deselect All',
  bookshelf_cancel: 'Cancel',
  bookshelf_sort_default: 'Default',
  bookshelf_sort_update: 'Updated',
  bookshelf_sort_progress: 'Progress',
  bookshelf_sort_recommendation: 'Rec. Value',
  bookshelf_sort_title: 'Title',
  bookshelf_sort_category: 'Category',
  bookshelf_public_reading: ' public',
  bookshelf_private_reading: ' private',
  bookshelf_view_public_page: 'View my public page',
  bookshelf_toolbar_private_reading: 'Private',
  bookshelf_toolbar_download: 'Download',
  bookshelf_toolbar_add_to_list: 'Add to List',
  bookshelf_toolbar_pin_top: 'Pin',
  bookshelf_toolbar_group_to: 'Group...',
  bookshelf_toolbar_remove: 'Remove',
  bookshelf_private_modal_title: 'Private Reading',
  bookshelf_private_modal_desc: 'After enabling, reading records for selected books will not be visible to others',
  bookshelf_private_modal_enable: 'Enable',
  bookshelf_remove_modal_title: 'Remove selected books from shelf?',
  bookshelf_remove_modal_confirm: 'Remove',

  // --- Search Page ---
  search_hot_list: 'Hot Search',
  search_more_rankings: 'More Rankings',
  search_tab_all: 'All',
  search_tab_ebook: 'E-books',
  search_tab_audiobook: 'Audiobooks',
  search_tab_fulltext: 'Full Text',
  search_tab_author: 'Authors',
  search_tab_book_list: 'Book Lists',
  search_author_section: 'Authors',
  search_more: 'More',
  search_ebook_section: 'E-books',
  search_audiobook_section: 'Audiobooks',
  search_no_result: 'No results found',

  // --- Category Pages ---
  category_list_title: 'Categories',
  category_sub_all: 'All',
  category_filter_word_count: 'Word Count',
  category_filter_payment_type: 'Payment Type',
  category_filter_popularity: 'Popularity',

  // --- Book Detail Page ---
  book_detail_paid: 'Paid',
  book_detail_listen: 'Listen',
  book_detail_top_chart: 'Top',
  book_detail_stat_reading: 'Readers',
  book_detail_stat_listening: 'Listens',
  book_detail_stat_person: '',
  book_detail_stat_times: ' plays',
  book_detail_friends_reading: '1 friend reading',
  book_detail_my_reading: 'My Reading',
  book_detail_my_listening: 'My Listening',
  book_detail_currently_reading: 'Reading',
  book_detail_currently_listening: 'Listening',
  book_detail_word_count: 'Words',
  book_detail_rating: 'Rating',
  book_detail_weread_recommendation: 'WeRead Recommendation',
  book_detail_write_review: 'Write Review',
  book_detail_masterpiece: 'Masterpiece',
  book_detail_recommend: 'Recommend',
  book_detail_average: 'Average',
  book_detail_not_recommend: 'Not Recommended',
  book_detail_tag_all: 'All',
  book_detail_tag_tragic_figures: 'Tragic figures',
  book_detail_tag_tears: 'In tears',
  book_detail_tag_plain_prose: 'Plain style',
  book_detail_published_date: 'Published Jul 2021',
  book_detail_person_review: ' reviews',
  book_detail_add_to_shelf: 'Add to Shelf',
  book_detail_added_to_shelf: 'On Shelf',
  book_detail_read_button: 'Read',
  book_detail_shelf_modal_private: 'Private Reading',
  book_detail_shelf_modal_download: 'Download',
  book_detail_shelf_modal_move: 'Move to...',
  book_detail_shelf_modal_remove: 'Remove from Shelf',
  book_detail_shelf_modal_cancel: 'Cancel',

  // --- Reader Page ---
  reader_added: 'Added',
  reader_add_to_shelf: 'Add to Shelf',
  reader_no_content: 'No content available',
  reader_intro: 'Introduction',
  reader_swipe_to_start: 'Swipe left to start reading',
  reader_membership_paid: 'Members only',
  reader_free: 'Free to read',
  reader_approx_finish: 'About 51 hours to finish',
  reader_reading_duration: 'Reading Time',
  reader_notes: 'Notes',
  reader_last_read_here: 'Last read here',
  reader_reading_detail: 'Reading Details',
  reader_auto_page_turn: 'Enable Auto Page Turn',
  reader_theme_color: 'Color',
  reader_theme_background: 'Background',
  reader_typography_margin_small: 'S',
  reader_typography_margin_label: 'Margin',
  reader_typography_margin_large: 'L',
  reader_typography_line_tight: 'Tight',
  reader_typography_line_label: 'Spacing',
  reader_typography_line_loose: 'Loose',
  reader_typography_font: 'Source Han Sans',
  reader_typography_indent: 'First Line Indent',
  reader_typography_page_turn: 'Page Turn',
  reader_shelf_modal_private: 'Private Reading',
  reader_shelf_modal_download: 'Download',
  reader_shelf_modal_move: 'Move to...',
  reader_shelf_modal_remove: 'Remove from Shelf',
  reader_shelf_modal_cancel: 'Cancel',

  // --- Audiobooks Page ---
  audiobooks_tab_audiobook: 'Audiobooks',
  audiobooks_tab_friends: 'Friends',
  audiobooks_search_category: 'Category',
  audiobooks_community_recommended: 'Recommended',
  audiobooks_community_following: 'Following',
  audiobooks_community_chat: 'Chat',
  audiobooks_community_topics: 'Topics',
  audiobooks_community_mine: 'Mine',
  audiobooks_recommended_for_you: 'Recommended for You',
  audiobooks_refresh_batch: 'Refresh',
  audiobooks_hot_chart: 'Hot Listening Chart',
  audiobooks_view_full_chart: 'View full chart',
  audiobooks_good_listen_value: 'Listen Rating',
  audiobooks_listens: ' listens',
  audiobooks_friends_tag: 'Friends',
  audiobooks_challenge_tag: '# 21-Day Reading Challenge',

  // --- Me Page ---
  me_badge: 'Badges',
  me_become_member: 'Become a Premium Member',
  me_first_month_deal: 'First month only 9 CNY/month',
  me_coins: 'Coins',
  me_balance: 'Balance',
  me_benefits: 'Benefits',
  me_benefits_detail: '0 days | Gift coins 40.00',
  me_reading_ranking: 'Reading Leaderboard',
  me_ranking_position: 'Rank #1',
  me_reading_duration: 'Reading Time',
  me_this_month: 'This month',
  me_reading: 'Reading',
  me_finished: 'Finished',
  me_cumulative: 'Total',
  me_books_unit: ' books',
  me_notes: 'Notes',
  me_no_notes: 'No notes yet',
  me_subscription: 'Subscriptions',
  me_not_published: 'Not published yet',
  me_book_lists: 'Book Lists',
  me_unit_ge: '',
  me_following: 'Following',
  me_followers_count: ' followers',
  me_following_count: 'Following {0} people',
  me_liked: 'Liked',
  me_no_likes: 'No likes yet',
  me_browsing_history: 'History',
  me_this_month_books: '4 books this month',
  me_web_version: 'Web Version',
  me_eink: 'E-ink',
  me_eink_desc: 'Designed for WeRead',

  // --- My Profile Page ---
  my_profile_title: 'My Profile',
  my_profile_followers_visible: 'Visible to followers',
  my_profile_reading_duration: 'Reading Time',
  my_profile_likes_received: 'Likes Received',
  my_profile_followers: 'Followers',
  my_profile_tab_shelf: 'Shelf',
  my_profile_tab_finished: 'Finished',
  my_profile_no_books: 'No books',
  my_profile_recent_activity: 'Started reading {0} 1 day ago',
  my_profile_view_shelf: 'View Shelf',
  my_profile_view_all: 'View All',

  // --- Edit Profile Page ---
  edit_profile_title: 'Edit Profile',
  edit_profile_avatar: 'Avatar',
  edit_profile_nickname: 'Nickname',
  edit_profile_nickname_placeholder: 'Enter nickname',
  edit_profile_gender: 'Gender',
  edit_profile_gender_hint: 'Displayed publicly and used for personalized book recommendations',
  edit_profile_introduction: 'About Me',
  edit_profile_introduction_placeholder: 'Share your profession or hobbies',
  edit_profile_signature: 'Signature',
  edit_profile_signature_placeholder: 'Enter signature',

  // --- Gender Selection Page ---
  gender_title: 'Select Gender',
  gender_done: 'Done',
  gender_male: 'Male',
  gender_female: 'Female',

  // --- Following Page ---
  following_tab_following: 'Following',
  following_tab_followers: 'Followers',
  following_wechat_friends: 'WeChat Friends',
  following_count: 'Following {0} people',
  following_status_followed: 'Following',
  following_no_followers: 'No followers yet',

  // --- Wechat Friends Page ---
  wechat_friends_title: 'WeChat Friends',
  wechat_friends_select: 'Select',
  wechat_friends_follow: 'Follow',
  wechat_friends_reading_time: 'Read {0}',
  wechat_friends_reading_hours_minutes: '{0}h {1}min',
  wechat_friends_reading_minutes: '{0}min',
  wechat_friends_currently_reading: 'She is reading…',

  // --- User Profile Page ---
  user_profile_personal_page: 'Profile',
  user_profile_wechat_friend: 'WeChat Friend',
  user_profile_reading_duration: 'Reading Time',
  user_profile_likes_received: 'Likes Received',
  user_profile_followers: 'Followers',
  user_profile_followed: 'Following',
  user_profile_follow: 'Follow',
  user_profile_badges_title: 'Badges Earned',
  user_profile_badges_count: '16 badges earned',
  user_profile_bookshelf_title: 'Bookshelf',
  user_profile_recent_activity: 'Started reading {0} 5 years ago',
  user_profile_view_shelf: 'View Shelf',
  user_profile_unfollow_desc: 'After unfollowing, you will no longer receive updates from this user',
  user_profile_unfollow: 'Unfollow',
  user_profile_close: 'Close',

  // --- User Bookshelf Page ---
  user_bookshelf_shelf: 'Shelf',
  user_bookshelf_count: ' books',

  // --- Coins Page ---
  coins_title: 'Coins',
  coins_recharge: 'Top Up',
  coins_no_expire: 'Coins never expire and can be used for all content',
  coins_transactions: 'Transaction History',
  coins_purchase_books: 'Books purchased with coins or earned from events',
  coins_auto_purchase: 'Auto Purchase',

  // --- Transactions Page ---
  transactions_title: 'Transaction History',
  transactions_gift_record: 'Gift Records',
  transactions_type_gift_coins: 'Gift Coins',

  // --- My Reading Page ---
  my_reading_title: 'My Reading',
  my_reading_tab_week: 'Week',
  my_reading_tab_month: 'Month',
  my_reading_tab_year: 'Year',
  my_reading_tab_total: 'Total',
  my_reading_tab_history: 'History',
  my_reading_this_week: 'This Week',
  my_reading_this_month: 'This Month',
  my_reading_this_year: 'This Year',
  my_reading_daily_avg: 'Daily average',
  my_reading_friends_ranking: 'Friends Ranking',
  my_reading_rank_unit: '',
  my_reading_challenge: 'Reading Challenge',
  my_reading_challenge_desc: 'Win 365-day Premium Membership + 500 Coins',
  my_reading_go_challenge: 'Join',
  my_reading_duration_distribution: 'Reading Time Distribution',
  my_reading_no_record_week: 'No reading records this week',
  my_reading_no_record: 'No reading records',
  my_reading_longest_weekday: 'Read the most on {0}, {1} minutes',
  my_reading_longest_day: 'Read the most on day {0}, {1} minutes',
  my_reading_longest_month: 'Read the most in month {0}, {1} minutes',
  my_reading_calendar_title: 'Reading Days',
  my_reading_calendar_month: 'M',
  my_reading_calendar_year: 'Y',
  my_reading_cumulative_days: 'Days read',
  my_reading_cumulative_days_unit: ' days',
  my_reading_cumulative_minutes: '{0} minutes read',

  // --- Reading List Page ---
  reading_list_title: 'My Reading',
  reading_list_tab_all: 'All',
  reading_list_tab_reading: 'Reading',
  reading_list_tab_finished: 'Finished',
  reading_list_filter: 'Filter',
  reading_list_year_unit: '',
  reading_list_less_than: 'Less than',
  reading_list_read_to: 'Read to',
  reading_list_status_reading: 'Reading',
  reading_list_month_finished: ' finished',
  reading_list_month_started: ' started reading',
  reading_list_no_records: 'No reading records',

  // --- Book Lists Page ---
  book_lists_tab_my: 'My Book Lists ({0})',
  book_lists_tab_collected: 'Collected Book Lists',
  book_lists_section_liked_books: 'Liked Books',
  book_lists_liked_title: "{0}'s Liked Books",
  book_lists_add_books: 'Add Books',
  book_lists_my_lists_count_label: '{0} My Lists',
  book_lists_view_public_homepage: 'View My Public Homepage',
  book_lists_empty_collected: 'No collected book lists yet',
  book_lists_view_popular: 'View popular book lists',
  book_lists_edit_title: 'Edit Book List',
  book_lists_sync_to_home: 'Sync to homepage',
  book_lists_done: 'Done',
  book_lists_search_books: 'Search books',
  book_lists_shelf_section: 'Bookshelf',
  book_lists_recommendation_placeholder: 'Tap to write a recommendation…',
  book_lists_delete_book: 'Remove book',
  book_lists_add_books_done: 'Done',
  book_lists_nothing_to_add: 'No books available to add',

  // --- Settings Page ---
  settings_title: 'Settings',
  settings_no_auto_lock: 'Keep screen on while reading',
  settings_allow_landscape: 'Allow landscape while reading',
  settings_hide_thoughts: 'Hide others\' thoughts while reading',
  settings_show_time_battery: 'Show time and battery while reading',
  settings_volume_key_turn: 'Use volume keys to turn pages',
  settings_first_line_indent: 'First line indent',
  settings_click_left_next: 'Tap left side for next page',
  settings_block_web_novels: 'Block web novels in search and recommendations',
  settings_mix_audio: 'Allow simultaneous playback with other apps',
  settings_auto_download: 'Auto download when added to shelf',
  settings_page_turn_style: 'Page Turn Style',
  settings_dark_mode: 'Dark Mode',
  settings_dark_mode_follow_system: 'Follow System',
  settings_dark_mode_enabled: 'Enabled',
  settings_dark_mode_disabled: 'Disabled',
  settings_privacy: 'Privacy',
  settings_student_auth: 'Student Verification',
  settings_student_auth_desc: 'Get exclusive badges and membership',
  settings_teen_mode: 'Teen Mode',
  settings_teen_mode_status: 'Disabled',
  settings_notifications: 'Notifications',
  settings_login_devices: 'Login Devices',
  settings_clear_cache: 'Clear Cache',
  settings_publish_on_weread: 'Publish on WeRead',
  settings_publish_desc: 'Submit manuscripts',
  settings_business_cooperation: 'Business Cooperation',
  settings_about_weread: 'About WeRead',
  settings_follow_wechat_account: 'Follow WeChat Account',
  settings_help_feedback: 'Help & Feedback',
  settings_logout: 'Log Out',

  // --- Auto Download Page ---
  auto_download_title: 'Auto Download on Add to Shelf',
  auto_download_member_only: 'Auto download is a premium feature',
  auto_download_upgrade: 'Upgrade',
  auto_download_intro: 'After enabling "Auto Download on Add to Shelf":',
  auto_download_rule_1: 'Books added to shelf will be downloaded automatically.',
  auto_download_rule_2: 'Books on shelf but not downloaded will auto-download on next read.',
  auto_download_rule_3: 'When storage is full, downloading new content will clean up least recently read books.',
  auto_download_rule_4: 'Per-chapter purchases, audiobooks, and large books (200MB+) still require manual download.',
  auto_download_rule_5: 'Books batch-added via book lists still require manual download.',

  // --- Page Turn Style Page ---
  page_turn_title: 'Page Turn Style',
  page_turn_simulation: 'Simulation',
  page_turn_swipe: 'Swipe Left/Right',
  page_turn_scroll: 'Scroll Up/Down',
  page_turn_cover: 'Cover',

  // --- Dark Mode Page ---
  dark_mode_title: 'Dark Mode',
  dark_mode_follow_system: 'Follow System',
  dark_mode_follow_system_desc: 'When enabled, dark mode will follow system settings',
  dark_mode_manual_select: 'Manual Selection',
  dark_mode_light: 'Light',
  dark_mode_dark: 'Dark',

  // --- Privacy Page ---
  privacy_title: 'Privacy',
  privacy_personal_page: 'Profile Page',
  privacy_require_follow_request: 'Approve follow requests',
  privacy_require_follow_request_desc: 'When enabled, only approved users can follow you',
  privacy_hide_vip_global: 'Hide premium member status globally',
  privacy_hide_vip_global_desc: 'When enabled, premium member status is hidden for both you and others',
  privacy_auto_private_reading: 'Auto-enable private reading on add to shelf',
  privacy_auto_private_reading_desc: 'Books with private reading enabled will not show reading activity publicly',
  privacy_shelf_replacement: 'Stand-in Shelf',
  privacy_shelf_replacement_desc: 'When enabled, a stand-in shelf will replace your real shelf in your profile. Others can only see...',
  privacy_reject_stranger_msg: 'Block messages from non-followers',
  privacy_blacklist: 'Blocked Users',
  privacy_wechat_articles: 'WeChat Articles',
  privacy_account: 'Account',
  privacy_close_personalized_rec: 'Disable personalized recommendations',
  privacy_close_reading_rank: 'Disable reading leaderboard',
  privacy_get_account_copy: 'Get account data copy',
  privacy_basic_policy: 'Basic Privacy Policy Summary',
  privacy_full_policy: 'Full Privacy Policy Summary',
  privacy_personal_info_list: 'Personal Info Collection List',
  privacy_third_party_list: 'Third-party Data Sharing List',

  // --- Profile Privacy Page ---
  profile_privacy_title: 'Profile Page',
  profile_privacy_edit_profile: 'Edit Profile',
  profile_privacy_display_modules: 'Display Modules',
  profile_privacy_shelf: 'Bookshelf',
  profile_privacy_liked_books: 'Liked Books',
  profile_privacy_book_lists: 'Book Lists',
  profile_privacy_badges: 'Badges',
  profile_privacy_thoughts: 'Thoughts',
  profile_privacy_visibility: 'Visibility',
  profile_privacy_self_only: 'Only Me',
  profile_privacy_mutual_only: 'Mutual Followers',
  profile_privacy_followers_only: 'Followers Only',
  profile_privacy_everyone: 'Everyone',

  // --- Notifications Page ---
  notifications_title: 'Notifications',
  notifications_new_follower: 'New follower notifications',
  notifications_new_follower_desc: 'When disabled, you won\'t be notified when others follow you',
  notifications_wechat_friend: 'New WeChat friend join notifications',
  notifications_wechat_friend_desc: 'When disabled, you won\'t be notified when WeChat friends join WeRead',
  notifications_activity_welfare: 'Activity & welfare notifications',
  notifications_activity_welfare_desc: 'When disabled, you won\'t receive direct messages about free activities or benefits.',

  // --- Common / Shared ---
  common_cancel: 'Cancel',
  common_minutes_unit: 'min',
  common_person_unit: '',
  common_unit_ge: '',
  common_wan: '0k',
  common_wan_zi: '0k words',
  common_zi: ' words',
};
