import type { NavigationDeclaration, ScrollContainerDeclaration } from './navigation.types';

// X 当前仅需要一个统一主滚动容器命名（与 Wechat 对齐）。
// 注意：同名容器在 __getScrollMeta__ 里会覆盖，因此要求“同一时刻仅一个可见 main”。
const MAIN_SCROLL: ScrollContainerDeclaration[] = [
  { name: 'main', direction: 'vertical', description: '主内容区' },
];

const POST_ACTIONS = [
  { id: 'post.item.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
  { id: 'post.item.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
  { id: 'post.item.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
  { id: 'post.item.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
  { id: 'user.item.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
] as const;

export const NAVIGATION_DECLARATION = {
  app: 'x',

  routes: [
    // =========================
    // Main Tabs（主 TabBar 用独立 pathname 区分）
    // =========================
    {
      path: '/',
      component: 'HomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'home.tab.foryou',
          search: { tab: 'foryou' },
          description: '首页-为你推荐信息流',
          actions: [
            { id: 'home.foryou.post.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'home.foryou.post.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'home.foryou.post.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'home.foryou.post.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'home.foryou.user.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
          ],
        },
        {
          id: 'home.tab.following',
          search: { tab: 'following' },
          description: '首页-正在关注信息流',
          actions: [
            { id: 'home.following.post.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'home.following.post.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'home.following.post.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'home.following.post.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'home.following.user.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
          ],
        },
        { id: 'home.tab.foryou.menu.drawer', search: { tab: 'foryou', menu: 'drawer' }, description: '首页-为你推荐-侧边栏' },
        { id: 'home.tab.following.menu.drawer', search: { tab: 'following', menu: 'drawer' }, description: '首页-正在关注-侧边栏' },
      ],
      queryParams: {},
      description: '首页',
    },
    {
      path: '/search',
      component: 'SearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'search.tab.foryou',
          search: { tab: 'foryou' },
          description: '搜索-为你推荐',
          actions: [
            { id: 'search.foryou.post.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.foryou.post.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.foryou.post.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.foryou.post.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.foryou.user.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
          ],
        },
        {
          id: 'search.tab.trending',
          search: { tab: 'trending' },
          description: '搜索-当前趋势',
          actions: [
            { id: 'search.trending.post.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.trending.post.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.trending.post.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.trending.post.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.trending.user.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
          ],
        },
        {
          id: 'search.tab.news',
          search: { tab: 'news' },
          description: '搜索-新闻',
          actions: [
            { id: 'search.news.post.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.news.post.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.news.post.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.news.post.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.news.user.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
          ],
        },
        {
          id: 'search.tab.sports',
          search: { tab: 'sports' },
          description: '搜索-体育',
          actions: [
            { id: 'search.sports.post.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.sports.post.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.sports.post.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.sports.post.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.sports.user.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
          ],
        },
        {
          id: 'search.tab.entertainment',
          search: { tab: 'entertainment' },
          description: '搜索-娱乐',
          actions: [
            { id: 'search.entertainment.post.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.entertainment.post.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.entertainment.post.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.entertainment.post.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.entertainment.user.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
          ],
        },
        { id: 'search.tab.foryou.menu.drawer', search: { tab: 'foryou', menu: 'drawer' }, description: '搜索-为你推荐-侧边栏' },
        { id: 'search.tab.trending.menu.drawer', search: { tab: 'trending', menu: 'drawer' }, description: '搜索-当前趋势-侧边栏' },
        { id: 'search.tab.news.menu.drawer', search: { tab: 'news', menu: 'drawer' }, description: '搜索-新闻-侧边栏' },
        { id: 'search.tab.sports.menu.drawer', search: { tab: 'sports', menu: 'drawer' }, description: '搜索-体育-侧边栏' },
        { id: 'search.tab.entertainment.menu.drawer', search: { tab: 'entertainment', menu: 'drawer' }, description: '搜索-娱乐-侧边栏' },
      ],
      queryParams: {},
      description: '搜索',
    },
    {
      path: '/search/input',
      component: 'SearchInputPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'searchInput.base',
          search: {},
          description: '搜索输入页',
          actions: [
            {
              id: 'search.query.input',
              label: '输入搜索关键字',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            { id: 'search.post.like', label: '搜索结果-点赞帖子', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.post.retweet', label: '搜索结果-转发帖子', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'search.post.bookmark', label: '搜索结果-书签帖子', behavior: 'submit', paramsSchema: { id: 'string' } },
          ],
        },
      ],
      queryParams: {},
      description: '搜索输入页',
    },
    {
      path: '/grok',
      component: 'GrokPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'grok.base',
          search: {},
          description: 'Grok-对话首页',
          actions: [
            {
              id: 'grok.prompt.input',
              label: '输入提问内容',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            { id: 'grok.mode.open', label: '打开模式选择', behavior: 'toggle' },
            { id: 'grok.history.open', label: '打开历史记录', behavior: 'submit' },
            { id: 'grok.chat.new', label: '新建对话', behavior: 'submit' },
            { id: 'grok.quick.createImage', label: '创建图片', behavior: 'submit' },
            { id: 'grok.quick.editImage', label: '编辑图片', behavior: 'submit' },
            { id: 'grok.quick.voiceMode', label: '进入语音模式', behavior: 'submit' },
            { id: 'grok.file.attach', label: '添加附件', behavior: 'submit' },
            {
              id: 'grok.message.send',
              label: '发送消息',
              behavior: 'submit',
              paramsSchema: { content: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: 'Grok',
    },
    {
      path: '/notifications',
      component: 'NotificationsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'notifications.tab.all', search: { tab: 'all' }, description: '通知-全部' },
        { id: 'notifications.tab.verified', search: { tab: 'verified' }, description: '通知-已认证' },
        { id: 'notifications.tab.mentions', search: { tab: 'mentions' }, description: '通知-提及' },
      ],
      queryParams: {},
      description: '通知',
    },
    {
      path: '/messages',
      component: 'MessagesPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'messages.tab.all', search: { tab: 'all' }, description: '消息-全部' },
        { id: 'messages.tab.unread', search: { tab: 'unread' }, description: '消息-未读' },
        { id: 'messages.tab.groups', search: { tab: 'groups' }, description: '消息-群组' },
        { id: 'messages.tab.requests', search: { tab: 'requests' }, description: '消息-请求' },
      ],
      queryParams: {},
      description: '消息',
    },

    // =========================
    // Sub Pages（子页面）
    // =========================
    {
      path: '/profile',
      component: 'ProfilePage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'profile.base',
          search: {},
          description: '个人主页',
           actions: [
             { id: 'profile.post.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
             { id: 'profile.post.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
             { id: 'profile.post.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
             { id: 'profile.post.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
             { id: 'profile.user.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
           ],
         },
       ],
       queryParams: {},
       description: '个人主页',
    },
    {
       path: '/user/:id',
       component: 'UserProfilePage',
       params: { id: 'string' },
       entryPoint: 'deepLink',
       scrollContainers: MAIN_SCROLL,
       uiStates: [
         {
           id: 'userProfile.base',
           search: {},
           description: '用户主页',
           actions: [
             { id: 'userProfile.post.retweet', label: '转发推文', behavior: 'submit', paramsSchema: { id: 'string' } },
             { id: 'userProfile.post.like', label: '点赞推文', behavior: 'submit', paramsSchema: { id: 'string' } },
             { id: 'userProfile.post.share', label: '分享推文', behavior: 'submit', paramsSchema: { id: 'string' } },
             { id: 'userProfile.post.bookmark', label: '书签推文', behavior: 'submit', paramsSchema: { id: 'string' } },
             { id: 'userProfile.user.follow', label: '关注用户', behavior: 'submit', paramsSchema: { id: 'string' } },
           ],
         },
       ],
      queryParams: {},
      description: '用户主页',
    },
    {
      path: '/reply/:id',
      component: 'ReplyPage',
      params: { id: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'reply.base',
          search: {},
          description: '回复编辑页',
          actions: [
            {
              id: 'reply.content.input',
              label: '输入回复内容',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'reply.post.submit',
              label: '发布回复',
              behavior: 'submit',
              paramsSchema: { postId: 'string', content: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '回复',
    },
    {
      path: '/compose',
      component: 'ComposePage',
      params: {},
      entryPoint: 'deepLink',
      scrollContainers: [],
      uiStates: [
        {
          id: 'compose.base',
          search: {},
          description: '发布帖子',
          actions: [
            {
              id: 'compose.content.input',
              label: '输入帖子内容',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'compose.post.submit',
              label: '发布帖子',
              behavior: 'submit',
              paramsSchema: { content: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '发布',
    },
    {
      path: '/messages/:id',
      component: 'ChatPage',
      params: { id: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'chat.base',
          search: {},
          description: '聊天详情',
          actions: [
            {
              id: 'chat.message.input',
              label: '输入私信内容',
              behavior: 'input',
              paramsSchema: { value: 'string' },
            },
            {
              id: 'chat.message.send',
              label: '发送私信',
              behavior: 'submit',
              paramsSchema: { conversationId: 'string', content: 'string' },
            },
          ],
        },
      ],
      queryParams: {},
      description: '聊天详情',
    },
    {
      path: '/connections/:id',
      component: 'UserConnectionsPage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'connections.tab.following', search: { type: 'following' }, description: '正在关注列表' },
        { id: 'connections.tab.followers', search: { type: 'followers' }, description: '关注者列表' },
      ],
      queryParams: {},
      description: '关注/关注者列表',
    },

    // =========================
    // Post Details & Activity
    // =========================
    {
      path: '/status/:id',
      component: 'PostDetailsPage',
      params: { id: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        {
          id: 'status.base',
          search: {},
          description: '帖子详情',
          actions: [
            ...POST_ACTIONS,
            { id: 'status.post.like', label: '点赞帖子', behavior: 'submit', paramsSchema: { id: 'string' } },
            { id: 'status.post.bookmark', label: '书签帖子', behavior: 'submit', paramsSchema: { id: 'string' } },
          ],
        },
      ],
      queryParams: {},
      description: '帖子详情',
    },
    {
      path: '/status/:id/activity',
      component: 'PostActivityPage',
      params: { id: 'string' },
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [
        { id: 'status.activity.tab.quotes', search: { tab: 'quotes' }, description: '帖子活动-引用' },
        { id: 'status.activity.tab.retweets', search: { tab: 'retweets' }, description: '帖子活动-转帖' },
      ],
      queryParams: {},
      description: '帖子活动',
    },

    // =========================
    // Settings Tree
    // =========================
    {
      path: '/settings',
      component: 'SettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.base', search: {}, description: '设置主页' }],
      queryParams: {},
      description: '设置',
    },
    {
      path: '/settings/account',
      component: 'SettingsAccountPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.account.base', search: {}, description: '账号设置' }],
      queryParams: {},
      description: '账号设置',
    },
    {
      path: '/settings/account/info',
      component: 'SettingsAccountInfoPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.account.info.base', search: {}, description: '账号信息' }],
      queryParams: {},
      description: '账号信息',
    },
    {
      path: '/settings/privacy',
      component: 'SettingsPrivacyPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.privacy.base', search: {}, description: '隐私和安全' }],
      queryParams: {},
      description: '隐私和安全',
    },
    {
      path: '/settings/privacy/audience',
      component: 'SettingsPrivacyAudiencePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.privacy.audience.base', search: {}, description: '受众和圈人' }],
      queryParams: {},
      description: '受众和圈人',
    },
    {
      path: '/settings/privacy/your-posts',
      component: 'SettingsPrivacyYourPostsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.privacy.yourPosts.base', search: {}, description: '你的帖子' }],
      queryParams: {},
      description: '你的帖子',
    },
    {
      path: '/settings/privacy/chat',
      component: 'SettingsPrivacyChatPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.privacy.chat.base', search: {}, description: '聊天隐私' }],
      queryParams: {},
      description: '聊天隐私',
    },
    {
      path: '/settings/privacy/space',
      component: 'SettingsPrivacySpacePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.privacy.space.base', search: {}, description: '空间隐私' }],
      queryParams: {},
      description: '空间隐私',
    },
    {
      path: '/settings/privacy/find-contacts',
      component: 'SettingsPrivacyFindContactsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.privacy.findContacts.base', search: {}, description: '联系人隐私' }],
      queryParams: {},
      description: '联系人隐私',
    },
    {
      path: '/settings/privacy/about-account',
      component: 'SettingsPrivacyAboutAccountPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.privacy.aboutAccount.base', search: {}, description: '关于你的账号' }],
      queryParams: {},
      description: '关于你的账号',
    },
    {
      path: '/settings/privacy/seen',
      component: 'SettingsSeenContentPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.seen.base', search: {}, description: '你看到的内容' }],
      queryParams: {},
      description: '你看到的内容',
    },
    {
      path: '/settings/privacy/seen/explore',
      component: 'SettingsSeenExplorePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.seen.explore.base', search: {}, description: '探索设置' }],
      queryParams: {},
      description: '探索设置',
    },
    {
      path: '/settings/notifications',
      component: 'SettingsNotificationsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.notifications.base', search: {}, description: '通知设置' }],
      queryParams: {},
      description: '通知设置',
    },
    {
      path: '/settings/notifications/preferences',
      component: 'SettingsNotificationPreferencesPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.notifications.preferences.base', search: {}, description: '通知偏好设置' }],
      queryParams: {},
      description: '通知偏好设置',
    },
    {
      path: '/settings/notifications/preferences/push',
      component: 'SettingsNotificationPushPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.notifications.preferences.push.base', search: {}, description: '推送通知设置' }],
      queryParams: {},
      description: '推送通知设置',
    },
    {
      path: '/settings/notifications/filter',
      component: 'SettingsNotificationFilterPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.notifications.filter.base', search: {}, description: '通知过滤器' }],
      queryParams: {},
      description: '通知过滤器',
    },
    {
      path: '/settings/timeline',
      component: 'SettingsTimelinePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.timeline.base', search: {}, description: '时间线设置' }],
      queryParams: {},
      description: '时间线设置',
    },
    {
      path: '/settings/timeline/interactions',
      component: 'SettingsTimelineInteractionsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.timeline.interactions.base', search: {}, description: '帖子互动设置' }],
      queryParams: {},
      description: '帖子互动设置',
    },
    {
      path: '/settings/timeline/home-tags',
      component: 'SettingsTimelineHomeTagsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'settings.timeline.homeTags.base', search: {}, description: '"主页"标签设置' }],
      queryParams: {},
      description: '"主页"标签设置',
    },
  ],

  transitions: [
    // =========================
    // Bottom Tab Bar
    // =========================
    {
      id: 'tab.home',
      from: ['*'],
      to: '/',
      search: { tab: 'foryou' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到首页',
      ui: { placement: 'tabbar', icon: 'tab_home', gesture: 'tap' },
    },
    {
      id: 'tab.search',
      from: ['*'],
      to: '/search',
      search: { tab: 'foryou' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到搜索',
      ui: { placement: 'tabbar', icon: 'tab_search', gesture: 'tap' },
    },
    {
      id: 'tab.grok',
      from: ['*'],
      to: '/grok',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到 Grok',
      ui: { placement: 'tabbar', icon: 'tab_grok', gesture: 'tap' },
    },
    {
      id: 'tab.notifications',
      from: ['*'],
      to: '/notifications',
      search: { tab: 'all' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到通知',
      ui: { placement: 'tabbar', icon: 'tab_notifications', gesture: 'tap' },
    },
    {
      id: 'tab.messages',
      from: ['*'],
      to: '/messages',
      search: { tab: 'all' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到消息',
      ui: { placement: 'tabbar', icon: 'tab_messages', gesture: 'tap' },
    },

    // =========================
    // Home: 内部信息流 Tab（为你推荐 / 正在关注）
    // =========================
    {
      id: 'home.feed.tab.toForyou',
      from: { path: '/', search: { tab: '*' } },
      to: '/',
      search: { tab: 'foryou' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到为你推荐',
      ui: { placement: 'content', icon: 'home_tab_foryou', gesture: 'tap' },
    },
    {
      id: 'home.feed.tab.toFollowing',
      from: { path: '/', search: { tab: '*' } },
      to: '/',
      search: { tab: 'following' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换到正在关注',
      ui: { placement: 'content', icon: 'home_tab_following', gesture: 'tap' },
    },

    // =========================
    // Search: 顶部分类 Tab
    // =========================
    {
      id: 'search.tab.toForyou',
      from: { path: '/search', search: { tab: '*' } },
      to: '/search',
      search: { tab: 'foryou' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换搜索到为你推荐',
      ui: { placement: 'content', icon: 'search_tab_foryou', gesture: 'tap' },
    },
    {
      id: 'search.tab.toTrending',
      from: { path: '/search', search: { tab: '*' } },
      to: '/search',
      search: { tab: 'trending' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换搜索到当前趋势',
      ui: { placement: 'content', icon: 'search_tab_trending', gesture: 'tap' },
    },
    {
      id: 'search.tab.toNews',
      from: { path: '/search', search: { tab: '*' } },
      to: '/search',
      search: { tab: 'news' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换搜索到新闻',
      ui: { placement: 'content', icon: 'search_tab_news', gesture: 'tap' },
    },
    {
      id: 'search.tab.toSports',
      from: { path: '/search', search: { tab: '*' } },
      to: '/search',
      search: { tab: 'sports' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换搜索到体育',
      ui: { placement: 'content', icon: 'search_tab_sports', gesture: 'tap' },
    },
    {
      id: 'search.tab.toEntertainment',
      from: { path: '/search', search: { tab: '*' } },
      to: '/search',
      search: { tab: 'entertainment' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换搜索到娱乐',
      ui: { placement: 'content', icon: 'search_tab_entertainment', gesture: 'tap' },
    },
    {
      id: 'search.input.open',
      from: { path: '/search', search: { tab: '*' } },
      to: '/search/input',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开搜索输入页',
      ui: { placement: 'topbar', icon: 'search_bar', gesture: 'tap' },
    },
    {
      id: 'home.drawer.open',
      from: { path: '/', search: { tab: '*' } },
      to: '/',
      search: { menu: 'drawer' },
      searchParams: {},
      preserveParams: ['tab'],
      mode: 'push',
      params: {},
      label: '打开侧边栏',
      ui: { placement: 'topbar', icon: 'drawer', gesture: 'tap' },
    },
    {
      id: 'search.drawer.open',
      from: { path: '/search', search: { tab: '*' } },
      to: '/search',
      search: { menu: 'drawer' },
      searchParams: {},
      preserveParams: ['tab'],
      mode: 'push',
      params: {},
      label: '打开侧边栏',
      ui: { placement: 'topbar', icon: 'drawer', gesture: 'tap' },
    },
    {
      id: 'grok.drawer.open',
      from: '/grok',
      to: '/grok',
      search: { menu: 'drawer' },
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开侧边栏',
      ui: { placement: 'topbar', icon: 'drawer', gesture: 'tap' },
    },
    {
      id: 'notifications.drawer.open',
      from: { path: '/notifications', search: { tab: '*' } },
      to: '/notifications',
      search: { menu: 'drawer' },
      searchParams: {},
      preserveParams: ['tab'],
      mode: 'push',
      params: {},
      label: '打开侧边栏',
      ui: { placement: 'topbar', icon: 'drawer', gesture: 'tap' },
    },
    {
      id: 'messages.drawer.open',
      from: { path: '/messages', search: { tab: '*' } },
      to: '/messages',
      search: { menu: 'drawer' },
      searchParams: {},
      preserveParams: ['tab'],
      mode: 'push',
      params: {},
      label: '打开侧边栏',
      ui: { placement: 'topbar', icon: 'drawer', gesture: 'tap' },
    },
    {
      id: 'user.open.fromSearch',
      from: '/search/input',
      to: '/user/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开用户主页',
      ui: { placement: 'content', icon: 'user', gesture: 'tap' },
    },
    {
      id: 'user.open.fromPost',
      from: [{ path: '/', search: { tab: '*' } }, '/reply/:id', '/status/:id', { path: '/status/:id/activity', search: { tab: '*' } }, '/profile', '/user/:id', { path: '/connections/:id', search: { type: 'following' } }, { path: '/connections/:id', search: { type: 'followers' } }, '/search/input'],
      to: '/user/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开用户主页',
      ui: { placement: 'content', icon: 'user_avatar', gesture: 'tap' },
    },
    {
      id: 'user.follow',
      from: [{ path: '/', search: { tab: '*' } }, '/user/:id'],
      to: '/user/:id',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: { id: 'string' },
      label: '关注/取消关注用户',
      ui: { placement: 'content', icon: 'follow', gesture: 'tap' },
    },
    {
      id: 'connections.open',
      from: ['/user/:id', '/profile'],
      to: '/connections/:id',
      search: {},
      searchParams: { type: 'string' },
      mode: 'push',
      params: { id: 'string' },
      label: '查看关注/关注者列表',
      ui: { placement: 'content', icon: 'connections', gesture: 'tap' },
    },
    {
      id: 'connections.tab.toFollowing',
      from: { path: '/connections/:id', search: { type: 'followers' } },
      to: '/connections/:id',
      search: { type: 'following' },
      searchParams: {},
      mode: 'replace',
      params: { id: 'string' },
      label: '切换到正在关注',
      ui: { placement: 'content', icon: 'connections_following', gesture: 'tap' },
    },
    {
      id: 'connections.tab.toFollowers',
      from: { path: '/connections/:id', search: { type: 'following' } },
      to: '/connections/:id',
      search: { type: 'followers' },
      searchParams: {},
      mode: 'replace',
      params: { id: 'string' },
      label: '切换到关注者',
      ui: { placement: 'content', icon: 'connections_followers', gesture: 'tap' },
    },
    {
      id: 'reply.open',
      from: [{ path: '/', search: { tab: '*' } }, '/status/:id', '/search/input', '/profile', '/user/:id'],
      to: '/reply/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开回复编辑页',
      ui: { placement: 'content', icon: 'reply', gesture: 'tap' },
    },
    {
      id: 'post.open',
      from: [{ path: '/', search: { tab: '*' } }, '/user/:id', '/profile', '/search/input'],
      to: '/status/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '查看推文详情',
      ui: { placement: 'content', icon: 'post', gesture: 'tap' },
    },
    {
      id: 'trend.open',
      from: { path: '/search', search: { tab: '*' } },
      to: '/search/input',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '查看趋势详情',
      ui: { placement: 'content', icon: 'trend', gesture: 'tap' },
    },

    // =========================
    // Notifications: 内部 Tab（全部 / 已认证 / 提及）
    // =========================
    {
      id: 'notifications.tab.toAll',
      from: { path: '/notifications', search: { tab: '*' } },
      to: '/notifications',
      search: { tab: 'all' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换通知到全部',
      ui: { placement: 'content', icon: 'notifications_tab_all', gesture: 'tap' },
    },
    {
      id: 'notifications.tab.toVerified',
      from: { path: '/notifications', search: { tab: '*' } },
      to: '/notifications',
      search: { tab: 'verified' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换通知到已认证',
      ui: { placement: 'content', icon: 'notifications_tab_verified', gesture: 'tap' },
    },
    {
      id: 'notifications.tab.toMentions',
      from: { path: '/notifications', search: { tab: '*' } },
      to: '/notifications',
      search: { tab: 'mentions' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换通知到提及',
      ui: { placement: 'content', icon: 'notifications_tab_mentions', gesture: 'tap' },
    },

    // =========================
    // Messages: 内部 Tab（全部 / 未读 / 群组 / 请求）
    // =========================
    {
      id: 'messages.tab.toAll',
      from: { path: '/messages', search: { tab: '*' } },
      to: '/messages',
      search: { tab: 'all' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换消息到全部',
      ui: { placement: 'content', icon: 'messages_tab_all', gesture: 'tap' },
    },
    {
      id: 'messages.tab.toUnread',
      from: { path: '/messages', search: { tab: '*' } },
      to: '/messages',
      search: { tab: 'unread' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换消息到未读',
      ui: { placement: 'content', icon: 'messages_tab_unread', gesture: 'tap' },
    },
    {
      id: 'messages.tab.toGroups',
      from: { path: '/messages', search: { tab: '*' } },
      to: '/messages',
      search: { tab: 'groups' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换消息到群组',
      ui: { placement: 'content', icon: 'messages_tab_groups', gesture: 'tap' },
    },
    {
      id: 'messages.tab.toRequests',
      from: { path: '/messages', search: { tab: '*' } },
      to: '/messages',
      search: { tab: 'requests' },
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '切换消息到请求',
      ui: { placement: 'content', icon: 'messages_tab_requests', gesture: 'tap' },
    },

    // =========================
    // Sub page opens
    // =========================
    {
      id: 'profile.open',
      from: [
        { path: '/', search: { tab: '*' } },
        { path: '/search', search: { tab: '*' } },
        '/grok',
        { path: '/notifications', search: { tab: '*' } },
        { path: '/messages', search: { tab: '*' } },
      ],
      to: '/profile',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开个人主页',
      ui: { placement: 'topbar', icon: 'avatar', gesture: 'tap' },
    },
    {
      id: 'compose.open',
      from: [
        { path: '/', search: { tab: '*' } },
        { path: '/search', search: { tab: '*' } },
        '/search/input',
        '/status/:id',
        '/profile',
        '/user/:id',
      ],
      to: '/compose',
      search: {},
      searchParams: { quotedPostId: 'string' },
      mode: 'push',
      params: {},
      label: '打开发布页',
      ui: { placement: 'fab', icon: 'compose', gesture: 'tap' },
    },
    {
      id: 'messages.conversation.open',
      from: { path: '/messages', search: { tab: '*' } },
      to: '/messages/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '打开对话详情',
      ui: { placement: 'content', icon: 'conversation_item', gesture: 'tap' },
      dataSource: { ref: 'conversations', paramMapping: { id: 'id' }, labelField: 'id' },
    },

    // =========================
    // Post Details & Activity
    // =========================
    {
      id: 'status.open',
      from: ['/status/:id', { path: '/status/:id/activity', search: { tab: '*' } }],
      to: '/status/:id',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '查看帖子详情',
      ui: { placement: 'content', icon: 'post', gesture: 'tap' },
    },
    {
      id: 'status.activity.open',
      from: ['/status/:id', { path: '/', search: { tab: '*' } }, '/search/input', '/profile', '/user/:id'],
      to: '/status/:id/activity',
      search: { tab: 'quotes' },
      searchParams: {},
      mode: 'push',
      params: { id: 'string' },
      label: '查看帖子活动',
      ui: { placement: 'content', icon: 'chart', gesture: 'tap' },
    },

    // =========================
    // Settings Tree
    // =========================
    {
      id: 'settings.open',
      from: ['*'],
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开设置',
      ui: { placement: 'drawer', icon: 'settings', gesture: 'tap' },
    },
    {
      id: 'settings.account.open',
      from: '/settings',
      to: '/settings/account',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开账号设置',
      ui: { placement: 'content', icon: 'settings_account', gesture: 'tap' },
    },
    {
      id: 'settings.account.info.open',
      from: '/settings/account',
      to: '/settings/account/info',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开账号信息',
      ui: { placement: 'content', icon: 'settings_account_info', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.open',
      from: '/settings',
      to: '/settings/privacy',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开隐私和安全',
      ui: { placement: 'content', icon: 'settings_privacy', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.audience.open',
      from: '/settings/privacy',
      to: '/settings/privacy/audience',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开受众和圈人设置',
      ui: { placement: 'content', icon: 'settings_privacy_audience', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.yourPosts.open',
      from: '/settings/privacy',
      to: '/settings/privacy/your-posts',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开你的帖子设置',
      ui: { placement: 'content', icon: 'settings_privacy_yourPosts', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.chat.open',
      from: '/settings/privacy',
      to: '/settings/privacy/chat',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开聊天隐私设置',
      ui: { placement: 'content', icon: 'settings_privacy_chat', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.space.open',
      from: '/settings/privacy',
      to: '/settings/privacy/space',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开空间隐私设置',
      ui: { placement: 'content', icon: 'settings_privacy_space', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.findContacts.open',
      from: '/settings/privacy',
      to: '/settings/privacy/find-contacts',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开联系人隐私设置',
      ui: { placement: 'content', icon: 'settings_privacy_findContacts', gesture: 'tap' },
    },
    {
      id: 'settings.privacy.aboutAccount.open',
      from: '/settings/privacy',
      to: '/settings/privacy/about-account',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开关于你的账号',
      ui: { placement: 'content', icon: 'settings_privacy_aboutAccount', gesture: 'tap' },
    },
    {
      id: 'settings.seen.open',
      from: '/settings/privacy',
      to: '/settings/privacy/seen',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开你看到的内容设置',
      ui: { placement: 'content', icon: 'settings_seen', gesture: 'tap' },
    },
    {
      id: 'settings.seen.explore.open',
      from: '/settings/privacy/seen',
      to: '/settings/privacy/seen/explore',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开探索设置',
      ui: { placement: 'content', icon: 'settings_seen_explore', gesture: 'tap' },
    },
    {
      id: 'settings.notifications.open',
      from: '/settings',
      to: '/settings/notifications',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开通知设置',
      ui: { placement: 'content', icon: 'settings_notifications', gesture: 'tap' },
    },
    {
      id: 'settings.notifications.preferences.open',
      from: '/settings/notifications',
      to: '/settings/notifications/preferences',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开通知偏好设置',
      ui: { placement: 'content', icon: 'settings_notifications_preferences', gesture: 'tap' },
    },
    {
      id: 'settings.notifications.preferences.push.open',
      from: '/settings/notifications/preferences',
      to: '/settings/notifications/preferences/push',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开推送通知设置',
      ui: { placement: 'content', icon: 'settings_notifications_push', gesture: 'tap' },
    },
    {
      id: 'settings.notifications.filter.open',
      from: '/settings/notifications',
      to: '/settings/notifications/filter',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开通知过滤器',
      ui: { placement: 'content', icon: 'settings_notifications_filter', gesture: 'tap' },
    },
    {
      id: 'settings.timeline.open',
      from: '/settings',
      to: '/settings/timeline',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开时间线设置',
      ui: { placement: 'content', icon: 'settings_timeline', gesture: 'tap' },
    },
    {
      id: 'settings.timeline.interactions.open',
      from: '/settings/timeline',
      to: '/settings/timeline/interactions',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开帖子互动设置',
      ui: { placement: 'content', icon: 'settings_timeline_interactions', gesture: 'tap' },
    },
    {
      id: 'settings.timeline.homeTags.open',
      from: '/settings/timeline',
      to: '/settings/timeline/home-tags',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开"主页"标签设置',
      ui: { placement: 'content', icon: 'settings_timeline_homeTags', gesture: 'tap' },
    },
  ],

  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
