import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  app_name: 'Spotify',

  // ── Bottom Tab Bar ──
  tab_home: 'Home',
  tab_search: 'Search',
  tab_library: 'Your Library',
  tab_premium: 'Premium',
  tab_create: 'Create',

  // ── Error / Fallback ──
  app_load_error: 'Spotify App loading error, please refresh the page',

  // ── Home Page tabs ──
  home_tab_all: 'All',
  home_tab_wrapped: 'Wrapped',
  home_tab_music: 'Music',
  home_tab_podcast: 'Podcasts',

  // ── Home Page sections ──
  home_personalized_subtitle: 'Experience playlists crafted for your music taste',
  home_section_start_listening: 'Start Listening',
  home_section_guess_you_like: 'Made For You',
  home_section_daily_picks: "Today's Picks",
  home_similar_artists_label: 'More like',
  home_type_album: 'Album',
  home_type_playlist: 'Playlist',
  home_section_charts: 'Charts',
  home_section_featured_charts: 'Featured Charts',
  home_section_recommended_artists: 'Recommended Artists',
  home_section_new_hot_selections: 'New Music Hot Picks',
  home_section_hottest_today: "Today's Hottest Singles",
  home_section_all_new_music: 'All New Music',
  home_section_party: 'Party',
  home_section_joyful: 'Joyful',
  home_section_sad_songs: 'Sad Songs',
  home_section_sing_along: 'Sing Along',
  home_section_trending_for_you: 'Trending Songs For You',
  home_section_chill: 'Chill',
  home_section_instrumentals: 'Instrumentals',

  // ── Home Page — Podcast tab ──
  home_podcast_hot: 'Popular Podcasts',
  home_podcast_listen_episode: 'Listen to Episode',

  // ── Home Page — Wrapped tab ──
  home_wrapped_top_artists_tracks: '2024 Top Artists and Tracks',
  home_wrapped_most_popular: 'Most Popular',
  home_wrapped_curated: 'Curated',
  home_wrapped_global_shows: '2025 Top Global Shows',

  // ── Search Page ──
  search_title: 'Search',
  search_placeholder: 'What do you want to listen to?',
  search_filter_songs: 'Songs',
  search_filter_playlists: 'Playlists',
  search_filter_albums: 'Albums',
  search_filter_podcasts: 'Podcasts',
  search_filter_videos: 'Videos',
  search_filter_artists: 'Artists',
  search_loading: 'Searching...',
  search_no_results: 'No results found',
  search_empty_title: 'Play what you love',
  search_empty_subtitle: 'Search for artists, songs, podcasts, and more.',
  search_result_album: 'Album',
  search_result_artist: 'Artist',
  search_result_song: 'Song',
  search_section_discover: 'Discover New Content',
  search_section_browse_all: 'Browse All',

  // ── Library Page ──
  library_title: 'Your Library',
  library_chip_playlist: 'Playlists',
  library_chip_artist: 'Artists',
  library_chip_creator_you: 'By you',
  library_sort_recent: 'Recently Played',
  library_import_music: 'Import your music from other apps',
  library_liked_songs: 'Liked Songs',
  library_playlist_count: 'Playlist \u2022 {count} songs',
  library_add_artist: 'Add Artist',
  library_subtitle_artist: 'Artist',
  library_add_artist_title: 'Choose more artists\nyou like.',
  library_add_artist_search: 'Search',
  library_add_artist_done: 'Done',

  // ── Player Page ──
  player_playing_from: 'Playing from Playlist',
  player_radio_suffix: 'Radio',
  player_queue_title: 'Queue',
  player_queue_now_playing: 'Now playing {artist} Radio',
  player_queue_up_next: 'Up Next',
  player_shuffle: 'Shuffle',
  player_repeat: 'Repeat',
  player_repeat_one: 'Repeat One',
  player_timer: 'Timer',
  player_sleep_timer: 'Sleep Timer',
  player_minutes: 'minutes',
  player_close_timer: 'Turn Off Timer',
  player_fade_music: 'Fade Out Music',
  player_fade_music_desc: 'Gradually lower volume when timer ends',

  // ── Playlist Page ──
  playlist_subtitle_artist: 'Artist',
  playlist_track_count: '{count} songs',
  playlist_duration_minutes: 'min',

  // ── Liked Songs Page ──
  liked_songs_title: 'Liked Songs',
  liked_songs_count: '{count} songs',
  liked_songs_join: 'Add to This Playlist',
  liked_songs_empty: "You haven't liked any songs yet.\nGo like some songs from the player!",

  // ── Create Page ──
  create_menu_title: 'Create Menu',
  create_invite_title: 'Invite friends to a Blend',
  create_invite_desc: 'Invite up to 10 friends to a Blend. A Blend is a shared playlist that gives social recommendations based on all your music tastes.',
  create_playlist: 'Playlist',
  create_playlist_desc: 'Create a playlist with songs or episodes',
  create_collaborative: 'Collaborative Playlist',
  create_collaborative_desc: 'Create a playlist with friends',
  create_blend: 'Blend',
  create_blend_desc: "Merge friends' music tastes into one playlist",
  create_add_podcast: 'Add Podcasts',
  create_naming_title: 'Name your playlist',
  create_naming_default: 'My Playlist',
  create_naming_error_exists: 'Playlist already exists',
  create_cancel: 'Cancel',
  create_submit: 'Create',

  // ── Artist Page ──
  artist_loading: 'Loading...',
  artist_monthly_listeners: '{count} monthly listeners',
  artist_following: 'Following',
  artist_popular: 'Popular',

  // ── Profile Page ──
  profile_followers_following: '{followers} followers \u2022 {following} following',
  profile_edit: 'Edit',
  profile_playlists: 'Playlists',
  profile_my_playlist: 'My Playlist 1',
  profile_saves_count: '{count} saves',

  // ── Premium Page ──
  premium_hero_title: 'Listen without limits. Try Premium Individual for HK$0 for 1 month via Spotify subscription.',
  premium_trial_button: 'Try 1 month for HK$0',
  premium_trial_desc: 'HK$0 for 1 month, then HK$78/month. Offer available only for users who are new to Premium and subscribe through Spotify. Offers via Google Play may differ. Terms apply.',
  premium_why_title: 'Why go Premium?',
  premium_feature_no_ads: 'Ad-free music listening',
  premium_feature_download: 'Download to listen offline',
  premium_feature_any_order: 'Play songs in any order',
  premium_feature_lossless: 'Lossless audio quality',
  premium_feature_listen_together: 'Listen with friends in real time',
  premium_feature_manage_queue: 'Manage your listening queue',
  premium_available_plans: 'Available Plans',
  premium_plan_terms: 'Terms apply. Offer valid only for first-time Premium users.',

  // ── Payment Page ──
  payment_checkout: 'Checkout',
  payment_change_plan: 'Change Plan',
  payment_billing_note_1: 'Billed monthly starting today.',
  payment_billing_note_2: 'Cancel online anytime.',
  payment_terms_link: 'Terms apply',
  payment_select_method: 'Select Payment Method',
  payment_method_desc: 'You can pay directly through Spotify or use your Google Play account.',
  payment_spotify_desc: 'Pay through Spotify using any supported payment method.',
  payment_continue_spotify: 'Continue with Spotify',
  payment_region: 'Hong Kong',
  payment_change_region: 'Change Country/Region',
  payment_per_month: '/mo',

  // ── Settings Page ──
  settings_title: 'Settings',
  settings_account: 'Account',
  settings_account_desc: 'Username \u2022 Close Account',
  settings_content_display: 'Content & Display',
  settings_content_display_desc: 'Canvas \u2022 "Create" Button',
  settings_playback: 'Playback',
  settings_playback_desc: 'Gapless \u2022 Autoplay',
  settings_privacy: 'Privacy Settings',
  settings_privacy_desc: 'Private Session \u2022 Public Playlists',
  settings_notifications: 'Notifications',
  settings_notifications_desc: 'Push \u2022 Email',
  settings_apps_devices: 'Apps & Devices',
  settings_apps_devices_desc: 'Google Maps \u2022 Spotify Connect',
  settings_data_saver: 'Data Saver & Offline',
  settings_data_saver_desc: 'Data Saver Mode \u2022 Download via Cellular',
  settings_media_quality: 'Media Quality',
  settings_media_quality_desc: 'Wi-Fi Streaming Quality \u2022 Audio Download Quality',
  settings_about: 'About & Support',
  settings_about_desc: 'Version \u2022 Privacy Policy',
  settings_logout: 'Log Out',

  // ── Settings > Account Page ──
  account_title: 'Account',
  account_details: 'Account Details',
  account_username: 'Username',
  account_plan: 'Your Plan',
  account_free_plan: 'Free Plan',
  account_view_plan: 'View Plan',
  account_delete_hint: 'To permanently delete your data, close your account.',

  // ── Settings > Content & Display ──
  content_preferences: 'Content Preferences',
  content_reduce_motion: 'Reduce Motion',
  content_reduce_motion_desc: 'Disable various distracting autoplay animations.',
  content_canvas: 'Canvas',
  content_canvas_desc: 'Show short looping visuals on the Now Playing view.',
  content_explicit: 'Allow Explicit Content',
  content_explicit_desc: 'Explicit content (marked with "E") is playable. When off, explicit music and podcasts will be skipped and explicit audiobooks will be hidden (if available).',
  content_explicit_info: 'This setting may take a moment to take effect.',
  content_unavailable: 'Show Unavailable Songs',
  content_unavailable_desc: 'Songs that are unavailable (e.g., removed by the artist or region-restricted) are still visible to others.',
  content_display_preferences: 'Display Preferences',
  content_create_button: '"Create" Button',
  content_create_button_desc: 'The "Create" button will appear in the main navigation bar.',

  // ── Settings > Playback ──
  playback_title: 'Playback',
  playback_transition: 'Track Transition',
  playback_gapless: 'Gapless Playback',
  playback_gapless_desc: 'Remove any gaps or pauses between tracks.',
  playback_automix: 'Automix',
  playback_automix_desc: 'Smoothly transition between songs in certain playlists.',
  playback_crossfade: 'Crossfade',
  playback_crossfade_desc: 'Adjust the duration of fade and overlap between tracks.',
  playback_crossfade_unit: 'sec',
  playback_listening_control: 'Listening Controls',
  playback_autoplay: 'Autoplay',
  playback_autoplay_desc: 'Play similar content when your listening ends.',
  playback_mono: 'Mono Audio',
  playback_mono_desc: 'Left and right speakers play the same audio.',
  playback_broadcast: 'Device Broadcast Status',
  playback_broadcast_desc: 'Allow other apps on the device to show what you are listening to.',
  playback_equalizer: 'Equalizer',
  playback_equalizer_desc: 'Adjust different frequencies to enhance your audio experience.',

  // ── Settings > Privacy ──
  privacy_title: 'Privacy Settings',
  privacy_listening_activity: 'Listening Activity',
  privacy_private_session: 'Private Session',
  privacy_private_session_desc: 'Temporarily hide your listening activity from followers.',
  privacy_private_session_info: 'The private session will end automatically after 6 hours.',
  privacy_listening_activity_toggle: 'Listening Activity',
  privacy_listening_activity_desc: 'Your followers can see what you are listening to in real time.',
  privacy_recent_artists: 'Recently Played Artists',
  privacy_recent_artists_desc: 'Users can see your recently listened artists on your profile.',
  privacy_playlist_visibility: 'Playlist Visibility',
  privacy_public_playlists: 'Public Playlists',
  privacy_public_playlists_desc: 'New playlists you create are public by default, and can be added to your profile.',
  privacy_public_playlists_info: 'Only playlists created after this setting change will be affected.',
  privacy_profile_playlists: 'Playlists Shown on Profile',
  privacy_profile_playlists_desc: 'New playlists you create will appear on your profile by default.',

  // ── Settings > Notifications ──
  notifications_title: 'Notifications',
  notifications_disabled_title: 'Notifications are off for this device',
  notifications_disabled_desc: 'Even if you turn on Push below, you won\'t receive notifications.',
  notifications_go_to_settings: 'Go to Settings',
  notifications_choose_desc: 'Choose which push and email notifications to receive.',
  notifications_music_artists: 'Music & Artists',
  notifications_podcasts_shows: 'Podcasts & Shows',
  notifications_new_episodes: 'New Podcast Episodes',
  notifications_new_episodes_desc: 'No followed shows',
  notifications_audiobooks: 'Audiobooks',
  notifications_privacy_features: 'Privacy Features',
  notifications_privacy_features_desc: 'Push Notifications',
  notifications_concerts: 'Live Concerts & Events',
  notifications_virtual_events: 'Virtual Events',
  notifications_off: 'Off',

  // ── Settings > Apps & Devices ──
  apps_devices_title: 'Apps & Devices',
  apps_connected: 'Connected Apps',
  apps_google_maps_desc: 'Link your Spotify account to play directly in the Google Maps app.',
  apps_waze_desc: 'Link your Spotify account to play directly in the Waze app.',
  apps_voice_suggestions: 'Voice Assistant Suggestions',
  apps_voice_suggestions_desc: 'You will receive suggestions about connecting voice assistants on this device.',
  apps_other_devices: 'Other Devices',
  apps_connect_control: 'Spotify Connect Control',
  apps_connect_control_desc: 'When listening on other devices, you can control Spotify from your phone\'s lock screen.',
  apps_local_visibility: 'Local Device Visibility',
  apps_local_visibility_desc: 'Only show devices connected via local Wi-Fi or Ethernet in the device menu.',
  apps_local_files: 'Local Audio Files',
  apps_local_files_desc: 'You can add tracks from this device to Your Library.',
  apps_get_app: 'Get App',

  // ── Settings > Data Saver & Offline ──
  data_saver_title: 'Data Saver & Offline',
  data_saver_section: 'Data Saver Mode',
  data_saver_desc: 'Choose whether to optimize your data usage. Turning this on lowers streaming quality and disables other data-heavy features like video previews.',
  data_saver_always_on: 'Always On',
  data_saver_auto: 'Automatic',
  data_saver_auto_desc: "Adjusts based on Android's data saver settings.",
  data_saver_always_off: 'Always Off',
  data_saver_download_streaming: 'Downloads & Streaming',
  data_saver_download_cellular: 'Download via Cellular',
  data_saver_download_cellular_desc: 'Start or continue downloads when not connected to Wi-Fi.',
  data_saver_download_audio_only: 'Download Video Podcasts as Audio Only',
  data_saver_download_audio_only_desc: 'Only save audio when downloading video podcasts.',
  data_saver_stream_audio_only: 'Stream Video Podcasts as Audio Only',
  data_saver_stream_audio_only_desc: 'When not connected to Wi-Fi, only play audio of video podcasts.',
  data_saver_bg_info: 'Video is never streamed when Spotify is running in the background.',
  data_saver_storage: 'Storage',
  data_saver_other_apps: 'Other Apps',
  data_saver_free: 'Free',

  // ── Settings > Media Quality ──
  media_quality_title: 'Media Quality',
  media_quality_audio_streaming: 'Audio Streaming Quality',
  media_quality_streaming_info: 'The quality of the next track will change (unless a downloaded or higher-quality cached track is available).',
  media_quality_wifi: 'Wi-Fi Streaming Quality',
  media_quality_wifi_desc: 'Choose the audio streaming quality when connected to a network.',
  media_quality_cellular: 'Cellular Streaming Quality',
  media_quality_cellular_desc: 'Choose the audio streaming quality when using cellular data.',
  media_quality_download: 'Downloads',
  media_quality_download_quality: 'Download Quality',
  media_quality_auto: 'Automatic',
  media_quality_low: 'Low',
  media_quality_normal: 'Normal',
  media_quality_high: 'High',
  media_quality_very_high: 'Very High',
  media_quality_lossless: 'Lossless',

  // ── Settings > About & Support ──
  about_title: 'About & Support',
  about_version: 'Version',
  about_privacy_policy: 'Privacy Policy',
  about_third_party: 'Third-Party Licenses',
  about_terms: 'Terms of Use',
  about_platform_rules: 'Platform Rules',

  // ── Track Menu Sheet ──
  track_menu_share: 'Share',
  track_menu_lyrics_on: 'Lyrics · On',
  track_menu_lyrics_off: 'Lyrics · Off',
  track_menu_remove_liked: 'Remove from Liked Songs',
  track_menu_add_liked: 'Add to Liked Songs',
  track_menu_add_to_playlist: 'Add to Playlist',
  track_menu_add_to_other_playlists: 'Add to other playlists',
  track_menu_remove_from_playlist: 'Remove from Playlist',
  track_menu_hide_from_playlist: 'Hide from this Playlist',
  track_menu_listen_ad_free: 'Listen ad-free',
  track_menu_add_to_queue: 'Add to Queue',
  track_menu_go_to_queue: 'Go to queue',
  track_menu_go_to_album: 'Go to Album',
  track_menu_go_to_artist: 'Go to Artist',
  track_menu_create_jam: 'Start a Jam',
  track_menu_remove_from_taste: 'Remove from Taste overview',
  track_menu_sleep_timer: 'Sleep Timer',
  track_menu_go_to_song_radio: 'Go to song radio',
  track_menu_view_producers: 'View song credits',
  track_menu_show_spotify_code: 'Show Spotify Code',

  // ── Queue Toast ──
  queue_toast_added: 'Added to Queue',
  queue_toast_open: 'Open',

  // ── Liked Toast ──
  liked_toast_added: 'Added to Liked Songs',
  liked_toast_change: 'Change',

  // ── Add to Playlist Sheet ──
  add_to_playlist_title: 'Add to Playlist',
  save_location_title: 'Save location',
  add_to_playlist_default_subtitle: 'Playlist',
  add_to_playlist_new: 'Create new playlist and add',

  // ── Sidebar ──
  sidebar_view_profile: 'View Profile',
  sidebar_add_account: 'Add Account',
  sidebar_whats_new: "What's New",
  sidebar_listening_stats: 'Listening Stats',
  sidebar_listening_stats_badge: 'New',
  sidebar_recent_played: 'Recently Played',
  sidebar_your_updates: 'Your Updates',
  sidebar_settings_privacy: 'Settings & Privacy',
  sidebar_activity_off: 'Activity Off',
  sidebar_messages: 'Messages',
  sidebar_messages_desc: 'Share your favorites with friends directly on Spotify.',
  sidebar_new_message: 'New Message',

  // ── Recent Played Page ──
  recent_title: 'Recently Played',
  recent_filter_music: 'Music',
  recent_today: 'Today',
  recent_yesterday: 'Yesterday',
  recent_no_records: 'No play history',
  recent_played_count: 'Played {count} songs',
  recent_unknown_item: 'Unknown item',
  recent_played_songs_playlist: 'Played 2 songs \u2022 Playlist \u2022 Spotify',
  recent_played_some_songs: 'Played several songs',

  // ── What's New Page ──
  whats_new_title: "What's New",
  whats_new_subtitle: 'Latest releases from artists, podcasts, and shows you follow.',
  whats_new_filter_music: 'Music',
  whats_new_filter_podcasts: 'Podcasts & Shows',
  whats_new_earlier: 'Earlier',
  whats_new_type_single: 'Single',

  // ── Short Video Page ──
  video_now_playing: 'Now Playing',
  video_follow: 'Follow',
  video_fans_suffix: 'followers',

  // ── Category Page ──
  category_detail: 'Category Details',
  category_loading: 'Loading...',
  category_loading_content: 'Fetching category content',
  category_load_failed: 'Load Failed',
  category_more_developing: 'More content coming soon',
  category_no_data: 'No detailed data for this category',
  category_no_content: 'No content',
  category_2025_review: '2025 Music Review',
  category_2025_top_artists: '2025 Top Artists and Tracks',
  category_upcoming_title: 'Upcoming New Releases',
  category_upcoming_subtitle: 'Top 10 Upcoming New Songs',
  category_release_date: 'Release Date:',
  category_pre_save_count: 'pre-saves',
  category_2025_local: '2025 Most Popular Local Artists & Groups',
  category_2025_hk_artists: '2025 Most Popular Hong Kong Artists & Groups',
  category_2025_hk_songs: '2025 Hottest Songs in Hong Kong',
  category_saves_count: 'saves',
  category_2025_annual_review: '2025 Music\nReview',

  // ── Login Landing Page ──
  login_add_account: 'Add Account',
  login_hero_line1: 'With Spotify,',
  login_hero_line2: 'listen to millions of songs for free.',
  login_signup_free: 'Sign Up Free',
  login_sign_in: 'Log In',
  login_device_warning: 'Anyone using this device while you are logged in can access your account.',

  // ── Signup Page ──
  signup_start_listening: 'Sign up to start listening',
  signup_continue_email: 'Continue with Email',
  signup_continue_google: 'Continue with Google',
  signup_have_account: 'Already have an account?',
  signup_login: 'Log In',

  // ── Create Account Page ──
  create_account_title: 'Create Account',
  create_account_provide_email: 'Enter your email',
  create_account_confirm_email: "You'll need to confirm this email later.",
  create_account_next: 'Next',

  // ── Create Password Page ──
  create_password_title: 'Create Password',
  create_password_hint: 'Use at least 10 characters.',

  // ── Create Date Page ──
  create_date_title: "What's your date of birth?",
  create_date_year: 'Year',
  create_date_month: 'Month',
  create_date_day: 'Day',

  // ── Create Gender Page ──
  create_gender_title: "What's your gender?",
  create_gender_female: 'Female',
  create_gender_male: 'Male',
  create_gender_nonbinary: 'Non-binary',
  create_gender_other: 'Other',
  create_gender_prefer_not: 'Prefer not to say',

  // ── Create Name Page ──
  create_name_title: "What's your name?",
  create_name_profile_hint: 'This name will appear on your Spotify profile.',
  create_name_required: 'Required',
  create_name_personalized: 'Spotify is a personalized service.',
  create_name_terms_agree: 'I agree to the Spotify Terms of Use.',
  create_name_terms: 'Terms of Use',
  create_name_privacy_notice: 'By clicking "Create Account", you confirm that you have read how we process your personal data in our Privacy Policy.',
  create_name_privacy_policy: 'Privacy Policy',
  create_name_no_marketing: 'I do not wish to receive promotional messages from Spotify.',
  create_name_share_data: 'I agree to share my registration data with Spotify\'s content providers for marketing purposes.',
  create_name_create_account: 'Create Account',

  // ── Choose Artists Page ──
  choose_artists_title: 'Choose 3 or more\nartists you like.',
  choose_artists_search: 'Search',
  choose_artists_done: 'Done',

  // ── Signup Complete Page ──
  signup_complete_title: 'Great choices!',
  signup_complete_desc: "We've made a playlist for you to start listening.",
  signup_complete_start: 'Start Listening',
  signup_complete_later: 'Maybe Later',
};
