/**
 * Spotify 字符串资源 — 对应 AOSP res/values/strings.xml
 */
export const strings = {
  app_name: 'Spotify',

  // ── Bottom Tab Bar (SpotifyApp.tsx) ──
  tab_home: '主页',
  tab_search: '搜索',
  tab_library: '音乐库',
  tab_premium: 'Premium',
  tab_create: '创建',

  // ── Error / Fallback (SpotifyApp.tsx) ──
  app_load_error: 'Spotify App 加载错误，请刷新页面',

  // ── Home Page tabs ──
  home_tab_all: '全部',
  home_tab_wrapped: '年度总结',
  home_tab_music: '音乐',
  home_tab_podcast: '播客',

  // ── Home Page sections ──
  home_personalized_subtitle: '体验根据你的音乐品味打造的专属歌单',
  home_section_start_listening: '开始收听',
  home_section_guess_you_like: '猜你喜欢',
  home_section_daily_picks: '今日推荐',
  home_similar_artists_label: '与 相似的更多艺人',
  home_type_album: '专辑',
  home_type_playlist: '歌单',
  home_section_charts: '排行榜',
  home_section_featured_charts: '精选排行榜',
  home_section_recommended_artists: '推荐艺人',
  home_section_new_hot_selections: '新音乐热门精选',
  home_section_hottest_today: '今日最火热单',
  home_section_all_new_music: '全新音乐',
  home_section_party: '派对',
  home_section_joyful: '欢乐',
  home_section_sad_songs: '悲伤的歌曲',
  home_section_sing_along: '跟唱',
  home_section_trending_for_you: '为你推荐的热播歌曲',
  home_section_chill: '弛放',
  home_section_instrumentals: '器乐伴奏',

  // ── Home Page — Podcast tab ──
  home_podcast_hot: '热门播客',
  home_podcast_listen_episode: '试听单集',

  // ── Home Page — Wrapped tab ──
  home_wrapped_top_artists_tracks: '2024 年度热门艺人和曲目',
  home_wrapped_most_popular: '最受欢迎',
  home_wrapped_curated: '精选',
  home_wrapped_global_shows: '2025 年全球热门节目',

  // ── Search Page ──
  search_title: '搜索',
  search_placeholder: '想听什么？',
  search_filter_songs: '歌曲',
  search_filter_playlists: '歌单',
  search_filter_albums: '专辑',
  search_filter_podcasts: '播客',
  search_filter_videos: '视频',
  search_filter_artists: '艺人',
  search_loading: '搜索中...',
  search_no_results: '未找到相关结果',
  search_empty_title: '播放你喜爱的内容',
  search_empty_subtitle: '搜索艺人、歌曲、播客等。',
  search_result_album: '专辑',
  search_result_artist: '艺人',
  search_result_song: '歌曲',
  search_section_discover: '发现新内容',
  search_section_browse_all: '浏览全部',

  // ── Library Page ──
  library_title: '音乐库',
  library_chip_playlist: '歌单',
  library_chip_artist: '艺人',
  library_chip_creator_you: '创建者：你',
  library_sort_recent: '最近播放',
  library_import_music: '从其他 App 汇入你的音乐',
  library_liked_songs: '已点赞的歌曲',
  library_playlist_count: '歌单 • {count} 首歌曲',
  library_add_artist: '添加艺人',
  library_subtitle_artist: '艺人',
  library_add_artist_title: '选择更多你喜欢的\n艺人。',
  library_add_artist_search: '搜索',
  library_add_artist_done: '完成',

  // ── Player Page ──
  player_playing_from: '播放自"歌单"',
  player_radio_suffix: '电台',
  player_queue_title: '队列',
  player_queue_now_playing: '正在播放 {artist} 电台',
  player_queue_up_next: '待播清单',
  player_shuffle: '随机播放',
  player_repeat: '循环播放',
  player_repeat_one: '重复一次',
  player_timer: '定时器',
  player_sleep_timer: '睡眠定时器',
  player_minutes: '分钟',
  player_close_timer: '关闭定时器',
  player_fade_music: '淡出音乐',
  player_fade_music_desc: '定时结束时逐渐降低音量',

  // ── Playlist Page ──
  playlist_subtitle_artist: '艺人',
  playlist_track_count: '{count} 首歌曲',
  playlist_duration_minutes: '分钟',

  // ── Liked Songs Page ──
  liked_songs_title: '已点赞的歌曲',
  liked_songs_count: '{count} 首歌曲',
  liked_songs_join: '加入此歌单',
  liked_songs_empty: '还没有点赞的歌曲。\n去播放条点个小心心吧！',

  // ── Create Page ──
  create_menu_title: '创建菜单',
  create_invite_title: '邀请好友加入共享合辑',
  create_invite_desc: '最多可邀请 10 位好友加入共享合辑。共享合辑是一份共享歌单，可根据你所有的音乐喜好进行社交推荐。',
  create_playlist: '歌单',
  create_playlist_desc: '创建包含歌曲或单集的歌单',
  create_collaborative: '共建歌单',
  create_collaborative_desc: '与好友一起创建歌单',
  create_blend: '共享合辑',
  create_blend_desc: '将好友的音乐喜好合并为一个歌单',
  create_add_podcast: '添加播客',
  create_naming_title: '为你的歌单命名',
  create_naming_default: '我的歌单',
  create_naming_error_exists: '歌单已存在',
  create_cancel: '取消',
  create_submit: '创建',

  // ── Artist Page ──
  artist_loading: '加载中...',
  artist_monthly_listeners: '每月有 {count} 名听众',
  artist_following: '关注中',
  artist_popular: '热门',

  // ── Profile Page ──
  profile_followers_following: '{followers} 位粉丝 • 关注 {following} 人',
  profile_edit: '编辑',
  profile_playlists: '歌单',
  profile_my_playlist: '我的歌单 1',
  profile_saves_count: '{count} 个人收藏',

  // ── Premium Page ──
  premium_hero_title: '无限畅听。通过 Spotify 订阅，HK$0 体验 Premium Individual 1 月。',
  premium_trial_button: '只需 HK$0 即可试用 1 个月',
  premium_trial_desc: '仅需 HK$0 即可体验 1 个月，之后每月 HK$78。优惠只适用于之前尚未试用过 Premium，并且通过 Spotify 订阅的用户。通过 Google Play 付款可获取的优惠可能不同。须遵守相关条款。',
  premium_why_title: '为什么要订阅 Premium？',
  premium_feature_no_ads: '无广告畅听音乐',
  premium_feature_download: '下载以离线收听',
  premium_feature_any_order: '以任何顺序播放歌曲',
  premium_feature_lossless: '无损音质',
  premium_feature_listen_together: '与好友一起实时聆听',
  premium_feature_manage_queue: '管理听歌队列',
  premium_available_plans: '可用套餐',
  premium_plan_terms: '适用条款。优惠仅对首次使用 Premium 的用户有效。',

  // ── Payment Page ──
  payment_checkout: '结账',
  payment_change_plan: '更改套餐',
  payment_billing_note_1: '从今天开始按月计费。',
  payment_billing_note_2: '可随时在线取消。',
  payment_terms_link: '需遵守相关条款',
  payment_select_method: '选择支付方式',
  payment_method_desc: '你可以直接通过 Spotify 或使用 Google Play 账号付款。',
  payment_spotify_desc: '使用任意一种支持的付款方式，通过 Spotify 付款。',
  payment_continue_spotify: '使用 Spotify 继续',
  payment_region: '香港',
  payment_change_region: '更改国家/地区',
  payment_per_month: '/月',

  // ── Settings Page ──
  settings_title: '设置',
  settings_account: '账号',
  settings_account_desc: '用户名 • 关停账号',
  settings_content_display: '内容与展示',
  settings_content_display_desc: 'Canvas • "创建"按钮',
  settings_playback: '播放',
  settings_playback_desc: '无缝播放 • 自动播放',
  settings_privacy: '隐私设置',
  settings_privacy_desc: '私人听歌房 • 公开歌单',
  settings_notifications: '通知',
  settings_notifications_desc: '推送 • 电子邮件',
  settings_apps_devices: '应用和设备',
  settings_apps_devices_desc: 'Google 地图 • Spotify 畅听功能控制',
  settings_data_saver: '节省流量与离线播放',
  settings_data_saver_desc: '节省流量模式 • 通过移动流量下载',
  settings_media_quality: '媒体品质',
  settings_media_quality_desc: 'Wi-Fi 串流播放品质 • 音频下载品质',
  settings_about: '关于和支持',
  settings_about_desc: '版本 • 隐私政策',
  settings_logout: '退出',

  // ── Settings > Account Page ──
  account_title: '账号',
  account_details: '账号详情',
  account_username: '用户名',
  account_plan: '你的套餐',
  account_free_plan: '免费套餐',
  account_view_plan: '查看套餐',
  account_delete_hint: '如要永久删除你的数据，请关停账号。',

  // ── Settings > Content & Display ──
  content_preferences: '内容偏好设置',
  content_reduce_motion: '减少动画数量',
  content_reduce_motion_desc: '禁用各种可能令人分心的自动播放动画。',
  content_canvas: 'Canvas',
  content_canvas_desc: '在"当前播放"视图上显示简短的循环视觉效果。',
  content_explicit: '允许播放儿童不宜内容',
  content_explicit_desc: '儿童不宜内容（以"E"标签标记）已可播放。关闭时，系统将跳过儿童不宜的音乐和播客，并隐藏儿童不宜的有声书（如有）。',
  content_explicit_info: '此设置可能需等待一段时间后才能生效。',
  content_unavailable: '显示无法播放的歌曲',
  content_unavailable_desc: '无法获取的歌曲（例如已由艺人删除或有地区限制）仍可供他人查看。',
  content_display_preferences: '显示偏好设置',
  content_create_button: '"创建"按钮',
  content_create_button_desc: '"创建"按钮将显示在主导航栏中。',

  // ── Settings > Playback ──
  playback_title: '播放',
  playback_transition: '曲目过渡效果',
  playback_gapless: '无缝播放',
  playback_gapless_desc: '删除曲目之间可能出现的任何间隔或停顿。',
  playback_automix: '自动合辑',
  playback_automix_desc: '让在特定歌单中流畅切换歌曲。',
  playback_crossfade: '淡入/淡出',
  playback_crossfade_desc: '调整曲目之间淡入淡出和重叠的时长。',
  playback_crossfade_unit: '秒',
  playback_listening_control: '聆听控制',
  playback_autoplay: '自动播放',
  playback_autoplay_desc: '在你所聆听的内容结束时播放类似内容。',
  playback_mono: '单声道音频',
  playback_mono_desc: '左右扬声器播放相同的音频。',
  playback_broadcast: '设备广播状态',
  playback_broadcast_desc: '允许设备上的其他应用显示你正在收听的内容。',
  playback_equalizer: '均衡器',
  playback_equalizer_desc: '调整不同的频率以提升音频体验。',

  // ── Settings > Privacy ──
  privacy_title: '隐私设置',
  privacy_listening_activity: '收听动态',
  privacy_private_session: '私人听歌房',
  privacy_private_session_desc: '暂时对你的粉丝隐藏收听动态。',
  privacy_private_session_info: '私人时段将于 6 小时后自动结束。',
  privacy_listening_activity_toggle: '收听动态',
  privacy_listening_activity_desc: '你的粉丝可以实时看到你正在收听的内容。',
  privacy_recent_artists: '最近听过其作品的艺人',
  privacy_recent_artists_desc: '用户可以在你的个人资料上看到你最近收听的艺人。',
  privacy_playlist_visibility: '歌单可见性',
  privacy_public_playlists: '公开歌单',
  privacy_public_playlists_desc: '你创建的新歌单默认为可供其他人查看，你也可以将其添加至你的个人资料。',
  privacy_public_playlists_info: '只有你在更改此设置后创建的歌单会受到影响。',
  privacy_profile_playlists: '歌单会显示在你的个人资料中',
  privacy_profile_playlists_desc: '你创建的新歌单会默认显示在你的个人资料中。',

  // ── Settings > Notifications ──
  notifications_title: '通知',
  notifications_disabled_title: '此设备已关闭通知',
  notifications_disabled_desc: '即使在下方开启"推送"，你也不会收到通知。',
  notifications_go_to_settings: '前往"设置"',
  notifications_choose_desc: '选择要接收的推送通知和电子邮件通知。',
  notifications_music_artists: '音乐和艺人',
  notifications_podcasts_shows: '播客和节目',
  notifications_new_episodes: '新播客单集',
  notifications_new_episodes_desc: '暂无关注的节目',
  notifications_audiobooks: '有声书',
  notifications_privacy_features: '隐私设置功能',
  notifications_privacy_features_desc: '推送通知',
  notifications_concerts: '现场演唱会和活动',
  notifications_virtual_events: '虚拟活动',
  notifications_off: '关闭',

  // ── Settings > Apps & Devices ──
  apps_devices_title: '应用和设备',
  apps_connected: '已连接的应用',
  apps_google_maps_desc: '关联你的 Spotify 帐号以直接在 Google 地图应用中播放。',
  apps_waze_desc: '关联你的 Spotify 帐号以直接在 Waze 应用中播放。',
  apps_voice_suggestions: '语音助手建议',
  apps_voice_suggestions_desc: '你将在此设备上收到关于连接语音助手的建议。',
  apps_other_devices: '其他设备',
  apps_connect_control: 'Spotify 畅联功能控制',
  apps_connect_control_desc: '在其他设备上收听时，你可以通过手机的锁定屏幕控制 Spotify。',
  apps_local_visibility: '本地设备可见性',
  apps_local_visibility_desc: '仅在设备菜单显示连接本地 Wi-Fi 或以太网的设备。',
  apps_local_files: '本地音频文件',
  apps_local_files_desc: '你可以将此设备中的曲目添加至"音乐库"。',
  apps_get_app: '获取应用',

  // ── Settings > Data Saver & Offline ──
  data_saver_title: '节省流量与离线播放',
  data_saver_section: '节省流量模式',
  data_saver_desc: '选择是否要优化你的流量使用情况。开启该功能会降低串流播放品质并禁用其他使用大量流量的功能，例如视频预览。',
  data_saver_always_on: '始终开启',
  data_saver_auto: '自动',
  data_saver_auto_desc: '根据 Android 的节省流量设置进行调整。',
  data_saver_always_off: '始终关闭',
  data_saver_download_streaming: '下载内容与串流播放',
  data_saver_download_cellular: '通过移动流量下载',
  data_saver_download_cellular_desc: '当未连接 Wi-Fi 时，开始或继续下载。',
  data_saver_download_audio_only: '仅下载视频播客的音频',
  data_saver_download_audio_only_desc: '下载视频播客时仅保存音频。',
  data_saver_stream_audio_only: '仅串流播放视频播客的音频',
  data_saver_stream_audio_only_desc: '当未连接 Wi-Fi 时，仅播放视频播客的音频。',
  data_saver_bg_info: '当 Spotify 应用在后台运行时，从不串流播放视频。',
  data_saver_storage: '存储',
  data_saver_other_apps: '其他应用',
  data_saver_free: '空闲',

  // ── Settings > Media Quality ──
  media_quality_title: '媒体品质',
  media_quality_audio_streaming: '音频串流播放品质',
  media_quality_streaming_info: '下一首曲目的音质将会变更（除非已下载或有音质更佳的缓存曲目可用）。',
  media_quality_wifi: 'Wi-Fi 串流播放品质',
  media_quality_wifi_desc: '选择连接至网络时串流播放音频的品质。',
  media_quality_cellular: '移动流量串流播放品质',
  media_quality_cellular_desc: '选择使用移动数据时串流播放音频的品质。',
  media_quality_download: '下载',
  media_quality_download_quality: '下载品质',
  media_quality_auto: '自动',
  media_quality_low: '低',
  media_quality_normal: '标准',
  media_quality_high: '高',
  media_quality_very_high: '超高',
  media_quality_lossless: '无损',

  // ── Settings > About & Support ──
  about_title: '关于和支持',
  about_version: '版本',
  about_privacy_policy: '隐私政策',
  about_third_party: '第三方许可',
  about_terms: '使用条款',
  about_platform_rules: '平台规则',

  // ── Track Menu Sheet ──
  track_menu_share: '分享',
  track_menu_lyrics_on: '歌词 · 开启',
  track_menu_lyrics_off: '歌词 · 关闭',
  track_menu_remove_liked: '从已点赞的歌曲中移除',
  track_menu_add_liked: '添加至已点赞的歌曲',
  track_menu_add_to_playlist: '加入歌单',
  track_menu_add_to_other_playlists: '添加至其他歌单',
  track_menu_remove_from_playlist: '从此歌单中删除',
  track_menu_hide_from_playlist: '在此歌单中隐藏',
  track_menu_listen_ad_free: '畅听音乐,免受广告干扰',
  track_menu_add_to_queue: '加入播放队列',
  track_menu_go_to_queue: '转至播放队列',
  track_menu_go_to_album: '转至专辑',
  track_menu_go_to_artist: '转至艺人',
  track_menu_create_jam: '创建Jam',
  track_menu_remove_from_taste: '从偏好概览中移除曲目',
  track_menu_sleep_timer: '睡眠定时器',
  track_menu_go_to_song_radio: '转至歌曲电台',
  track_menu_view_producers: '查看歌曲制作人',
  track_menu_show_spotify_code: '显示Spotify音乐码',

  // ── Queue Toast ──
  queue_toast_added: '已加入播放队列',
  queue_toast_open: '打开',

  // ── Liked Toast ──
  liked_toast_added: '已添加到 已点赞的歌曲',
  liked_toast_change: '更改',

  // ── Add to Playlist Sheet ──
  add_to_playlist_title: '加入歌单',
  save_location_title: '保存位置',
  add_to_playlist_default_subtitle: '歌单',
  add_to_playlist_new: '新建歌单并加入',

  // ── Sidebar ──
  sidebar_view_profile: '查看个人资料',
  sidebar_add_account: '添加帐号',
  sidebar_whats_new: '新增内容',
  sidebar_listening_stats: '收听统计信息',
  sidebar_listening_stats_badge: '新增',
  sidebar_recent_played: '最近播放',
  sidebar_your_updates: '你的更新',
  sidebar_settings_privacy: '设置和隐私',
  sidebar_activity_off: '动态已关闭',
  sidebar_messages: '消息',
  sidebar_messages_desc: '直接在 Spotify 上与好友分享你的心头好。',
  sidebar_new_message: '新消息',

  // ── Recent Played Page ──
  recent_title: '最近播放',
  recent_filter_music: '音乐',
  recent_today: '今天',
  recent_yesterday: '昨天',
  recent_no_records: '暂无播放记录',
  recent_played_count: '已播放 {count} 首歌曲',
  recent_unknown_item: '未知项',
  recent_played_songs_playlist: '已播放 2 首歌曲 • 歌单 • Spotify',
  recent_played_some_songs: '已播放若干首歌曲',

  // ── What's New Page ──
  whats_new_title: '新增内容',
  whats_new_subtitle: '你关注的艺人、播客和节目的最新发布内容。',
  whats_new_filter_music: '音乐',
  whats_new_filter_podcasts: '播客和节目',
  whats_new_earlier: '较早',
  whats_new_type_single: '单曲',

  // ── Short Video Page ──
  video_now_playing: '当前播放',
  video_follow: '关注',
  video_fans_suffix: '位粉丝',

  // ── Category Page ──
  category_detail: '分类详情',
  category_loading: '加载中…',
  category_loading_content: '正在获取分类内容',
  category_load_failed: '加载失败',
  category_more_developing: '更多内容开发中',
  category_no_data: '该分类暂无详细数据',
  category_no_content: '暂无内容',
  category_2025_review: '2025年度音乐回顾',
  category_2025_top_artists: '2025年度热门艺人和曲目',
  category_upcoming_title: '即将发布的新歌',
  category_upcoming_subtitle: '十大即将发布的新歌',
  category_release_date: '发布时间:',
  category_pre_save_count: '次预收藏',
  category_2025_local: '2025 最受欢迎本地歌手及组合',
  category_2025_hk_artists: '2025 香港最受欢迎歌手及组合',
  category_2025_hk_songs: '2025 香港最热歌曲',
  category_saves_count: '个人收藏',
  category_2025_annual_review: '2025 年度音乐\n回顾',

  // ── Login Landing Page ──
  login_add_account: '添加账号',
  login_hero_line1: '通过Spotify，',
  login_hero_line2: '免费畅听百万首歌曲。',
  login_signup_free: '免费注册',
  login_sign_in: '登录',
  login_device_warning: '当你处于登录状态时，其他任何使用此设备的人均可访问你的账号。',

  // ── Signup Page ──
  signup_start_listening: '注册即可开始收听',
  signup_continue_email: '使用电子邮件继续',
  signup_continue_google: '使用Google账号继续',
  signup_have_account: '已拥有账号?',
  signup_login: '登录',

  // ── Create Account Page ──
  create_account_title: '创建账号',
  create_account_provide_email: '请提供你的电子邮件',
  create_account_confirm_email: '你需要稍后确认此邮件。',
  create_account_next: '下一步',

  // ── Create Password Page ──
  create_password_title: '创建密码',
  create_password_hint: '使用至少10个字符。',

  // ── Create Date Page ──
  create_date_title: '你的出生日期是哪天？',
  create_date_year: '年',
  create_date_month: '月',
  create_date_day: '日',

  // ── Create Gender Page ──
  create_gender_title: '你的性别是？',
  create_gender_female: '女',
  create_gender_male: '男',
  create_gender_nonbinary: '非二元性别',
  create_gender_other: '其他',
  create_gender_prefer_not: '不愿说明',

  // ── Create Name Page ──
  create_name_title: '你的名字是?',
  create_name_profile_hint: '此名称会显示在你的Spotify个人资料中。',
  create_name_required: '必需',
  create_name_personalized: 'Spotify是一项个性化服务。',
  create_name_terms_agree: '我同意Spotify使用条款。',
  create_name_terms: '使用条款',
  create_name_privacy_notice: '点击"创建账号"即表示你确认已阅读我们的隐私政策中处理你的个人数据的方式。',
  create_name_privacy_policy: '隐私政策',
  create_name_no_marketing: '我不希望接收来自Spotify的推广消息。',
  create_name_share_data: '我同意与Spotify的内容提供商分享注册数据，以用于市场推广目的。',
  create_name_create_account: '创建账号',

  // ── Choose Artists Page ──
  choose_artists_title: '选择你喜欢的3位或是\n更多艺人。',
  choose_artists_search: '搜索',
  choose_artists_done: '完成',

  // ── Signup Complete Page ──
  signup_complete_title: '不错的选择！',
  signup_complete_desc: '我们专门制作了一个歌单，方便你开始聆听。',
  signup_complete_start: '开始聆听',
  signup_complete_later: '以后再说',
} as const;

export type StringKey = keyof typeof strings;
