import type { NavigationDeclaration } from './navigation.types';

const MAIN_SCROLL = [
  { name: 'main', direction: 'vertical', description: '页面主内容区' },
] as const;

export const NAVIGATION_DECLARATION = {
  app: 'calendar',
  routes: [
    {
      path: '/',
      component: 'CalendarHomePage',
      params: {},
      entryPoint: 'home',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.home.base', search: {}, description: '日历首页' }],
      queryParams: {},
      description: '日历首页',
    },
    {
      path: '/settings',
      component: 'CalendarSettingsPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.settings.base', search: {}, description: '日历设置页' }],
      queryParams: {},
      description: '日历设置页',
    },
    {
      path: '/new-event',
      component: 'CalendarNewEventPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.newEvent.base', search: {}, description: '新建日程页' }],
      queryParams: {},
      description: '新建日程页',
    },
    {
      path: '/event/:eventId',
      component: 'CalendarEventDetailPage',
      params: { eventId: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.eventDetail.base', search: {}, description: '日程详情页' }],
      queryParams: {},
      description: '日程详情页',
    },
    {
      path: '/event/:eventId/edit',
      component: 'CalendarNewEventPage',
      params: { eventId: 'string' },
      entryPoint: 'deepLink',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.eventEdit.base', search: {}, description: '编辑日程页' }],
      queryParams: {},
      description: '编辑日程页',
    },
    {
      path: '/search',
      component: 'CalendarSearchPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.search.base', search: {}, description: '搜索页' }],
      queryParams: {},
      description: '搜索页',
    },
    {
      path: '/date-jump',
      component: 'CalendarDateJumpPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.dateJump.base', search: {}, description: '日期跳转页' }],
      queryParams: {},
      description: '日期跳转页',
    },
    {
      path: '/date-calculate',
      component: 'CalendarDateCalculatePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.dateCalculate.base', search: {}, description: '日期计算页' }],
      queryParams: {},
      description: '日期计算页',
    },
    {
      path: '/subscription',
      component: 'CalendarSubscriptionPage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.subscription.base', search: {}, description: '订阅管理页' }],
      queryParams: {},
      description: '订阅管理页',
    },
    {
      path: '/desk-theme',
      component: 'CalendarDeskThemePage',
      params: {},
      entryPoint: 'none',
      scrollContainers: MAIN_SCROLL,
      uiStates: [{ id: 'calendar.deskTheme.base', search: {}, description: '桌面组件主题页' }],
      queryParams: {},
      description: '桌面组件主题页',
    },
  ],
  transitions: [
    {
      id: 'settings.open',
      from: '/',
      to: '/settings',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开日历设置页',
      ui: { placement: 'topbar', icon: 'settings', gesture: 'tap' },
    },
    {
      id: 'new-event.open',
      from: '/',
      to: '/new-event',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开新建日程页',
      ui: { placement: 'topbar', icon: 'add', gesture: 'tap' },
    },
    {
      id: 'event.open',
      from: ['/', '/search', '/new-event', '/event/:eventId/edit'],
      to: '/event/:eventId',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { eventId: 'string' },
      label: '打开日程详情页',
      ui: { placement: 'content', icon: 'event', gesture: 'tap' },
    },
    {
      id: 'event.edit',
      from: '/event/:eventId',
      to: '/event/:eventId/edit',
      search: {},
      searchParams: {},
      mode: 'push',
      params: { eventId: 'string' },
      label: '打开编辑日程页',
      ui: { placement: 'content', icon: 'edit', gesture: 'tap' },
    },
    {
      id: 'search.open',
      from: '/',
      to: '/search',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开搜索页',
      ui: { placement: 'topbar', icon: 'search', gesture: 'tap' },
    },
    {
      id: 'date-jump.open',
      from: '/',
      to: '/date-jump',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开日期跳转页',
      ui: { placement: 'content', icon: 'calendar', gesture: 'tap' },
    },
    {
      id: 'date-calculate.open',
      from: '/',
      to: '/date-calculate',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开日期计算页',
      ui: { placement: 'content', icon: 'calculate', gesture: 'tap' },
    },
    {
      id: 'subscription.open',
      from: '/',
      to: '/subscription',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开订阅管理页',
      ui: { placement: 'content', icon: 'subscription', gesture: 'tap' },
    },
    {
      id: 'desk-theme.open',
      from: '/',
      to: '/desk-theme',
      search: {},
      searchParams: {},
      mode: 'push',
      params: {},
      label: '打开桌面主题页',
      ui: { placement: 'content', icon: 'theme', gesture: 'tap' },
    },
    {
      id: 'home.open',
      from: ['/settings', '/new-event', '/event/:eventId', '/event/:eventId/edit', '/search', '/date-jump', '/date-calculate', '/subscription', '/desk-theme'],
      to: '/',
      search: {},
      searchParams: {},
      mode: 'replace',
      params: {},
      label: '返回日历首页',
      ui: { placement: 'none', icon: 'home', gesture: 'tap' },
    },
  ],
  capabilities: {
    historyBack: true,
  },
} as const satisfies NavigationDeclaration;

export type TransitionId = typeof NAVIGATION_DECLARATION.transitions[number]['id'];
