/**
 * Railway12306 字符串资源 — 对应 AOSP res/values/strings.xml
 * 服务名称、订单分类、出行指南等用户可见标签
 */
export const strings = {
  // Service grid names
  service_station_screen: '车站大屏',
  service_commuter_pass: '计次·定期票',
  service_ecard: '铁路e卡通',
  service_timetable: '时刻表',
  service_warm_service: '温馨服务',
  service_air_rail: '空铁联运',
  service_elder: '敬老版',
  service_hotel: '酒店住宿',
  service_car_rental: '租车·约车',
  service_tourism: '铁路旅游',
  service_food: '餐饮·特产',
  service_bus_ship: '汽车·船票',
  service_mall: '铁路商城',
  service_invoice: '电子发票',
  service_insurance: '出行保险',
  service_bus_ticket: '汽车票',
  service_accident_insurance: '乘意险',
  service_water_rail: '铁水联运',
  service_express: '高铁急送',
  service_ski: '雪具服务',
  service_ship: '船票',
  service_pet_transport: '宠物托运',
  service_light_travel: '轻装行',
  service_unicom_gift: '联通礼包',
  service_crt: '中铁银通',
  service_auto_transport: '汽车托运',

  // Order category names
  order_food: '餐饮·特产订单',
  order_insurance: '保险订单',
  order_hotel: '酒店订单',
  order_air_rail: '空铁联运订单',
  order_commuter: '计次·定期票订单',
  order_car_rental: '租车·约车订单',
  order_business_class: '商务座服务订单',
  order_mall: '铁路商城订单',
  order_bus: '汽车票订单',
  order_tour: '门票·旅游订单',
  order_water_rail: '铁水联运订单',
  order_ship: '船票订单',
  order_pet: '宠物托运订单',

  // Travel guide names
  guide_sale_time: '起售时间',
  guide_delay_check: '正晚点查询',
  guide_price_check: '票价查询',
  guide_transfer_time: '换乘时间',
  guide_agency: '代售点查询',
  guide_more: '更多',
  guide_quick_refund: '快捷退票',
  guide_contact: '联系方式…',
  guide_check_price: '查票价',
  guide_check_agency: '查代售点',
  guide_station_nav: '站内导航',
  guide_delay_short: '正晚点',
  guide_train_status: '列车状态',

  // Common functions
  func_id_verify: '人证核验',
  func_fingerprint: '指纹登录',
  func_change_password: '修改密码',
  func_change_phone: '修改手机号',
  func_notifications: '通知设置',
  func_student_verify: '学生资质核验',

  // Warm services
  warm_temp_id: '临时身份证明',
  warm_lost_found: '遗失物品',
  warm_suggestion: '建议',
  warm_complaint: '投诉',
  warm_special_passenger: '重点旅客',
  warm_service_phone: '客服电话',
  warm_foreign_service: '外国商务人…',

  // Info services
  info_announcement: '公告',
  info_faq: '常见问题',
  info_usage_notice: '使用须知',
  info_service_rules: '服务规章',
  info_railway_insurance: '铁路保险',
  info_about: '关于',

  // Member benefits
  member_points_title: '积分权益',
  member_points_desc: '购票领畅行积分',
  member_exchange_title: '兑换车票',
  member_exchange_desc: '畅行积分兑换车票',
  member_waitlist_title: '无票候补',
  member_waitlist_desc: '候补车票免核验',
  member_activity_title: '会员活动',
  member_activity_desc: '不定期会员活动',

  // Tags
  tag_limited_offer: '限时优惠',

  // Date and day names
  date_suffix_month: '月',
  date_suffix_day: '日',
  day_sun: '周日',
  day_mon: '周一',
  day_tue: '周二',
  day_wed: '周三',
  day_thu: '周四',
  day_fri: '周五',
  day_sat: '周六',

  // Tab labels
  tab_home: '首页',
  tab_travel: '出行服务',
  tab_orders: '订单',
  tab_member: '铁路会员',
  tab_my: '我的',

  // Home page
  home_date_today: '今天',
  home_search_hint: '目的地 / 车次 / 车站',
  home_tab_train: '火车票',
  home_tab_flight: '飞机票',
  home_tab_bus: '汽车票',
  home_student_ticket: '学生票',
  home_query_btn: '查询车票',
  home_clear_history: '清除历史',
  home_trip_reminder: '行程提醒',
  home_gate_prefix: '候车：',

  // Common actions
  action_back: '返回',
  action_cancel: '取消',
  action_confirm: '确定',
  action_edit: '编辑',
  action_preview: '预览',
  action_save: '保存',
  common_and: '和',
  common_new: '新',
  common_notice: '温馨提示',

  // All apps page
  all_apps_title: '全部应用',
  all_apps_featured_section: '精选应用',
  all_apps_travel_services_section: '出行服务',
  all_apps_travel_guide_section: '出行向导',
  all_apps_third_party_section: '第三方服务',
  all_apps_passenger_services_section: '温馨服务',

  // Fingerprint page
  fingerprint_enabled_status: '指纹登录已开启',
  fingerprint_disabled_status: '指纹登录已关闭',
  fingerprint_turn_off: '关闭指纹登录',
  fingerprint_turn_on: '开启指纹登录',

  // ID verification page
  id_verify_success_message: '您的人证信息核验成功。',
  agreement_verification_service: '《认证服务协议》',
  policy_privacy: '《隐私权政策》',

  // Invoice email page
  invoice_email_title: '发送邮箱设置',
  invoice_email_default_label: '常用发送邮箱地址',
  invoice_email_default_desc: '设置成功后，发送电子发票时默认使用此邮箱；为确保邮件发送成功，建议填写国内邮箱地址。',
  invoice_email_placeholder: '请输入邮箱地址',
  invoice_email_notes_title: '温馨提示：',
  invoice_email_note_1: '1.设置常用邮箱地址后，在发送电子发票时会默认使用此邮箱地址。邮箱地址可手动调整。',
  invoice_email_note_2: '2.请仔细检查邮箱地址，以避免输入错误导致无法收到电子发票。',
  invoice_email_note_3: '3.为确保邮件发送成功，建议填写国内邮箱地址。',
  invoice_email_note_4: '4.受运营商影响，发送邮件可能会有一定延迟，请耐心等待。如长时间未收到，请检查您的垃圾邮件。',
  invoice_email_saved_success: '常用发送邮箱地址保存成功',

  // Invoice page
  invoice_header_title: '铁路电子发票',
  invoice_header_desc: '自助开具电子发票',
  invoice_request_title: '发票申请',
  invoice_request_type_label: '抬头类型',
  invoice_request_header_label: '发票抬头',
  invoice_request_tax_id_label: '发票税号',
  invoice_manage_headers: '发票抬头管理',
  invoice_issue_button: '开具电子发票',
  invoice_service_notes_reminder: '开具电子发票前请仔细阅读业务须知',
  invoice_service_notes_title: '业务须知',
  invoice_service_note_1: '1.铁路旅客运输领域推广使用电子发票（铁路电子客票），旅客需报销入账时，可通过铁路12306开具电子发票。',
  invoice_service_note_2: '2.电子发票（铁路电子客票）属于全面数字化的电子发票，与纸质增值税发票具有同等法律效力。',
  invoice_service_note_3: '3.铁路运输企业对通过铁路客票发售和预订系统办理境内旅客运输售票、退票、改签业务并支付费用的，提供开具电子发票服务。',

  // Member page
  member_guide: '会员须知',
  member_level_one_star: '一星会员',
  member_recipient: '受让人',
  member_points_expire_notice: '{points}乘车积分将于{date}到期',
  member_upgrade_notice: '升级三星会员还需{points}乘车积分',
  member_travel_points: '乘车积分',
  member_food_tag: '兑换餐饮',
  member_dining_points: '订餐积分',
  member_benefits_title: '会员权益',
  member_view_benefit: '去查看›',
  member_events_title: '精彩会员活动',
  member_no_events: '暂无活动',

  // My page
  my_passengers: '乘车人',
  my_orders_short: '我的订单',
  my_coupons: '优惠券',
  my_phone_verified: '手机核验成功',
  my_identity_verified: '已实名认证',
  my_advance_booking_title: '预约购票服务专区',
  my_advance_booking_desc: '提前预订车票，圆每一个回家的梦！',
  my_travel_guide_title: '出行向导',
  my_common_features_title: '常用功能',
  my_notifications_title: '通知消息',
  my_system_settings_title: '系统设置',
  my_info_services_title: '信息服务',

  // Notification settings page
  notification_settings_title: '通知设置',
  notification_settings_subtitle: '请选择服务通知的渠道',
  notification_alipay_initial: '支',
  notification_alipay_name: '支付宝',
  notification_current_channel: '当前通知渠道',
  notification_alipay_nickname: '昵称：***',
  notification_alipay_linked_at: '绑定时间：2021年08月02日16:43',
  notification_wechat_initial: '微',
  notification_wechat_name: '微信',
  notification_linked: '绑定',
  notification_wechat_desc: '绑定后，可开启微信接收服务通知',
  notification_notes_body: '通知方式进行相关调整，将通过“铁路12306”App客户端为您推送相关消息（需开启通知权限）。您也可以选择通过微信或支付宝接收。列车运行调整的通知仍然发送短信通知给您。',

  // Settings page
  settings_title: '设置',
  settings_change_password_desc: '为您的账户增加安全保障',
  settings_payment_settings: '支付设置',
  settings_payment_settings_desc: '轻松出行，便捷支付',
  settings_notification_desc: '可接收服务通知',
  settings_id_verify_desc: '完成人证核验，提升账户安全性',
  settings_fingerprint_desc: '登录更便捷',
  settings_badge_on: '已开启',
  settings_version_switch_desc: '多个版本自由切换，满足不同使用需求',
  settings_font_size_contrast: '字体大小及对比度',
  settings_font_size_contrast_desc: '设置字体大小及对比度，方便查看内容',
  settings_permissions: '权限设置',
  settings_permissions_desc: '开启权限，方便使用',
  settings_recent_purchase: '最近购买推荐',
  settings_recent_purchase_desc: '关闭后不推荐常购车次',
  settings_personalized_ad: '个性化广告推荐',
  settings_personalized_ad_desc: '关闭后，将降低广告和您的相关度',
  settings_personal_info_collection: '个人信息收集清单',
  settings_third_party_info_sharing: '第三方共享个人信息清单',
  settings_close_account: '注销',
  settings_version_number: '版本号 {version}',
  settings_sign_out: '退出登录',

  // Travel service page
  travel_service_title: '出行服务',
  travel_service_banner: '春节出行 · 精选优惠',
  travel_service_empty_title: '您还没有行程哦～',
  travel_service_empty_desc: '购票后将显示待出行的行程信息',
  travel_service_book_now: '去购票',
  travel_service_dining_title: '12306 网络订餐',
  travel_service_dining_desc: '期待每一次出行',
  travel_service_journey_title: '精彩旅程 尽在12306',
  travel_service_card_homestay: '精品民宿推荐',
  travel_service_card_ecard_desc: '无需排队购票，直接扫码乘车',

  // Version switch page
  version_switch_title: '版本切换',
  version_standard_name: '标准版',
  version_standard_desc: '全功能标准版本',
  version_senior_name: '敬老版',
  version_senior_desc: '大字设计，功能简洁',
  version_english_name: '英文版',
  version_english_desc: '为外国旅客提供更加简单便利的功能服务',

  // Station select page
  station_select_title: '车站选择',
  station_search_hint: '请输入（如：北京市/北京站/beijing/bj）',
  station_empty: '未找到匹配的车站',
  station_my_location: '我的位置',
  station_relocate: '重新定位',
  station_common: '常用车站',
  station_hot: '热门车站',
  station_domestic: '国内站点',
  station_international: '国际站点',
  station_type_start: '始',
  station_type_end: '终',

  // Query result page
  query_tab_direct: '直达',
  query_tab_transfer: '中转',
  query_calendar_label: '日历',
  query_customize_transfer: '定制中转',
  query_loading: '查询中...',
  query_error_prefix: '查询失败: ',
  query_empty_direct: '很抱歉，按您的查询条件，当前未找到从 {from} 到 {to} 的列车。',
  query_empty_direct_hint: '您可使用中转换乘功能，查询途中换乘一次的部分列车余票情况',
  query_empty_transfer: '未找到中转方案',
  warm_tip_label: '温馨提示：',
  warm_tip_title: '温馨提示',

  // Train card badges
  tag_exchangeable: '兑',
  tag_berth: '铺',
  tag_quiet: '静',

  // Seat status
  seat_available: '有票',
  seat_available_short: '有',
  seat_count_suffix: '张',
  seat_waitlist: '候补',
  seat_none: '无',
  seat_sold_out: '售罄',
  seat_book_btn: '预订',
  seat_discount_suffix: '折',
  price_from_suffix: '起',

  // Filter panel
  filter_section_train_type: '车次类型',
  filter_type_high_speed: '高铁/动车',
  filter_type_regular: '普通车',
  filter_section_train_group: '车组类型',
  filter_section_seat_type: '席别类型',
  filter_section_from_station: '出发车站',
  filter_section_to_station: '到达车站',
  filter_section_other: '其他筛选',
  filter_only_departure: '只看始发',
  filter_only_terminal: '只看终到',
  filter_section_dep_time: '出发时间',
  filter_section_arr_time: '到达时间',
  filter_clear: '清空',
  filter_confirm: '确认',

  // Sticky filter bar
  filter_btn: '筛选',
  filter_only_high_speed: '只看高铁/动车',
  filter_only_regular: '只看普通车',
  filter_only_available: '只看有票',

  // Sort bar
  sort_duration_asc: '耗时最短',
  sort_duration_desc: '耗时最长',
  sort_depart_asc: '发时最早',
  sort_depart_desc: '发时最晚',
  sort_price_asc: '价格最低',
  sort_price_desc: '价格最高',
  sort_waitlist: '候补下单',
  sort_show_price: '显示票价',

  // Transfer result
  transfer_total_prefix: '全程',
  transfer_arrive_suffix: '到达',
  transfer_depart_suffix: '出发',
  transfer_seat_change: '车内换座',
  transfer_leg_suffix: '程',

  // Order confirm page
  order_confirm_title: '确认订单',
  order_refund_rules: '退改说明',
  order_prev_day: '前一天',
  order_next_day: '后一天',
  order_quiet_tip: '提示：本列车二等座设置静音车厢。',
  order_no_passenger: '暂无乘车人，请先选择乘车人',
  order_select_passenger: '选择乘车人',
  order_points_recipient: '积分受让人',
  order_agree_prefix: '提交订单表示已阅读并同意',
  order_terms_transport: '《国铁集团铁路旅客运输规程》',
  order_terms_service: '《服务条款》',
  order_submit: '提交订单',
  order_error: '订单信息异常',
  order_processing_title: '温馨提示',
  order_processing_msg: '订单处理中 。。。',

  // Orders page
  orders_title: '订单',
  orders_warm_tip: '温馨提示',
  orders_train_section: '火车票订单',
  orders_pending: '待支付',
  orders_paid: '已支付',
  orders_waitlist_order: '候补订单',
  orders_my_tickets: '本人车票',
  orders_invoice: '电子发票',
  orders_collapse: '收起',
  orders_expand: '查看更多',

  // Swap stations dialog
  swap_dialog_title: '温馨提示',
  swap_dialog_message: '确定交换发到站吗？',
  swap_dialog_cancel: '取消',
  swap_dialog_confirm: '确定',

  // Common order status
  order_status_refunded: '已退票',
  order_status_pending_payment: '待支付',
  order_status_paid: '已支付',

  // Add passenger page
  add_passenger_title: '添加乘车人',
  add_passenger_recommended: '推荐',
  add_passenger_scan_title: '扫描/上传证件快速填写',
  add_passenger_scan_desc: '您可通过扫描证件或上传证件照片快速填写信息，建议您使用自动填写。',
  add_passenger_view_example: '查看示例',
  add_passenger_id_type: '证件类型',
  add_passenger_name: '姓名',
  add_passenger_name_placeholder: '请输入真实姓名，以便购票',
  add_passenger_id_number: '证件号码',
  add_passenger_id_number_placeholder: '用于身份核验，请正确填写',
  add_passenger_ticket_type: '优惠(乘车)类型',
  add_passenger_contact_info: '联系方式',
  add_passenger_mobile: '手机号码',
  add_passenger_mobile_placeholder: '填写乘车人手机号码',
  add_passenger_mobile_notice: '请填写乘车人真实有效的联系方式，以便接收铁路部门推送的重要服务信息，以及在紧急特殊情况下的联系。',
  add_passenger_submit: '提交',
  add_passenger_invalid_id: '请输入正确的身份证号！',
  add_passenger_invalid_mobile: '请输入正确的手机号码',
  add_passenger_empty_name: '请填写乘车人姓名',
  add_passenger_empty_id: '请输入正确的身份证号！',
  add_passenger_empty_mobile: '请填写乘车人手机号码',
  add_passenger_duplicate: '该联系人已存在，请使用不同的姓名和证件。',
  add_passenger_confirm_title: '请仔细核对个人信息',
  add_passenger_not_provided: '未填写',
  add_passenger_tips_title: '温馨提示：',
  add_passenger_tips_1: '1.请提供乘车人真实有效的联系方式。',
  add_passenger_tips_2: '2.互联网售票实行实名制，请确认填写乘车人基本信息。',
  add_passenger_tips_3: '3.如旅客身份信息未能在添加后的24小时内通过核验，请乘车人持有效身份证件原件到车站办理身份核验。',
  add_passenger_tips_4: '4.乘车人在添加后30天内不允许删除，每个账号最多允许添加30个乘客。',

  // Incomplete orders page
  incomplete_orders_title: '未完成',
  incomplete_orders_empty: '暂无订单',
  incomplete_orders_remaining: '剩余：',
  incomplete_orders_via: '经停站',
  incomplete_orders_duration: '历时',
  incomplete_orders_departure: '发车时间：',
  incomplete_orders_discount: '8.3折',
  incomplete_orders_change_refund: '退改说明',
  incomplete_orders_show_more: '点击查看剩余{n}人',
  incomplete_orders_insurance_title: '铁路出行专属保险',
  incomplete_orders_insurance_main_title: '安心畅行 多重保障',
  incomplete_orders_insurance_more_products: '其他产品',
  incomplete_orders_insurance_desc: '最高88万意外伤害 | 5万个人三者责任险',
  incomplete_orders_insurance_unit: '/人',
  incomplete_orders_insurance_accident: '保意外伤害',
  incomplete_orders_insurance_medical: '保医疗费用',
  incomplete_orders_insurance_liability: '保三者人伤财损',
  incomplete_orders_please_read: '请阅读',
  incomplete_orders_purchase_notice: '投保须知',
  incomplete_orders_policy_terms: '保险条款',
  incomplete_orders_disclaimer: '免责条款',
  incomplete_orders_quick_pay_badge: '无需跳转 快速支付',
  incomplete_orders_quick_pay_scan: '扫码乘车 简单出行',
  incomplete_orders_order_total: '订单金额明细',
  incomplete_orders_ticket_price: '车票价格',
  incomplete_orders_total: '总金额',
  incomplete_orders_details: '明细',
  incomplete_orders_cancel_order: '取消订单',
  incomplete_orders_buy_return: '购买返程',
  incomplete_orders_pay_now: '立即支付',
  incomplete_orders_cancel_confirm_message: '如果取消订单，今天将无法继续支付。如需继续购票，请返回未完成订单重新操作。',
  incomplete_orders_confirm_cancel: '确定取消',
  incomplete_orders_leave_confirm_message: '确定要放弃支付吗？放弃支付不会取消订单，如需继续支付请在《未完成订单》中进行。',
  incomplete_orders_order_payment: '订单支付',
  incomplete_orders_choose_payment_method: '选择支付方式',
  incomplete_orders_other_payment_methods: '其他支付',
  incomplete_orders_other_payment_desc: '银行卡，支付宝，微信等。',
  incomplete_orders_add_protection: '添加铁路乘意险，让家人更放心',
  incomplete_orders_no_coverage: '无保障',
  incomplete_orders_best_value: '性价比高',
  incomplete_orders_accident_medical_plan: '乘意险·平安',
  incomplete_orders_max_payout: '最高赔付',
  incomplete_orders_person: '人',
  incomplete_orders_accident_luggage_plan: '乘意险·行李',
  incomplete_orders_go_pay: '去支付',
  incomplete_orders_seat_reassigned_message: '本次列车剩余席位（铺位）已无法满足您的需求，系统已经为您自动分配了其他席位（铺位），请确认后继续支付或取消订单。',

  // Order detail page
  order_detail_title: '订单详情',
  order_detail_not_found: '订单不存在或已过期。',
  order_detail_order_id: '订单号',
  order_detail_copy: '复制',
  order_detail_ordered_at: '下单时间',
  order_detail_travel_date: '乘车日期',
  order_detail_change_destination: '变更到站',
  order_detail_reschedule: '改签',
  order_detail_refund: '退票',
  order_detail_unassigned_seat: '不对号入座',
  order_detail_show_more: '点击查看剩余{n}人',
  order_detail_order_meal: '订餐',
  order_detail_travel_insurance: '购乘意险',
  order_detail_qr_check_in: '二维码检票',
  order_detail_share_text: '美好旅途，快与朋友一起分享吧~',
  order_detail_share_now: '立即分享',
  order_detail_validity_notice: '订单信息查询有效期限为30天',
  order_detail_hotel_deal: '酒店优惠',
  order_detail_hotel: '酒店',
  order_detail_travel_easier: '出行更轻松',
  order_detail_check_in: '入住',
  order_detail_night: '晚',
  order_detail_check_out: '离店',

  // Paid orders page
  paid_orders_title: '已支付',
  paid_orders_tab_upcoming: '未出行订单',
  paid_orders_tab_history: '历史订单',
  paid_orders_child_notice: '免费乘车儿童申报（未满6周岁）',
  paid_orders_add_now: '去添加',
  paid_orders_empty: '订单信息保存期限为30天，没有查到您的订单信息',
  paid_orders_ordered_on: '下单日期',
  paid_orders_order_id_label: '订单号：',
  paid_orders_departure_label: '发车时间：',
  paid_orders_passengers_label: '总张数：',
  paid_orders_tickets_suffix: '张',
  paid_orders_passenger_display_more: '{name} 等{count}人',
  paid_orders_retention_notice: '订单信息保存期限为30天',
  paid_orders_ad_title: '12306餐饮',
  paid_orders_ad_desc: '沿途美食 送餐到座',
  paid_orders_book_now: '立即预订',

  // Payment password page
  payment_password_title: '消费密码',
  payment_password_change_tab: '修改密码',
  payment_password_reset_tab: '重置密码',
  payment_password_old_label: '原密码：',
  payment_password_old_placeholder: '请输入6位数字原密码',
  payment_password_new_label: '新密码：',
  payment_password_new_placeholder: '请输入6位数字新密码',
  payment_password_confirm_label: '密码确认：',
  payment_password_confirm_placeholder: '请再次输入新密码',
  payment_password_tips_body: '消费密码修改、重置后，新密码将即刻生效，密码仅能添加6位有效数字。',

  // Payment platform page
  payment_platform_title: '请您支付',
  payment_platform_done: '完成',
  payment_platform_subtitle: '中国铁路电子支付平台',
  payment_platform_amount_due: '应付金额',
  payment_platform_jd_name: '京东支付',
  payment_platform_jd_offer: '限量减1-298，白条新减30',
  payment_platform_other_methods: '选择其他11种支付方式',
  payment_platform_submit: '提交支付',
  payment_platform_merchant_name: '铁路12306',
  payment_platform_subject: '火车票',

  // Payment success page
  payment_success_title: '支付成功',
  payment_success_notification_settings: '通知设置',
  payment_success_order_details: '订单详情',
  payment_success_meal_reservation: '餐饮预订',
  payment_success_trip_assistance: '出行无忧',
  payment_success_hot: '热',
  payment_success_pack_light: '轻装出行',
  payment_success_share_text: '美好旅途，快与朋友一起分享吧~',
  payment_success_share_now: '立即分享',
  payment_success_hotel_deals: '{city}酒店',
  payment_success_hotel_offer: '火车票用户限时享',
  payment_success_check_in: '入住',
  payment_success_night: '晚',
  payment_success_check_out: '离店',
  payment_success_claim_coupon: '领券预订',
  payment_success_hotel_coupon: '酒店券',
  payment_success_car_rental_deals: '春游租车特惠',
  payment_success_view_now: '点击立即查看',
  payment_success_activity_period: '活动时间：2026年3月1日-2026年5月31日',
  payment_success_ad: '广告',
  payment_success_dining_desc: '沿途美食，送餐到座',
  payment_success_car_rental_title: '租车预订',
  payment_success_car_rental_offer: '新人首日最高减100元',
  payment_success_pickup: '取车点',
  payment_success_duration: '时间',
  payment_success_days: '天',
  payment_success_choose_car: '立即选车',

  // Refund confirm flow
  refund_notice_title: '温馨提示',
  refund_notice_message: '您确定要退票吗？如有预约出站引导或特殊重点旅客服务将自动为您取消，如有预订餐饮或特产，请按规定自行办理退订。',
  refund_notice_continue: '继续',
  refund_confirm_title: '退票确认',
  refund_confirm_departure_time: '发车时间',
  refund_confirm_notice_title: '温馨提示:',
  refund_confirm_rule_1_prefix: '改签和退票规则详见',
  refund_confirm_rule_link: '退改说明',
  refund_confirm_rule_2: '改签或变更到站后的车票乘车日期在春运期间的，退票按开车前不足24小时标准（按票面价格20%）核收退票费。',
  refund_confirm_rule_3: '实际核收退票费及应退款将按最终交易时间计算。',
  refund_confirm_total_label: '退票总额',
  refund_confirm_detail_label: '明细',
  refund_confirm_cancel: '取消退票',
  refund_confirm_submit: '确定退票',

  // Refund success page
  refund_success_title: '操作成功',
  refund_success_banner: '您已退票成功',
  refund_success_business_id: '业务号',
  refund_success_details_title: '退款明细',
  refund_success_train: '车次',
  refund_success_passengers: '乘车人',
  refund_success_original_fare: '原票价',
  refund_success_rate: '退票费率',
  refund_success_service_fee: '手续费',
  refund_success_total: '共计退款',
  refund_success_back: '返回订单',
} as const;

export type StringKey = keyof typeof strings;
