import type { StringKey } from './strings';

export const stringsEn: Partial<Record<StringKey, string>> = {
  // Tab labels
  tab_home: 'Home',
  tab_travel: 'Travel',
  tab_orders: 'Orders',
  tab_member: 'Membership',
  tab_my: 'My',

  // Service grid names
  service_station_screen: 'Station Board',
  service_commuter_pass: 'Multi-ride / Season Pass',
  service_ecard: 'Railway e-Card',
  service_timetable: 'Timetable',
  service_warm_service: 'Passenger Services',
  service_air_rail: 'Air-Rail Transfer',
  service_elder: 'Senior Mode',
  service_hotel: 'Hotels',
  service_car_rental: 'Car Rental / Ride-hailing',
  service_tourism: 'Railway Tourism',
  service_food: 'Food & Specialties',
  service_bus_ship: 'Bus & Ferry Tickets',
  service_mall: 'Railway Mall',
  service_invoice: 'E-Invoice',
  service_insurance: 'Travel Insurance',
  service_bus_ticket: 'Bus Tickets',
  service_accident_insurance: 'Accident Insurance',
  service_water_rail: 'Rail-Water Transfer',
  service_express: 'High-speed Rail Express',
  service_ski: 'Ski Gear Service',
  service_ship: 'Ferry Tickets',
  service_pet_transport: 'Pet Shipping',
  service_light_travel: 'Luggage-free Travel',
  service_unicom_gift: 'Unicom Gift Pack',
  service_crt: 'CRT Silver Card',
  service_auto_transport: 'Vehicle Shipping',

  // Order category names
  order_food: 'Food & Specialty Orders',
  order_insurance: 'Insurance Orders',
  order_hotel: 'Hotel Orders',
  order_air_rail: 'Air-Rail Transfer Orders',
  order_commuter: 'Multi-ride / Season Pass Orders',
  order_car_rental: 'Car Rental / Ride-hailing Orders',
  order_business_class: 'Business Class Service Orders',
  order_mall: 'Railway Mall Orders',
  order_bus: 'Bus Ticket Orders',
  order_tour: 'Attraction & Tour Orders',
  order_water_rail: 'Rail-Water Transfer Orders',
  order_ship: 'Ferry Ticket Orders',
  order_pet: 'Pet Shipping Orders',

  // Travel guide names
  guide_sale_time: 'Ticket Sale Time',
  guide_delay_check: 'Delay Inquiry',
  guide_price_check: 'Fare Inquiry',
  guide_transfer_time: 'Transfer Time',
  guide_agency: 'Ticket Agency Lookup',
  guide_more: 'More',
  guide_quick_refund: 'Quick Refund',
  guide_contact: 'Contact...',
  guide_check_price: 'Check Fares',
  guide_check_agency: 'Find Agencies',
  guide_station_nav: 'Station Navigation',
  guide_delay_short: 'Delays',
  guide_train_status: 'Train Status',

  // Common functions
  func_id_verify: 'ID Verification',
  func_fingerprint: 'Fingerprint Login',
  func_change_password: 'Change Password',
  func_change_phone: 'Change Phone Number',
  func_notifications: 'Notification Settings',
  func_student_verify: 'Student ID Verification',

  // Warm services
  warm_temp_id: 'Temporary ID',
  warm_lost_found: 'Lost & Found',
  warm_suggestion: 'Suggestions',
  warm_complaint: 'Complaints',
  warm_special_passenger: 'Priority Passengers',
  warm_service_phone: 'Customer Service Hotline',
  warm_foreign_service: 'Foreign Business...',

  // Info services
  info_announcement: 'Announcements',
  info_faq: 'FAQ',
  info_usage_notice: 'Usage Notice',
  info_service_rules: 'Service Regulations',
  info_railway_insurance: 'Railway Insurance',
  info_about: 'About',

  // Member benefits
  member_points_title: 'Points & Benefits',
  member_points_desc: 'Earn travel points with tickets',
  member_exchange_title: 'Redeem Tickets',
  member_exchange_desc: 'Redeem travel points for tickets',
  member_waitlist_title: 'Waitlist',
  member_waitlist_desc: 'Waitlist without verification',
  member_activity_title: 'Member Events',
  member_activity_desc: 'Occasional member events',

  // Tags
  tag_limited_offer: 'Limited Offer',

  // Date and day names
  date_suffix_month: '/',
  date_suffix_day: '',
  day_sun: 'Sun',
  day_mon: 'Mon',
  day_tue: 'Tue',
  day_wed: 'Wed',
  day_thu: 'Thu',
  day_fri: 'Fri',
  day_sat: 'Sat',

  // Home page
  home_date_today: 'Today',
  home_search_hint: 'Destination / Train No. / Station',
  home_tab_train: 'Train',
  home_tab_flight: 'Flight',
  home_tab_bus: 'Bus',
  home_student_ticket: 'Student',
  home_query_btn: 'Search Tickets',
  home_clear_history: 'Clear History',
  home_trip_reminder: 'Upcoming Trip',
  home_gate_prefix: 'Gate: ',

  // Common actions
  action_back: 'Back',
  action_cancel: 'Cancel',
  action_confirm: 'Confirm',
  action_edit: 'Edit',
  action_preview: 'Preview',
  action_save: 'Save',
  common_and: 'and',
  common_new: 'New',
  common_notice: 'Notice',

  // All apps page
  all_apps_title: 'All apps',
  all_apps_featured_section: 'Featured apps',
  all_apps_travel_services_section: 'Travel services',
  all_apps_travel_guide_section: 'Travel guide',
  all_apps_third_party_section: 'Third-party services',
  all_apps_passenger_services_section: 'Passenger services',

  // Fingerprint page
  fingerprint_enabled_status: 'Fingerprint login is on',
  fingerprint_disabled_status: 'Fingerprint login is off',
  fingerprint_turn_off: 'Turn off fingerprint login',
  fingerprint_turn_on: 'Turn on fingerprint login',

  // ID verification page
  id_verify_success_message: 'Your identity information has been verified successfully.',
  agreement_verification_service: 'Verification Service Agreement',
  policy_privacy: 'Privacy Policy',

  // Invoice email page
  invoice_email_title: 'Delivery email',
  invoice_email_default_label: 'Default delivery email',
  invoice_email_default_desc: 'After saving, this email will be used by default when sending e-invoices. To improve delivery success, a domestic email provider is recommended.',
  invoice_email_placeholder: 'Enter email address',
  invoice_email_notes_title: 'Notes:',
  invoice_email_note_1: '1. After setting a default email address, it will be used automatically when sending e-invoices. You can still adjust it manually later.',
  invoice_email_note_2: '2. Please double-check the address carefully to avoid delivery failure caused by typing mistakes.',
  invoice_email_note_3: '3. To improve delivery success, a domestic email address is recommended.',
  invoice_email_note_4: '4. Due to carrier or email provider delays, delivery may take some time. If you do not receive it for a long time, please check your spam folder.',
  invoice_email_saved_success: 'Default delivery email saved successfully',

  // Invoice page
  invoice_header_title: 'Railway e-invoice',
  invoice_header_desc: 'Issue e-invoices by yourself',
  invoice_request_title: 'Invoice request',
  invoice_request_type_label: 'Type',
  invoice_request_header_label: 'Header',
  invoice_request_tax_id_label: 'Tax ID',
  invoice_manage_headers: 'Manage headers',
  invoice_issue_button: 'Issue e-invoice',
  invoice_service_notes_reminder: 'Please read the service notes carefully before issuing an e-invoice',
  invoice_service_notes_title: 'Service notes',
  invoice_service_note_1: '1. Electronic invoices (railway e-tickets) are being promoted for railway passenger transport. Passengers who need reimbursement records can issue an e-invoice through Railway 12306.',
  invoice_service_note_2: '2. Electronic invoices (railway e-tickets) are fully digital invoices and have the same legal effect as paper VAT invoices.',
  invoice_service_note_3: '3. Railway transport enterprises provide e-invoice issuance for domestic passenger ticket booking, refunds, and ticket changes completed through the railway ticketing and reservation system.',

  // Member page
  member_guide: 'Member Guide',
  member_level_one_star: '1-Star Member',
  member_recipient: 'Recipient',
  member_points_expire_notice: '{points} travel points expire on {date}',
  member_upgrade_notice: '{points} more travel points to reach 3-Star Member',
  member_travel_points: 'Travel points',
  member_food_tag: 'Food',
  member_dining_points: 'Dining points',
  member_benefits_title: 'Member benefits',
  member_view_benefit: 'View >',
  member_events_title: 'Member events',
  member_no_events: 'No events right now',

  // My page
  my_passengers: 'Passengers',
  my_orders_short: 'My orders',
  my_coupons: 'Coupons',
  my_phone_verified: 'Phone verified',
  my_identity_verified: 'Identity verified',
  my_advance_booking_title: 'Advance booking zone',
  my_advance_booking_desc: 'Book early and make every trip home easier',
  my_travel_guide_title: 'Travel guide',
  my_common_features_title: 'Common features',
  my_notifications_title: 'Notifications',
  my_system_settings_title: 'Settings',
  my_info_services_title: 'Info services',

  // Notification settings page
  notification_settings_title: 'Notification settings',
  notification_settings_subtitle: 'Choose how you want to receive service notifications',
  notification_alipay_initial: 'A',
  notification_alipay_name: 'Alipay',
  notification_current_channel: 'Current channel',
  notification_alipay_nickname: 'Nickname: ***',
  notification_alipay_linked_at: 'Linked on: 2021-08-02 16:43',
  notification_wechat_initial: 'W',
  notification_wechat_name: 'WeChat',
  notification_linked: 'Linked',
  notification_wechat_desc: 'After linking, you can receive service notifications through WeChat.',
  notification_notes_body: 'If notification delivery methods are adjusted, related messages will be pushed through the Railway 12306 app (notification permission required). You can also choose to receive them through WeChat or Alipay. Notices about train operation changes will still be sent to you by SMS.',

  // Settings page
  settings_title: 'Settings',
  settings_change_password_desc: 'Add more security to your account',
  settings_payment_settings: 'Payment settings',
  settings_payment_settings_desc: 'Travel easily with convenient payments',
  settings_notification_desc: 'Receive service notifications',
  settings_id_verify_desc: 'Verify identity to improve account security',
  settings_fingerprint_desc: 'Faster sign-in',
  settings_badge_on: 'On',
  settings_version_switch_desc: 'Switch freely between versions for different needs',
  settings_font_size_contrast: 'Font size & contrast',
  settings_font_size_contrast_desc: 'Adjust text size and contrast for easier reading',
  settings_permissions: 'Permissions',
  settings_permissions_desc: 'Enable permissions for smoother use',
  settings_recent_purchase: 'Recent purchase suggestions',
  settings_recent_purchase_desc: 'Turn off to stop recommending frequent trains',
  settings_personalized_ad: 'Personalized ad suggestions',
  settings_personalized_ad_desc: 'Turn off to reduce ad relevance to you',
  settings_personal_info_collection: 'Personal information collection list',
  settings_third_party_info_sharing: 'Third-party personal information sharing list',
  settings_close_account: 'Close account',
  settings_version_number: 'Version {version}',
  settings_sign_out: 'Sign out',

  // Travel service page
  travel_service_title: 'Travel services',
  travel_service_banner: 'Spring Festival travel deals',
  travel_service_empty_title: 'No trips yet',
  travel_service_empty_desc: 'Your upcoming trip info will appear after booking',
  travel_service_book_now: 'Book now',
  travel_service_dining_title: '12306 Online Dining',
  travel_service_dining_desc: 'Make every trip more enjoyable',
  travel_service_journey_title: 'Great journeys start on 12306',
  travel_service_card_homestay: 'Boutique homestay picks',
  travel_service_card_ecard_desc: 'Scan and ride without queueing for tickets',

  // Version switch page
  version_switch_title: 'Version switch',
  version_standard_name: 'Standard',
  version_standard_desc: 'Full-feature standard version',
  version_senior_name: 'Senior Mode',
  version_senior_desc: 'Larger text and simpler features',
  version_english_name: 'English Version',
  version_english_desc: 'Provide simpler and more convenient functional services for foreign travelers',

  // Station select page
  station_select_title: 'Select Station',
  station_search_hint: 'City / Station / Pinyin / Code',
  station_empty: 'No matching stations found',
  station_my_location: 'My Location',
  station_relocate: 'Relocate',
  station_common: 'Frequent Stations',
  station_hot: 'Popular Stations',
  station_domestic: 'Domestic',
  station_international: 'International',
  station_type_start: 'O',
  station_type_end: 'T',

  // Query result page
  query_tab_direct: 'Direct',
  query_tab_transfer: 'Transfer',
  query_calendar_label: 'Calendar',
  query_customize_transfer: 'Custom Transfer',
  query_loading: 'Searching...',
  query_error_prefix: 'Search failed: ',
  query_empty_direct: 'Sorry, no trains were found from {from} to {to} for your current search criteria.',
  query_empty_direct_hint: 'You can use Transfer to check partial availability for routes with one connection.',
  query_empty_transfer: 'No transfer routes found',
  warm_tip_label: 'Note: ',
  warm_tip_title: 'Note',

  // Train card badges
  tag_exchangeable: 'X',
  tag_berth: 'B',
  tag_quiet: 'Q',

  // Seat status
  seat_available: 'Avail',
  seat_available_short: 'Y',
  seat_count_suffix: '',
  seat_waitlist: 'WL',
  seat_none: '--',
  seat_sold_out: 'Full',
  seat_book_btn: 'Book',
  seat_discount_suffix: '%',
  price_from_suffix: '+',

  // Filter panel
  filter_section_train_type: 'Train Type',
  filter_type_high_speed: 'High-speed / EMU',
  filter_type_regular: 'Regular',
  filter_section_train_group: 'Train Series',
  filter_section_seat_type: 'Seat Class',
  filter_section_from_station: 'Departure Station',
  filter_section_to_station: 'Arrival Station',
  filter_section_other: 'Other Filters',
  filter_only_departure: 'Origin Only',
  filter_only_terminal: 'Terminal Only',
  filter_section_dep_time: 'Departure Time',
  filter_section_arr_time: 'Arrival Time',
  filter_clear: 'Clear',
  filter_confirm: 'Apply',

  // Sticky filter bar
  filter_btn: 'Filter',
  filter_only_high_speed: 'High-speed / EMU',
  filter_only_regular: 'Regular',
  filter_only_available: 'Available Only',

  // Sort bar
  sort_duration_asc: 'Shortest',
  sort_duration_desc: 'Longest',
  sort_depart_asc: 'Earliest',
  sort_depart_desc: 'Latest',
  sort_price_asc: 'Cheapest',
  sort_price_desc: 'Costliest',
  sort_waitlist: 'Waitlist',
  sort_show_price: 'Show Fares',

  // Transfer result
  transfer_total_prefix: 'Total ',
  transfer_arrive_suffix: ' arr.',
  transfer_depart_suffix: ' dep.',
  transfer_seat_change: 'Seat change on board',
  transfer_leg_suffix: '',

  // Order confirm page
  order_confirm_title: 'Confirm Order',
  order_refund_rules: 'Refund Policy',
  order_prev_day: 'Prev Day',
  order_next_day: 'Next Day',
  order_quiet_tip: 'Note: This train has quiet coaches in 2nd class.',
  order_no_passenger: 'No passenger selected. Please add one.',
  order_select_passenger: 'Select Passenger',
  order_points_recipient: 'Points Recipient',
  order_agree_prefix: 'By submitting you agree to ',
  order_terms_transport: 'Transport Terms',
  order_terms_service: 'Service Terms',
  order_submit: 'Submit Order',
  order_error: 'Order information error',
  order_processing_title: 'Processing',
  order_processing_msg: 'Order is being processed...',

  // Orders page
  orders_title: 'Orders',
  orders_warm_tip: 'Notice',
  orders_train_section: 'Train Ticket Orders',
  orders_pending: 'Unpaid',
  orders_paid: 'Paid',
  orders_waitlist_order: 'Waitlist Orders',
  orders_my_tickets: 'My Tickets',
  orders_invoice: 'E-Invoice',
  orders_collapse: 'Collapse',
  orders_expand: 'View More',

  // Swap stations dialog
  swap_dialog_title: 'Notice',
  swap_dialog_message: 'Swap departure and arrival stations?',
  swap_dialog_cancel: 'Cancel',
  swap_dialog_confirm: 'Confirm',

  // Common order status
  order_status_refunded: 'Refunded',
  order_status_pending_payment: 'Pending payment',
  order_status_paid: 'Paid',

  // Add passenger page
  add_passenger_title: 'Add passenger',
  add_passenger_recommended: 'Recommended',
  add_passenger_scan_title: 'Scan / upload ID card to fill in quickly',
  add_passenger_scan_desc: 'You can scan an ID card or upload a photo to fill in the information quickly. We recommend auto-fill for better accuracy.',
  add_passenger_view_example: 'View example',
  add_passenger_id_type: 'ID type',
  add_passenger_name: 'Name',
  add_passenger_name_placeholder: 'Enter the real name used for ticketing',
  add_passenger_id_number: 'ID number',
  add_passenger_id_number_placeholder: 'Used for identity verification',
  add_passenger_ticket_type: 'Ticket type',
  add_passenger_contact_info: 'Contact info',
  add_passenger_mobile: 'Mobile',
  add_passenger_mobile_placeholder: 'Phone number of the passenger',
  add_passenger_mobile_notice: 'Please provide a reachable phone number so that railway service messages can be delivered in time.',
  add_passenger_submit: 'Save',
  add_passenger_invalid_id: 'Please enter a valid ID number!',
  add_passenger_invalid_mobile: 'Please enter a valid mobile number.',
  add_passenger_empty_name: 'Please enter the passenger name.',
  add_passenger_empty_id: 'Please enter a valid ID number!',
  add_passenger_empty_mobile: 'Please enter the passenger mobile number.',
  add_passenger_duplicate: 'This contact already exists. Please use a different name or ID number.',
  add_passenger_confirm_title: 'Please verify passenger information.',
  add_passenger_not_provided: 'Not provided',
  add_passenger_tips_title: 'Tips:',
  add_passenger_tips_1: '1. Please provide a valid contact for the passenger.',
  add_passenger_tips_2: '2. Ticket sales require real-name verification.',
  add_passenger_tips_3: '3. If the identity information cannot be verified within 24 hours, please verify it at the station.',
  add_passenger_tips_4: '4. A contact cannot be deleted within 30 days after adding, and each account can add up to 30 passengers.',

  // Incomplete orders page
  incomplete_orders_title: 'Pending orders',
  incomplete_orders_empty: 'No pending orders found.',
  incomplete_orders_remaining: 'Remaining:',
  incomplete_orders_via: 'via',
  incomplete_orders_duration: 'Duration',
  incomplete_orders_departure: 'Departure:',
  incomplete_orders_discount: '17% off',
  incomplete_orders_change_refund: 'Change / refund',
  incomplete_orders_show_more: 'Show {n} more',
  incomplete_orders_insurance_title: 'Railway travel insurance',
  incomplete_orders_insurance_main_title: 'Safe journey, multiple protections',
  incomplete_orders_insurance_more_products: 'More products',
  incomplete_orders_insurance_desc: 'Up to ¥880,000 accident protection',
  incomplete_orders_insurance_unit: '/person',
  incomplete_orders_insurance_accident: 'Accident cover',
  incomplete_orders_insurance_medical: 'Medical expenses',
  incomplete_orders_insurance_liability: 'Third-party liability',
  incomplete_orders_please_read: 'Please read',
  incomplete_orders_purchase_notice: 'Purchase notice',
  incomplete_orders_policy_terms: 'Policy terms',
  incomplete_orders_disclaimer: 'Disclaimer',
  incomplete_orders_quick_pay_badge: 'Fast pay, no transfer needed',
  incomplete_orders_quick_pay_scan: 'Scan to ride',
  incomplete_orders_order_total: 'Order total',
  incomplete_orders_ticket_price: 'Ticket price',
  incomplete_orders_total: 'Total',
  incomplete_orders_details: 'Details',
  incomplete_orders_cancel_order: 'Cancel order',
  incomplete_orders_buy_return: 'Buy return ticket',
  incomplete_orders_pay_now: 'Pay now',
  incomplete_orders_cancel_confirm_message: 'If you cancel the order, you can no longer continue payment today. You may still book tickets later with this account.',
  incomplete_orders_confirm_cancel: 'Confirm cancel',
  incomplete_orders_leave_confirm_message: 'Leave payment? The order will not be cancelled. You can continue from Pending Orders later.',
  incomplete_orders_order_payment: 'Order payment',
  incomplete_orders_choose_payment_method: 'Choose a payment method',
  incomplete_orders_other_payment_methods: 'Other payment methods',
  incomplete_orders_other_payment_desc: 'Cards, wallets, and more.',
  incomplete_orders_add_protection: 'Add protection for your family.',
  incomplete_orders_no_coverage: 'No coverage',
  incomplete_orders_best_value: 'Best value',
  incomplete_orders_accident_medical_plan: 'Accident + medical',
  incomplete_orders_max_payout: 'Max payout',
  incomplete_orders_person: 'person',
  incomplete_orders_accident_luggage_plan: 'Accident cover',
  incomplete_orders_go_pay: 'Pay',
  incomplete_orders_seat_reassigned_message: 'Your preferred seat is no longer available on this train. The system has automatically assigned another seat for you. Please confirm to continue payment, or cancel the order.',

  // Order detail page
  order_detail_title: 'Order details',
  order_detail_not_found: 'Order not found or has expired.',
  order_detail_order_id: 'Order ID',
  order_detail_copy: 'Copy',
  order_detail_ordered_at: 'Ordered',
  order_detail_travel_date: 'Travel date',
  order_detail_change_destination: 'Change destination',
  order_detail_reschedule: 'Reschedule',
  order_detail_refund: 'Refund',
  order_detail_unassigned_seat: 'Unassigned seat',
  order_detail_show_more: 'Show {n} more passengers',
  order_detail_order_meal: 'Order meal',
  order_detail_travel_insurance: 'Travel insurance',
  order_detail_qr_check_in: 'Check-in',
  order_detail_share_text: 'Have a nice trip. Share it with friends.',
  order_detail_share_now: 'Share now',
  order_detail_validity_notice: 'Order information is valid for 30 days',
  order_detail_hotel_deal: 'Hotel deal',
  order_detail_hotel: 'Hotel',
  order_detail_travel_easier: 'Travel made easier',
  order_detail_check_in: 'Check-in',
  order_detail_night: 'night',
  order_detail_check_out: 'Check-out',

  // Paid orders page
  paid_orders_title: 'Paid orders',
  paid_orders_tab_upcoming: 'Upcoming',
  paid_orders_tab_history: 'History',
  paid_orders_child_notice: 'Free child ride declaration (under 6)',
  paid_orders_add_now: 'Add now',
  paid_orders_empty: 'Your order history will be kept for 30 days.',
  paid_orders_ordered_on: 'Ordered on',
  paid_orders_order_id_label: 'Order ID:',
  paid_orders_departure_label: 'Departure:',
  paid_orders_passengers_label: 'Passengers:',
  paid_orders_tickets_suffix: 'tickets',
  paid_orders_passenger_display_more: '{name} +{extraCount}',
  paid_orders_retention_notice: 'Your order history will be kept for 30 days.',
  paid_orders_ad_title: '12306 Dining',
  paid_orders_ad_desc: 'Food delivered to your seat',
  paid_orders_book_now: 'Book now',

  // Payment password page
  payment_password_title: 'Payment password',
  payment_password_change_tab: 'Change password',
  payment_password_reset_tab: 'Reset password',
  payment_password_old_label: 'Old password:',
  payment_password_old_placeholder: '6-digit password',
  payment_password_new_label: 'New password:',
  payment_password_new_placeholder: 'Enter a new 6-digit password',
  payment_password_confirm_label: 'Confirm:',
  payment_password_confirm_placeholder: 'Re-enter the new password',
  payment_password_tips_body: 'After changing or resetting the payment password, the new password takes effect immediately and must be 6 digits long.',

  // Payment platform page
  payment_platform_title: 'Please pay',
  payment_platform_done: 'Done',
  payment_platform_subtitle: 'Railway 12306 electronic payment platform',
  payment_platform_amount_due: 'Amount due',
  payment_platform_jd_name: 'JD Pay',
  payment_platform_jd_offer: 'Limited offer: -298, white-box new users get 0.',
  payment_platform_other_methods: '11 more payment methods',
  payment_platform_submit: 'Pay now',
  payment_platform_merchant_name: 'Railway 12306',
  payment_platform_subject: 'Train ticket',

  // Payment success page
  payment_success_title: 'Payment successful',
  payment_success_notification_settings: 'Notification settings',
  payment_success_order_details: 'Order details',
  payment_success_meal_reservation: 'Meal reservation',
  payment_success_trip_assistance: 'Trip assistance',
  payment_success_hot: 'Hot',
  payment_success_pack_light: 'Pack light',
  payment_success_share_text: 'Have a nice trip. Share it with friends.',
  payment_success_share_now: 'Share now',
  payment_success_hotel_deals: '{city} hotel deals',
  payment_success_hotel_offer: 'Limited-time travel offer',
  payment_success_check_in: 'Check-in',
  payment_success_night: 'night',
  payment_success_check_out: 'Check-out',
  payment_success_claim_coupon: 'Claim coupon',
  payment_success_hotel_coupon: 'Hotel coupon',
  payment_success_car_rental_deals: 'Spring car rental deals',
  payment_success_view_now: 'Tap to view now',
  payment_success_activity_period: 'Active: 2026-03-01 to 2026-05-31',
  payment_success_ad: 'Ad',
  payment_success_dining_desc: 'Meal delivery along your trip',
  payment_success_car_rental_title: 'Car rental booking',
  payment_success_car_rental_offer: 'Up to 100 off for new users',
  payment_success_pickup: 'Pickup',
  payment_success_duration: 'Duration',
  payment_success_days: 'days',
  payment_success_choose_car: 'Choose a car',

  // Refund confirm flow
  refund_notice_title: 'Notice',
  refund_notice_message: 'Are you sure you want to refund this ticket? Reserved station guidance or special passenger services will be cancelled automatically. Meal or specialty orders should be cancelled separately as required.',
  refund_notice_continue: 'Continue',
  refund_confirm_title: 'Refund confirmation',
  refund_confirm_departure_time: 'Departure time',
  refund_confirm_notice_title: 'Notice:',
  refund_confirm_rule_1_prefix: 'Change and refund rules are in ',
  refund_confirm_rule_link: 'Refund policy',
  refund_confirm_rule_2: 'For tickets changed to a Spring Festival travel date, refunds less than 24 hours before departure are charged at 20% of the ticket price.',
  refund_confirm_rule_3: 'The final fee and refund amount are calculated by the final transaction time.',
  refund_confirm_total_label: 'Refund total',
  refund_confirm_detail_label: 'Details',
  refund_confirm_cancel: 'Cancel refund',
  refund_confirm_submit: 'Confirm refund',

  // Refund success page
  refund_success_title: 'Operation successful',
  refund_success_banner: 'Your refund was successful.',
  refund_success_business_id: 'Business ID',
  refund_success_details_title: 'Refund details',
  refund_success_train: 'Train',
  refund_success_passengers: 'Passengers',
  refund_success_original_fare: 'Original fare',
  refund_success_rate: 'Refund rate',
  refund_success_service_fee: 'Service fee',
  refund_success_total: 'Total refund',
  refund_success_back: 'Back to orders',
};
